import type { Metadata } from "next";
import { LegalPage } from "@/app/components/legal-page";

export const metadata: Metadata = { title: "Cookie Policy", description: "How Growvelt uses cookies and similar technologies across applicable Growvelt services." };

const sections = [
  { heading: "1. What this policy covers", paragraphs: ["This Cookie Policy explains how Growvelt uses cookies and similar technologies across applicable Growvelt services and platforms.", "Cookies are small pieces of information a website can store in your browser. Similar technologies include localStorage, sessionStorage, browser and device state, and PWA Cache Storage."] },
  { heading: "2. Why Growvelt uses these technologies", paragraphs: ["Growvelt uses these technologies to provide secure accounts, remember requested choices, protect services, support core platform functionality, and where applicable improve the experience.", "Some technologies are essential. Others, such as optional Analytics or Advertising technologies, are controlled through applicable consent choices when they are enabled."] },
  { heading: "3. Essential technologies", paragraphs: ["Essential technologies are always active because Growvelt needs them to provide core functionality. They may support authentication and sessions, security, requested OAuth or payment flows, essential browser state, and core PWA support.", "You cannot disable essential technologies through Growvelt Cookie Settings because doing so could prevent account, security, or requested features from working."] },
  { heading: "4. Authentication, security, and requested services", paragraphs: ["Applicable Growvelt services use Supabase authentication and session technologies to help keep accounts signed in and secure. Security tools, including Cloudflare Turnstile where applicable, may help prevent fraud, abuse, and automated misuse.", "If you choose Google, LinkedIn where available, or another supported OAuth sign-in method, that provider may process information under its own policies. If you enter an applicable payment flow, Paystack or another payment provider may process information under its own terms and privacy policy."] },
  { heading: "5. Browser storage, preferences, and PWA support", paragraphs: ["Growvelt may use localStorage, sessionStorage, and related browser state for theme, language where available, interface preferences, recent searches, banner dismissals, temporary drafts, requested tool or support state, referral attribution where applicable, and browser or device notification preferences where applicable.", "PWA and Cache Storage may be used for approved offline or performance features. These technologies support the requested experience; they are not a separate Functional or Preferences consent category at this time."] },
  { heading: "6. Embedded and third-party content", paragraphs: ["Some Growvelt services may include third-party content such as YouTube embedded media. Loading that content may allow the provider to process information or set technologies under its own policies.", "Growvelt does not control third-party providers or their policies."] },
  { heading: "7. Optional Analytics", paragraphs: ["Analytics is an optional category. Based on current audits, Growvelt does not currently have an analytics tracker installed.", "Growvelt may introduce optional analytics technologies in the future on applicable services. Where required or applicable, those technologies would respect your consent choice."] },
  { heading: "8. Optional Advertising", paragraphs: ["Advertising is an optional category. Based on current audits, Growvelt does not currently have a browser advertising or marketing tracker installed.", "Growvelt may introduce optional advertising or marketing measurement technologies in the future on applicable services. Where required or applicable, those technologies would respect your consent choice."] },
  { heading: "9. Your consent cookie and choices", paragraphs: ["Growvelt uses the first-party growvelt_cookie_consent cookie to remember your cookie or technology choices and consent-version information. It is not intended to contain passwords, authentication credentials or tokens, payment information, account role, Premium status, administrator status, or sensitive personal information.", "On Growvelt platforms where Cookie Settings are available, you can accept or reject optional technologies, manage your choices, and change them later. Cookie Settings are not yet identical across every Growvelt platform."] },
  { heading: "10. Browser controls and retention", paragraphs: ["Most browsers allow you to review, remove, or block cookies and storage. Blocking or removing essential technologies may mean parts of Growvelt do not work as intended.", "Cookies and browser-storage records may have different lifetimes depending on their purpose. Consent information may have a defined lifetime and may be refreshed if Growvelt materially changes its consent categories or policy."] },
  { heading: "11. Changes and contact", paragraphs: ["We may update this Cookie Policy as Growvelt services, technologies, or practices change. The updated version will be posted with a revised date.", "For privacy questions or requests, contact us at support@growvelt.com or through the Contact us page."] },
];

export default function CookiePolicyPage() { return <LegalPage title="Cookie Policy" summary="A plain-language explanation of cookies and similar technologies used across applicable Growvelt services." updated="August 17, 2026" sections={sections} />; }
