import type { Metadata } from "next";
import { LegalPage } from "@/app/components/legal-page";

export const metadata: Metadata = { title: "Refund Policy", description: "Growvelt Learning payment confirmation, full-refund eligibility, processing, access, and dispute policy." };

const sections = [
  { heading: "1. Payment confirmation", paragraphs: ["The course price displayed at checkout is the final course price charged by Growvelt unless the checkout clearly states otherwise. Paystack processes the payment. Growvelt grants access only after receiving or independently verifying authoritative payment confirmation.", "A browser redirect, screenshot, debit alert, or pending bank transaction does not by itself prove successful payment. If a payment appears successful but access is unavailable, contact support@growvelt.com with the Growvelt order reference and do not pay again unless Growvelt confirms the first attempt failed."] },
  { heading: "2. Routine full-refund eligibility", paragraphs: ["A learner may request a routine full refund within 14 calendar days after successful payment when less than 20% of the course has been completed.", "A completed course is not eligible for a routine refund. A course for which a certificate has already been issued is not eligible for a routine refund. Growvelt does not currently offer partial refunds."] },
  { heading: "3. Exceptional review", paragraphs: ["Growvelt may review an exceptional full-refund request outside the routine criteria. Approval is not automatic and may consider course availability, payment records, access and completion history, fraud prevention, and relevant support information.", "These operational criteria do not replace or restrict mandatory consumer rights that apply under applicable law."] },
  { heading: "4. Refund processing", paragraphs: ["Send refund requests to refund@growvelt.com from the email address connected to the Growvelt account and include the Growvelt order reference and reason for the request. Growvelt targets acknowledgement within one business day and operator review within two business days.", "Refunds are processed asynchronously by Paystack. Requested, pending, processing, or needs-attention states are not completed refunds. Growvelt treats a refund as completed only after authoritative provider confirmation. The time for funds to appear may depend on the payment provider and financial institution."] },
  { heading: "5. Course access and learning history", paragraphs: ["After a processed full refund, future access to the course ends. Growvelt retains the enrollment record, lesson progress, quiz attempts, completion history, transaction records, and audit history for integrity, security, dispute resolution, and operational purposes.", "A learner may purchase the course again later through a new order where the course remains available and the purchase passes Growvelt's current safety checks. A new purchase does not rewrite or reactivate the earlier refunded order or entitlement."] },
  { heading: "6. Certificates, fraud, and chargebacks", paragraphs: ["Routine refunds are not available after certificate issuance. If Growvelt exceptionally refunds a purchase after certificate issuance, the historical certificate remains unless a separate fraud or abuse determination requires revocation.", "When fraud, abuse, or an authoritative chargeback is confirmed, Growvelt may revoke the certificate's public validity while preserving its immutable historical and audit record. During an unresolved payment dispute, course access normally remains available until Paystack confirms a financial loss or merchant-accepted outcome."] },
  { heading: "7. Contact", paragraphs: ["For refund requests, email refund@growvelt.com. For general account, course, or technical help, contact support@growvelt.com."] },
];

export default function RefundPolicyPage() { return <LegalPage title="Refund Policy" summary="How Growvelt Learning confirms payments, reviews full-refund requests, and handles access after refunds or chargebacks." updated="September 1, 2026" sections={sections} />; }
