import type { Metadata } from "next";
import { LegalPage } from "@/app/components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Growvelt collects, uses, protects, and manages personal information across learning and careers services." };

const sections = [
  { heading: "1. About this policy", paragraphs: ["This Privacy Policy explains how Growvelt Technologies Limited (RC - 8738218) collects, uses, shares, protects, and manages personal information across applicable Growvelt services and platforms, including career, hiring, learning, support, and related tools.", "Product-specific features may process different information. This policy applies alongside notices shown in a relevant Growvelt service and the terms or policies of third parties you choose to use."] },
  { heading: "2. Information we collect", paragraphs: ["We collect information you provide when you create an account, sign in, apply for jobs, save jobs, post jobs, request verification, register for courses, make payments, subscribe to updates, contact support, or use forms and tools.", "This may include your name, email address, phone number, location, professional details, profile information, resume or CV, application answers, company details, messages, uploaded files, course activity, and support requests."] },
  { heading: "3. Accounts, authentication, and profiles", paragraphs: ["When you sign in with email and password, Google, LinkedIn where available, or another supported method, we may process account identifiers, email addresses, profile names, avatar images, login timestamps, and authentication status to create and secure your account.", "Growvelt uses Supabase authentication and session handling on applicable services. Where third-party sign-in is selected, the provider may share limited account information according to your settings and that provider's privacy policy."] },
  { heading: "4. Applications, learning, payments, and tools", paragraphs: ["We process job application information to submit, track, and update applications. Relevant employers may access information needed to review applications for jobs they manage. We process course enrollment, lesson progress, assessment attempts, and certificate records to provide learning services.", "When you use Career Assistant or another requested tool, we process the information you submit and the resulting output to provide that feature. Drafts, requested reports, support conversations, and similar temporary workflow state may be processed or stored where applicable to provide the feature you requested.", "When you enter an applicable payment flow, Paystack or another payment provider may process payment information under its own terms and privacy policy. Growvelt does not intentionally store full card numbers or sensitive banking credentials on its own servers."] },
  { heading: "5. How we use information", paragraphs: ["We use information to operate and secure Growvelt services, provide accounts and requested features, deliver learning, support job applications and employer services, process payments where applicable, respond to support requests, prevent fraud and abuse, communicate updates, and improve our services.", "We may also use referral attribution where applicable, administer legitimate platform preferences, and meet legal obligations, resolve disputes, and enforce our terms."] },
  { heading: "6. Cookies and similar technologies", paragraphs: ["Growvelt uses essential cookies and similar technologies to provide core functionality. These may include authentication and session technologies, security controls, requested OAuth and payment flows, and essential platform state.", "We may also use browser storage such as localStorage and sessionStorage for theme, language where available, interface preferences, recent or temporary workflow state, banner dismissals, drafts, and other requested functionality. PWA and Cache Storage may support approved offline or performance features. Browser or device notification state may be stored where applicable when you request or manage notifications."] },
  { heading: "7. Consent choices and optional technologies", paragraphs: ["Growvelt uses the first-party growvelt_cookie_consent cookie to remember cookie or technology choices and consent-version information. It is not intended to contain passwords, authentication credentials or tokens, payment information, account role, Premium status, administrator status, or sensitive personal information.", "Essential technologies are always active because they are needed for core functionality. Analytics and Advertising are optional categories. Based on current audits, Growvelt does not currently have an analytics or browser advertising tracker installed. If optional analytics or advertising or marketing measurement technologies are enabled in the future on an applicable Growvelt service, they may be used only in accordance with applicable consent choices.", "On Growvelt platforms where Cookie Settings are available, you can accept, reject, or later change optional choices. You can also use browser controls to manage cookies and storage, although blocking essential technologies may prevent parts of a service from working."] },
  { heading: "8. Security and embedded content", paragraphs: ["We use reasonable technical and organizational safeguards to protect information. Security technologies such as Cloudflare Turnstile may be used on relevant forms or services to prevent abuse. No online service is completely secure, so users should also protect their passwords, devices, and account access.", "Some Growvelt services may contain third-party content, such as YouTube video embeds. Loading third-party content may allow that provider to process information or set technologies under its own policies. Growvelt does not control third-party providers."] },
  { heading: "9. When we share information", paragraphs: ["We may share information with providers that help operate Growvelt, including hosting, database, authentication, storage, artificial intelligence processing, email delivery, translation, payments, security, support, and embedded-media providers. They process information as needed to provide their services under their applicable terms and safeguards.", "We may share application information with the relevant employer or recruiter, and may disclose information where required by law, to protect users, investigate abuse, enforce our terms, or as part of a business transfer. We do not sell personal information as a standalone product."] },
  { heading: "10. Retention and account deletion", paragraphs: ["We keep personal information and related technology records for as long as needed to provide services, maintain accounts, support applications, meet legal obligations, resolve disputes, prevent fraud, and enforce our terms. Retention varies by data type, purpose, and applicable service.", "When an eligible learner deletes an account, Growvelt asks whether an earned certificate should remain publicly verifiable. If the learner chooses to keep verification, the certificate's issued snapshot may remain available without remaining linked to an active account. If the learner chooses to remove public verification, the learner name is removed from that verification record and the certificate is marked revoked. Instructors with dependent course content and active administrators require managed offboarding before account deletion so that learning content and platform authority are handled safely.", "Cookies and browser-storage records may have different lifetimes. Consent information may have a defined lifetime and may be refreshed if Growvelt materially changes its consent categories or policy."] },
  { heading: "11. Your choices and rights", paragraphs: ["You may update certain account details, manage available preferences, unsubscribe from optional emails, or contact us to request access, correction, deletion, or restriction of information where applicable law permits.", "You may withdraw or change optional consent through Cookie Settings on Growvelt platforms where available. Some information may need to be retained for legal, security, payment, anti-fraud, or legitimate business reasons."] },
  { heading: "12. Changes and contact", paragraphs: ["We may update this policy as Growvelt services, technology, legal requirements, or business practices change. The updated version will be posted with a revised date.", "For privacy questions or requests, contact us at support@growvelt.com or through the Contact us page."] },
];

export default function PrivacyPolicyPage() { return <LegalPage title="Privacy Policy" summary="How Growvelt handles personal information and technology choices across our services and platforms." updated="August 23, 2026" sections={sections} />; }
