import type { Metadata } from "next";
import { LegalPage } from "@/app/components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Growvelt collects, uses, protects, and manages personal information across learning and careers services." };

const sections = [
  { heading: "1. Information we collect", paragraphs: ["We collect information you provide when you create an account, sign in, apply for jobs, save jobs, post jobs, request verification, register for courses, make payments, subscribe to updates, contact support, or use forms.", "This may include your name, email address, phone number, location, professional details, profile information, resume or CV, application answers, company details, messages, uploaded files, and support requests."] },
  { heading: "2. Account and profile data", paragraphs: ["When you sign in with email, password, Google, or another supported method, we may process account identifiers, email addresses, profile names, avatar images, login timestamps, and authentication status to create and secure your account.", "Where third-party sign-in is available, the provider may share limited account information according to your settings and that provider's privacy policy."] },
  { heading: "3. Applications, employers, courses, and payments", paragraphs: ["We process job application information to submit, track, and update applications. Relevant employers may access information needed to review applications for jobs they manage.", "We process course enrollment, lesson progress, assessment attempts, and certificate records to provide learning services. When a payment service is used, third-party providers may process payment information; Growvelt does not intentionally store full card numbers or sensitive banking credentials on its own servers."] },
  { heading: "4. Career Assistant and AI processing", paragraphs: ["When you use Career Assistant, we process the information you submit to provide the requested result. This can include resume text, job descriptions, application details, interview answers, candidate evidence, evaluation criteria, and generated reports.", "Career Assistant may use automated rules and external artificial intelligence service providers. Users should remove identification numbers, home addresses, medical information, protected characteristics, and any information not necessary for the task."] },
  { heading: "5. How we use information", paragraphs: ["We use information to operate and secure Growvelt, provide accounts and services, deliver courses, process enrollments, issue and verify certificates, support job applications and employer services, respond to support requests, prevent fraud and abuse, communicate updates, and improve our services."] },
  { heading: "6. Cookies, analytics, and technical data", paragraphs: ["We may collect technical information such as device type, browser, IP address, pages visited, referring pages, session activity, and interaction data. Cookies or similar technologies help keep users signed in, remember preferences, improve performance, and understand service use."] },
  { heading: "7. When we share information", paragraphs: ["We may share information with providers that help operate Growvelt, including hosting, database, authentication, storage, AI processing, email delivery, analytics, payments, security, and support providers.", "We may share application information with the relevant employer or recruiter, and may disclose information where required by law, to protect users, investigate abuse, enforce our terms, or as part of a business transfer. We do not sell personal information as a standalone product."] },
  { heading: "8. Retention and security", paragraphs: ["We keep information for as long as needed to provide services, maintain accounts, support applications, meet legal obligations, resolve disputes, prevent fraud, and enforce our terms. Retention varies by data type and purpose.", "We use reasonable technical and organizational measures to protect information. No online service is completely secure, so users should also protect their passwords, devices, and account access."] },
  { heading: "9. Your choices and rights", paragraphs: ["You may update certain account details, manage preferences, unsubscribe from optional emails, or contact us to request access, correction, deletion, or restriction of information where applicable law permits.", "Some information may need to be retained for legal, security, payment, anti-fraud, or legitimate business reasons."] },
  { heading: "10. External links, changes, and contact", paragraphs: ["External employer websites, partner job boards, payment pages, social media pages, and other third-party resources control their own privacy practices. Review their policies before sharing personal information.", "We may update this policy as services, technology, legal requirements, or business practices change. For privacy questions or requests, Contact us."] },
];

export default function PrivacyPolicyPage() { return <LegalPage title="Privacy Policy" summary="How Growvelt collects, uses, protects, and manages personal information across our learning and career services." updated="July 24, 2026" sections={sections} />; }
