import Link from "next/link";
import { getRequestLocale } from "@/app/lib/i18n-server";

export const metadata = { title: "Admin Reviews" };

export default async function DashboardAdminPage() {
  const locale = await getRequestLocale();
  const text = locale === "fr" ? { eyebrow: "Examens administrateur", title: "Protégez la qualité de Growvelt Learning.", copy: "Examinez les candidatures d’instructeurs et les cours soumis dans des parcours de modération protégés.", instructors: "Examens des instructeurs", instructorTitle: "Examiner les candidatures d’enseignement.", instructorCopy: "Étudiez les candidatures en attente et accordez l’accès instructeur uniquement par la décision administrateur officielle.", openInstructors: "Ouvrir les examens des instructeurs", courses: "Examens des cours", courseTitle: "Modérer les contenus soumis.", courseCopy: "Examinez les informations, les déclarations de droits, le programme et les quiz avant publication ou retour au brouillon.", openCourses: "Ouvrir les examens des cours" } : locale === "es" ? { eyebrow: "Revisiones de administración", title: "Protege la calidad de Growvelt Learning.", copy: "Revisa solicitudes de instructores y cursos enviados mediante flujos de moderación protegidos.", instructors: "Revisiones de instructores", instructorTitle: "Revisar solicitudes de enseñanza.", instructorCopy: "Examina las solicitudes pendientes y concede acceso de instructor solo mediante la decisión oficial de administración.", openInstructors: "Abrir revisiones de instructores", courses: "Revisiones de cursos", courseTitle: "Moderar contenido enviado.", courseCopy: "Examina los datos, declaraciones de derechos, plan de estudios y cuestionarios antes de publicar o devolver un borrador.", openCourses: "Abrir revisiones de cursos" } : { eyebrow: "Admin Reviews", title: "Protect the quality of Growvelt Learning.", copy: "Review Instructor applications and submitted courses through separate, protected moderation workflows.", instructors: "Instructor Reviews", instructorTitle: "Review teaching applications.", instructorCopy: "Inspect pending applications and grant teaching capability only through the authoritative Admin decision.", openInstructors: "Open Instructor Reviews", courses: "Course Reviews", courseTitle: "Moderate submitted learning.", courseCopy: "Inspect course metadata, rights declarations, curriculum, and secure quiz structure before publishing or returning a draft.", openCourses: "Open Course Reviews" };
  return <section className="admin-page admin-operations-page section-shell">
    <header className="admin-page-header admin-review-hero"><p className="eyebrow">{text.eyebrow}</p><h1>{text.title}</h1><p>{text.copy}</p></header>
    <div className="admin-operations-grid">
      <section className="admin-operation-card"><span className="admin-operation-number">01</span><div><p className="eyebrow">{text.instructors}</p><h2>{text.instructorTitle}</h2><p>{text.instructorCopy}</p></div><Link className="button button-primary" href="/dashboard/admin/instructors">{text.openInstructors} <span aria-hidden="true">→</span></Link></section>
      <section className="admin-operation-card"><span className="admin-operation-number">02</span><div><p className="eyebrow">{text.courses}</p><h2>{text.courseTitle}</h2><p>{text.courseCopy}</p></div><Link className="button button-secondary" href="/dashboard/admin/courses">{text.openCourses} <span aria-hidden="true">→</span></Link></section>
    </div>
  </section>;
}
