"use client";

import Link from "next/link";
import { useLanguage } from "@/app/components/language-provider";

const content = {
  en: { eyebrow: "Growvelt help centre", title: "Questions about learning, careers, or working with Growvelt?", intro: "Start here for direct answers across Growvelt Learning and Growvelt Careers. If your question is not covered, the team is ready to help.", contact: "Contact us", explore: "Explore courses", label: "Frequently asked questions", groups: [["Learning and certificates", [["How do I find a course?", "Use the published course catalog to search current courses by title, topic, category, level, and access details."], ["What does it take to earn a certificate?", "Certificates are issued from an eligible completed course record. Text and video activities must be completed, and required quizzes must be passed."], ["Can I verify a Growvelt certificate?", "Yes. Each issued certificate has a unique public verification code and a verification page."], ["Can I teach on Growvelt?", "You can apply to teach, then create a draft course for review once your Instructor access is approved."]]], ["Jobs and careers", [["Where do I apply for jobs?", "Growvelt Careers is the jobs experience. Use it to explore current opportunities and follow the application route for the role."], ["Does completing a course guarantee a job?", "No. Learning and certificates demonstrate completed learning, but no course or certificate guarantees an interview, offer, salary, visa, or employment outcome."], ["Can an employer work with Growvelt?", "Yes. Employers can visit Growvelt Careers for job and hiring tools, or contact us about an employer or workforce partnership."]]], ["Support and partnerships", [["How do I contact Growvelt?", "Use the Contact page for course support, account questions, jobs, career tools, teaching enquiries, or a general message."], ["What kinds of partnerships does Growvelt consider?", "Growvelt considers practical learning, workforce development, jobs and employer access, academic, nonprofit, community, and career-development initiatives."], ["Where can I get WhatsApp support?", "The Contact page and the site footer include Growvelt’s current WhatsApp support channel."]]]], },
  fr: { eyebrow: "Centre d’aide Growvelt", title: "Des questions sur l’apprentissage, la carrière ou la collaboration avec Growvelt ?", intro: "Trouvez ici des réponses directes sur Growvelt Learning et Growvelt Careers. Si votre question n’est pas traitée, l’équipe est prête à vous aider.", contact: "Nous contacter", explore: "Explorer les cours", label: "Questions fréquentes", groups: [["Apprentissage et certificats", [["Comment trouver un cours ?", "Utilisez le catalogue de cours publiés pour rechercher les cours actuels par titre, sujet, catégorie, niveau et modalités d’accès."], ["Que faut-il pour obtenir un certificat ?", "Les certificats sont délivrés à partir d’un dossier de cours éligible et terminé. Les activités texte et vidéo doivent être achevées, et les quiz requis réussis."], ["Puis-je vérifier un certificat Growvelt ?", "Oui. Chaque certificat délivré possède un code public de vérification unique et une page de vérification."], ["Puis-je enseigner sur Growvelt ?", "Vous pouvez postuler pour enseigner, puis créer un brouillon de cours à examiner une fois votre accès formateur approuvé."]]], ["Emploi et carrière", [["Où postuler à des emplois ?", "Growvelt Careers est l’expérience emploi. Utilisez-la pour explorer les opportunités actuelles et suivre la procédure de candidature du poste."], ["Terminer un cours garantit-il un emploi ?", "Non. L’apprentissage et les certificats démontrent une formation achevée, mais aucun cours ou certificat ne garantit un entretien, une offre, un salaire, un visa ou un emploi."], ["Un employeur peut-il travailler avec Growvelt ?", "Oui. Les employeurs peuvent visiter Growvelt Careers pour les outils d’emploi et de recrutement, ou nous contacter pour un partenariat employeur ou de main-d’œuvre."]]], ["Assistance et partenariats", [["Comment contacter Growvelt ?", "Utilisez la page Contact pour l’aide aux cours, les questions de compte, l’emploi, les outils de carrière, les demandes d’enseignement ou un message général."], ["Quels types de partenariats Growvelt considère-t-il ?", "Growvelt considère les initiatives d’apprentissage pratique, de développement de la main-d’œuvre, d’accès à l’emploi et aux employeurs, académiques, associatives, communautaires et de développement de carrière."], ["Où obtenir l’assistance WhatsApp ?", "La page Contact et le pied de page du site indiquent le canal d’assistance WhatsApp actuel de Growvelt."]]]], },
  es: { eyebrow: "Centro de ayuda de Growvelt", title: "¿Preguntas sobre aprendizaje, carreras o cómo trabajar con Growvelt?", intro: "Comienza aquí para obtener respuestas directas sobre Growvelt Learning y Growvelt Careers. Si tu pregunta no aparece, el equipo está listo para ayudarte.", contact: "Contáctanos", explore: "Explorar cursos", label: "Preguntas frecuentes", groups: [["Aprendizaje y certificados", [["¿Cómo encuentro un curso?", "Usa el catálogo de cursos publicados para buscar cursos actuales por título, tema, categoría, nivel y detalles de acceso."], ["¿Qué se necesita para obtener un certificado?", "Los certificados se emiten a partir de un registro de curso elegible y completado. Las actividades de texto y video deben completarse y los cuestionarios requeridos deben aprobarse."], ["¿Puedo verificar un certificado de Growvelt?", "Sí. Cada certificado emitido tiene un código público de verificación único y una página de verificación."], ["¿Puedo enseñar en Growvelt?", "Puedes solicitar enseñar y luego crear un borrador de curso para revisión una vez que se apruebe tu acceso de instructor."]]], ["Empleos y carreras", [["¿Dónde solicito empleos?", "Growvelt Careers es la experiencia de empleos. Úsala para explorar oportunidades actuales y seguir la ruta de solicitud para el puesto."], ["¿Completar un curso garantiza un empleo?", "No. El aprendizaje y los certificados demuestran formación completada, pero ningún curso o certificado garantiza una entrevista, oferta, salario, visa o resultado laboral."], ["¿Puede un empleador trabajar con Growvelt?", "Sí. Los empleadores pueden visitar Growvelt Careers para herramientas de empleo y contratación, o contactarnos sobre una colaboración de empleador o fuerza laboral."]]], ["Soporte y colaboraciones", [["¿Cómo contacto a Growvelt?", "Usa la página de contacto para soporte de cursos, preguntas de cuenta, empleos, herramientas de carrera, consultas de enseñanza o un mensaje general."], ["¿Qué tipos de colaboraciones considera Growvelt?", "Growvelt considera iniciativas de aprendizaje práctico, desarrollo de fuerza laboral, empleos y acceso de empleadores, académicas, sin fines de lucro, comunitarias y de desarrollo profesional."], ["¿Dónde obtengo soporte por WhatsApp?", "La página de contacto y el pie de página incluyen el canal actual de soporte por WhatsApp de Growvelt."]]]], },
} as const;

export function FaqPageContent() {
  const { locale } = useLanguage();
  const text = content[locale];
  return <main><section className="faq-page-hero section-shell"><p className="eyebrow">{text.eyebrow}</p><h1>{text.title}</h1><p>{text.intro}</p><div className="hero-actions"><Link className="button button-primary" href="/contact">{text.contact}</Link><Link className="button button-secondary" href="/learn">{text.explore}</Link></div></section><section className="faq-page-groups section-shell" aria-label={text.label}>{text.groups.map(([title, items]) => <section key={title}><h2>{title}</h2>{items.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</section>)}</section></main>;
}
