"use client";

import Link from "next/link";
import { ArrowRight, Building2, GraduationCap, Handshake, HeartHandshake } from "lucide-react";
import { useLanguage } from "@/app/components/language-provider";
import { PublicInquiryForm } from "@/app/components/public-inquiry-form";

const copy = {
  en: { eyebrow: "Partner with Growvelt", title: "Build practical digital-skills opportunities with us.", intro: "Growvelt brings learning, career development, and opportunity closer together. We welcome partnerships that make useful skills and meaningful next steps more accessible.", start: "Start a partnership conversation", about: "About Growvelt", collaboration: "A practical collaboration", collaborationTitle: "Skills development that connects to what people can do next.", learning: "Learning", readiness: "Career readiness", opportunity: "Opportunity", why: "Why collaborate", whyTitle: "A shared route from learning to confidence and opportunity.", whyCopy: "Partnerships work best when they have a clear audience, an honest learning need, and a useful outcome. Growvelt can explore ideas for training, practical workshops, learner support, and career-focused programmes with your team.", ways: "Ways to work together", waysTitle: "Partnerships shaped around useful outcomes.", begin: "How we begin", beginTitle: "A clear conversation before a commitment.", types: [{ title: "Corporate partners", description: "Build practical training, workforce development, employer access, or capacity-building programmes with Growvelt." }, { title: "Academic institutions", description: "Explore learner support, practical workshops, curriculum collaboration, and career-readiness initiatives." }, { title: "Nonprofits and NGOs", description: "Work together on inclusive digital-skills programmes and community-focused learning opportunities." }, { title: "Community partners", description: "Connect learners, job seekers, mentors, and opportunities through thoughtful referral or collaboration models." }], steps: [{ title: "Share the opportunity", description: "Tell us who you want to support and the outcome you want to create." }, { title: "Explore the fit", description: "We review the idea, available learning paths, and practical delivery needs together." }, { title: "Design the next step", description: "Agree a focused way to move forward, with clear responsibilities and learner value." }] },
  fr: { eyebrow: "Devenir partenaire de Growvelt", title: "Créons ensemble des opportunités pratiques de compétences numériques.", intro: "Growvelt rapproche l’apprentissage, l’évolution professionnelle et les opportunités. Nous accueillons les partenariats qui rendent les compétences utiles et les prochaines étapes concrètes plus accessibles.", start: "Démarrer une conversation de partenariat", about: "À propos de Growvelt", collaboration: "Une collaboration pratique", collaborationTitle: "Un développement des compétences relié à ce que les personnes peuvent faire ensuite.", learning: "Apprentissage", readiness: "Préparation professionnelle", opportunity: "Opportunité", why: "Pourquoi collaborer", whyTitle: "Un parcours commun, de l’apprentissage à la confiance et aux opportunités.", whyCopy: "Les partenariats fonctionnent mieux avec un public clair, un besoin d’apprentissage réel et un résultat utile. Growvelt peut explorer avec votre équipe des idées de formation, d’ateliers pratiques, de soutien aux apprenants et de programmes axés sur la carrière.", ways: "Façons de travailler ensemble", waysTitle: "Des partenariats conçus autour de résultats utiles.", begin: "Comment nous commençons", beginTitle: "Une conversation claire avant tout engagement.", types: [{ title: "Partenaires entreprises", description: "Construisez avec Growvelt des formations pratiques, des programmes de développement de la main-d’œuvre, d’accès employeur ou de renforcement des capacités." }, { title: "Établissements universitaires", description: "Explorez le soutien aux apprenants, les ateliers pratiques, la collaboration sur les programmes et les initiatives de préparation professionnelle." }, { title: "Associations et ONG", description: "Travaillons ensemble sur des programmes inclusifs de compétences numériques et des opportunités d’apprentissage communautaires." }, { title: "Partenaires communautaires", description: "Reliez apprenants, chercheurs d’emploi, mentors et opportunités par des modèles réfléchis de recommandation ou de collaboration." }], steps: [{ title: "Partagez l’opportunité", description: "Dites-nous qui vous souhaitez accompagner et le résultat que vous voulez créer." }, { title: "Explorez l’adéquation", description: "Nous examinons ensemble l’idée, les parcours d’apprentissage disponibles et les besoins pratiques de mise en œuvre." }, { title: "Concevez la prochaine étape", description: "Convenez d’une manière ciblée d’avancer, avec des responsabilités claires et une valeur pour les apprenants." }] },
  es: { eyebrow: "Asóciate con Growvelt", title: "Construye con nosotros oportunidades prácticas de habilidades digitales.", intro: "Growvelt acerca el aprendizaje, el desarrollo profesional y la oportunidad. Recibimos colaboraciones que hacen más accesibles las habilidades útiles y los próximos pasos significativos.", start: "Inicia una conversación de colaboración", about: "Acerca de Growvelt", collaboration: "Una colaboración práctica", collaborationTitle: "Desarrollo de habilidades conectado con lo que las personas pueden hacer después.", learning: "Aprendizaje", readiness: "Preparación profesional", opportunity: "Oportunidad", why: "Por qué colaborar", whyTitle: "Una ruta compartida desde el aprendizaje hasta la confianza y la oportunidad.", whyCopy: "Las colaboraciones funcionan mejor cuando tienen una audiencia clara, una necesidad real de aprendizaje y un resultado útil. Growvelt puede explorar con tu equipo ideas de capacitación, talleres prácticos, apoyo a estudiantes y programas enfocados en la carrera.", ways: "Formas de trabajar juntos", waysTitle: "Colaboraciones diseñadas alrededor de resultados útiles.", begin: "Cómo empezamos", beginTitle: "Una conversación clara antes de un compromiso.", types: [{ title: "Socios corporativos", description: "Construye con Growvelt capacitación práctica, desarrollo de fuerza laboral, acceso para empleadores o programas de desarrollo de capacidades." }, { title: "Instituciones académicas", description: "Explora apoyo a estudiantes, talleres prácticos, colaboración curricular e iniciativas de preparación profesional." }, { title: "Organizaciones sin fines de lucro y ONG", description: "Trabajemos juntos en programas inclusivos de habilidades digitales y oportunidades de aprendizaje centradas en la comunidad." }, { title: "Socios comunitarios", description: "Conecta estudiantes, buscadores de empleo, mentores y oportunidades mediante modelos de recomendación o colaboración bien pensados." }], steps: [{ title: "Comparte la oportunidad", description: "Cuéntanos a quién quieres apoyar y el resultado que deseas crear." }, { title: "Explora el encaje", description: "Revisamos juntos la idea, las rutas de aprendizaje disponibles y las necesidades prácticas de entrega." }, { title: "Diseña el próximo paso", description: "Acordamos una forma enfocada de avanzar, con responsabilidades claras y valor para los estudiantes." }] },
} as const;

const typeIcons = [Building2, GraduationCap, HeartHandshake, Handshake];

export function PartnerPageContent() {
  const { locale } = useLanguage();
  const text = copy[locale];
  return <main>
    <section className="partner-hero section-shell" aria-labelledby="partner-title"><div><p className="eyebrow">{text.eyebrow}</p><h1 id="partner-title">{text.title}</h1><p>{text.intro}</p><div className="hero-actions"><a className="button button-primary" href="#partner-form">{text.start}</a><Link className="button button-secondary" href="/about">{text.about}</Link></div></div><aside className="partner-hero-card"><p className="eyebrow">{text.collaboration}</p><strong>{text.collaborationTitle}</strong><div><span>{text.learning}</span><ArrowRight aria-hidden="true" /><span>{text.readiness}</span><ArrowRight aria-hidden="true" /><span>{text.opportunity}</span></div></aside></section>
    <section className="section-shell partner-introduction" aria-labelledby="partner-why-title"><div><p className="eyebrow">{text.why}</p><h2 id="partner-why-title">{text.whyTitle}</h2></div><p>{text.whyCopy}</p></section>
    <section className="section-shell partner-type-grid" aria-labelledby="partner-types-title"><div className="partner-section-heading"><p className="eyebrow">{text.ways}</p><h2 id="partner-types-title">{text.waysTitle}</h2></div><div>{text.types.map(({ title, description }, index) => { const Icon = typeIcons[index]; return <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{description}</p></article>; })}</div></section>
    <section className="section-shell partner-process" aria-labelledby="partner-process-title"><div><p className="eyebrow">{text.begin}</p><h2 id="partner-process-title">{text.beginTitle}</h2></div><ol>{text.steps.map(({ title, description }, index) => <li key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{title}</strong><p>{description}</p></div></li>)}</ol></section>
    <div id="partner-form" className="section-shell"><PublicInquiryForm kind="partnership" /></div>
  </main>;
}
