-- Growvelt Courses website database schema.
-- Run this in a separate Supabase project for courses.growvelt.com.

create table if not exists public.course_contacts (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  phone text,
  type text,
  message text,
  source_page text,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source_page text,
  created_at timestamptz not null default now()
);

create table if not exists public.partner_requests (
  id bigint generated by default as identity primary key,
  full_name text,
  email text not null,
  phone text,
  partnership_type text,
  idea text,
  source_page text,
  created_at timestamptz not null default now()
);

create table if not exists public.course_registrations (
  id bigint generated by default as identity primary key,
  registration_ref text unique,
  full_name text not null,
  email text not null,
  phone text,
  course text not null,
  learning_mode text,
  experience_level text,
  message text,
  payment_status text not null default 'pending',
  payment_amount numeric(10, 2),
  payment_currency text,
  paystack_reference text unique,
  paystack_access_code text,
  paystack_transaction_id text,
  payer_email text,
  paid_at timestamptz,
  email_sent_at timestamptz,
  admin_notified_at timestamptz,
  source_page text,
  created_at timestamptz not null default now()
);

alter table public.course_registrations
  add column if not exists registration_ref text unique,
  add column if not exists payment_amount numeric(10, 2),
  add column if not exists payment_currency text,
  add column if not exists paystack_reference text,
  add column if not exists paystack_access_code text,
  add column if not exists paystack_transaction_id text,
  add column if not exists payer_email text,
  add column if not exists paid_at timestamptz,
  add column if not exists email_sent_at timestamptz,
  add column if not exists admin_notified_at timestamptz;

create unique index if not exists course_registrations_paystack_reference_key
on public.course_registrations (paystack_reference);

create table if not exists public.course_leads (
  id bigint generated by default as identity primary key,
  payload jsonb not null default '{}'::jsonb,
  source_page text,
  created_at timestamptz not null default now()
);

alter table public.course_contacts enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.partner_requests enable row level security;
alter table public.course_registrations enable row level security;
alter table public.course_leads enable row level security;

create policy "Allow public course contact submissions"
on public.course_contacts
for insert
to anon
with check (true);

create policy "Allow public newsletter subscriptions"
on public.newsletter_subscribers
for insert
to anon
with check (true);

create policy "Allow public partner requests"
on public.partner_requests
for insert
to anon
with check (true);

create policy "Allow public course registrations"
on public.course_registrations
for insert
to anon
with check (true);

create policy "Allow public course lead submissions"
on public.course_leads
for insert
to anon
with check (true);
