-- Growvelt Learning - Step 03 Seed Published Courses
-- Run this in Supabase SQL Editor after the learning platform tables exist.
-- This publishes the current website course list into public.learning_courses.
--
-- Safe to rerun:
-- Each course uses a unique slug. If the slug already exists, the course is updated.

insert into public.learning_courses (
  title,
  slug,
  summary,
  description,
  level,
  category,
  thumbnail_url,
  price_amount,
  price_currency,
  is_free,
  is_limited_time_free,
  status,
  published_at
)
values
  (
    'Data Analysis',
    'data-analysis',
    'Learn how to analyze and interpret data effectively for business decisions.',
    'Build practical data analysis skills with Excel, SQL, Power BI, and portfolio-ready reporting projects.',
    'Beginner to job-ready',
    'Data Analytics',
    'images/Data Analysis.png',
    360000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Data Analysis with Excel',
    'data-analysis-with-excel',
    'Learn spreadsheet analysis, cleaning, formulas, charts, and reporting workflows.',
    'Use Excel to clean data, analyze business questions, and prepare practical reports.',
    'Beginner',
    'Data Analytics',
    'images/Data Analysis.png',
    105000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Excel for Data Analysis',
    'excel-for-data-analysis',
    'Build strong Excel foundations for analysis, dashboards, and business reporting.',
    'Learn Excel formulas, pivot tables, charts, and structured analysis for real work.',
    'Beginner',
    'Data Analytics',
    'images/Data Analysis.png',
    105000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Business Analysis',
    'business-analysis',
    'Learn how to document requirements, map processes, and support business decisions.',
    'Build practical business analysis skills for requirements, stakeholder communication, and project documentation.',
    'Beginner to intermediate',
    'Business',
    'images/Building Dashboard Classes.png',
    230000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Data Science',
    'data-science',
    'Master data science concepts including Python, SQL, and machine learning foundations.',
    'Learn Python, data preparation, exploratory analysis, and introductory machine learning for practical projects.',
    'Intermediate',
    'Data Science',
    'images/Data Science.png',
    480000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Power BI for Business Analysis',
    'power-bi-for-business-analysis',
    'Create dashboards and reports that help teams understand performance and make decisions.',
    'Learn Power BI modeling, visualization, DAX basics, and dashboard storytelling.',
    'Beginner to intermediate',
    'Business Intelligence',
    'images/Building Dashboard Classes.png',
    110000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'SQL for Data Analytics',
    'sql-for-data-analytics',
    'Write SQL queries for filtering, joining, grouping, and reporting on data.',
    'Learn practical SQL for analytics, reporting, business questions, and portfolio projects.',
    'Beginner',
    'Data Analytics',
    'images/data.png',
    120000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Python for Data Analysis',
    'python-for-data-analysis',
    'Use Python to clean, analyze, and visualize data for real-world projects.',
    'Learn Python foundations, pandas, analysis workflows, and charts for analytics.',
    'Beginner to intermediate',
    'Data Analytics',
    'images/Data Science.png',
    130000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Python',
    'python',
    'Learn Python programming foundations for automation, analysis, and problem solving.',
    'Build Python basics including syntax, functions, files, data structures, and practical projects.',
    'Beginner',
    'Programming',
    'images/Data Science.png',
    120000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'R for Data Analysis',
    'r-for-data-analysis',
    'Learn R foundations for data cleaning, analysis, charts, and statistical reporting.',
    'Use R for practical analytics workflows, data visualization, and beginner-friendly reporting.',
    'Beginner',
    'Data Analytics',
    'images/data.png',
    120000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Web Development',
    'web-development',
    'Learn how to build responsive websites and practical web experiences.',
    'Build web pages with HTML, CSS, JavaScript, responsive layouts, and deployable projects.',
    'Beginner to job-ready',
    'Web Development',
    'images/Building Dashboard Classes.png',
    360000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Cybersecurity',
    'cybersecurity',
    'Learn cybersecurity foundations, safe systems thinking, and practical defensive concepts.',
    'Understand security basics, risk, networks, common threats, and defensive practices.',
    'Beginner',
    'Cybersecurity',
    'images/technology-7111798_1280.jpg',
    250000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Social Media Marketing',
    'social-media-marketing',
    'Grow your brand and engage audiences with practical digital marketing strategies.',
    'Learn content planning, audience growth, analytics, campaigns, and brand communication.',
    'Beginner',
    'Digital Marketing',
    'images/Social Media.png',
    180000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Graphics Design',
    'graphics-design',
    'Learn design principles, visual communication, and practical creative tools.',
    'Build graphics design skills for social media, brand assets, and professional visual projects.',
    'Beginner',
    'Creative Skills',
    'images/illustrator.png',
    150000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Basic Computer Literacy',
    'basic-computer-literacy',
    'Build confidence using computers, files, email, and everyday digital tools.',
    'Learn computer basics, internet use, file management, typing, and essential productivity skills.',
    'Beginner',
    'Digital Skills',
    'images/data.png',
    50000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Microsoft Word',
    'microsoft-word',
    'Learn document creation, formatting, editing, and professional Word workflows.',
    'Build Microsoft Word skills for school, business, office work, and professional documents.',
    'Beginner',
    'Productivity',
    'images/data.png',
    10000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Microsoft PowerPoint',
    'microsoft-powerpoint',
    'Create clear, professional presentations for school, work, and business.',
    'Learn slide design, presentation structure, visuals, and delivery-ready formatting.',
    'Beginner',
    'Productivity',
    'images/Building Dashboard Classes.png',
    10000,
    'NGN',
    false,
    false,
    'published',
    now()
  ),
  (
    'Google Drive',
    'google-drive',
    'Learn cloud file storage, sharing, collaboration, and Google Workspace basics.',
    'Use Google Drive to organize, share, collaborate, and manage files confidently.',
    'Beginner',
    'Productivity',
    'images/Google LOGO.png',
    70000,
    'NGN',
    false,
    false,
    'published',
    now()
  )
on conflict (slug) do update
set
  title = excluded.title,
  summary = excluded.summary,
  description = excluded.description,
  level = excluded.level,
  category = excluded.category,
  thumbnail_url = excluded.thumbnail_url,
  price_amount = excluded.price_amount,
  price_currency = excluded.price_currency,
  is_free = excluded.is_free,
  is_limited_time_free = excluded.is_limited_time_free,
  status = excluded.status,
  published_at = coalesce(public.learning_courses.published_at, excluded.published_at),
  updated_at = now();
