-- Phase 3C: immutable admin review decisions about company seller proceeds.
-- A review is evidence for a future release workflow, not a release, reserve,
-- payout approval, Paystack transfer, or live-checkout capability.
begin;

create table public.learning_company_seller_payout_reviews (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.learning_company_commercial_sales(purchase_id) on delete restrict,
  actor_user_id uuid not null references public.profiles(id) on delete restrict,
  decision text not null check (decision in ('continue_hold','approve_for_future_release')),
  evidence_reference text not null check (char_length(evidence_reference) between 8 and 200),
  idempotency_key text not null unique check (char_length(idempotency_key) between 8 and 120),
  remaining_held_minor_snapshot bigint not null check (remaining_held_minor_snapshot >= 0),
  review_state_snapshot text not null,
  reviewed_at timestamptz not null default now()
);

create index learning_company_seller_payout_reviews_purchase_idx
  on public.learning_company_seller_payout_reviews(purchase_id,reviewed_at desc,id desc);

alter table public.learning_company_seller_payout_reviews enable row level security;
revoke all on public.learning_company_seller_payout_reviews from public,anon,authenticated,service_role;
grant select on public.learning_company_seller_payout_reviews to service_role;

create trigger prevent_learning_company_seller_payout_review_mutation
before update or delete on public.learning_company_seller_payout_reviews
for each row execute function public.prevent_learning_company_sale_mutation();

create or replace function public.record_learning_company_seller_payout_review(
  p_purchase_id bigint,p_actor_user_id uuid,p_decision text,
  p_evidence_reference text,p_idempotency_key text)
returns bigint language plpgsql security definer set search_path to '' as $function$
declare purchase_row public.learning_company_paid_course_purchases%rowtype;
  existing public.learning_company_seller_payout_reviews%rowtype;
  review_row record; review_key bigint;
begin
  if p_purchase_id is null or p_actor_user_id is null
     or p_decision not in ('continue_hold','approve_for_future_release')
     or p_decision is null
     or char_length(btrim(coalesce(p_evidence_reference,''))) not between 8 and 200
     or char_length(btrim(coalesce(p_idempotency_key,''))) not between 8 and 120 then
    raise exception 'Invalid company seller review' using errcode = '22023';
  end if;
  if not exists (select 1 from public.account_capabilities capability
    where capability.user_id = p_actor_user_id and capability.capability = 'admin'
      and capability.status = 'active') then
    raise exception 'Active Learning Admin required' using errcode = '42501';
  end if;
  select * into purchase_row from public.learning_company_paid_course_purchases purchase
  where purchase.id = p_purchase_id for update;
  if not found then raise exception 'Company purchase not found' using errcode = 'P0002'; end if;

  select * into existing from public.learning_company_seller_payout_reviews review
  where review.idempotency_key = btrim(p_idempotency_key) for update;
  if found then
    if existing.purchase_id <> p_purchase_id or existing.actor_user_id <> p_actor_user_id
       or existing.decision <> p_decision
       or existing.evidence_reference <> btrim(p_evidence_reference) then
      raise exception 'Company seller review key conflicts with another decision'
        using errcode = '23505';
    end if;
    return existing.id;
  end if;

  select * into review_row from public.list_learning_company_seller_payout_review_queue() queue
  where queue.purchase_id = p_purchase_id;
  if not found then raise exception 'Company seller hold not found' using errcode = 'P0002'; end if;
  if p_decision = 'approve_for_future_release'
     and (review_row.review_state <> 'manual_admin_review_required'
       or review_row.remaining_held_minor <= 0) then
    raise exception 'Company seller proceeds still require a hold or case review'
      using errcode = '22023';
  end if;

  insert into public.learning_company_seller_payout_reviews(
    purchase_id,actor_user_id,decision,evidence_reference,idempotency_key,
    remaining_held_minor_snapshot,review_state_snapshot)
  values(p_purchase_id,p_actor_user_id,p_decision,btrim(p_evidence_reference),
    btrim(p_idempotency_key),review_row.remaining_held_minor,review_row.review_state)
  returning id into review_key;
  insert into public.learning_audit_events(
    actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(p_actor_user_id,'admin_operator','company_seller_payout.review_recorded',
    'learning_company_paid_course_purchase',p_purchase_id::text,
    jsonb_build_object('review_id',review_key,'decision',p_decision,
      'review_state',review_row.review_state,
      'remaining_held_minor',review_row.remaining_held_minor));
  return review_key;
end;$function$;

revoke all on function public.record_learning_company_seller_payout_review(
  bigint,uuid,text,text,text) from public,anon,authenticated;
grant execute on function public.record_learning_company_seller_payout_review(
  bigint,uuid,text,text,text) to postgres,service_role;

commit;
