-- Phase 0E: payment-provider-neutral financial transaction foundation.
-- This migration creates no checkout, accepts no payment, publishes no paid
-- course, and does not modify existing application rows.

drop policy if exists "Allow public course registrations" on public.course_registrations;
revoke all on table public.course_registrations from anon, authenticated;
grant select, insert, update, delete on table public.course_registrations to postgres, service_role;

create table public.learning_orders (
  id bigint generated by default as identity primary key,
  order_reference text not null unique default ('GL-' || upper(replace(gen_random_uuid()::text, '-', ''))),
  learner_id uuid references public.profiles(id) on delete set null,
  course_id bigint references public.learning_courses(id) on delete set null,
  instructor_id uuid references public.profiles(id) on delete set null,
  learner_reference uuid not null default gen_random_uuid(),
  course_title_snapshot text not null,
  instructor_name_snapshot text,
  gross_amount_minor bigint not null check (gross_amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  status text not null default 'created'
    check (status in ('created', 'payment_pending', 'paid', 'cancelled', 'partially_refunded', 'refunded', 'chargeback')),
  commercial_terms_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  cancelled_at timestamptz,
  constraint learning_orders_reference_format_check
    check (order_reference ~ '^GL-[A-F0-9]{32}$'),
  constraint learning_orders_status_timestamp_check check (
    (status in ('paid', 'partially_refunded', 'refunded', 'chargeback') and paid_at is not null and cancelled_at is null)
    or (status = 'cancelled' and cancelled_at is not null and paid_at is null)
    or (status in ('created', 'payment_pending') and paid_at is null and cancelled_at is null)
  )
);

create index learning_orders_learner_created_idx on public.learning_orders (learner_id, created_at desc, id desc);
create index learning_orders_course_created_idx on public.learning_orders (course_id, created_at desc, id desc);
create index learning_orders_status_created_idx on public.learning_orders (status, created_at desc, id desc);

create table public.learning_payment_attempts (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.learning_orders(id) on delete restrict,
  idempotency_key uuid not null unique default gen_random_uuid(),
  provider text not null check (provider ~ '^[a-z][a-z0-9_]{1,30}$'),
  provider_reference text,
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  status text not null default 'initialized'
    check (status in ('initialized', 'pending', 'succeeded', 'failed', 'abandoned')),
  initialized_at timestamptz not null default now(),
  verified_at timestamptz,
  failed_at timestamptz,
  failure_code text,
  failure_message text,
  constraint learning_payment_attempts_provider_reference_key unique (provider, provider_reference),
  constraint learning_payment_attempts_failure_message_length_check
    check (failure_message is null or char_length(failure_message) <= 1000),
  constraint learning_payment_attempts_status_timestamp_check check (
    (status = 'succeeded' and verified_at is not null and failed_at is null)
    or (status = 'failed' and failed_at is not null and verified_at is null)
    or (status in ('initialized', 'pending', 'abandoned') and verified_at is null and failed_at is null)
  )
);

create index learning_payment_attempts_order_idx on public.learning_payment_attempts (order_id, initialized_at desc, id desc);
create index learning_payment_attempts_status_idx on public.learning_payment_attempts (status, initialized_at desc, id desc);

create table public.learning_payment_provider_events (
  id bigint generated by default as identity primary key,
  provider text not null check (provider ~ '^[a-z][a-z0-9_]{1,30}$'),
  provider_event_id text not null,
  event_type text not null check (event_type ~ '^[a-zA-Z0-9_.:-]{2,100}$'),
  payload_digest text not null check (payload_digest ~ '^[a-f0-9]{64}$'),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  signature_valid boolean not null,
  processing_status text not null default 'received'
    check (processing_status in ('received', 'processed', 'ignored', 'failed')),
  order_id bigint references public.learning_orders(id) on delete restrict,
  payment_attempt_id bigint references public.learning_payment_attempts(id) on delete restrict,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text,
  constraint learning_payment_provider_events_provider_event_key unique (provider, provider_event_id),
  constraint learning_payment_provider_events_error_length_check
    check (processing_error is null or char_length(processing_error) <= 2000),
  constraint learning_payment_provider_events_processing_check
    check ((processing_status = 'received' and processed_at is null) or (processing_status <> 'received' and processed_at is not null))
);

create index learning_payment_provider_events_status_idx on public.learning_payment_provider_events (processing_status, received_at, id);
create index learning_payment_provider_events_order_idx on public.learning_payment_provider_events (order_id, received_at desc, id desc);

create table public.learning_ledger_transactions (
  id bigint generated by default as identity primary key,
  transaction_reference uuid not null unique default gen_random_uuid(),
  order_id bigint not null references public.learning_orders(id) on delete restrict,
  transaction_type text not null
    check (transaction_type in ('payment_capture', 'processor_fee', 'refund', 'chargeback', 'adjustment')),
  currency text not null check (currency = 'NGN'),
  occurred_at timestamptz not null default now(),
  description text,
  created_by uuid references public.profiles(id) on delete set null,
  constraint learning_ledger_transactions_description_length_check
    check (description is null or char_length(description) <= 1000)
);

create index learning_ledger_transactions_order_idx on public.learning_ledger_transactions (order_id, occurred_at, id);

create table public.learning_ledger_entries (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.learning_ledger_transactions(id) on delete restrict,
  line_number smallint not null check (line_number > 0),
  account_code text not null check (account_code ~ '^[a-z][a-z0-9_.]{2,80}$'),
  amount_minor bigint not null check (amount_minor <> 0),
  currency text not null check (currency = 'NGN'),
  counterparty_type text,
  counterparty_reference text,
  created_at timestamptz not null default now(),
  constraint learning_ledger_entries_transaction_line_key unique (transaction_id, line_number),
  constraint learning_ledger_entries_counterparty_type_check
    check (counterparty_type is null or counterparty_type ~ '^[a-z][a-z0-9_]{1,40}$')
);

create index learning_ledger_entries_account_idx on public.learning_ledger_entries (account_code, created_at, id);

create table public.learning_course_entitlements (
  id bigint generated by default as identity primary key,
  learner_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.learning_courses(id) on delete restrict,
  order_id bigint not null unique references public.learning_orders(id) on delete restrict,
  enrollment_id bigint unique references public.enrollments(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'revoked', 'refunded', 'chargeback')),
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  revocation_reason text,
  constraint learning_course_entitlements_learner_course_key unique (learner_id, course_id),
  constraint learning_course_entitlements_revocation_reason_length_check
    check (revocation_reason is null or char_length(revocation_reason) <= 1000),
  constraint learning_course_entitlements_status_timestamp_check
    check ((status = 'active' and revoked_at is null) or (status <> 'active' and revoked_at is not null))
);

create index learning_course_entitlements_course_idx on public.learning_course_entitlements (course_id, status, granted_at desc);

create table public.learning_payment_cases (
  id bigint generated by default as identity primary key,
  case_reference uuid not null unique default gen_random_uuid(),
  order_id bigint not null references public.learning_orders(id) on delete restrict,
  payment_attempt_id bigint references public.learning_payment_attempts(id) on delete restrict,
  case_type text not null check (case_type in ('refund', 'chargeback')),
  status text not null default 'opened'
    check (status in ('opened', 'pending', 'succeeded', 'failed', 'cancelled', 'won', 'lost')),
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  reason text,
  provider_case_reference text,
  initiated_by uuid references public.profiles(id) on delete set null,
  opened_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint learning_payment_cases_provider_reference_key unique (case_type, provider_case_reference),
  constraint learning_payment_cases_reason_length_check check (reason is null or char_length(reason) <= 2000),
  constraint learning_payment_cases_resolution_check
    check ((status in ('opened', 'pending') and resolved_at is null) or (status in ('succeeded', 'failed', 'cancelled', 'won', 'lost') and resolved_at is not null))
);

create index learning_payment_cases_order_idx on public.learning_payment_cases (order_id, opened_at desc, id desc);
create index learning_payment_cases_status_idx on public.learning_payment_cases (status, opened_at, id);

alter table public.learning_orders enable row level security;
alter table public.learning_payment_attempts enable row level security;
alter table public.learning_payment_provider_events enable row level security;
alter table public.learning_ledger_transactions enable row level security;
alter table public.learning_ledger_entries enable row level security;
alter table public.learning_course_entitlements enable row level security;
alter table public.learning_payment_cases enable row level security;

revoke all on table public.learning_orders, public.learning_payment_attempts,
  public.learning_payment_provider_events, public.learning_ledger_transactions,
  public.learning_ledger_entries, public.learning_course_entitlements,
  public.learning_payment_cases from public, anon, authenticated;
grant select, insert, update, delete on table public.learning_orders,
  public.learning_payment_attempts, public.learning_payment_provider_events,
  public.learning_ledger_transactions, public.learning_ledger_entries,
  public.learning_course_entitlements, public.learning_payment_cases to postgres, service_role;

revoke all on sequence public.learning_orders_id_seq,
  public.learning_payment_attempts_id_seq, public.learning_payment_provider_events_id_seq,
  public.learning_ledger_transactions_id_seq, public.learning_ledger_entries_id_seq,
  public.learning_course_entitlements_id_seq, public.learning_payment_cases_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.learning_orders_id_seq,
  public.learning_payment_attempts_id_seq, public.learning_payment_provider_events_id_seq,
  public.learning_ledger_transactions_id_seq, public.learning_ledger_entries_id_seq,
  public.learning_course_entitlements_id_seq, public.learning_payment_cases_id_seq
  to postgres, service_role;

create or replace function public.protect_learning_order_financial_snapshot()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if old.order_reference is distinct from new.order_reference
    or old.learner_reference is distinct from new.learner_reference
    or old.course_title_snapshot is distinct from new.course_title_snapshot
    or old.instructor_name_snapshot is distinct from new.instructor_name_snapshot
    or old.gross_amount_minor is distinct from new.gross_amount_minor
    or old.currency is distinct from new.currency
    or old.commercial_terms_version is distinct from new.commercial_terms_version
    or (old.learner_id is distinct from new.learner_id and new.learner_id is not null)
    or (old.course_id is distinct from new.course_id and new.course_id is not null)
    or (old.instructor_id is distinct from new.instructor_id and new.instructor_id is not null)
  then
    raise exception 'Learning order financial snapshots are immutable' using errcode = '42501';
  end if;

  if old.status is distinct from new.status and not (
    (old.status = 'created' and new.status in ('payment_pending', 'cancelled'))
    or (old.status = 'payment_pending' and new.status in ('paid', 'cancelled'))
    or (old.status = 'paid' and new.status in ('partially_refunded', 'refunded', 'chargeback'))
    or (old.status = 'partially_refunded' and new.status in ('refunded', 'chargeback'))
    or (old.status = 'refunded' and new.status = 'chargeback')
  ) then
    raise exception 'Unsupported learning order status transition' using errcode = '22023';
  end if;

  new.updated_at := now();
  return new;
end;
$function$;

create or replace function public.validate_learning_payment_attempt()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare order_row record;
begin
  select gross_amount_minor, currency into order_row
  from public.learning_orders where id = new.order_id;
  if not found or new.amount_minor <> order_row.gross_amount_minor or new.currency <> order_row.currency then
    raise exception 'Payment attempt amount must match its authoritative order snapshot' using errcode = '22023';
  end if;
  return new;
end;
$function$;

create or replace function public.prevent_learning_financial_record_delete()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  raise exception 'Financial history is retained and cannot be deleted' using errcode = '42501';
end;
$function$;

create or replace function public.validate_learning_course_entitlement()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare order_row record;
begin
  select learner_id, course_id, status into order_row from public.learning_orders where id = new.order_id;
  if not found or order_row.status <> 'paid' or order_row.learner_id is distinct from new.learner_id
    or order_row.course_id is distinct from new.course_id
  then raise exception 'Paid entitlement must match a paid authoritative order' using errcode = '22023'; end if;
  return new;
end;
$function$;

create or replace function public.validate_learning_payment_case()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare order_row record;
begin
  select gross_amount_minor, currency into order_row from public.learning_orders where id = new.order_id;
  if not found or new.amount_minor > order_row.gross_amount_minor or new.currency <> order_row.currency then
    raise exception 'Payment case amount must fit its authoritative order' using errcode = '22023';
  end if;
  if new.payment_attempt_id is not null and not exists (
    select 1 from public.learning_payment_attempts where id = new.payment_attempt_id and order_id = new.order_id
  ) then raise exception 'Payment case attempt does not belong to its order' using errcode = '22023'; end if;
  return new;
end;
$function$;

create or replace function public.validate_learning_provider_event_links()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if new.order_id is not null and new.payment_attempt_id is not null and not exists (
    select 1 from public.learning_payment_attempts where id = new.payment_attempt_id and order_id = new.order_id
  ) then raise exception 'Provider event attempt does not belong to its order' using errcode = '22023'; end if;
  return new;
end;
$function$;

create or replace function public.prevent_learning_ledger_mutation()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  raise exception 'Financial ledger records are append-only' using errcode = '42501';
end;
$function$;

create or replace function public.assert_learning_ledger_transaction_balanced()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare transaction_key bigint;
declare ledger_currency text;
declare entry_count integer;
declare net_amount bigint;
begin
  if tg_table_name = 'learning_ledger_transactions' then
    transaction_key := new.id;
  elsif tg_op = 'DELETE' then
    transaction_key := old.transaction_id;
  else
    transaction_key := new.transaction_id;
  end if;
  select currency into ledger_currency from public.learning_ledger_transactions where id = transaction_key;
  select count(*)::integer, coalesce(sum(amount_minor), 0)::bigint
    into entry_count, net_amount
  from public.learning_ledger_entries where transaction_id = transaction_key;
  if ledger_currency is null or entry_count < 2 or net_amount <> 0
    or exists (select 1 from public.learning_ledger_entries where transaction_id = transaction_key and currency <> ledger_currency)
  then
    raise exception 'Ledger transaction must contain at least two balanced entries in one currency' using errcode = '23514';
  end if;
  return new;
end;
$function$;

create or replace function public.capture_learning_financial_audit_event()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare entity_key text;
declare event_metadata jsonb;
begin
  entity_key := new.id::text;
  event_metadata := jsonb_build_object(
    'old_status', case when tg_op = 'INSERT' then null else old.status end,
    'new_status', new.status
  );
  insert into public.learning_audit_events (actor_user_id, actor_role, action, entity_type, entity_id, metadata)
  values (auth.uid(), coalesce(auth.role(), 'database'), tg_argv[0], tg_argv[1], entity_key, event_metadata);
  return new;
end;
$function$;

revoke all on function public.protect_learning_order_financial_snapshot(),
  public.validate_learning_payment_attempt(), public.prevent_learning_financial_record_delete(),
  public.validate_learning_course_entitlement(), public.validate_learning_payment_case(),
  public.validate_learning_provider_event_links(),
  public.prevent_learning_ledger_mutation(), public.assert_learning_ledger_transaction_balanced(),
  public.capture_learning_financial_audit_event() from public, anon, authenticated;
grant execute on function public.protect_learning_order_financial_snapshot(),
  public.validate_learning_payment_attempt(), public.prevent_learning_financial_record_delete(),
  public.validate_learning_course_entitlement(), public.validate_learning_payment_case(),
  public.validate_learning_provider_event_links(),
  public.prevent_learning_ledger_mutation(), public.assert_learning_ledger_transaction_balanced(),
  public.capture_learning_financial_audit_event() to postgres, service_role;

create trigger protect_learning_order_financial_snapshot
before update on public.learning_orders
for each row execute function public.protect_learning_order_financial_snapshot();

create trigger validate_learning_payment_attempt
before insert or update of order_id, amount_minor, currency on public.learning_payment_attempts
for each row execute function public.validate_learning_payment_attempt();

create trigger validate_learning_provider_event_links
before insert or update of order_id, payment_attempt_id on public.learning_payment_provider_events
for each row execute function public.validate_learning_provider_event_links();

create trigger validate_learning_course_entitlement
before insert or update of learner_id, course_id, order_id on public.learning_course_entitlements
for each row execute function public.validate_learning_course_entitlement();

create trigger validate_learning_payment_case
before insert or update of order_id, payment_attempt_id, amount_minor, currency on public.learning_payment_cases
for each row execute function public.validate_learning_payment_case();

create trigger prevent_learning_order_delete before delete on public.learning_orders
for each row execute function public.prevent_learning_financial_record_delete();
create trigger prevent_learning_payment_attempt_delete before delete on public.learning_payment_attempts
for each row execute function public.prevent_learning_financial_record_delete();
create trigger prevent_learning_provider_event_delete before delete on public.learning_payment_provider_events
for each row execute function public.prevent_learning_financial_record_delete();
create trigger prevent_learning_payment_case_delete before delete on public.learning_payment_cases
for each row execute function public.prevent_learning_financial_record_delete();

create trigger prevent_learning_ledger_transaction_update_delete
before update or delete on public.learning_ledger_transactions
for each row execute function public.prevent_learning_ledger_mutation();
create trigger prevent_learning_ledger_entry_update_delete
before update or delete on public.learning_ledger_entries
for each row execute function public.prevent_learning_ledger_mutation();

create constraint trigger assert_learning_ledger_entry_balanced
after insert on public.learning_ledger_entries
deferrable initially deferred
for each row execute function public.assert_learning_ledger_transaction_balanced();

create constraint trigger assert_learning_ledger_transaction_balanced
after insert on public.learning_ledger_transactions
deferrable initially deferred
for each row execute function public.assert_learning_ledger_transaction_balanced();

create trigger audit_learning_order_insert after insert on public.learning_orders
for each row execute function public.capture_learning_financial_audit_event('order.created', 'learning_order');
create trigger audit_learning_order_status after update of status on public.learning_orders
for each row when (old.status is distinct from new.status)
execute function public.capture_learning_financial_audit_event('order.status_changed', 'learning_order');
create trigger audit_learning_entitlement_insert after insert on public.learning_course_entitlements
for each row execute function public.capture_learning_financial_audit_event('entitlement.created', 'course_entitlement');
create trigger audit_learning_entitlement_status after update of status on public.learning_course_entitlements
for each row when (old.status is distinct from new.status)
execute function public.capture_learning_financial_audit_event('entitlement.status_changed', 'course_entitlement');
create trigger audit_learning_payment_case_insert after insert on public.learning_payment_cases
for each row execute function public.capture_learning_financial_audit_event('payment_case.created', 'payment_case');
create trigger audit_learning_payment_case_status after update of status on public.learning_payment_cases
for each row when (old.status is distinct from new.status)
execute function public.capture_learning_financial_audit_event('payment_case.status_changed', 'payment_case');
