-- Phase 3A1: company learning workspaces, employee seats, and invitations.
-- This customer workspace is separate from provider organizations, courses,
-- instructor earnings, payouts, and commercial reporting.
begin;

create table public.learning_company_workspaces (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 2 and 160),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' and char_length(slug) between 3 and 100),
  status text not null default 'active' check (status in ('active','suspended','archived')),
  created_by uuid not null references public.profiles(id) on delete restrict,
  seat_limit integer not null default 25 check (seat_limit between 1 and 100000),
  created_at timestamptz not null default now(),
  suspended_at timestamptz,
  archived_at timestamptz,
  constraint learning_company_workspaces_lifecycle_check check (
    (status='active' and suspended_at is null and archived_at is null)
    or (status='suspended' and suspended_at is not null and archived_at is null)
    or (status='archived' and archived_at is not null)
  )
);
create index learning_company_workspaces_created_by_idx on public.learning_company_workspaces(created_by,created_at desc,id desc);

create table public.learning_company_memberships (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.learning_company_workspaces(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete restrict,
  role text not null check (role in ('owner','admin','member')),
  status text not null default 'active' check (status in ('active','suspended','removed')),
  granted_by uuid not null references public.profiles(id) on delete restrict,
  granted_at timestamptz not null default now(),
  ended_at timestamptz,
  end_reason text check (end_reason is null or char_length(end_reason) between 2 and 500),
  constraint learning_company_memberships_lifecycle_check check (
    (status='active' and ended_at is null and end_reason is null)
    or (status in ('suspended','removed') and ended_at is not null)
  )
);
create unique index learning_company_memberships_one_active_member on public.learning_company_memberships(workspace_id,user_id) where status='active';
create unique index learning_company_memberships_one_active_owner on public.learning_company_memberships(workspace_id) where status='active' and role='owner';
create index learning_company_memberships_user_idx on public.learning_company_memberships(user_id,status,granted_at desc,id desc);

create table public.learning_company_invitations (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.learning_company_workspaces(id) on delete restrict,
  invited_email text not null check (invited_email=lower(btrim(invited_email)) and char_length(invited_email) between 3 and 320),
  invited_user_id uuid references public.profiles(id) on delete restrict,
  role text not null check (role in ('admin','member')),
  status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled','expired')),
  invited_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  expires_at timestamptz not null default (now()+interval '30 days'),
  constraint learning_company_invitations_lifecycle_check check ((status='pending' and responded_at is null) or (status in ('accepted','declined','cancelled','expired') and responded_at is not null)),
  constraint learning_company_invitations_expiry_check check (expires_at > created_at)
);
create unique index learning_company_invitations_one_pending on public.learning_company_invitations(workspace_id,invited_email) where status='pending';
create index learning_company_invitations_recipient_idx on public.learning_company_invitations(invited_email,status,created_at desc,id desc);

create table public.learning_company_membership_events (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.learning_company_workspaces(id) on delete restrict,
  membership_id bigint references public.learning_company_memberships(id) on delete restrict,
  invitation_id bigint references public.learning_company_invitations(id) on delete restrict,
  event_type text not null check (event_type in ('workspace.created','membership.created','membership.removed','invitation.created','invitation.accepted','invitation.declined','invitation.cancelled','invitation.expired')),
  actor_user_id uuid references public.profiles(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  occurred_at timestamptz not null default now()
);
create index learning_company_membership_events_workspace_idx on public.learning_company_membership_events(workspace_id,occurred_at,id);

create table public.learning_company_notifications (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique check (char_length(idempotency_key) between 8 and 240),
  invitation_id bigint references public.learning_company_invitations(id) on delete restrict,
  recipient_email text not null check (char_length(recipient_email) between 3 and 320),
  delivery_status text not null default 'pending' check (delivery_status in ('pending','sent','failed','not_configured')),
  provider_message_id text,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error text check (last_error is null or char_length(last_error) <= 1000),
  created_at timestamptz not null default now(),
  last_attempted_at timestamptz,
  sent_at timestamptz
);

alter table public.learning_company_workspaces enable row level security;
alter table public.learning_company_memberships enable row level security;
alter table public.learning_company_invitations enable row level security;
alter table public.learning_company_membership_events enable row level security;
alter table public.learning_company_notifications enable row level security;
revoke all on public.learning_company_workspaces,public.learning_company_memberships,public.learning_company_invitations,public.learning_company_membership_events,public.learning_company_notifications from public,anon,authenticated;
grant select,insert,update,delete on public.learning_company_workspaces,public.learning_company_memberships,public.learning_company_invitations,public.learning_company_membership_events,public.learning_company_notifications to postgres,service_role;
grant usage,select on sequence public.learning_company_workspaces_id_seq,public.learning_company_memberships_id_seq,public.learning_company_invitations_id_seq,public.learning_company_membership_events_id_seq,public.learning_company_notifications_id_seq to postgres,service_role;

create or replace function public.create_own_learning_company_workspace(p_name text,p_slug text)
returns table(workspace_id bigint,name text,slug text,status text,seat_limit integer,created_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare workspace_key bigint; normalized_name text:=btrim(p_name); normalized_slug text:=lower(btrim(p_slug));
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if normalized_name is null or char_length(normalized_name) not between 2 and 160 or normalized_slug is null or normalized_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' or char_length(normalized_slug) not between 3 and 100 then raise exception 'Invalid company workspace identity' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-company-owner:'||auth.uid()::text,0));
  if exists(select 1 from public.learning_company_memberships membership join public.learning_company_workspaces workspace on workspace.id=membership.workspace_id where membership.user_id=auth.uid() and membership.role='owner' and membership.status='active' and workspace.status='active') then raise exception 'This account already owns an active company workspace' using errcode='P0001'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-company-workspace:'||normalized_slug,0));
  insert into public.learning_company_workspaces(name,slug,created_by) values(normalized_name,normalized_slug,auth.uid()) returning id into workspace_key;
  insert into public.learning_company_memberships(workspace_id,user_id,role,granted_by) values(workspace_key,auth.uid(),'owner',auth.uid());
  insert into public.learning_company_membership_events(workspace_id,membership_id,event_type,actor_user_id,metadata) select workspace_key,membership.id,'workspace.created',auth.uid(),jsonb_build_object('source','company_workspace.create','seat_limit',25) from public.learning_company_memberships membership where membership.workspace_id=workspace_key and membership.user_id=auth.uid() and membership.status='active';
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(auth.uid(),'learner','company_workspace.created','learning_company_workspace',workspace_key::text,jsonb_build_object('slug',normalized_slug));
  return query select workspace.id,workspace.name,workspace.slug,workspace.status,workspace.seat_limit,workspace.created_at from public.learning_company_workspaces workspace where workspace.id=workspace_key;
end;$function$;

create or replace function public.list_own_learning_company_workspaces()
returns table(workspace_id bigint,name text,slug text,workspace_status text,membership_role text,membership_status text,seat_limit integer,active_member_count bigint,pending_invitation_count bigint,created_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  return query select workspace.id,workspace.name,workspace.slug,workspace.status,membership.role,membership.status,workspace.seat_limit,
    (select count(*) from public.learning_company_memberships active_members where active_members.workspace_id=workspace.id and active_members.status='active'),
    (select count(*) from public.learning_company_invitations pending_invitations where pending_invitations.workspace_id=workspace.id and pending_invitations.status='pending'),workspace.created_at
    from public.learning_company_memberships membership join public.learning_company_workspaces workspace on workspace.id=membership.workspace_id where membership.user_id=auth.uid() order by workspace.created_at desc,workspace.id desc;
end;$function$;

create or replace function public.create_learning_company_invitation(p_workspace_id bigint,p_invited_email text,p_role text)
returns table(invitation_id bigint,workspace_id bigint,invited_email text,role text,status text,expires_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare invitation_key bigint; normalized_email text:=lower(btrim(p_invited_email)); invitee_id uuid; existing public.learning_company_invitations%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if p_workspace_id is null or normalized_email is null or char_length(normalized_email) not between 3 and 320 or p_role not in ('admin','member') then raise exception 'Invalid company invitation' using errcode='22023'; end if;
  if not exists(select 1 from public.learning_company_workspaces workspace join public.learning_company_memberships membership on membership.workspace_id=workspace.id where workspace.id=p_workspace_id and workspace.status='active' and membership.user_id=auth.uid() and membership.role in ('owner','admin') and membership.status='active') then raise exception 'Active company manager required' using errcode='42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-company-invitation:'||p_workspace_id::text||':'||normalized_email,0));
  select id into invitee_id from public.profiles where email=normalized_email;
  if invitee_id is not null and exists(select 1 from public.learning_company_memberships member where member.workspace_id=p_workspace_id and member.user_id=invitee_id and member.status='active') then raise exception 'This person is already an active company member' using errcode='23505'; end if;
  select * into existing from public.learning_company_invitations invitation where invitation.workspace_id=p_workspace_id and invitation.invited_email=normalized_email and invitation.status='pending' for update;
  if found then return query select existing.id,existing.workspace_id,existing.invited_email,existing.role,existing.status,existing.expires_at; return; end if;
  if (select count(*) from public.learning_company_memberships member where member.workspace_id=p_workspace_id and member.status='active') + (select count(*) from public.learning_company_invitations invitation where invitation.workspace_id=p_workspace_id and invitation.status='pending') >= (select seat_limit from public.learning_company_workspaces where id=p_workspace_id) then raise exception 'Company seat limit reached' using errcode='P0001'; end if;
  insert into public.learning_company_invitations(workspace_id,invited_email,invited_user_id,role,invited_by) values(p_workspace_id,normalized_email,invitee_id,p_role,auth.uid()) returning id into invitation_key;
  insert into public.learning_company_membership_events(workspace_id,invitation_id,event_type,actor_user_id,metadata) values(p_workspace_id,invitation_key,'invitation.created',auth.uid(),jsonb_build_object('role',p_role,'email',normalized_email));
  return query select invitation.id,invitation.workspace_id,invitation.invited_email,invitation.role,invitation.status,invitation.expires_at from public.learning_company_invitations invitation where invitation.id=invitation_key;
end;$function$;

create or replace function public.list_own_learning_company_invitations()
returns table(invitation_id bigint,workspace_id bigint,workspace_name text,role text,status text,invited_by_name text,expires_at timestamptz,created_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
declare current_email text;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  select lower(email) into current_email from public.profiles where id=auth.uid();
  return query select invitation.id,invitation.workspace_id,workspace.name,invitation.role,invitation.status,coalesce(inviter.full_name,invitation.invited_email),invitation.expires_at,invitation.created_at from public.learning_company_invitations invitation join public.learning_company_workspaces workspace on workspace.id=invitation.workspace_id left join public.profiles inviter on inviter.id=invitation.invited_by where invitation.status='pending' and workspace.status='active' and (invitation.invited_user_id=auth.uid() or invitation.invited_email=current_email) order by invitation.created_at desc,invitation.id desc;
end;$function$;

create or replace function public.list_own_learning_company_members(p_workspace_id bigint)
returns table(member_id uuid,full_name text,email text,role text,status text,granted_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or not exists(select 1 from public.learning_company_memberships membership where membership.workspace_id=p_workspace_id and membership.user_id=auth.uid() and membership.status='active') then raise exception 'Active company membership required' using errcode='42501'; end if;
  return query select membership.user_id,profile.full_name,profile.email,membership.role,membership.status,membership.granted_at from public.learning_company_memberships membership join public.profiles profile on profile.id=membership.user_id where membership.workspace_id=p_workspace_id order by case membership.role when 'owner' then 1 when 'admin' then 2 else 3 end,profile.full_name nulls last,profile.email;
end;$function$;

create or replace function public.list_own_learning_company_invitations_as_manager(p_workspace_id bigint)
returns table(invitation_id bigint,invited_email text,role text,status text,created_at timestamptz,expires_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or not exists(select 1 from public.learning_company_memberships membership join public.learning_company_workspaces workspace on workspace.id=membership.workspace_id where membership.workspace_id=p_workspace_id and membership.user_id=auth.uid() and membership.role in ('owner','admin') and membership.status='active' and workspace.status='active') then raise exception 'Active company manager required' using errcode='42501'; end if;
  return query select invitation.id,invitation.invited_email,invitation.role,invitation.status,invitation.created_at,invitation.expires_at from public.learning_company_invitations invitation where invitation.workspace_id=p_workspace_id order by invitation.created_at desc,invitation.id desc;
end;$function$;

create or replace function public.respond_to_learning_company_invitation(p_invitation_id bigint,p_response text)
returns table(workspace_id bigint,role text,status text)
language plpgsql security definer set search_path to '' as $function$
declare current_email text; invitation public.learning_company_invitations%rowtype; membership_key bigint;
begin
  if auth.uid() is null or p_response not in ('accepted','declined') then raise exception 'Invalid company invitation response' using errcode='22023'; end if;
  select lower(email) into current_email from public.profiles where id=auth.uid();
  select * into invitation from public.learning_company_invitations company_invitation where company_invitation.id=p_invitation_id and company_invitation.status='pending' and (company_invitation.invited_user_id=auth.uid() or company_invitation.invited_email=current_email) for update;
  if not found or invitation.expires_at<=now() then raise exception 'Company invitation is unavailable' using errcode='P0002'; end if;
  if p_response='declined' then update public.learning_company_invitations set status='declined',responded_at=now() where id=invitation.id; insert into public.learning_company_membership_events(workspace_id,invitation_id,event_type,actor_user_id) values(invitation.workspace_id,invitation.id,'invitation.declined',auth.uid()); return query select invitation.workspace_id,invitation.role,'declined'::text; return; end if;
  if not exists(select 1 from public.learning_company_workspaces workspace where workspace.id=invitation.workspace_id and workspace.status='active') then raise exception 'Company workspace is unavailable' using errcode='P0002'; end if;
  if exists(select 1 from public.learning_company_memberships membership where membership.workspace_id=invitation.workspace_id and membership.user_id=auth.uid() and membership.status='active') then raise exception 'Already an active company member' using errcode='23505'; end if;
  insert into public.learning_company_memberships(workspace_id,user_id,role,granted_by) values(invitation.workspace_id,auth.uid(),invitation.role,invitation.invited_by) returning id into membership_key;
  update public.learning_company_invitations set status='accepted',responded_at=now(),invited_user_id=auth.uid() where id=invitation.id;
  insert into public.learning_company_membership_events(workspace_id,membership_id,invitation_id,event_type,actor_user_id,metadata) values(invitation.workspace_id,membership_key,invitation.id,'invitation.accepted',auth.uid(),jsonb_build_object('role',invitation.role));
  return query select invitation.workspace_id,invitation.role,'accepted'::text;
end;$function$;

create or replace function public.cancel_learning_company_invitation(p_workspace_id bigint,p_invitation_id bigint)
returns void language plpgsql security definer set search_path to '' as $function$
declare invitation public.learning_company_invitations%rowtype;
begin
  if auth.uid() is null or not exists(select 1 from public.learning_company_memberships where workspace_id=p_workspace_id and user_id=auth.uid() and role in ('owner','admin') and status='active') then raise exception 'Active company manager required' using errcode='42501'; end if;
  select * into invitation from public.learning_company_invitations where id=p_invitation_id and workspace_id=p_workspace_id and status='pending' for update;
  if not found then raise exception 'Pending company invitation not found' using errcode='P0002'; end if;
  update public.learning_company_invitations set status='cancelled',responded_at=now() where id=invitation.id;
  insert into public.learning_company_membership_events(workspace_id,invitation_id,event_type,actor_user_id) values(p_workspace_id,invitation.id,'invitation.cancelled',auth.uid());
end;$function$;

create or replace function public.remove_learning_company_member(p_workspace_id bigint,p_member_id uuid)
returns void language plpgsql security definer set search_path to '' as $function$
declare target public.learning_company_memberships%rowtype;
begin
  if auth.uid() is null or not exists(select 1 from public.learning_company_memberships where workspace_id=p_workspace_id and user_id=auth.uid() and role in ('owner','admin') and status='active') then raise exception 'Active company manager required' using errcode='42501'; end if;
  select * into target from public.learning_company_memberships where workspace_id=p_workspace_id and user_id=p_member_id and status='active' for update;
  if not found or target.role='owner' then raise exception 'Company member cannot be removed' using errcode='42501'; end if;
  if target.role='admin' and not exists(select 1 from public.learning_company_memberships where workspace_id=p_workspace_id and user_id=auth.uid() and role='owner' and status='active') then raise exception 'Only company owner can remove an admin' using errcode='42501'; end if;
  update public.learning_company_memberships set status='removed',ended_at=now(),end_reason='Removed by company manager' where id=target.id;
  insert into public.learning_company_membership_events(workspace_id,membership_id,event_type,actor_user_id) values(p_workspace_id,target.id,'membership.removed',auth.uid());
end;$function$;

revoke all on function public.create_own_learning_company_workspace(text,text),public.list_own_learning_company_workspaces(),public.create_learning_company_invitation(bigint,text,text),public.list_own_learning_company_invitations(),public.list_own_learning_company_members(bigint),public.list_own_learning_company_invitations_as_manager(bigint),public.respond_to_learning_company_invitation(bigint,text),public.cancel_learning_company_invitation(bigint,bigint),public.remove_learning_company_member(bigint,uuid) from public,anon,authenticated;
grant execute on function public.create_own_learning_company_workspace(text,text),public.list_own_learning_company_workspaces(),public.create_learning_company_invitation(bigint,text,text),public.list_own_learning_company_invitations(),public.list_own_learning_company_members(bigint),public.list_own_learning_company_invitations_as_manager(bigint),public.respond_to_learning_company_invitation(bigint,text),public.cancel_learning_company_invitation(bigint,bigint),public.remove_learning_company_member(bigint,uuid) to authenticated,postgres,service_role;

commit;
