-- Phase 1C2B: bounded, auditable operations for the existing authoritative
-- matured-earnings release routine. No payout, transfer, or economic rule is added.

begin;

create table public.learning_instructor_earnings_release_runs (
  id bigint generated by default as identity primary key,
  invocation_source text not null check (invocation_source in ('scheduler','admin_recovery')),
  actor_user_id uuid references public.profiles(id) on delete restrict,
  status text not null default 'started' check (status in ('started','succeeded','failed')),
  released_count integer not null default 0 check (released_count between 0 and 100),
  failure_code text check (failure_code is null or failure_code ~ '^[a-z][a-z0-9_]{2,80}$'),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint learning_instructor_earnings_release_runs_actor_check check (
    (invocation_source='scheduler' and actor_user_id is null) or
    (invocation_source='admin_recovery' and actor_user_id is not null)
  ),
  constraint learning_instructor_earnings_release_runs_lifecycle_check check (
    (status='started' and completed_at is null and released_count=0 and failure_code is null) or
    (status='succeeded' and completed_at is not null and failure_code is null) or
    (status='failed' and completed_at is not null and released_count=0 and failure_code is not null)
  )
);
create index learning_instructor_earnings_release_runs_recent_idx
  on public.learning_instructor_earnings_release_runs(started_at desc,id desc);

alter table public.learning_instructor_earnings_release_runs enable row level security;
revoke all on public.learning_instructor_earnings_release_runs from public,anon,authenticated;
grant select,insert,update,delete on public.learning_instructor_earnings_release_runs to postgres,service_role;

create or replace function public.prevent_learning_instructor_earnings_release_run_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if tg_op='DELETE' then
    raise exception 'Earnings release run history is retained and cannot be deleted' using errcode='42501';
  end if;
  if old.invocation_source is distinct from new.invocation_source
    or old.actor_user_id is distinct from new.actor_user_id
    or old.started_at is distinct from new.started_at then
    raise exception 'Earnings release run identity is immutable' using errcode='42501';
  end if;
  if old.status<>'started' then
    raise exception 'Completed earnings release run cannot be changed' using errcode='42501';
  end if;
  if new.status='succeeded' and new.completed_at is not null and new.failure_code is null and new.released_count between 0 and 100 then
    return new;
  end if;
  if new.status='failed' and new.completed_at is not null and new.released_count=0 and new.failure_code is not null then
    return new;
  end if;
  raise exception 'Unsupported earnings release run transition' using errcode='22023';
end;$function$;

create trigger prevent_learning_instructor_earnings_release_run_mutation
before update or delete on public.learning_instructor_earnings_release_runs
for each row execute function public.prevent_learning_instructor_earnings_release_run_mutation();

create or replace function public.start_learning_instructor_earnings_release_run(
  p_invocation_source text,
  p_actor_user_id uuid default null
)
returns bigint language plpgsql security definer set search_path to '' as $function$
declare run_id bigint;
begin
  if p_invocation_source not in ('scheduler','admin_recovery') then
    raise exception 'Invalid earnings release invocation source' using errcode='22023';
  end if;
  if p_invocation_source='scheduler' and p_actor_user_id is not null then
    raise exception 'Scheduler release runs cannot carry an actor' using errcode='22023';
  end if;
  if p_invocation_source='admin_recovery' and (
    p_actor_user_id is null or not exists(
      select 1 from public.account_capabilities capability
      where capability.user_id=p_actor_user_id and capability.capability='admin' and capability.status='active'
    )
  ) then
    raise exception 'Active administrator required' using errcode='42501';
  end if;
  insert into public.learning_instructor_earnings_release_runs(invocation_source,actor_user_id)
  values(p_invocation_source,p_actor_user_id) returning id into run_id;
  return run_id;
end;$function$;

-- This wrapper deliberately has no economic or time inputs. It uses the existing
-- release routine, database now(), and a fixed operational batch limit of 100.
create or replace function public.execute_learning_instructor_earnings_release_run(p_run_id bigint)
returns integer language plpgsql security definer set search_path to '' as $function$
declare run_row public.learning_instructor_earnings_release_runs%rowtype; released integer;
begin
  select * into run_row from public.learning_instructor_earnings_release_runs
  where id=p_run_id for update;
  if not found or run_row.status<>'started' then
    raise exception 'Earnings release run is not executable' using errcode='22023';
  end if;
  released:=public.release_matured_learning_instructor_earnings(100,run_row.actor_user_id);
  update public.learning_instructor_earnings_release_runs
  set status='succeeded',released_count=released,completed_at=now()
  where id=run_row.id;
  return released;
end;$function$;

create or replace function public.fail_learning_instructor_earnings_release_run(
  p_run_id bigint,
  p_failure_code text
)
returns void language plpgsql security definer set search_path to '' as $function$
begin
  if p_failure_code is null or p_failure_code !~ '^[a-z][a-z0-9_]{2,80}$' then
    raise exception 'Invalid earnings release failure code' using errcode='22023';
  end if;
  update public.learning_instructor_earnings_release_runs
  set status='failed',failure_code=p_failure_code,completed_at=now()
  where id=p_run_id and status='started';
  if not found then raise exception 'Earnings release run cannot be marked failed' using errcode='22023'; end if;
end;$function$;

create or replace function public.list_learning_instructor_earnings_release_runs(
  p_operator_id uuid,
  p_limit integer default 20
)
returns table(
  run_id bigint,
  invocation_source text,
  actor_user_id uuid,
  status text,
  released_count integer,
  failure_code text,
  started_at timestamptz,
  completed_at timestamptz
)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if p_operator_id is null or not exists(
    select 1 from public.account_capabilities capability
    where capability.user_id=p_operator_id and capability.capability='admin' and capability.status='active'
  ) then raise exception 'Active administrator required' using errcode='42501'; end if;
  return query
  select run.id,run.invocation_source,run.actor_user_id,run.status,run.released_count,
    run.failure_code,run.started_at,run.completed_at
  from public.learning_instructor_earnings_release_runs run
  order by run.started_at desc,run.id desc
  limit least(greatest(coalesce(p_limit,20),1),100);
end;$function$;

revoke all on function
  public.prevent_learning_instructor_earnings_release_run_mutation(),
  public.start_learning_instructor_earnings_release_run(text,uuid),
  public.execute_learning_instructor_earnings_release_run(bigint),
  public.fail_learning_instructor_earnings_release_run(bigint,text),
  public.list_learning_instructor_earnings_release_runs(uuid,integer)
from public,anon,authenticated;
grant execute on function
  public.prevent_learning_instructor_earnings_release_run_mutation(),
  public.start_learning_instructor_earnings_release_run(text,uuid),
  public.execute_learning_instructor_earnings_release_run(bigint),
  public.fail_learning_instructor_earnings_release_run(bigint,text),
  public.list_learning_instructor_earnings_release_runs(uuid,integer)
to postgres,service_role;

commit;
