-- Phase 1B2A: administrator-controlled, full-only Paystack test refunds.
-- Forward-only and additive. Original captures and existing financial/access history are not rewritten.

alter table public.learning_payment_cases
  add column provider text not null default 'paystack' check (provider = 'paystack'),
  add column idempotency_key uuid,
  add column provider_status text,
  add column provider_case_id text,
  add column provider_transaction_id text,
  add column requested_amount_minor bigint,
  add column processed_amount_minor bigint,
  add column reason_code text,
  add column operator_note text,
  add column requested_at timestamptz,
  add column provider_submitted_at timestamptz,
  add column last_verified_at timestamptz,
  add column action_required_at timestamptz,
  add column processed_at timestamptz,
  add column failed_at timestamptz,
  add column failure_code text,
  add column failure_message text,
  add column updated_at timestamptz not null default now();

alter table public.learning_payment_cases drop constraint learning_payment_cases_status_check;
alter table public.learning_payment_cases drop constraint learning_payment_cases_resolution_check;
alter table public.learning_payment_cases
  add constraint learning_payment_cases_status_check check (status in (
    'opened','requested','submitting','pending','processing','needs_attention','processed',
    'succeeded','failed','cancelled','won','lost'
  )),
  add constraint learning_payment_cases_refund_amount_check check (
    case_type <> 'refund' or (requested_amount_minor = amount_minor and (processed_amount_minor is null or processed_amount_minor = amount_minor))
  ),
  add constraint learning_payment_cases_reason_code_check check (reason_code is null or reason_code ~ '^[a-z][a-z0-9_]{1,60}$'),
  add constraint learning_payment_cases_operator_note_check check (operator_note is null or char_length(operator_note) between 3 and 2000),
  add constraint learning_payment_cases_failure_check check (failure_message is null or char_length(failure_message) <= 2000),
  add constraint learning_payment_cases_provider_status_check check (provider_status is null or provider_status in ('requested','pending','processing','needs-attention','failed','processed','cancelled'));

create unique index learning_payment_cases_idempotency_key on public.learning_payment_cases(idempotency_key) where idempotency_key is not null;
create unique index learning_payment_cases_provider_case_id_key on public.learning_payment_cases(provider,provider_case_id) where provider_case_id is not null;
create unique index learning_payment_cases_one_open_full_refund on public.learning_payment_cases(order_id)
  where case_type='refund' and status in ('requested','submitting','pending','processing','needs_attention');

create table public.learning_payment_case_events (
  id bigint generated by default as identity primary key,
  payment_case_id bigint not null references public.learning_payment_cases(id) on delete restrict,
  event_type text not null check (event_type ~ '^[a-z][a-z0-9_.]{2,100}$'),
  normalized_status text not null,
  provenance text not null check (provenance in ('operator','webhook','provider_api','system')),
  provider_event_id bigint references public.learning_payment_provider_events(id) on delete restrict,
  operator_id uuid references public.profiles(id) on delete set null,
  note text check (note is null or char_length(note) <= 2000),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default now()
);
alter table public.learning_payment_case_events enable row level security;
create index learning_payment_case_events_case_idx on public.learning_payment_case_events(payment_case_id,created_at,id);
revoke all on table public.learning_payment_case_events from public,anon,authenticated;
grant select,insert on table public.learning_payment_case_events to postgres,service_role;
revoke all on sequence public.learning_payment_case_events_id_seq from public,anon,authenticated;
grant usage,select on sequence public.learning_payment_case_events_id_seq to postgres,service_role;
create trigger learning_payment_case_events_immutable before update or delete on public.learning_payment_case_events
for each row execute function public.prevent_learning_ledger_mutation();

alter table public.learning_payment_provider_events add column payment_case_id bigint references public.learning_payment_cases(id) on delete restrict;
create index learning_payment_provider_events_case_idx on public.learning_payment_provider_events(payment_case_id,received_at,id) where payment_case_id is not null;
alter table public.learning_ledger_transactions add column payment_case_id bigint references public.learning_payment_cases(id) on delete restrict;
create unique index learning_ledger_one_refund_per_case_key on public.learning_ledger_transactions(payment_case_id)
  where transaction_type='refund' and payment_case_id is not null;

create or replace function public.validate_learning_provider_event_links()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if new.order_id is not null and new.payment_attempt_id is not null and not exists (
    select 1 from public.learning_payment_attempts where id=new.payment_attempt_id and order_id=new.order_id
  ) then raise exception 'Provider event attempt does not belong to its order' using errcode='22023'; end if;
  if new.payment_case_id is not null and not exists (
    select 1 from public.learning_payment_cases c
    where c.id=new.payment_case_id
      and (new.order_id is null or c.order_id=new.order_id)
      and (new.payment_attempt_id is null or c.payment_attempt_id=new.payment_attempt_id)
  ) then raise exception 'Provider event case does not belong to its order or attempt' using errcode='22023'; end if;
  return new;
end;
$function$;
revoke all on function public.validate_learning_provider_event_links() from public,anon,authenticated;
grant execute on function public.validate_learning_provider_event_links() to postgres,service_role;
drop trigger validate_learning_provider_event_links on public.learning_payment_provider_events;
create trigger validate_learning_provider_event_links before insert or update of order_id,payment_attempt_id,payment_case_id
on public.learning_payment_provider_events for each row execute function public.validate_learning_provider_event_links();

create or replace function public.prevent_learning_payment_case_identity_change()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if old.order_id is distinct from new.order_id or old.payment_attempt_id is distinct from new.payment_attempt_id
    or old.case_type is distinct from new.case_type or old.amount_minor is distinct from new.amount_minor
    or old.currency is distinct from new.currency or old.idempotency_key is distinct from new.idempotency_key
    or old.requested_amount_minor is distinct from new.requested_amount_minor or old.initiated_by is distinct from new.initiated_by
  then raise exception 'Payment case financial identity is immutable' using errcode='42501'; end if;
  if old.status is distinct from new.status and not (
    (old.status='requested' and new.status in ('submitting','cancelled')) or
    (old.status='submitting' and new.status in ('pending','processing','needs_attention','failed')) or
    (old.status='pending' and new.status in ('processing','needs_attention','processed','failed')) or
    (old.status='processing' and new.status in ('needs_attention','processed','failed')) or
    (old.status='needs_attention' and new.status in ('processing','processed','failed'))
  ) then raise exception 'Unsupported payment case status transition' using errcode='22023'; end if;
  new.updated_at:=now(); return new;
end;$function$;
revoke all on function public.prevent_learning_payment_case_identity_change() from public,anon,authenticated;
grant execute on function public.prevent_learning_payment_case_identity_change() to postgres,service_role;
create trigger protect_learning_payment_case_identity before update on public.learning_payment_cases
for each row execute function public.prevent_learning_payment_case_identity_change();

create or replace function public.request_paystack_test_full_refund(
  p_order_reference text,p_operator_id uuid,p_idempotency_key uuid,p_confirmation text,p_reason_code text,p_operator_note text
) returns table(case_id bigint,case_reference uuid,amount_minor bigint,currency text,status text,provider_transaction_id text)
language plpgsql security definer set search_path to '' as $function$
declare order_row record; case_row public.learning_payment_cases%rowtype; normalized_note text; normalized_reason text;
begin
  if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active')
  then raise exception 'Active administrator required' using errcode='42501'; end if;
  if p_confirmation is distinct from p_order_reference then raise exception 'Exact order-reference confirmation required' using errcode='22023'; end if;
  if p_idempotency_key is null then raise exception 'Refund idempotency key required' using errcode='22023'; end if;
  normalized_reason:=lower(trim(coalesce(p_reason_code,''))); normalized_note:=trim(coalesce(p_operator_note,''));
  if normalized_reason !~ '^[a-z][a-z0-9_]{1,60}$' or char_length(normalized_note) not between 3 and 2000
  then raise exception 'Refund reason and operator note required' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended('refund:'||p_order_reference,0));
  select o.*,a.id attempt_id,a.provider_transaction_id into order_row from public.learning_orders o
  join public.learning_payment_attempts a on a.order_id=o.id and a.provider='paystack' and a.status='succeeded'
  where o.order_reference=p_order_reference order by a.id desc limit 1 for update of o,a;
  if not found then raise exception 'Paid Paystack order not found' using errcode='P0002'; end if;
  select c.* into case_row from public.learning_payment_cases c where c.idempotency_key=p_idempotency_key;
  if found then
    if case_row.order_id<>order_row.id or case_row.case_type<>'refund' then raise exception 'Refund idempotency conflict' using errcode='23505'; end if;
    return query select case_row.id,case_row.case_reference,case_row.amount_minor,case_row.currency,case_row.status,case_row.provider_transaction_id; return;
  end if;
  if order_row.status<>'paid' then raise exception 'Order is not eligible for a full refund' using errcode='22023'; end if;
  if exists(select 1 from public.learning_payment_cases c where c.order_id=order_row.id and c.case_type='refund' and c.status in ('requested','submitting','pending','processing','needs_attention','processed','succeeded'))
  then raise exception 'A refund already exists for this order' using errcode='23505'; end if;
  insert into public.learning_payment_cases(order_id,payment_attempt_id,case_type,status,amount_minor,currency,reason,initiated_by,
    provider,idempotency_key,provider_transaction_id,requested_amount_minor,reason_code,operator_note,requested_at)
  values(order_row.id,order_row.attempt_id,'refund','requested',order_row.gross_amount_minor,order_row.currency,normalized_note,p_operator_id,
    'paystack',p_idempotency_key,order_row.provider_transaction_id,order_row.gross_amount_minor,normalized_reason,normalized_note,now()) returning * into case_row;
  insert into public.learning_payment_case_events(payment_case_id,event_type,normalized_status,provenance,operator_id,note)
  values(case_row.id,'refund.requested','requested','operator',p_operator_id,normalized_note);
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(p_operator_id,'admin_operator','refund.requested','payment_case',case_row.id::text,jsonb_build_object('order_id',order_row.id,'amount_minor',order_row.gross_amount_minor,'currency',order_row.currency,'reason_code',normalized_reason));
  return query select case_row.id,case_row.case_reference,case_row.amount_minor,case_row.currency,case_row.status,case_row.provider_transaction_id;
end;$function$;

create or replace function public.mark_paystack_test_refund_submitting(p_case_id bigint,p_operator_id uuid)
returns text language plpgsql security definer set search_path to '' as $function$
begin
 if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
 update public.learning_payment_cases set status='submitting' where id=p_case_id and case_type='refund' and status='requested';
 if not found then return 'already_submitted'; end if;
 insert into public.learning_payment_case_events(payment_case_id,event_type,normalized_status,provenance,operator_id) values(p_case_id,'refund.submitting','submitting','operator',p_operator_id);
 return 'submitting';
end;$function$;

create or replace function public.record_paystack_test_refund_submission(
 p_case_id bigint,p_provider_case_id text,p_provider_status text,p_provider_reference text,p_operator_id uuid
) returns text language plpgsql security definer set search_path to '' as $function$
declare normalized text;
begin
 if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
 normalized:=replace(lower(trim(p_provider_status)),'-','_');
 if normalized not in('pending','processing','needs_attention','failed','processed') then raise exception 'Unsupported refund provider status' using errcode='22023'; end if;
 update public.learning_payment_cases set provider_case_id=p_provider_case_id,provider_case_reference=p_provider_reference,
   provider_status=replace(normalized,'_','-'),provider_submitted_at=coalesce(provider_submitted_at,now()),last_verified_at=now(),
   status=case when normalized='processed' then 'pending' else normalized end,
   failed_at=case when normalized='failed' then now() else null end,
   failure_code=case when normalized='failed' then 'provider_failed' else null end,
   resolved_at=case when normalized='failed' then now() else null end
 where id=p_case_id and case_type='refund' and status in('submitting','pending','processing','needs_attention');
 if not found then return 'already_resolved'; end if;
 insert into public.learning_payment_case_events(payment_case_id,event_type,normalized_status,provenance,operator_id,metadata)
 values(p_case_id,'refund.provider_submitted',normalized,'provider_api',p_operator_id,jsonb_build_object('provider_case_id',p_provider_case_id,'provider_reference',p_provider_reference));
 return normalized;
end;$function$;

create or replace function public.receive_paystack_test_refund_event(
 p_provider_event_id text,p_payload_digest text,p_transaction_reference text,p_provider_case_id text,
 p_provider_status text,p_amount_minor bigint,p_currency text,p_domain text,p_payload jsonb
) returns table(outcome text,event_id bigint)
language plpgsql security definer set search_path to '' as $function$
declare case_row record; existing record; event_key bigint; normalized text;
begin
 normalized:=replace(lower(trim(p_provider_status)),'_','-');
 if p_domain<>'test' or p_currency<>'NGN' or p_amount_minor<=0 or p_payload_digest!~'^[a-f0-9]{64}$'
   or normalized not in('pending','processing','needs-attention','failed','processed')
 then raise exception 'Invalid Paystack test refund event' using errcode='22023'; end if;
 select * into existing from public.learning_payment_provider_events where provider='paystack' and provider_event_id=p_provider_event_id for update;
 if found then
   if existing.payload_digest<>p_payload_digest then return query select 'duplicate_payload_mismatch',existing.id; else return query select case when existing.processing_status='processed' then 'already_processed' else 'already_received' end,existing.id; end if; return;
 end if;
 select c.id,c.order_id,c.payment_attempt_id into case_row from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id
 where c.case_type='refund' and (c.provider_case_id=p_provider_case_id or (o.order_reference=p_transaction_reference and c.status in('submitting','pending','processing','needs_attention'))) order by c.id desc limit 1;
 if not found then
   insert into public.learning_payment_provider_events(provider,provider_event_id,event_type,payload_digest,payload,signature_valid,processing_status,recovery_status)
   values('paystack',p_provider_event_id,'refund.'||normalized,p_payload_digest,p_payload,true,'failed','manual_review') returning id into event_key;
   update public.learning_payment_provider_events set processed_at=now(),processing_error='No matching refund case' where id=event_key;
   return query select 'unknown_refund',event_key;
   return;
 end if;
 insert into public.learning_payment_provider_events(provider,provider_event_id,event_type,payload_digest,payload,signature_valid,processing_status,order_id,payment_attempt_id,payment_case_id,recovery_status)
 values('paystack',p_provider_event_id,'refund.'||normalized,p_payload_digest,p_payload,true,'received',case_row.order_id,case_row.payment_attempt_id,case_row.id,'none') returning id into event_key;
 return query select 'received',event_key;
end;$function$;

create or replace function public.finalize_paystack_test_full_refund(p_case_id bigint,p_provider_event_id bigint,p_provenance text,p_operator_id uuid default null)
returns table(outcome text,order_id bigint,ledger_transaction_id bigint) language plpgsql security definer set search_path to '' as $function$
declare case_row record; entitlement_row record; ledger_key bigint;
begin
 perform pg_advisory_xact_lock(hashtextextended('refund-case:'||p_case_id::text,0));
 select c.*,o.order_reference,o.status order_status,o.gross_amount_minor,o.learner_id,o.course_id into case_row
 from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.id=p_case_id and c.case_type='refund' for update of c,o;
 if not found then raise exception 'Refund case not found' using errcode='P0002'; end if;
 select id into ledger_key from public.learning_ledger_transactions where payment_case_id=p_case_id and transaction_type='refund';
 if ledger_key is not null then return query select 'already_processed',case_row.order_id,ledger_key; return; end if;
 if case_row.provider_status<>'processed' or case_row.amount_minor<>case_row.gross_amount_minor then raise exception 'Authoritative processed full refund required' using errcode='22023'; end if;
 if case_row.order_status<>'paid' then raise exception 'Order is not refundable' using errcode='22023'; end if;
 insert into public.learning_ledger_transactions(order_id,payment_case_id,transaction_type,currency,description,created_by)
 values(case_row.order_id,p_case_id,'refund',case_row.currency,'Processed Paystack full course refund',p_operator_id) returning id into ledger_key;
 insert into public.learning_ledger_entries(transaction_id,line_number,account_code,amount_minor,currency,counterparty_type,counterparty_reference)
 values(ledger_key,1,'liability.marketplace_sales_unallocated',case_row.amount_minor,case_row.currency,'payment_case',case_row.case_reference::text),
       (ledger_key,2,'asset.paystack_receivable',-case_row.amount_minor,case_row.currency,'payment_provider',coalesce(case_row.provider_case_id,case_row.provider_case_reference));
 update public.learning_orders set status='refunded' where id=case_row.order_id;
 update public.learning_course_entitlements e set status='refunded',revoked_at=now(),revocation_reason='Full Paystack refund processed' where e.order_id=case_row.order_id and e.status='active' returning e.id,e.enrollment_id into entitlement_row;
 if not found then raise exception 'Active entitlement not found' using errcode='P0002'; end if;
 update public.enrollments set status='cancelled' where id=entitlement_row.enrollment_id and learner_id=case_row.learner_id and course_id=case_row.course_id and status in('active','completed');
 if not found then raise exception 'Active or completed enrollment not found' using errcode='P0002'; end if;
 update public.learning_payment_cases set status='processed',processed_amount_minor=amount_minor,processed_at=now(),resolved_at=now(),last_verified_at=now() where id=p_case_id;
 insert into public.learning_payment_case_events(payment_case_id,event_type,normalized_status,provenance,provider_event_id,operator_id,metadata)
 values(p_case_id,'refund.processed','processed',p_provenance,p_provider_event_id,p_operator_id,jsonb_build_object('ledger_transaction_id',ledger_key));
 insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
 values(p_operator_id,case when p_operator_id is null then 'payment_system' else 'admin_operator' end,'refund.processed','payment_case',p_case_id::text,jsonb_build_object('order_id',case_row.order_id,'ledger_transaction_id',ledger_key,'amount_minor',case_row.amount_minor));
 return query select 'refunded',case_row.order_id,ledger_key;
end;$function$;

create or replace function public.process_paystack_test_refund_event(p_event_id bigint)
returns table(outcome text,order_id bigint,ledger_transaction_id bigint) language plpgsql security definer set search_path to '' as $function$
declare event_row record; case_row record; normalized text; result_row record; result_outcome text; result_order_id bigint; result_ledger_id bigint;
begin
 select * into event_row from public.learning_payment_provider_events where id=p_event_id and provider='paystack' for update;
 if not found or event_row.event_type not like 'refund.%' or (not event_row.signature_valid and event_row.verification_source<>'provider_api') then raise exception 'Refund event is not processable' using errcode='22023'; end if;
 if event_row.processing_status='processed' then select c.order_id into case_row from public.learning_payment_cases c where c.id=event_row.payment_case_id; return query select 'already_processed',case_row.order_id,null::bigint; return; end if;
 if event_row.payment_case_id is null then update public.learning_payment_provider_events set processing_status='failed',processed_at=now(),processing_error='No matching refund case',recovery_status='manual_review' where id=p_event_id; return query select 'unknown_refund',null::bigint,null::bigint; return; end if;
 normalized:=replace(event_row.event_type,'refund.','');
 update public.learning_payment_provider_events set processing_attempts=processing_attempts+1,last_attempted_at=now() where id=p_event_id;
 update public.learning_payment_cases set provider_case_id=coalesce(provider_case_id,event_row.payload->>'refund_id'),provider_case_reference=coalesce(provider_case_reference,event_row.payload->>'refund_reference'),
   provider_status=normalized,last_verified_at=now(),status=case normalized when 'needs-attention' then 'needs_attention' else normalized end,
   action_required_at=case when normalized='needs-attention' then now() else action_required_at end,
   failed_at=case when normalized='failed' then now() else failed_at end,
   failure_code=case when normalized='failed' then 'provider_failed' else failure_code end,
   resolved_at=case when normalized='failed' then now() else resolved_at end
 where id=event_row.payment_case_id and status in('submitting','pending','processing','needs_attention');
 insert into public.learning_payment_case_events(payment_case_id,event_type,normalized_status,provenance,provider_event_id,metadata)
 values(event_row.payment_case_id,event_row.event_type,replace(normalized,'-','_'),event_row.verification_source,p_event_id,event_row.payload);
 if normalized='processed' then
   select * into result_row from public.finalize_paystack_test_full_refund(event_row.payment_case_id,p_event_id,event_row.verification_source,null);
   result_outcome:=result_row.outcome; result_order_id:=result_row.order_id; result_ledger_id:=result_row.ledger_transaction_id;
 else result_outcome:=replace(normalized,'-','_'); result_order_id:=event_row.order_id; result_ledger_id:=null; end if;
 update public.learning_payment_provider_events set processing_status='processed',processed_at=now(),processing_error=null,recovery_status='resolved' where id=p_event_id;
 return query select result_outcome,result_order_id,result_ledger_id;
end;$function$;

create or replace function public.receive_paystack_test_verified_refund(
 p_case_id bigint,p_provider_case_id text,p_provider_status text,p_provider_reference text,p_amount_minor bigint,p_currency text,p_domain text,p_payload jsonb,p_operator_id uuid
) returns bigint language plpgsql security definer set search_path to '' as $function$
declare case_row record; event_key bigint; digest text; normalized text;
begin
 if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
 normalized:=replace(lower(trim(p_provider_status)),'_','-');
 if p_domain<>'test' or p_currency<>'NGN' or normalized not in('pending','processing','needs-attention','failed','processed') then raise exception 'Invalid verified refund' using errcode='22023'; end if;
 select * into case_row from public.learning_payment_cases where id=p_case_id and case_type='refund';
 if not found or case_row.amount_minor<>p_amount_minor then raise exception 'Verified refund does not match case' using errcode='22023'; end if;
 digest:=encode(extensions.digest(convert_to(p_payload::text,'UTF8'),'sha256'),'hex');
 insert into public.learning_payment_provider_events(provider,provider_event_id,event_type,payload_digest,payload,signature_valid,verification_source,processing_status,order_id,payment_attempt_id,payment_case_id,recovery_status)
 values('paystack','refund.verify:'||p_provider_case_id||':'||normalized,'refund.'||normalized,digest,p_payload,false,'provider_api','received',case_row.order_id,case_row.payment_attempt_id,p_case_id,'none')
 on conflict(provider,provider_event_id) do update set received_at=public.learning_payment_provider_events.received_at returning id into event_key;
 update public.learning_payment_cases set provider_case_id=coalesce(provider_case_id,p_provider_case_id),provider_case_reference=coalesce(provider_case_reference,p_provider_reference),last_verified_at=now() where id=p_case_id;
 insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(p_operator_id,'admin_operator','refund.verified_via_api','payment_case',p_case_id::text,jsonb_build_object('provider_status',normalized,'event_id',event_key));
 return event_key;
end;$function$;

create or replace function public.recover_paystack_test_refund_event(p_event_id bigint,p_operator_id uuid)
returns table(outcome text,order_id bigint,ledger_transaction_id bigint) language plpgsql security definer set search_path to '' as $function$
declare result_row record;
begin
 if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
 select * into result_row from public.process_paystack_test_refund_event(p_event_id);
 return query select result_row.outcome,result_row.order_id,result_row.ledger_transaction_id;
end;$function$;

create or replace function public.get_learning_refund_case_for_recovery(p_operator_id uuid,p_case_id bigint)
returns table(order_reference text,provider_case_id text,provider_transaction_id text)
language plpgsql stable security definer set search_path to '' as $function$
begin
 if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active')
 then raise exception 'Active administrator required' using errcode='42501'; end if;
 return query
 select o.order_reference,c.provider_case_id,c.provider_transaction_id
 from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id
 where c.id=p_case_id and c.case_type='refund' and c.status in('pending','processing','needs_attention')
   and c.provider_case_id is not null and c.provider_transaction_id is not null;
end;$function$;

create or replace function public.list_learning_refund_cases(p_operator_id uuid,p_order_id bigint default null)
returns table(case_id bigint,order_id bigint,order_reference text,case_reference uuid,status text,amount_minor bigint,currency text,reason_code text,operator_note text,
 provider_case_id text,provider_case_reference text,provider_status text,requested_at timestamptz,provider_submitted_at timestamptz,last_verified_at timestamptz,
 action_required_at timestamptz,processed_at timestamptz,failed_at timestamptz,failure_code text,failure_message text)
language plpgsql stable security definer set search_path to '' as $function$
begin
 if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
 return query select c.id,c.order_id,o.order_reference,c.case_reference,c.status,c.amount_minor,c.currency,c.reason_code,c.operator_note,c.provider_case_id,c.provider_case_reference,c.provider_status,c.requested_at,c.provider_submitted_at,c.last_verified_at,c.action_required_at,c.processed_at,c.failed_at,c.failure_code,c.failure_message
 from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and (p_order_id is null or c.order_id=p_order_id) order by c.opened_at desc,c.id desc;
end;$function$;

create or replace function public.list_learning_payment_case_events(p_operator_id uuid,p_case_id bigint)
returns table(event_id bigint,payment_case_id bigint,event_type text,normalized_status text,provenance text,note text,metadata jsonb,created_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
 if not exists(select 1 from public.account_capabilities ac where ac.user_id=p_operator_id and ac.capability='admin' and ac.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
 return query select e.id,e.payment_case_id,e.event_type,e.normalized_status,e.provenance,e.note,e.metadata,e.created_at from public.learning_payment_case_events e where p_case_id is null or e.payment_case_id=p_case_id order by e.created_at,e.id;
end;$function$;

create or replace function public.reconcile_paystack_test_refunds()
returns table(issue_type text,order_reference text,detail text) language sql stable security definer set search_path to '' as $function$
 select 'processed_refund_without_ledger',o.order_reference,'Processed refund case has no reversal ledger' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and c.status='processed' and not exists(select 1 from public.learning_ledger_transactions t where t.payment_case_id=c.id and t.transaction_type='refund')
 union all select 'refund_ledger_without_processed_case',o.order_reference,'Refund ledger is not backed by a processed case' from public.learning_ledger_transactions t join public.learning_orders o on o.id=t.order_id left join public.learning_payment_cases c on c.id=t.payment_case_id where t.transaction_type='refund' and (c.id is null or c.status<>'processed')
 union all select 'refund_amount_mismatch',o.order_reference,'Processed refund amount differs from authoritative gross' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and c.status='processed' and (c.amount_minor<>o.gross_amount_minor or c.currency<>o.currency)
 union all select 'refund_ledger_imbalance',o.order_reference,'Refund ledger is unbalanced or does not contain exactly two entries' from public.learning_ledger_transactions t join public.learning_orders o on o.id=t.order_id left join public.learning_ledger_entries e on e.transaction_id=t.id where t.transaction_type='refund' group by o.id,o.order_reference,t.id having count(e.id)<>2 or coalesce(sum(e.amount_minor),0)<>0
 union all select 'duplicate_refund_reversal',o.order_reference,'Order has more than one refund reversal' from public.learning_ledger_transactions t join public.learning_orders o on o.id=t.order_id where t.transaction_type='refund' group by o.id,o.order_reference having count(*)>1
 union all select 'refund_exceeds_gross',o.order_reference,'Processed refund reversals exceed order gross' from public.learning_orders o join public.learning_payment_cases c on c.order_id=o.id and c.case_type='refund' and c.status='processed' group by o.id,o.order_reference,o.gross_amount_minor having sum(c.processed_amount_minor)>o.gross_amount_minor
 union all select 'refunded_order_active_entitlement',o.order_reference,'Refunded order retains active entitlement' from public.learning_orders o join public.learning_course_entitlements e on e.order_id=o.id and e.status='active' where o.status='refunded'
 union all select 'refunded_order_active_enrollment',o.order_reference,'Refunded order retains active/completed enrollment' from public.learning_orders o join public.learning_course_entitlements e on e.order_id=o.id join public.enrollments n on n.id=e.enrollment_id and n.status in('active','completed') where o.status='refunded'
 union all select 'failed_refund_with_reversal',o.order_reference,'Failed refund has an economic reversal' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id join public.learning_ledger_transactions t on t.payment_case_id=c.id and t.transaction_type='refund' where c.case_type='refund' and c.status='failed'
 union all select 'provider_processed_local_incomplete',o.order_reference,'Provider reports processed but local refund finalization is incomplete' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and c.provider_status='processed' and c.status<>'processed'
 union all select 'stale_refund_case',o.order_reference,'Refund case requires verification or operator attention' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and ((c.status in('pending','processing') and c.updated_at<now()-interval '2 hours') or (c.status='needs_attention' and c.updated_at<now()-interval '15 minutes'))
 union all select 'refund_provider_event_unresolved',o.order_reference,'Refund provider event is failed or stale' from public.learning_payment_provider_events e join public.learning_orders o on o.id=e.order_id where e.event_type like 'refund.%' and (e.processing_status='failed' or (e.processing_status='received' and e.received_at<now()-interval '5 minutes'));
$function$;

revoke all on function public.request_paystack_test_full_refund(text,uuid,uuid,text,text,text),public.mark_paystack_test_refund_submitting(bigint,uuid),public.record_paystack_test_refund_submission(bigint,text,text,text,uuid),public.receive_paystack_test_refund_event(text,text,text,text,text,bigint,text,text,jsonb),public.finalize_paystack_test_full_refund(bigint,bigint,text,uuid),public.process_paystack_test_refund_event(bigint),public.receive_paystack_test_verified_refund(bigint,text,text,text,bigint,text,text,jsonb,uuid),public.recover_paystack_test_refund_event(bigint,uuid),public.get_learning_refund_case_for_recovery(uuid,bigint),public.list_learning_refund_cases(uuid,bigint),public.list_learning_payment_case_events(uuid,bigint),public.reconcile_paystack_test_refunds() from public,anon,authenticated;
grant execute on function public.request_paystack_test_full_refund(text,uuid,uuid,text,text,text),public.mark_paystack_test_refund_submitting(bigint,uuid),public.record_paystack_test_refund_submission(bigint,text,text,text,uuid),public.receive_paystack_test_refund_event(text,text,text,text,text,bigint,text,text,jsonb),public.finalize_paystack_test_full_refund(bigint,bigint,text,uuid),public.process_paystack_test_refund_event(bigint),public.receive_paystack_test_verified_refund(bigint,text,text,text,bigint,text,text,jsonb,uuid),public.recover_paystack_test_refund_event(bigint,uuid),public.get_learning_refund_case_for_recovery(uuid,bigint),public.list_learning_refund_cases(uuid,bigint),public.list_learning_payment_case_events(uuid,bigint),public.reconcile_paystack_test_refunds() to postgres,service_role;
