-- Phase 3C: record a company charge as one capture and immutable per-seat sales.
-- This is separate from learner orders/earnings/payouts. It does not assert
-- live-accounting readiness or enable Live Mode. Apply only after migration 43.
-- Forward-fix rollback: disable the posting trigger in a reviewed follow-up
-- migration, retain immutable capture/seat history, and reconcile affected
-- purchases. Never drop or rewrite posted financial rows to roll this back.
begin;

alter table public.learning_company_paid_course_purchases
  add column seller_instructor_id uuid references public.profiles(id) on delete restrict,
  add column seller_organization_id bigint references public.learning_provider_organizations(id) on delete restrict,
  add column seller_payee_id uuid references public.profiles(id) on delete restrict,
  add column commercial_terms_version text references public.learning_commercial_terms(version) on delete restrict;

create or replace function public.snapshot_learning_company_sale_terms()
returns trigger language plpgsql security definer set search_path to '' as $function$
declare course_row record; owner_key uuid;
begin
  select course.instructor_id,course.organization_id into course_row
  from public.learning_courses course where course.id = new.course_id;
  if not found or course_row.instructor_id is null then
    raise exception 'Company sale requires an instructor-owned course' using errcode = '22023';
  end if;
  new.seller_instructor_id := course_row.instructor_id;
  new.seller_organization_id := course_row.organization_id;
  if course_row.organization_id is null then
    new.seller_payee_id := course_row.instructor_id;
  else
    select membership.user_id into owner_key
    from public.learning_provider_organization_memberships membership
    where membership.organization_id = course_row.organization_id
      and membership.role = 'owner' and membership.status = 'active';
    if owner_key is null then
      raise exception 'Organization course has no active owner for the sale' using errcode = '22023';
    end if;
    new.seller_payee_id := owner_key;
  end if;
  new.commercial_terms_version := public.resolve_learning_commercial_terms_version(new.course_id,new.seller_payee_id);
  return new;
end;$function$;

create trigger snapshot_learning_company_sale_terms
before insert on public.learning_company_paid_course_purchases
for each row execute function public.snapshot_learning_company_sale_terms();

create or replace function public.protect_learning_company_purchase_sale_snapshot()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if old.workspace_id is distinct from new.workspace_id or old.course_id is distinct from new.course_id
     or old.requested_by is distinct from new.requested_by
     or old.course_title_snapshot is distinct from new.course_title_snapshot
     or old.provider_name_snapshot is distinct from new.provider_name_snapshot
     or old.unit_amount_minor is distinct from new.unit_amount_minor
     or old.total_amount_minor is distinct from new.total_amount_minor
     or old.currency is distinct from new.currency or old.seat_count is distinct from new.seat_count
     or old.seller_instructor_id is distinct from new.seller_instructor_id
     or old.seller_organization_id is distinct from new.seller_organization_id
     or old.seller_payee_id is distinct from new.seller_payee_id
     or old.commercial_terms_version is distinct from new.commercial_terms_version then
    raise exception 'Company sale identity and commercial snapshot are immutable' using errcode = '42501';
  end if;
  return new;
end;$function$;

create trigger protect_learning_company_purchase_sale_snapshot
before update on public.learning_company_paid_course_purchases
for each row execute function public.protect_learning_company_purchase_sale_snapshot();

create or replace function public.prevent_learning_company_sale_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  raise exception 'Company sale and ledger history is append-only' using errcode = '42501';
end;$function$;

create trigger prevent_learning_company_purchase_seat_mutation
before update or delete on public.learning_company_paid_course_purchase_seats
for each row execute function public.prevent_learning_company_sale_mutation();

create table public.learning_company_sale_ledger_transactions (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.learning_company_paid_course_purchases(id) on delete restrict,
  transaction_type text not null check (transaction_type in ('payment_capture','commercial_allocation')),
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  created_at timestamptz not null default now(),
  unique(purchase_id,transaction_type)
);

create table public.learning_company_sale_ledger_entries (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public.learning_company_sale_ledger_transactions(id) on delete restrict,
  line_number smallint not null check (line_number > 0),
  account_code text not null check (account_code ~ '^[a-z][a-z0-9_.]{2,80}$'),
  amount_minor bigint not null check (amount_minor <> 0),
  currency text not null check (currency = 'NGN'),
  unique(transaction_id,line_number)
);

create table public.learning_company_commercial_sales (
  purchase_id bigint primary key references public.learning_company_paid_course_purchases(id) on delete restrict,
  attempt_id bigint not null unique references public.learning_company_paid_course_purchase_attempts(id) on delete restrict,
  paystack_domain text not null check (paystack_domain in ('test','live')),
  provider_reference text not null unique,
  provider_transaction_id text not null,
  seller_instructor_id uuid not null references public.profiles(id) on delete restrict,
  seller_organization_id bigint references public.learning_provider_organizations(id) on delete restrict,
  seller_payee_id uuid not null references public.profiles(id) on delete restrict,
  commercial_terms_version text not null references public.learning_commercial_terms(version) on delete restrict,
  gross_amount_minor bigint not null check (gross_amount_minor > 0),
  platform_commission_minor bigint not null check (platform_commission_minor >= 0),
  seller_gross_minor bigint not null check (seller_gross_minor >= 0),
  currency text not null check (currency = 'NGN'),
  seat_count integer not null check (seat_count > 0),
  capture_ledger_transaction_id bigint not null unique references public.learning_company_sale_ledger_transactions(id) on delete restrict,
  allocation_ledger_transaction_id bigint not null unique references public.learning_company_sale_ledger_transactions(id) on delete restrict,
  posted_at timestamptz not null default now(),
  unique(paystack_domain,provider_transaction_id),
  check(gross_amount_minor = platform_commission_minor + seller_gross_minor)
);

create table public.learning_company_commercial_sale_lines (
  purchase_id bigint not null references public.learning_company_commercial_sales(purchase_id) on delete restrict,
  assigned_user_id uuid not null,
  course_id bigint not null references public.learning_courses(id) on delete restrict,
  unit_amount_minor bigint not null check (unit_amount_minor > 0),
  platform_commission_minor bigint not null check (platform_commission_minor >= 0),
  seller_gross_minor bigint not null check (seller_gross_minor >= 0),
  currency text not null check (currency = 'NGN'),
  primary key(purchase_id,assigned_user_id),
  foreign key(purchase_id,assigned_user_id)
    references public.learning_company_paid_course_purchase_seats(purchase_id,assigned_user_id) on delete restrict,
  check(unit_amount_minor = platform_commission_minor + seller_gross_minor)
);

create index learning_company_commercial_sales_payee_idx
  on public.learning_company_commercial_sales(seller_payee_id,posted_at desc,purchase_id desc);
create index learning_company_commercial_sales_organization_idx
  on public.learning_company_commercial_sales(seller_organization_id,posted_at desc,purchase_id desc);

alter table public.learning_company_sale_ledger_transactions enable row level security;
alter table public.learning_company_sale_ledger_entries enable row level security;
alter table public.learning_company_commercial_sales enable row level security;
alter table public.learning_company_commercial_sale_lines enable row level security;
revoke all on public.learning_company_sale_ledger_transactions,public.learning_company_sale_ledger_entries,
  public.learning_company_commercial_sales,public.learning_company_commercial_sale_lines from public,anon,authenticated,service_role;
grant select on public.learning_company_sale_ledger_transactions,public.learning_company_sale_ledger_entries,
  public.learning_company_commercial_sales,public.learning_company_commercial_sale_lines to service_role;

create trigger prevent_learning_company_sale_ledger_transaction_mutation
before update or delete on public.learning_company_sale_ledger_transactions
for each row execute function public.prevent_learning_company_sale_mutation();
create trigger prevent_learning_company_sale_ledger_entry_mutation
before update or delete on public.learning_company_sale_ledger_entries
for each row execute function public.prevent_learning_company_sale_mutation();
create trigger prevent_learning_company_commercial_sale_mutation
before update or delete on public.learning_company_commercial_sales
for each row execute function public.prevent_learning_company_sale_mutation();
create trigger prevent_learning_company_commercial_sale_line_mutation
before update or delete on public.learning_company_commercial_sale_lines
for each row execute function public.prevent_learning_company_sale_mutation();

create or replace function public.post_learning_company_commercial_sale(p_purchase_id bigint)
returns bigint language plpgsql security definer set search_path to '' as $function$
declare purchase_row public.learning_company_paid_course_purchases%rowtype;
  attempt_row public.learning_company_paid_course_purchase_attempts%rowtype;
  terms_row public.learning_commercial_terms%rowtype;
  captured_count integer; sale_key bigint; capture_key bigint; allocation_key bigint;
  commission_per_seat bigint; seller_per_seat bigint; commission_total bigint; seller_total bigint;
begin
  if p_purchase_id is null then raise exception 'Company purchase is required' using errcode = '22023'; end if;
  select * into purchase_row from public.learning_company_paid_course_purchases
  where id = p_purchase_id for update;
  if not found or purchase_row.status <> 'paid' then
    raise exception 'Verified paid company purchase is required' using errcode = '22023';
  end if;
  select sale.purchase_id into sale_key from public.learning_company_commercial_sales sale
  where sale.purchase_id = purchase_row.id;
  if found then return sale_key; end if;
  -- Older Test Mode purchases intentionally have no seller/terms snapshot.
  -- They require a reviewed historical backfill, not today's terms.
  if purchase_row.seller_payee_id is null or purchase_row.seller_instructor_id is null
     or purchase_row.commercial_terms_version is null then return null; end if;
  select * into attempt_row from public.learning_company_paid_course_purchase_attempts attempt
  where attempt.purchase_id = purchase_row.id and attempt.provider = 'paystack'
    and attempt.status = 'succeeded' for share;
  if not found or attempt_row.provider_transaction_id is null
     or attempt_row.amount_minor <> purchase_row.total_amount_minor
     or attempt_row.currency <> purchase_row.currency then
    raise exception 'Verified company charge does not match its purchase' using errcode = '22023';
  end if;
  if purchase_row.unit_amount_minor * purchase_row.seat_count <> purchase_row.total_amount_minor then
    raise exception 'Company seat amounts do not match the charge' using errcode = '22023';
  end if;
  select count(*) into captured_count from public.learning_company_paid_course_purchase_seats seat
  where seat.purchase_id = purchase_row.id;
  if captured_count <> purchase_row.seat_count then
    raise exception 'Company seat count changed after purchase preparation' using errcode = '22023';
  end if;
  select * into terms_row from public.learning_commercial_terms terms
  where terms.version = purchase_row.commercial_terms_version;
  if not found then raise exception 'Commercial terms snapshot is unavailable' using errcode = '22023'; end if;
  commission_per_seat := round(purchase_row.unit_amount_minor * terms_row.commission_basis_points / 10000.0)::bigint;
  seller_per_seat := purchase_row.unit_amount_minor - commission_per_seat;
  commission_total := commission_per_seat * purchase_row.seat_count;
  seller_total := seller_per_seat * purchase_row.seat_count;

  insert into public.learning_company_sale_ledger_transactions(purchase_id,transaction_type,amount_minor,currency)
  values(purchase_row.id,'payment_capture',purchase_row.total_amount_minor,purchase_row.currency)
  returning id into capture_key;
  insert into public.learning_company_sale_ledger_entries(transaction_id,line_number,account_code,amount_minor,currency)
  values(capture_key,1,'asset.paystack_receivable',purchase_row.total_amount_minor,purchase_row.currency),
        (capture_key,2,'liability.company_sales_unallocated',-purchase_row.total_amount_minor,purchase_row.currency);

  insert into public.learning_company_sale_ledger_transactions(purchase_id,transaction_type,amount_minor,currency)
  values(purchase_row.id,'commercial_allocation',purchase_row.total_amount_minor,purchase_row.currency)
  returning id into allocation_key;
  insert into public.learning_company_sale_ledger_entries(transaction_id,line_number,account_code,amount_minor,currency)
  values(allocation_key,1,'liability.company_sales_unallocated',purchase_row.total_amount_minor,purchase_row.currency);
  if commission_total > 0 then
    insert into public.learning_company_sale_ledger_entries(transaction_id,line_number,account_code,amount_minor,currency)
    values(allocation_key,2,'revenue.platform_commission',-commission_total,purchase_row.currency);
  end if;
  if seller_total > 0 then
    insert into public.learning_company_sale_ledger_entries(transaction_id,line_number,account_code,amount_minor,currency)
    values(allocation_key,3,'liability.company_seller_earnings_held',-seller_total,purchase_row.currency);
  end if;
  if exists(
    select 1 from public.learning_company_sale_ledger_transactions ledger
    join public.learning_company_sale_ledger_entries entry on entry.transaction_id = ledger.id
    where ledger.id in (capture_key,allocation_key)
    group by ledger.id having sum(entry.amount_minor) <> 0 or count(*) < 2
  ) then raise exception 'Company commercial ledger is not balanced' using errcode = '23514'; end if;

  insert into public.learning_company_commercial_sales(
    purchase_id,attempt_id,paystack_domain,provider_reference,provider_transaction_id,
    seller_instructor_id,seller_organization_id,seller_payee_id,commercial_terms_version,
    gross_amount_minor,platform_commission_minor,seller_gross_minor,currency,seat_count,
    capture_ledger_transaction_id,allocation_ledger_transaction_id)
  values(purchase_row.id,attempt_row.id,attempt_row.paystack_domain,attempt_row.provider_reference,
    attempt_row.provider_transaction_id,purchase_row.seller_instructor_id,purchase_row.seller_organization_id,
    purchase_row.seller_payee_id,purchase_row.commercial_terms_version,purchase_row.total_amount_minor,
    commission_total,seller_total,purchase_row.currency,purchase_row.seat_count,capture_key,allocation_key);
  insert into public.learning_company_commercial_sale_lines(
    purchase_id,assigned_user_id,course_id,unit_amount_minor,platform_commission_minor,seller_gross_minor,currency)
  select purchase_row.id,seat.assigned_user_id,purchase_row.course_id,purchase_row.unit_amount_minor,
    commission_per_seat,seller_per_seat,purchase_row.currency
  from public.learning_company_paid_course_purchase_seats seat where seat.purchase_id = purchase_row.id;
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(null,'payment_system','company_paid_course.sale_posted','learning_company_paid_course_purchase',purchase_row.id::text,
    jsonb_build_object('seat_count',purchase_row.seat_count,'gross_amount_minor',purchase_row.total_amount_minor,
      'seller_organization_id',purchase_row.seller_organization_id,'paystack_domain',attempt_row.paystack_domain));
  return purchase_row.id;
end;$function$;

create or replace function public.post_learning_company_commercial_sale_after_charge()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if new.status = 'succeeded' and old.status is distinct from new.status then
    perform public.post_learning_company_commercial_sale(new.purchase_id);
  end if;
  return new;
end;$function$;

create trigger post_learning_company_commercial_sale_after_charge
after update of status on public.learning_company_paid_course_purchase_attempts
for each row execute function public.post_learning_company_commercial_sale_after_charge();

create or replace function public.reconcile_learning_company_commercial_sales()
returns table(purchase_id bigint,issue_type text)
language sql stable security definer set search_path to '' as $function$
  select purchase.id,'paid_purchase_missing_commercial_sale'::text
  from public.learning_company_paid_course_purchases purchase
  where purchase.status = 'paid' and not exists(
    select 1 from public.learning_company_commercial_sales sale where sale.purchase_id = purchase.id)
  union all
  select sale.purchase_id,'company_sale_amount_or_seat_mismatch'::text
  from public.learning_company_commercial_sales sale
  join public.learning_company_paid_course_purchases purchase on purchase.id = sale.purchase_id
  where sale.gross_amount_minor <> purchase.total_amount_minor
    or sale.gross_amount_minor <> sale.platform_commission_minor + sale.seller_gross_minor
    or sale.seat_count <> (select count(*) from public.learning_company_commercial_sale_lines line where line.purchase_id = sale.purchase_id)
    or sale.gross_amount_minor <> coalesce((select sum(line.unit_amount_minor) from public.learning_company_commercial_sale_lines line where line.purchase_id = sale.purchase_id),0)
    or sale.platform_commission_minor <> coalesce((select sum(line.platform_commission_minor) from public.learning_company_commercial_sale_lines line where line.purchase_id = sale.purchase_id),0)
    or sale.seller_gross_minor <> coalesce((select sum(line.seller_gross_minor) from public.learning_company_commercial_sale_lines line where line.purchase_id = sale.purchase_id),0)
  union all
  select sale.purchase_id,'company_sale_ledger_identity_mismatch'::text
  from public.learning_company_commercial_sales sale
  join public.learning_company_sale_ledger_transactions capture on capture.id = sale.capture_ledger_transaction_id
  join public.learning_company_sale_ledger_transactions allocation on allocation.id = sale.allocation_ledger_transaction_id
  where capture.purchase_id <> sale.purchase_id or capture.transaction_type <> 'payment_capture'
    or capture.amount_minor <> sale.gross_amount_minor
    or allocation.purchase_id <> sale.purchase_id or allocation.transaction_type <> 'commercial_allocation'
    or allocation.amount_minor <> sale.gross_amount_minor
  union all
  select ledger.purchase_id,'company_ledger_unbalanced'::text
  from public.learning_company_sale_ledger_transactions ledger
  left join public.learning_company_sale_ledger_entries entry on entry.transaction_id = ledger.id
  group by ledger.purchase_id,ledger.id having coalesce(sum(entry.amount_minor),0) <> 0 or count(entry.id) < 2;
$function$;

revoke all on function public.snapshot_learning_company_sale_terms(),
  public.protect_learning_company_purchase_sale_snapshot(),
  public.prevent_learning_company_sale_mutation(),
  public.post_learning_company_commercial_sale(bigint),
  public.post_learning_company_commercial_sale_after_charge(),
  public.reconcile_learning_company_commercial_sales() from public,anon,authenticated;
grant execute on function public.post_learning_company_commercial_sale(bigint),
  public.reconcile_learning_company_commercial_sales() to postgres,service_role;

commit;
