-- Phase 2A1: Training-organization provider identity and memberships.
-- This is deliberately non-commercial: it does not alter courses, orders,
-- allocations, earnings, payouts, certificates, or historical records.
begin;

create table public.learning_provider_organizations (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 2 and 160),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' and char_length(slug) between 3 and 100),
  status text not null default 'active' check (status in ('active','suspended','archived')),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  suspended_at timestamptz,
  archived_at timestamptz,
  constraint learning_provider_organizations_lifecycle_check check (
    (status='active' and suspended_at is null and archived_at is null)
    or (status='suspended' and suspended_at is not null and archived_at is null)
    or (status='archived' and archived_at is not null)
  )
);
create index learning_provider_organizations_created_by_idx on public.learning_provider_organizations(created_by,created_at desc,id desc);

create table public.learning_provider_organization_memberships (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.learning_provider_organizations(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete restrict,
  role text not null check (role in ('owner','admin','instructor')),
  status text not null default 'active' check (status in ('active','suspended','revoked')),
  granted_by uuid not null references public.profiles(id) on delete restrict,
  granted_at timestamptz not null default now(),
  ended_at timestamptz,
  end_reason text check (end_reason is null or char_length(end_reason) between 2 and 500),
  constraint learning_provider_organization_memberships_lifecycle_check check (
    (status='active' and ended_at is null and end_reason is null)
    or (status in ('suspended','revoked') and ended_at is not null)
  )
);
create unique index learning_provider_organization_memberships_one_active_member
  on public.learning_provider_organization_memberships(organization_id,user_id) where status='active';
create unique index learning_provider_organization_memberships_one_active_owner
  on public.learning_provider_organization_memberships(organization_id) where status='active' and role='owner';
create index learning_provider_organization_memberships_user_idx on public.learning_provider_organization_memberships(user_id,status,granted_at desc,id desc);

create table public.learning_provider_organization_membership_events (
  id bigint generated by default as identity primary key,
  membership_id bigint not null references public.learning_provider_organization_memberships(id) on delete restrict,
  organization_id bigint not null references public.learning_provider_organizations(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete restrict,
  event_type text not null check (event_type in ('membership.created','membership.suspended','membership.revoked')),
  actor_user_id uuid references public.profiles(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  occurred_at timestamptz not null default now()
);
create index learning_provider_organization_membership_events_membership_idx on public.learning_provider_organization_membership_events(membership_id,occurred_at,id);

alter table public.learning_provider_organizations enable row level security;
alter table public.learning_provider_organization_memberships enable row level security;
alter table public.learning_provider_organization_membership_events enable row level security;
revoke all on public.learning_provider_organizations,public.learning_provider_organization_memberships,public.learning_provider_organization_membership_events from public,anon,authenticated;
grant select,insert,update,delete on public.learning_provider_organizations,public.learning_provider_organization_memberships,public.learning_provider_organization_membership_events to postgres,service_role;

create or replace function public.prevent_learning_provider_organization_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if tg_op='DELETE' then raise exception 'Training organization history cannot be deleted' using errcode='42501'; end if;
  if old.id is distinct from new.id or old.name is distinct from new.name or old.slug is distinct from new.slug
    or old.created_by is distinct from new.created_by or old.created_at is distinct from new.created_at then
    raise exception 'Training organization identity is immutable' using errcode='42501';
  end if;
  if (old.status='active' and new.status='suspended' and new.suspended_at is not null and new.archived_at is null)
    or (old.status in ('active','suspended') and new.status='archived' and new.archived_at is not null) then return new; end if;
  raise exception 'Unsupported training organization lifecycle transition' using errcode='22023';
end;$function$;
create trigger prevent_learning_provider_organization_mutation before update or delete on public.learning_provider_organizations for each row execute function public.prevent_learning_provider_organization_mutation();

create or replace function public.prevent_learning_provider_organization_membership_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if tg_op='DELETE' then raise exception 'Training organization membership history cannot be deleted' using errcode='42501'; end if;
  if old.id is distinct from new.id or old.organization_id is distinct from new.organization_id or old.user_id is distinct from new.user_id
    or old.role is distinct from new.role or old.granted_by is distinct from new.granted_by or old.granted_at is distinct from new.granted_at then
    raise exception 'Training organization membership identity is immutable' using errcode='42501';
  end if;
  if old.status='active' and new.status in ('suspended','revoked') and new.ended_at is not null then return new; end if;
  raise exception 'Unsupported training organization membership transition' using errcode='22023';
end;$function$;
create trigger prevent_learning_provider_organization_membership_mutation before update or delete on public.learning_provider_organization_memberships for each row execute function public.prevent_learning_provider_organization_membership_mutation();

create or replace function public.prevent_learning_provider_organization_membership_event_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin raise exception 'Training organization membership events are append-only' using errcode='42501'; end;$function$;
create trigger prevent_learning_provider_organization_membership_event_mutation before update or delete on public.learning_provider_organization_membership_events for each row execute function public.prevent_learning_provider_organization_membership_event_mutation();

create or replace function public.create_own_learning_provider_organization(p_name text,p_slug text)
returns table(organization_id bigint,name text,slug text,status text,created_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare organization_key bigint; normalized_name text:=btrim(p_name); normalized_slug text:=lower(btrim(p_slug));
begin
  if auth.uid() is null or not public.is_approved_growvelt_instructor() then raise exception 'Active approved instructor required' using errcode='42501'; end if;
  if normalized_name is null or char_length(normalized_name) not between 2 and 160 or normalized_slug is null or normalized_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' or char_length(normalized_slug) not between 3 and 100 then raise exception 'Invalid training organization identity' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-provider-organization:'||normalized_slug,0));
  insert into public.learning_provider_organizations(name,slug,created_by) values(normalized_name,normalized_slug,auth.uid()) returning id into organization_key;
  insert into public.learning_provider_organization_memberships(organization_id,user_id,role,granted_by) values(organization_key,auth.uid(),'owner',auth.uid());
  insert into public.learning_provider_organization_membership_events(membership_id,organization_id,user_id,event_type,actor_user_id,metadata)
  select membership.id,organization_key,auth.uid(),'membership.created',auth.uid(),jsonb_build_object('role','owner','source','organization.create') from public.learning_provider_organization_memberships membership where membership.organization_id=organization_key and membership.user_id=auth.uid() and membership.status='active';
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(auth.uid(),'instructor','provider_organization.created','learning_provider_organization',organization_key::text,jsonb_build_object('slug',normalized_slug));
  return query select organization.id,organization.name,organization.slug,organization.status,organization.created_at from public.learning_provider_organizations organization where organization.id=organization_key;
end;$function$;

create or replace function public.list_own_learning_provider_organizations()
returns table(organization_id bigint,name text,slug text,organization_status text,membership_role text,membership_status text,created_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  return query select organization.id,organization.name,organization.slug,organization.status,membership.role,membership.status,organization.created_at from public.learning_provider_organization_memberships membership join public.learning_provider_organizations organization on organization.id=membership.organization_id where membership.user_id=auth.uid() order by organization.created_at desc,organization.id desc;
end;$function$;

revoke all on function public.prevent_learning_provider_organization_mutation(),public.prevent_learning_provider_organization_membership_mutation(),public.prevent_learning_provider_organization_membership_event_mutation(),public.create_own_learning_provider_organization(text,text),public.list_own_learning_provider_organizations() from public,anon,authenticated;
grant execute on function public.create_own_learning_provider_organization(text,text),public.list_own_learning_provider_organizations() to authenticated,postgres,service_role;
grant execute on function public.prevent_learning_provider_organization_mutation(),public.prevent_learning_provider_organization_membership_mutation(),public.prevent_learning_provider_organization_membership_event_mutation() to postgres,service_role;

commit;
