-- Phase 2B1: internal, admin-reviewed provider verification.
-- No public provider profile or public "verified" claim is introduced here.

create table public.learning_provider_organization_verifications (
  organization_id bigint primary key references public.learning_provider_organizations(id) on delete restrict,
  status text not null check (status in ('pending','verified','rejected')),
  legal_name text not null check (char_length(btrim(legal_name)) between 2 and 160),
  contact_email text not null check (char_length(btrim(contact_email)) between 5 and 320),
  website_url text check (website_url is null or char_length(website_url) <= 400),
  verification_statement text not null check (char_length(btrim(verification_statement)) between 30 and 2000),
  submitted_by uuid not null references public.profiles(id) on delete restrict,
  submitted_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(id) on delete restrict,
  reviewed_at timestamptz,
  review_note text check (review_note is null or char_length(review_note) <= 2000),
  constraint learning_provider_organization_verifications_lifecycle_check check (
    (status = 'pending' and reviewed_by is null and reviewed_at is null and review_note is null)
    or (status in ('verified','rejected') and reviewed_by is not null and reviewed_at is not null)
  )
);

create table public.learning_provider_organization_verification_events (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.learning_provider_organizations(id) on delete restrict,
  event_type text not null check (event_type in ('verification.submitted','verification.resubmitted','verification.verified','verification.rejected')),
  actor_user_id uuid references public.profiles(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  occurred_at timestamptz not null default now()
);

alter table public.learning_provider_organization_verifications enable row level security;
alter table public.learning_provider_organization_verification_events enable row level security;
revoke all on public.learning_provider_organization_verifications, public.learning_provider_organization_verification_events from public, anon, authenticated;
grant select, insert, update, delete on public.learning_provider_organization_verifications, public.learning_provider_organization_verification_events to postgres, service_role;

create or replace function public.submit_own_learning_provider_organization_verification(
  p_organization_id bigint,
  p_legal_name text,
  p_contact_email text,
  p_website_url text,
  p_verification_statement text
)
returns table(organization_id bigint, status text, submitted_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare
  current_verification public.learning_provider_organization_verifications%rowtype;
  legal_name_value text := btrim(p_legal_name);
  contact_email_value text := lower(btrim(p_contact_email));
  website_url_value text := nullif(btrim(p_website_url), '');
  statement_value text := btrim(p_verification_statement);
  is_resubmission boolean := false;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if p_organization_id is null or not exists (
    select 1 from public.learning_provider_organization_memberships membership
    join public.learning_provider_organizations organization on organization.id = membership.organization_id
    where membership.organization_id = p_organization_id and membership.user_id = auth.uid()
      and membership.role = 'owner' and membership.status = 'active' and organization.status = 'active'
  ) then raise exception 'Active organization owner required' using errcode='42501'; end if;
  if legal_name_value is null or char_length(legal_name_value) not between 2 and 160
    or contact_email_value is null or contact_email_value !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
    or (website_url_value is not null and (char_length(website_url_value) > 400 or website_url_value !~* '^https?://'))
    or statement_value is null or char_length(statement_value) not between 30 and 2000
  then raise exception 'Invalid provider verification details' using errcode='22023'; end if;

  select * into current_verification from public.learning_provider_organization_verifications as existing_verification where existing_verification.organization_id = p_organization_id for update;
  if found and current_verification.status = 'verified' then raise exception 'Provider is already verified' using errcode='P0001'; end if;
  if found and current_verification.status = 'pending' then raise exception 'Provider verification is already under review' using errcode='P0001'; end if;
  is_resubmission := found;

  if found then
    update public.learning_provider_organization_verifications
    set status = 'pending', legal_name = legal_name_value, contact_email = contact_email_value, website_url = website_url_value,
        verification_statement = statement_value, submitted_by = auth.uid(), submitted_at = now(), reviewed_by = null, reviewed_at = null, review_note = null
    where learning_provider_organization_verifications.organization_id = p_organization_id;
  else
    insert into public.learning_provider_organization_verifications(organization_id,status,legal_name,contact_email,website_url,verification_statement,submitted_by)
    values(p_organization_id,'pending',legal_name_value,contact_email_value,website_url_value,statement_value,auth.uid());
  end if;

  insert into public.learning_provider_organization_verification_events(organization_id,event_type,actor_user_id,metadata)
  values(p_organization_id,case when is_resubmission then 'verification.resubmitted' else 'verification.submitted' end,auth.uid(),jsonb_build_object('website_supplied',website_url_value is not null));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(auth.uid(),'organization_owner','provider_organization.verification_submitted','learning_provider_organization',p_organization_id::text,jsonb_build_object('resubmission',is_resubmission));
  return query select verification.organization_id,verification.status,verification.submitted_at from public.learning_provider_organization_verifications verification where verification.organization_id=p_organization_id;
end;$function$;

create or replace function public.list_own_learning_provider_organization_verifications()
returns table(organization_id bigint,status text,legal_name text,contact_email text,website_url text,verification_statement text,submitted_at timestamptz,reviewed_at timestamptz,review_note text)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  return query
  select verification.organization_id,verification.status,verification.legal_name,verification.contact_email,verification.website_url,verification.verification_statement,verification.submitted_at,verification.reviewed_at,verification.review_note
  from public.learning_provider_organization_verifications verification
  join public.learning_provider_organization_memberships membership on membership.organization_id=verification.organization_id
  where membership.user_id=auth.uid() and membership.status='active';
end;$function$;

revoke all on function public.submit_own_learning_provider_organization_verification(bigint,text,text,text,text),public.list_own_learning_provider_organization_verifications() from public,anon,authenticated;
grant execute on function public.submit_own_learning_provider_organization_verification(bigint,text,text,text,text),public.list_own_learning_provider_organization_verifications() to authenticated,postgres,service_role;

create or replace function public.list_pending_learning_provider_organization_verifications()
returns table(organization_id bigint,organization_name text,organization_slug text,legal_name text,contact_email text,website_url text,verification_statement text,submitted_at timestamptz,submitted_by_name text,submitted_by_email text)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or not public.is_growvelt_learning_admin() then raise exception 'Learning Admin access required' using errcode='42501'; end if;
  return query
  select organization.id,organization.name,organization.slug,verification.legal_name,verification.contact_email,verification.website_url,verification.verification_statement,verification.submitted_at,profile.full_name,profile.email
  from public.learning_provider_organization_verifications verification
  join public.learning_provider_organizations organization on organization.id=verification.organization_id
  join public.profiles profile on profile.id=verification.submitted_by
  where verification.status='pending'
  order by verification.submitted_at asc,verification.organization_id asc;
end;$function$;

create or replace function public.review_learning_provider_organization_verification(p_organization_id bigint,p_decision text,p_review_note text default null)
returns table(organization_id bigint,status text,reviewed_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare verification public.learning_provider_organization_verifications%rowtype; note_value text:=nullif(btrim(p_review_note),'');
begin
  if auth.uid() is null or not public.is_growvelt_learning_admin() then raise exception 'Learning Admin access required' using errcode='42501'; end if;
  if p_decision not in ('verified','rejected') then raise exception 'Invalid verification decision' using errcode='22023'; end if;
  if char_length(coalesce(note_value,''))>2000 or (p_decision='rejected' and char_length(coalesce(note_value,''))<10) then raise exception 'A rejection note of at least 10 characters is required' using errcode='22023'; end if;
  select * into verification from public.learning_provider_organization_verifications as pending_verification where pending_verification.organization_id=p_organization_id for update;
  if not found then raise exception 'Provider verification not found' using errcode='P0002'; end if;
  if verification.status<>'pending' then raise exception 'Provider verification is no longer pending' using errcode='P0001'; end if;
  update public.learning_provider_organization_verifications set status=p_decision,reviewed_by=auth.uid(),reviewed_at=now(),review_note=note_value where learning_provider_organization_verifications.organization_id=p_organization_id;
  insert into public.learning_provider_organization_verification_events(organization_id,event_type,actor_user_id,metadata) values(p_organization_id,case when p_decision='verified' then 'verification.verified' else 'verification.rejected' end,auth.uid(),jsonb_build_object('review_note_provided',note_value is not null));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(auth.uid(),'admin','provider_organization.verification_reviewed','learning_provider_organization',p_organization_id::text,jsonb_build_object('decision',p_decision));
  return query select verification_result.organization_id,verification_result.status,verification_result.reviewed_at from public.learning_provider_organization_verifications verification_result where verification_result.organization_id=p_organization_id;
end;$function$;

revoke all on function public.list_pending_learning_provider_organization_verifications(),public.review_learning_provider_organization_verification(bigint,text,text) from public,anon,authenticated;
grant execute on function public.list_pending_learning_provider_organization_verifications(),public.review_learning_provider_organization_verification(bigint,text,text) to authenticated,postgres,service_role;
