-- Phase 4: private coupon administration and atomic Test Mode reservations.
-- This migration does not alter checkout, orders, seller allocations or Live payments.

begin;

create table public.learning_promotion_coupons (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[A-Z0-9][A-Z0-9_-]{3,23}$'),
  discount_kind text not null check (discount_kind in ('fixed','percentage')),
  discount_value bigint not null,
  max_discount_minor bigint not null check (max_discount_minor > 0),
  minimum_charge_minor bigint not null check (minimum_charge_minor > 0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  max_redemptions integer check (max_redemptions is null or max_redemptions > 0),
  max_redemptions_per_user integer not null default 1 check (max_redemptions_per_user = 1),
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  disabled_by uuid references public.profiles(id) on delete set null,
  disabled_at timestamptz,
  constraint learning_promotion_coupons_dates_check check (starts_at < ends_at),
  constraint learning_promotion_coupons_discount_value_check check (
    (discount_kind = 'percentage' and discount_value between 1 and 10000)
    or (discount_kind = 'fixed' and discount_value between 1 and max_discount_minor)
  ),
  constraint learning_promotion_coupons_disabled_check check (
    (active and disabled_by is null and disabled_at is null)
    or (not active and disabled_at is not null)
  )
);

create table public.learning_promotion_coupon_courses (
  coupon_id bigint not null references public.learning_promotion_coupons(id) on delete restrict,
  course_id bigint not null references public.learning_courses(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (coupon_id, course_id)
);

create table public.learning_promotion_redemptions (
  id uuid primary key default gen_random_uuid(),
  coupon_id bigint not null references public.learning_promotion_coupons(id) on delete restrict,
  learner_id uuid not null references public.profiles(id) on delete restrict,
  course_id bigint not null references public.learning_courses(id) on delete restrict,
  reservation_key uuid not null unique,
  payment_mode text not null default 'test' check (payment_mode = 'test'),
  status text not null default 'reserved' check (status in ('reserved','consumed','released','expired')),
  order_id bigint unique references public.learning_orders(id) on delete restrict,
  currency text not null default 'NGN' check (currency = 'NGN'),
  list_price_minor bigint not null check (list_price_minor > 0),
  discount_minor bigint not null check (discount_minor > 0),
  customer_charge_minor bigint not null check (customer_charge_minor > 0),
  seller_share_minor bigint not null check (seller_share_minor >= 0),
  platform_share_minor bigint not null check (platform_share_minor >= 0),
  commercial_terms_version text not null,
  reserved_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  released_at timestamptz,
  constraint learning_promotion_redemptions_split_check check (
    list_price_minor = discount_minor + customer_charge_minor
    and customer_charge_minor = seller_share_minor + platform_share_minor
  ),
  constraint learning_promotion_redemptions_lifecycle_check check (
    (status = 'reserved' and consumed_at is null and released_at is null and order_id is null)
    or (status = 'consumed' and consumed_at is not null and released_at is null and order_id is not null)
    or (status in ('released','expired') and consumed_at is null and released_at is not null and order_id is null)
  )
);

create index learning_promotion_coupon_courses_course_idx
  on public.learning_promotion_coupon_courses(course_id, coupon_id);
create index learning_promotion_redemptions_coupon_status_idx
  on public.learning_promotion_redemptions(coupon_id, status, expires_at);
create index learning_promotion_redemptions_learner_idx
  on public.learning_promotion_redemptions(learner_id, coupon_id, status);

alter table public.learning_promotion_coupons enable row level security;
alter table public.learning_promotion_coupon_courses enable row level security;
alter table public.learning_promotion_redemptions enable row level security;
revoke all on public.learning_promotion_coupons, public.learning_promotion_coupon_courses,
  public.learning_promotion_redemptions from public, anon, authenticated, service_role;
revoke all on sequence public.learning_promotion_coupons_id_seq from public, anon, authenticated, service_role;

create or replace function public.prevent_learning_promotion_coupon_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if tg_op = 'DELETE' then
    raise exception 'Promotion coupon history cannot be deleted' using errcode = '42501';
  end if;
  if old.id is distinct from new.id or old.code is distinct from new.code
    or old.discount_kind is distinct from new.discount_kind
    or old.discount_value is distinct from new.discount_value
    or old.max_discount_minor is distinct from new.max_discount_minor
    or old.minimum_charge_minor is distinct from new.minimum_charge_minor
    or old.starts_at is distinct from new.starts_at or old.ends_at is distinct from new.ends_at
    or old.max_redemptions is distinct from new.max_redemptions
    or old.max_redemptions_per_user is distinct from new.max_redemptions_per_user
    or old.created_by is distinct from new.created_by or old.created_at is distinct from new.created_at then
    raise exception 'Coupon terms are immutable; disable and issue a new code' using errcode = '42501';
  end if;
  if old.active and not new.active and new.disabled_at is null then new.disabled_at := now(); end if;
  if not old.active and new.active then
    raise exception 'Disabled coupons cannot be reactivated' using errcode = '42501';
  end if;
  return new;
end;
$function$;

create trigger prevent_learning_promotion_coupon_mutation
before update or delete on public.learning_promotion_coupons
for each row execute function public.prevent_learning_promotion_coupon_mutation();

create or replace function public.list_learning_promotion_course_options_for_admin()
returns table(course_id bigint, title text, price_amount numeric, currency text)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or not public.is_growvelt_learning_admin() then
    raise exception 'Learning Admin capability required' using errcode = '42501';
  end if;
  return query
    select course.id, course.title, course.price_amount, course.price_currency
    from public.learning_courses course
    where course.status = 'published' and course.is_free = false
      and coalesce(course.is_limited_time_free, false) = false
      and coalesce(course.company_test_mode_only, false) = false
      and course.organization_id is null and course.price_currency = 'NGN'
      and course.price_amount > 0
      and not public.is_paystack_test_fixture_course(course.id)
    order by course.title, course.id;
end;
$function$;

create or replace function public.create_learning_promotion_coupon_for_admin(
  p_code text,
  p_discount_kind text,
  p_discount_value bigint,
  p_max_discount_minor bigint,
  p_minimum_charge_minor bigint,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_max_redemptions integer,
  p_course_ids bigint[]
)
returns bigint language plpgsql security definer set search_path to '' as $function$
declare
  actor_id uuid := auth.uid();
  normalized_code text := upper(btrim(p_code));
  coupon_key bigint;
  selected_count integer;
begin
  if actor_id is null or not public.is_growvelt_learning_admin() then
    raise exception 'Learning Admin capability required' using errcode = '42501';
  end if;
  if normalized_code is null or normalized_code !~ '^[A-Z0-9][A-Z0-9_-]{3,23}$'
    or p_discount_kind is null or p_discount_kind not in ('fixed','percentage')
    or p_discount_value is null or p_discount_value <= 0
    or p_max_discount_minor is null or p_max_discount_minor <= 0
    or p_minimum_charge_minor is null or p_minimum_charge_minor <= 0
    or p_starts_at is null or p_ends_at is null or p_starts_at >= p_ends_at
    or (p_discount_kind = 'percentage' and p_discount_value > 10000)
    or (p_discount_kind = 'fixed' and p_discount_value > p_max_discount_minor)
    or p_max_redemptions is not null and p_max_redemptions < 1
    or p_course_ids is null or cardinality(p_course_ids) not between 1 and 20 then
    raise exception 'Coupon settings are invalid' using errcode = '22023';
  end if;

  select count(distinct selected.course_id)::integer into selected_count
  from unnest(p_course_ids) selected(course_id)
  join public.learning_courses course on course.id = selected.course_id
  where course.status = 'published' and course.is_free = false
    and coalesce(course.is_limited_time_free, false) = false
    and coalesce(course.company_test_mode_only, false) = false
    and course.organization_id is null and course.price_currency = 'NGN'
    and course.price_amount > 0 and not public.is_paystack_test_fixture_course(course.id);
  if selected_count <> cardinality(p_course_ids) then
    raise exception 'Choose only currently eligible public paid courses' using errcode = '22023';
  end if;

  insert into public.learning_promotion_coupons(
    code, discount_kind, discount_value, max_discount_minor, minimum_charge_minor,
    starts_at, ends_at, max_redemptions, created_by
  ) values (
    normalized_code, p_discount_kind, p_discount_value, p_max_discount_minor,
    p_minimum_charge_minor, p_starts_at, p_ends_at, p_max_redemptions, actor_id
  ) returning id into coupon_key;

  insert into public.learning_promotion_coupon_courses(coupon_id, course_id)
    select coupon_key, selected.course_id from unnest(p_course_ids) selected(course_id);

  insert into public.learning_audit_events(actor_user_id, actor_role, action, entity_type, entity_id, metadata)
  values (actor_id, 'admin_operator', 'promotion_coupon.created', 'promotion_coupon', coupon_key::text,
    jsonb_build_object('discount_kind', p_discount_kind, 'course_count', cardinality(p_course_ids),
      'max_redemptions', p_max_redemptions));
  return coupon_key;
end;
$function$;

create or replace function public.disable_learning_promotion_coupon_for_admin(p_coupon_id bigint)
returns boolean language plpgsql security definer set search_path to '' as $function$
declare actor_id uuid := auth.uid();
begin
  if actor_id is null or not public.is_growvelt_learning_admin() then
    raise exception 'Learning Admin capability required' using errcode = '42501';
  end if;
  update public.learning_promotion_coupons
  set active = false, disabled_by = actor_id, disabled_at = now()
  where id = p_coupon_id and active;
  if not found then raise exception 'Active coupon not found' using errcode = 'P0002'; end if;
  insert into public.learning_audit_events(actor_user_id, actor_role, action, entity_type, entity_id, metadata)
  values (actor_id, 'admin_operator', 'promotion_coupon.disabled', 'promotion_coupon', p_coupon_id::text, '{}'::jsonb);
  return true;
end;
$function$;

create or replace function public.list_learning_promotion_coupons_for_admin()
returns table(
  coupon_id bigint, code text, discount_kind text, discount_value bigint,
  max_discount_minor bigint, minimum_charge_minor bigint, starts_at timestamptz,
  ends_at timestamptz, max_redemptions integer, active boolean,
  redeemed_count bigint, course_ids bigint[]
)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or not public.is_growvelt_learning_admin() then
    raise exception 'Learning Admin capability required' using errcode = '42501';
  end if;
  return query
    select coupon.id, coupon.code, coupon.discount_kind, coupon.discount_value,
      coupon.max_discount_minor, coupon.minimum_charge_minor, coupon.starts_at, coupon.ends_at,
      coupon.max_redemptions, coupon.active,
      (select count(*) from public.learning_promotion_redemptions redemption
        where redemption.coupon_id = coupon.id and (redemption.status = 'consumed'
          or (redemption.status = 'reserved' and redemption.expires_at > now()))),
      coalesce((select array_agg(link.course_id order by link.course_id)
        from public.learning_promotion_coupon_courses link where link.coupon_id = coupon.id), '{}'::bigint[])
    from public.learning_promotion_coupons coupon
    order by coupon.created_at desc, coupon.id desc
    limit 200;
end;
$function$;

create or replace function public.reserve_learning_promotion_coupon_for_test(
  p_code text,
  p_learner_id uuid,
  p_course_id bigint,
  p_reservation_key uuid
)
returns table(
  redemption_id uuid, status text, expires_at timestamptz, list_price_minor bigint,
  discount_minor bigint, customer_charge_minor bigint, seller_share_minor bigint,
  platform_share_minor bigint, commercial_terms_version text
)
language plpgsql security definer set search_path to '' as $function$
declare
  coupon_row public.learning_promotion_coupons%rowtype;
  course_row public.learning_courses%rowtype;
  terms_row public.learning_commercial_terms%rowtype;
  prior_row public.learning_promotion_redemptions%rowtype;
  redemption_key uuid;
  terms_version text;
  price_minor bigint;
  platform_minor bigint;
  seller_minor bigint;
  raw_discount bigint;
  discount_minor bigint;
  charge_minor bigint;
begin
  if coalesce(auth.role(), '') <> 'service_role' or p_learner_id is null
    or p_course_id is null or p_reservation_key is null then
    raise exception 'Coupon checkout reservation is unavailable' using errcode = '42501';
  end if;

  select * into prior_row from public.learning_promotion_redemptions
    where reservation_key = p_reservation_key;
  if found then
    if prior_row.learner_id <> p_learner_id or prior_row.course_id <> p_course_id
      or not exists(select 1 from public.learning_promotion_coupons coupon
        where coupon.id = prior_row.coupon_id and coupon.code = upper(btrim(p_code)))
      or prior_row.status <> 'reserved' or prior_row.expires_at <= now() then
      raise exception 'Coupon checkout reservation is unavailable' using errcode = '22023';
    end if;
    return query select prior_row.id, prior_row.status, prior_row.expires_at,
      prior_row.list_price_minor, prior_row.discount_minor, prior_row.customer_charge_minor,
      prior_row.seller_share_minor, prior_row.platform_share_minor, prior_row.commercial_terms_version;
    return;
  end if;

  select * into coupon_row from public.learning_promotion_coupons
    where code = upper(btrim(p_code)) for update;
  if not found or not coupon_row.active or coupon_row.starts_at > now() or coupon_row.ends_at <= now() then
    raise exception 'Coupon is invalid or unavailable' using errcode = '22023';
  end if;
  if not exists(select 1 from public.learning_promotion_coupon_courses link
      where link.coupon_id = coupon_row.id and link.course_id = p_course_id) then
    raise exception 'Coupon is invalid or unavailable' using errcode = '22023';
  end if;

  update public.learning_promotion_redemptions as redemption
    set status = 'expired', released_at = now()
    where redemption.coupon_id = coupon_row.id and redemption.status = 'reserved'
      and redemption.expires_at <= now();

  if coupon_row.max_redemptions is not null and (
      select count(*) from public.learning_promotion_redemptions redemption
      where redemption.coupon_id = coupon_row.id and (redemption.status = 'consumed'
        or (redemption.status = 'reserved' and redemption.expires_at > now()))
    ) >= coupon_row.max_redemptions then
    raise exception 'Coupon is invalid or unavailable' using errcode = '22023';
  end if;
  if (select count(*) from public.learning_promotion_redemptions redemption
      where redemption.coupon_id = coupon_row.id and redemption.learner_id = p_learner_id
        and (redemption.status = 'consumed' or (redemption.status = 'reserved' and redemption.expires_at > now())))
      >= coupon_row.max_redemptions_per_user then
    raise exception 'Coupon is invalid or unavailable' using errcode = '22023';
  end if;

  select * into course_row from public.learning_courses course
    where course.id = p_course_id and course.status = 'published'
      and course.is_free = false and coalesce(course.is_limited_time_free, false) = false
      and coalesce(course.company_test_mode_only, false) = false
      and course.organization_id is null and course.price_currency = 'NGN'
      and course.price_amount > 0 and not public.is_paystack_test_fixture_course(course.id);
  if not found then raise exception 'Coupon is invalid or unavailable' using errcode = '22023'; end if;

  terms_version := public.resolve_learning_commercial_terms_version(course_row.id, course_row.instructor_id);
  select * into terms_row from public.learning_commercial_terms where version = terms_version;
  if not found then raise exception 'Coupon is invalid or unavailable' using errcode = '22023'; end if;
  price_minor := round(course_row.price_amount * 100)::bigint;
  platform_minor := round(price_minor * terms_row.commission_basis_points / 10000.0)::bigint;
  seller_minor := price_minor - platform_minor;
  if coupon_row.discount_kind = 'fixed' then
    raw_discount := coupon_row.discount_value;
  else
    raw_discount := round(price_minor * coupon_row.discount_value / 10000.0)::bigint;
  end if;
  discount_minor := least(raw_discount, coupon_row.max_discount_minor);
  charge_minor := price_minor - discount_minor;
  if discount_minor <= 0 or discount_minor > platform_minor
    or charge_minor < coupon_row.minimum_charge_minor then
    raise exception 'Coupon is invalid or unavailable' using errcode = '22023';
  end if;

  insert into public.learning_promotion_redemptions(
    coupon_id, learner_id, course_id, reservation_key, list_price_minor,
    discount_minor, customer_charge_minor, seller_share_minor, platform_share_minor,
    commercial_terms_version, expires_at
  ) values (
    coupon_row.id, p_learner_id, course_row.id, p_reservation_key, price_minor,
    discount_minor, charge_minor, seller_minor, platform_minor - discount_minor,
    terms_version, now() + interval '15 minutes'
  ) returning id into redemption_key;

  return query select redemption.id, redemption.status, redemption.expires_at,
    redemption.list_price_minor, redemption.discount_minor, redemption.customer_charge_minor,
    redemption.seller_share_minor, redemption.platform_share_minor, redemption.commercial_terms_version
    from public.learning_promotion_redemptions redemption where redemption.id = redemption_key;
end;
$function$;

revoke all on function public.prevent_learning_promotion_coupon_mutation() from public, anon, authenticated;
revoke all on function public.list_learning_promotion_course_options_for_admin() from public, anon;
revoke all on function public.create_learning_promotion_coupon_for_admin(text,text,bigint,bigint,bigint,timestamptz,timestamptz,integer,bigint[]) from public, anon;
revoke all on function public.disable_learning_promotion_coupon_for_admin(bigint) from public, anon;
revoke all on function public.list_learning_promotion_coupons_for_admin() from public, anon;
revoke all on function public.reserve_learning_promotion_coupon_for_test(text,uuid,bigint,uuid) from public, anon, authenticated;
grant execute on function public.list_learning_promotion_course_options_for_admin() to authenticated, postgres;
grant execute on function public.create_learning_promotion_coupon_for_admin(text,text,bigint,bigint,bigint,timestamptz,timestamptz,integer,bigint[]) to authenticated, postgres;
grant execute on function public.disable_learning_promotion_coupon_for_admin(bigint) to authenticated, postgres;
grant execute on function public.list_learning_promotion_coupons_for_admin() to authenticated, postgres;
grant execute on function public.reserve_learning_promotion_coupon_for_test(text,uuid,bigint,uuid) to service_role, postgres;

commit;
