-- Phase 0C: append-only audit events for current privileged learning actions.
-- This migration creates new objects only and does not modify existing rows.

create table public.learning_audit_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_user_id uuid,
  actor_role text not null,
  action text not null check (action ~ '^[a-z][a-z0-9_.]{2,100}$'),
  entity_type text not null check (entity_type ~ '^[a-z][a-z0-9_]{1,60}$'),
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  constraint learning_audit_events_metadata_object_check check (jsonb_typeof(metadata) = 'object')
);

alter table public.learning_audit_events enable row level security;

create index learning_audit_events_occurred_at_idx on public.learning_audit_events (occurred_at desc, id desc);
create index learning_audit_events_entity_idx on public.learning_audit_events (entity_type, entity_id, occurred_at desc);
create index learning_audit_events_actor_idx on public.learning_audit_events (actor_user_id, occurred_at desc) where actor_user_id is not null;

revoke all on table public.learning_audit_events from public, anon, authenticated;
grant select, insert on table public.learning_audit_events to postgres, service_role;
revoke all on sequence public.learning_audit_events_id_seq from public, anon, authenticated;
grant usage, select on sequence public.learning_audit_events_id_seq to postgres, service_role;

create or replace function public.prevent_learning_audit_event_mutation()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  raise exception 'Learning audit events are append-only' using errcode = '42501';
end;
$function$;

revoke all on function public.prevent_learning_audit_event_mutation() from public, anon, authenticated;
grant execute on function public.prevent_learning_audit_event_mutation() to postgres, service_role;

create trigger learning_audit_events_immutable
before update or delete on public.learning_audit_events
for each row execute function public.prevent_learning_audit_event_mutation();

create or replace function public.capture_learning_security_audit_event()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  actor_id uuid := auth.uid();
  event_action text := tg_argv[0];
  event_entity_type text := tg_argv[1];
  event_entity_id text;
  event_metadata jsonb := '{}'::jsonb;
begin
  if tg_table_name = 'account_capabilities' then
    event_entity_id := new.user_id::text || ':' || new.capability;
    event_metadata := jsonb_build_object('old_status', case when tg_op = 'INSERT' then null else old.status end, 'new_status', new.status);
  elsif tg_table_name = 'instructor_profiles' then
    event_entity_id := new.user_id::text;
    event_metadata := jsonb_build_object('old_status', old.approval_status, 'new_status', new.approval_status);
  elsif tg_table_name = 'learning_courses' then
    event_entity_id := new.id::text;
    event_metadata := jsonb_build_object('old_status', old.status, 'new_status', new.status);
  elsif tg_table_name = 'certificates' then
    event_entity_id := new.id::text;
    event_metadata := jsonb_build_object('status', new.status, 'certificate_code', new.certificate_code);
  else
    raise exception 'Unsupported learning audit source';
  end if;

  insert into public.learning_audit_events (actor_user_id, actor_role, action, entity_type, entity_id, metadata)
  values (actor_id, coalesce(auth.role(), 'database'), event_action, event_entity_type, event_entity_id, event_metadata);
  return new;
end;
$function$;

revoke all on function public.capture_learning_security_audit_event() from public, anon, authenticated;
grant execute on function public.capture_learning_security_audit_event() to postgres, service_role;

create trigger audit_learning_capability_change
after insert or update of status on public.account_capabilities
for each row execute function public.capture_learning_security_audit_event('capability.changed', 'account_capability');

create trigger audit_instructor_application_decision
after update of approval_status on public.instructor_profiles
for each row when (old.approval_status is distinct from new.approval_status)
execute function public.capture_learning_security_audit_event('instructor_application.status_changed', 'instructor_application');

create trigger audit_learning_course_status
after update of status on public.learning_courses
for each row when (old.status is distinct from new.status)
execute function public.capture_learning_security_audit_event('course.status_changed', 'learning_course');

create trigger audit_learning_certificate_issue
after insert on public.certificates
for each row execute function public.capture_learning_security_audit_event('certificate.issued', 'certificate');

create trigger audit_learning_certificate_status
after update of status on public.certificates
for each row when (old.status is distinct from new.status)
execute function public.capture_learning_security_audit_event('certificate.status_changed', 'certificate');
