-- Phase 3C1: payment-ready company sponsored paid-course purchases.
-- This records a locked course-price and selected employee seats. It does not
-- initialize checkout, collect money, or grant paid access until live payment
-- approval is enabled in a later Phase 3C slice.
begin;

create table public.learning_company_paid_course_purchases (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.learning_company_workspaces(id) on delete restrict,
  course_id bigint not null references public.learning_courses(id) on delete restrict,
  requested_by uuid not null references public.profiles(id) on delete restrict,
  course_title_snapshot text not null,
  provider_name_snapshot text not null,
  unit_amount_minor bigint not null check (unit_amount_minor > 0),
  total_amount_minor bigint not null check (total_amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  seat_count integer not null check (seat_count between 1 and 100000),
  status text not null default 'checkout_ready' check (status in ('checkout_ready','checkout_pending','paid','cancelled','expired')),
  created_at timestamptz not null default now(),
  checkout_started_at timestamptz,
  paid_at timestamptz,
  cancelled_at timestamptz,
  constraint learning_company_paid_purchase_lifecycle_check check (
    (status = 'checkout_ready' and checkout_started_at is null and paid_at is null and cancelled_at is null)
    or (status = 'checkout_pending' and checkout_started_at is not null and paid_at is null and cancelled_at is null)
    or (status = 'paid' and checkout_started_at is not null and paid_at is not null and cancelled_at is null)
    or (status in ('cancelled','expired') and paid_at is null and cancelled_at is not null)
  )
);

create table public.learning_company_paid_course_purchase_seats (
  purchase_id bigint not null references public.learning_company_paid_course_purchases(id) on delete restrict,
  assigned_user_id uuid not null references public.profiles(id) on delete restrict,
  primary key (purchase_id, assigned_user_id)
);

create index learning_company_paid_purchase_workspace_idx on public.learning_company_paid_course_purchases(workspace_id, created_at desc, id desc);
create index learning_company_paid_purchase_seat_idx on public.learning_company_paid_course_purchase_seats(assigned_user_id, purchase_id);
alter table public.learning_company_paid_course_purchases enable row level security;
alter table public.learning_company_paid_course_purchase_seats enable row level security;
revoke all on public.learning_company_paid_course_purchases, public.learning_company_paid_course_purchase_seats from public, anon, authenticated;
grant select, insert, update, delete on public.learning_company_paid_course_purchases, public.learning_company_paid_course_purchase_seats to postgres, service_role;
grant usage, select on sequence public.learning_company_paid_course_purchases_id_seq to postgres, service_role;

create or replace function public.list_own_learning_company_paid_courses(p_workspace_id bigint)
returns table(course_id bigint,title text,summary text,category text,level text,price_amount numeric,currency text,instructor_name text,provider_name text)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or p_workspace_id is null or not exists(
    select 1 from public.learning_company_workspaces workspace
    join public.learning_company_memberships manager on manager.workspace_id = workspace.id
    where workspace.id = p_workspace_id and workspace.status = 'active' and manager.user_id = auth.uid() and manager.status = 'active' and manager.role in ('owner','admin')
  ) then raise exception 'Active company manager required' using errcode = '42501'; end if;
  return query
  select course_row.id, course_row.title, course_row.summary, course_row.category, course_row.level, course_row.price_amount, course_row.price_currency,
    instructor.full_name, coalesce(provider.name, instructor.full_name, 'Growvelt instructor')
  from public.learning_courses course_row
  left join public.profiles instructor on instructor.id = course_row.instructor_id
  left join public.learning_provider_organizations provider on provider.id = course_row.organization_id and provider.status = 'active'
  where course_row.status = 'published' and course_row.is_free = false and coalesce(course_row.is_limited_time_free, false) = false
    and course_row.price_amount is not null and course_row.price_amount > 0 and course_row.price_currency = 'NGN'
  order by course_row.published_at desc nulls last, course_row.id desc;
end;$function$;

create or replace function public.prepare_learning_company_paid_course_purchase(p_workspace_id bigint,p_course_id bigint,p_assigned_user_ids uuid[])
returns table(purchase_id bigint,course_title text,provider_name text,seat_count integer,unit_amount_minor bigint,total_amount_minor bigint,currency text,status text)
language plpgsql security definer set search_path to '' as $function$
declare course_snapshot record; requested_count integer; purchase_key bigint; duplicate_count integer;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if p_workspace_id is null or p_course_id is null or p_assigned_user_ids is null then raise exception 'Invalid company purchase' using errcode = '22023'; end if;
  requested_count := cardinality(p_assigned_user_ids);
  if requested_count is null or requested_count < 1 or requested_count > 100000 then raise exception 'Choose at least one employee' using errcode = '22023'; end if;
  if requested_count <> (select count(distinct selected_user_id) from unnest(p_assigned_user_ids) selected_user_id) then raise exception 'Each employee can be selected once' using errcode = '22023'; end if;
  if not exists(
    select 1 from public.learning_company_workspaces workspace
    join public.learning_company_memberships manager on manager.workspace_id = workspace.id
    where workspace.id = p_workspace_id and workspace.status = 'active' and manager.user_id = auth.uid() and manager.status = 'active' and manager.role in ('owner','admin')
  ) then raise exception 'Active company manager required' using errcode = '42501'; end if;
  if requested_count > (select workspace.seat_limit from public.learning_company_workspaces workspace where workspace.id = p_workspace_id) then raise exception 'Selected employees exceed the company seat limit' using errcode = '22023'; end if;
  if requested_count <> (
    select count(*) from public.learning_company_memberships member
    where member.workspace_id = p_workspace_id and member.user_id = any(p_assigned_user_ids) and member.status = 'active' and member.role <> 'owner'
  ) then raise exception 'Each selected employee must be an active company member' using errcode = '42501'; end if;
  select course.id, course.title, course.price_amount, course.price_currency, coalesce(provider.name, instructor.full_name, 'Growvelt instructor') as provider_name
  into course_snapshot
  from public.learning_courses course
  left join public.profiles instructor on instructor.id = course.instructor_id
  left join public.learning_provider_organizations provider on provider.id = course.organization_id and provider.status = 'active'
  where course.id = p_course_id and course.status = 'published' and course.is_free = false and coalesce(course.is_limited_time_free, false) = false
    and course.price_amount is not null and course.price_amount > 0 and course.price_currency = 'NGN'
  for share of course;
  if not found then raise exception 'Choose an eligible published paid course' using errcode = '22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-company-paid-purchase:' || p_workspace_id::text || ':' || p_course_id::text, 0));
  select count(*) into duplicate_count
  from public.learning_company_paid_course_purchase_seats seat
  join public.learning_company_paid_course_purchases purchase on purchase.id = seat.purchase_id
  where purchase.workspace_id = p_workspace_id and purchase.course_id = p_course_id and purchase.status in ('checkout_ready','checkout_pending','paid') and seat.assigned_user_id = any(p_assigned_user_ids);
  if duplicate_count > 0 then raise exception 'One or more employees already have a company purchase for this course' using errcode = '23505'; end if;
  insert into public.learning_company_paid_course_purchases(workspace_id,course_id,requested_by,course_title_snapshot,provider_name_snapshot,unit_amount_minor,total_amount_minor,currency,seat_count)
  values(p_workspace_id,p_course_id,auth.uid(),course_snapshot.title,course_snapshot.provider_name,round(course_snapshot.price_amount * 100)::bigint,round(course_snapshot.price_amount * 100)::bigint * requested_count,'NGN',requested_count)
  returning id into purchase_key;
  insert into public.learning_company_paid_course_purchase_seats(purchase_id,assigned_user_id)
  select purchase_key, selected_user_id from unnest(p_assigned_user_ids) selected_user_id;
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(auth.uid(),'company_manager','company_paid_course.purchase_prepared','learning_company_paid_course_purchase',purchase_key::text,jsonb_build_object('workspace_id',p_workspace_id,'course_id',p_course_id,'seat_count',requested_count,'total_amount_minor',round(course_snapshot.price_amount * 100)::bigint * requested_count,'currency','NGN'));
  return query select purchase.id,purchase.course_title_snapshot,purchase.provider_name_snapshot,purchase.seat_count,purchase.unit_amount_minor,purchase.total_amount_minor,purchase.currency,purchase.status from public.learning_company_paid_course_purchases purchase where purchase.id = purchase_key;
end;$function$;

create or replace function public.list_own_learning_company_paid_course_purchases(p_workspace_id bigint)
returns table(purchase_id bigint,course_title text,provider_name text,seat_count integer,unit_amount_minor bigint,total_amount_minor bigint,currency text,status text,created_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or p_workspace_id is null or not exists(
    select 1 from public.learning_company_workspaces workspace
    join public.learning_company_memberships manager on manager.workspace_id = workspace.id
    where workspace.id = p_workspace_id and workspace.status = 'active' and manager.user_id = auth.uid() and manager.status = 'active' and manager.role in ('owner','admin')
  ) then raise exception 'Active company manager required' using errcode = '42501'; end if;
  return query select purchase.id,purchase.course_title_snapshot,purchase.provider_name_snapshot,purchase.seat_count,purchase.unit_amount_minor,purchase.total_amount_minor,purchase.currency,purchase.status,purchase.created_at
  from public.learning_company_paid_course_purchases purchase
  where purchase.workspace_id = p_workspace_id order by purchase.created_at desc,purchase.id desc;
end;$function$;

revoke all on function public.list_own_learning_company_paid_courses(bigint), public.prepare_learning_company_paid_course_purchase(bigint,bigint,uuid[]), public.list_own_learning_company_paid_course_purchases(bigint) from public, anon, authenticated;
grant execute on function public.list_own_learning_company_paid_courses(bigint), public.prepare_learning_company_paid_course_purchase(bigint,bigint,uuid[]), public.list_own_learning_company_paid_course_purchases(bigint) to authenticated, postgres, service_role;

commit;
