-- Phase 3B1: private company assignments for published free courses only.
-- Paid company access and billing are intentionally deferred to Phase 3C.
begin;

create table public.learning_company_course_assignments (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.learning_company_workspaces(id) on delete restrict,
  course_id bigint not null references public.learning_courses(id) on delete restrict,
  assigned_user_id uuid not null references public.profiles(id) on delete restrict,
  assigned_by uuid not null references public.profiles(id) on delete restrict,
  status text not null default 'active' check (status in ('active','cancelled')),
  assigned_at timestamptz not null default now(),
  cancelled_at timestamptz,
  constraint learning_company_course_assignments_lifecycle_check check ((status='active' and cancelled_at is null) or (status='cancelled' and cancelled_at is not null))
);
create unique index learning_company_course_assignments_one_active on public.learning_company_course_assignments(workspace_id,course_id,assigned_user_id) where status='active';
create index learning_company_course_assignments_member_idx on public.learning_company_course_assignments(assigned_user_id,status,assigned_at desc,id desc);
alter table public.learning_company_course_assignments enable row level security;
revoke all on public.learning_company_course_assignments from public,anon,authenticated;
grant select,insert,update,delete on public.learning_company_course_assignments to postgres,service_role;
grant usage,select on sequence public.learning_company_course_assignments_id_seq to postgres,service_role;

create or replace function public.assign_learning_company_course(p_workspace_id bigint,p_course_id bigint,p_assigned_user_id uuid)
returns table(assignment_id bigint, enrollment_id bigint, access_state text)
language plpgsql security definer set search_path to '' as $function$
declare assignment_key bigint; enrollment_key bigint; existing public.learning_company_course_assignments%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if p_workspace_id is null or p_course_id is null or p_assigned_user_id is null then raise exception 'Invalid company assignment' using errcode='22023'; end if;
  if not exists(select 1 from public.learning_company_workspaces workspace join public.learning_company_memberships manager on manager.workspace_id=workspace.id where workspace.id=p_workspace_id and workspace.status='active' and manager.user_id=auth.uid() and manager.status='active' and manager.role in ('owner','admin')) then raise exception 'Active company manager required' using errcode='42501'; end if;
  if not exists(select 1 from public.learning_company_memberships employee where employee.workspace_id=p_workspace_id and employee.user_id=p_assigned_user_id and employee.status='active') then raise exception 'Employee is not an active company member' using errcode='42501'; end if;
  perform 1 from public.learning_courses course_row where course_row.id=p_course_id and course_row.status='published' and course_row.is_free=true and coalesce(course_row.price_amount,0)=0 and coalesce(course_row.is_limited_time_free,false)=false for share;
  if not found then raise exception 'Only published free courses can be assigned until company billing is available' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-company-course-assignment:'||p_workspace_id::text||':'||p_course_id::text||':'||p_assigned_user_id::text,0));
  select * into existing from public.learning_company_course_assignments assignment_row where assignment_row.workspace_id=p_workspace_id and assignment_row.course_id=p_course_id and assignment_row.assigned_user_id=p_assigned_user_id and assignment_row.status='active' for update;
  if found then
    select id into enrollment_key from public.enrollments where learner_id=p_assigned_user_id and course_id=p_course_id and status in ('active','completed');
    return query select existing.id,enrollment_key,'already_assigned'::text; return;
  end if;
  insert into public.learning_company_course_assignments(workspace_id,course_id,assigned_user_id,assigned_by) values(p_workspace_id,p_course_id,p_assigned_user_id,auth.uid()) returning id into assignment_key;
  insert into public.enrollments(learner_id,course_id,status) values(p_assigned_user_id,p_course_id,'active') on conflict(learner_id,course_id) do update set status='active',completed_at=null where public.enrollments.status='cancelled' returning id into enrollment_key;
  if enrollment_key is null then select id into enrollment_key from public.enrollments where learner_id=p_assigned_user_id and course_id=p_course_id and status in ('active','completed'); end if;
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(auth.uid(),'company_manager','company_course.assigned','learning_company_course_assignment',assignment_key::text,jsonb_build_object('workspace_id',p_workspace_id,'course_id',p_course_id,'assigned_user_id',p_assigned_user_id));
  return query select assignment_key,enrollment_key,'assigned'::text;
end;$function$;

create or replace function public.list_own_learning_company_assignable_courses(p_workspace_id bigint)
returns table(course_id bigint,title text,summary text,category text,level text)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or not exists(select 1 from public.learning_company_memberships manager join public.learning_company_workspaces workspace on workspace.id=manager.workspace_id where manager.workspace_id=p_workspace_id and manager.user_id=auth.uid() and manager.status='active' and manager.role in ('owner','admin') and workspace.status='active') then raise exception 'Active company manager required' using errcode='42501'; end if;
  return query select course_row.id,course_row.title,course_row.summary,course_row.category,course_row.level from public.learning_courses course_row where course_row.status='published' and course_row.is_free=true and coalesce(course_row.price_amount,0)=0 and coalesce(course_row.is_limited_time_free,false)=false order by course_row.published_at desc nulls last,course_row.id desc;
end;$function$;

create or replace function public.list_own_learning_company_course_assignments(p_workspace_id bigint)
returns table(assignment_id bigint,assigned_user_id uuid,employee_name text,employee_email text,course_id bigint,course_slug text,course_title text,assignment_status text,assigned_at timestamptz,enrollment_status text,progress_percent integer)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null or not exists(select 1 from public.learning_company_memberships manager join public.learning_company_workspaces workspace on workspace.id=manager.workspace_id where manager.workspace_id=p_workspace_id and manager.user_id=auth.uid() and manager.status='active' and manager.role in ('owner','admin') and workspace.status='active') then raise exception 'Active company manager required' using errcode='42501'; end if;
  return query with assignment_rows as (
    select assignment_row.id as source_assignment_id,assignment_row.assigned_user_id,profile_row.full_name,profile_row.email,course_row.id as source_course_id,course_row.slug,course_row.title,assignment_row.status,assignment_row.assigned_at,enrollment_row.id as source_enrollment_id,enrollment_row.status as source_enrollment_status
    from public.learning_company_course_assignments assignment_row join public.profiles profile_row on profile_row.id=assignment_row.assigned_user_id join public.learning_courses course_row on course_row.id=assignment_row.course_id left join public.enrollments enrollment_row on enrollment_row.learner_id=assignment_row.assigned_user_id and enrollment_row.course_id=assignment_row.course_id and enrollment_row.status in ('active','completed') where assignment_row.workspace_id=p_workspace_id
  ), totals as (
    select assignment_row.source_enrollment_id,count(lesson_row.id)::integer as total_count,count(lesson_row.id) filter(where case when lesson_row.lesson_type in ('text','video') then coalesce(progress_row.completed_at is not null and progress_row.progress_percent=100,false) when lesson_row.lesson_type='quiz' then exists(select 1 from public.quiz_lessons quiz_row join public.quiz_attempts attempt_row on attempt_row.quiz_id=quiz_row.id where quiz_row.lesson_id=lesson_row.id and attempt_row.enrollment_id=assignment_row.source_enrollment_id and attempt_row.passed) else false end)::integer as completed_count from assignment_rows assignment_row join public.course_modules module_row on module_row.course_id=assignment_row.source_course_id join public.lessons lesson_row on lesson_row.course_id=assignment_row.source_course_id and lesson_row.module_id=module_row.id and lesson_row.lesson_type in ('text','video','quiz') left join public.lesson_progress progress_row on progress_row.enrollment_id=assignment_row.source_enrollment_id and progress_row.lesson_id=lesson_row.id where assignment_row.source_enrollment_id is not null group by assignment_row.source_enrollment_id
  ) select assignment_row.source_assignment_id,assignment_row.assigned_user_id,assignment_row.full_name,assignment_row.email,assignment_row.source_course_id,assignment_row.slug,assignment_row.title,assignment_row.status,assignment_row.assigned_at,assignment_row.source_enrollment_status,case when coalesce(totals.total_count,0)=0 then 0 else least(100,(coalesce(totals.completed_count,0)*100)/totals.total_count) end from assignment_rows assignment_row left join totals on totals.source_enrollment_id=assignment_row.source_enrollment_id order by assignment_row.assigned_at desc,assignment_row.source_assignment_id desc;
end;$function$;

create or replace function public.list_own_learning_company_assigned_courses()
returns table(assignment_id bigint,workspace_id bigint,workspace_name text,course_id bigint,course_slug text,course_title text,assigned_at timestamptz,enrollment_status text)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  return query select assignment_row.id,workspace.id,workspace.name,course_row.id,course_row.slug,course_row.title,assignment_row.assigned_at,enrollment_row.status from public.learning_company_course_assignments assignment_row join public.learning_company_workspaces workspace on workspace.id=assignment_row.workspace_id and workspace.status='active' join public.learning_company_memberships membership on membership.workspace_id=workspace.id and membership.user_id=auth.uid() and membership.status='active' join public.learning_courses course_row on course_row.id=assignment_row.course_id and course_row.status='published' left join public.enrollments enrollment_row on enrollment_row.learner_id=auth.uid() and enrollment_row.course_id=assignment_row.course_id and enrollment_row.status in ('active','completed') where assignment_row.assigned_user_id=auth.uid() and assignment_row.status='active' order by assignment_row.assigned_at desc,assignment_row.id desc;
end;$function$;

revoke all on function public.assign_learning_company_course(bigint,bigint,uuid),public.list_own_learning_company_assignable_courses(bigint),public.list_own_learning_company_course_assignments(bigint),public.list_own_learning_company_assigned_courses() from public,anon,authenticated;
grant execute on function public.assign_learning_company_course(bigint,bigint,uuid),public.list_own_learning_company_assignable_courses(bigint),public.list_own_learning_company_course_assignments(bigint),public.list_own_learning_company_assigned_courses() to authenticated,postgres,service_role;

commit;
