-- Phase 3C: never reverse a previously released/reserved company seller
-- liability through the held-only reversal ledger. No writer for these
-- boundaries or company seller payout is enabled by this migration.
begin;

create table public.learning_company_seller_outflow_boundaries (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.learning_company_commercial_sales(purchase_id) on delete restrict,
  seller_payee_id uuid not null references public.profiles(id) on delete restrict,
  boundary_kind text not null check (boundary_kind in ('released','reserved','transferred')),
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  movement_reference text not null unique check (char_length(movement_reference) between 8 and 160),
  recorded_at timestamptz not null default now()
);

create index learning_company_seller_outflow_boundaries_purchase_idx
  on public.learning_company_seller_outflow_boundaries(purchase_id,id);

alter table public.learning_company_seller_outflow_boundaries enable row level security;
revoke all on public.learning_company_seller_outflow_boundaries
  from public,anon,authenticated,service_role;
grant select on public.learning_company_seller_outflow_boundaries to service_role;

create trigger prevent_learning_company_seller_outflow_boundary_mutation
before update or delete on public.learning_company_seller_outflow_boundaries
for each row execute function public.prevent_learning_company_sale_mutation();

create or replace function public.guard_learning_company_seller_outflow_boundary()
returns trigger language plpgsql security definer set search_path to '' as $function$
declare sale_row public.learning_company_commercial_sales%rowtype;
begin
  -- Both this marker and the reversal poster use the purchase row lock. A
  -- future money movement must insert its marker in the same transaction.
  perform 1 from public.learning_company_paid_course_purchases purchase
  where purchase.id = new.purchase_id for update;
  if not found then raise exception 'Company purchase not found' using errcode = 'P0002'; end if;
  select * into sale_row from public.learning_company_commercial_sales sale
  where sale.purchase_id = new.purchase_id;
  if not found or sale_row.seller_payee_id <> new.seller_payee_id
      or sale_row.currency <> new.currency then
    raise exception 'Company seller outflow identity mismatch' using errcode = '22023';
  end if;
  return new;
end;$function$;

create trigger guard_learning_company_seller_outflow_boundary
before insert on public.learning_company_seller_outflow_boundaries
for each row execute function public.guard_learning_company_seller_outflow_boundary();

create or replace function public.guard_learning_company_held_only_reversal()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  perform 1 from public.learning_company_paid_course_purchases purchase
  where purchase.id = new.purchase_id for update;
  if exists (
    select 1 from public.learning_company_seller_outflow_boundaries boundary
    where boundary.purchase_id = new.purchase_id
  ) then
    raise exception 'Company seller outflow requires manual post-release reversal accounting'
      using errcode = '22023';
  end if;
  return new;
end;$function$;

create trigger guard_learning_company_held_only_reversal
before insert on public.learning_company_commercial_reversals
for each row execute function public.guard_learning_company_held_only_reversal();

create or replace function public.assess_learning_company_seller_release_gate(
  p_purchase_id bigint)
returns table(
  purchase_id bigint,seller_payee_id uuid,paystack_domain text,
  remaining_held_minor bigint,currency text,latest_review_id bigint,
  release_gate_state text
)
language sql stable security definer set search_path to '' as $function$
  select queue.purchase_id,queue.seller_payee_id,sale.paystack_domain,
    queue.remaining_held_minor,queue.currency,latest.id,
    case
      when exists (select 1 from public.learning_company_seller_outflow_boundaries boundary
        where boundary.purchase_id = queue.purchase_id)
        then 'seller_outflow_manual_review_required'
      when queue.review_state <> 'manual_admin_review_required'
        then queue.review_state
      when latest.id is null then 'admin_approval_missing'
      when latest.decision = 'continue_hold' then 'admin_hold_recorded'
      when latest.review_state_snapshot <> queue.review_state
        or latest.remaining_held_minor_snapshot <> queue.remaining_held_minor
        then 'admin_approval_stale'
      when not exists (
        select 1 from public.account_capabilities capability
        where capability.user_id = latest.actor_user_id
          and capability.capability = 'admin' and capability.status = 'active'
      ) then 'approval_actor_inactive'
      when sale.paystack_domain <> 'live' then 'test_mode_nonpayable'
      else 'provider_settlement_verification_required'
    end as release_gate_state
  from public.list_learning_company_seller_payout_review_queue() queue
  join public.learning_company_commercial_sales sale
    on sale.purchase_id = queue.purchase_id
  left join lateral (
    select review.id,review.actor_user_id,review.decision,
      review.review_state_snapshot,review.remaining_held_minor_snapshot
    from public.learning_company_seller_payout_reviews review
    where review.purchase_id = queue.purchase_id
    order by review.reviewed_at desc,review.id desc
    limit 1
  ) latest on true
  where queue.purchase_id = p_purchase_id;
$function$;

revoke all on function public.guard_learning_company_seller_outflow_boundary(),
  public.guard_learning_company_held_only_reversal() from public,anon,authenticated,service_role;

commit;
