-- Phase 2A2: consent-based membership invitations for approved instructors.
-- No course, order, allocation, earning, payout, or provider state is changed.
begin;

create table public.learning_provider_organization_invitations (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.learning_provider_organizations(id) on delete restrict,
  invited_user_id uuid not null references public.profiles(id) on delete restrict,
  invited_email text not null check (invited_email=lower(btrim(invited_email)) and char_length(invited_email) between 3 and 320),
  role text not null check (role in ('admin','instructor')),
  status text not null default 'pending' check (status in ('pending','accepted','cancelled','expired')),
  invited_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  expires_at timestamptz not null default (now()+interval '30 days'),
  constraint learning_provider_organization_invitations_lifecycle_check check ((status='pending' and responded_at is null) or (status in ('accepted','cancelled','expired') and responded_at is not null)),
  constraint learning_provider_organization_invitations_expiry_check check (expires_at > created_at)
);
create unique index learning_provider_organization_invitations_one_pending on public.learning_provider_organization_invitations(organization_id,invited_user_id) where status='pending';
create index learning_provider_organization_invitations_invitee_idx on public.learning_provider_organization_invitations(invited_user_id,status,created_at desc,id desc);

create table public.learning_provider_organization_invitation_events (
  id bigint generated by default as identity primary key,
  invitation_id bigint not null references public.learning_provider_organization_invitations(id) on delete restrict,
  organization_id bigint not null references public.learning_provider_organizations(id) on delete restrict,
  event_type text not null check (event_type in ('invitation.created','invitation.accepted','invitation.cancelled','invitation.expired')),
  actor_user_id uuid references public.profiles(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  occurred_at timestamptz not null default now()
);
create index learning_provider_organization_invitation_events_invitation_idx on public.learning_provider_organization_invitation_events(invitation_id,occurred_at,id);

alter table public.learning_provider_organization_invitations enable row level security;
alter table public.learning_provider_organization_invitation_events enable row level security;
revoke all on public.learning_provider_organization_invitations,public.learning_provider_organization_invitation_events from public,anon,authenticated;
grant select,insert,update,delete on public.learning_provider_organization_invitations,public.learning_provider_organization_invitation_events to postgres,service_role;

create or replace function public.prevent_learning_provider_organization_invitation_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if tg_op='DELETE' then raise exception 'Training organization invitation history cannot be deleted' using errcode='42501'; end if;
  if old.id is distinct from new.id or old.organization_id is distinct from new.organization_id or old.invited_user_id is distinct from new.invited_user_id or old.invited_email is distinct from new.invited_email or old.role is distinct from new.role or old.invited_by is distinct from new.invited_by or old.created_at is distinct from new.created_at or old.expires_at is distinct from new.expires_at then raise exception 'Training organization invitation identity is immutable' using errcode='42501'; end if;
  if old.status='pending' and new.status in ('accepted','cancelled','expired') and new.responded_at is not null then return new; end if;
  raise exception 'Unsupported training organization invitation transition' using errcode='22023';
end;$function$;
create trigger prevent_learning_provider_organization_invitation_mutation before update or delete on public.learning_provider_organization_invitations for each row execute function public.prevent_learning_provider_organization_invitation_mutation();

create or replace function public.prevent_learning_provider_organization_invitation_event_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin raise exception 'Training organization invitation events are append-only' using errcode='42501'; end;$function$;
create trigger prevent_learning_provider_organization_invitation_event_mutation before update or delete on public.learning_provider_organization_invitation_events for each row execute function public.prevent_learning_provider_organization_invitation_event_mutation();

create or replace function public.create_learning_provider_organization_invitation(p_organization_id bigint,p_invited_email text,p_role text)
returns table(invitation_id bigint,organization_id bigint,invited_email text,role text,status text,expires_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare invitation_key bigint; invitee public.profiles%rowtype; normalized_email text:=lower(btrim(p_invited_email)); existing public.learning_provider_organization_invitations%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if p_organization_id is null or normalized_email is null or char_length(normalized_email) not between 3 and 320 or p_role not in ('admin','instructor') then raise exception 'Invalid organization invitation' using errcode='22023'; end if;
  if not exists(select 1 from public.learning_provider_organizations organization where organization.id=p_organization_id and organization.status='active') or not exists(select 1 from public.learning_provider_organization_memberships membership where membership.organization_id=p_organization_id and membership.user_id=auth.uid() and membership.role='owner' and membership.status='active') then raise exception 'Active organization owner required' using errcode='42501'; end if;
  select * into invitee from public.profiles where email=normalized_email;
  if not found then raise exception 'Invitee must already have a Growvelt Learning account' using errcode='P0002'; end if;
  perform public.assert_learning_approved_instructor(invitee.id);
  if exists(select 1 from public.learning_provider_organization_memberships membership where membership.organization_id=p_organization_id and membership.user_id=invitee.id and membership.status='active') then raise exception 'Instructor is already an active organization member' using errcode='23505'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-provider-organization-invitation:'||p_organization_id::text||':'||invitee.id::text,0));
  select * into existing from public.learning_provider_organization_invitations invitation where invitation.organization_id=p_organization_id and invitation.invited_user_id=invitee.id and invitation.status='pending' for update;
  if found then return query select existing.id,existing.organization_id,existing.invited_email,existing.role,existing.status,existing.expires_at; return; end if;
  insert into public.learning_provider_organization_invitations(organization_id,invited_user_id,invited_email,role,invited_by) values(p_organization_id,invitee.id,normalized_email,p_role,auth.uid()) returning id into invitation_key;
  insert into public.learning_provider_organization_invitation_events(invitation_id,organization_id,event_type,actor_user_id,metadata) values(invitation_key,p_organization_id,'invitation.created',auth.uid(),jsonb_build_object('role',p_role));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(auth.uid(),'organization_owner','provider_organization.invitation_created','learning_provider_organization_invitation',invitation_key::text,jsonb_build_object('organization_id',p_organization_id,'role',p_role));
  return query select invitation.id,invitation.organization_id,invitation.invited_email,invitation.role,invitation.status,invitation.expires_at from public.learning_provider_organization_invitations invitation where invitation.id=invitation_key;
end;$function$;

create or replace function public.list_own_learning_provider_organization_invitations()
returns table(invitation_id bigint,organization_id bigint,organization_name text,role text,expires_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  return query select invitation.id,organization.id,organization.name,invitation.role,invitation.expires_at from public.learning_provider_organization_invitations invitation join public.learning_provider_organizations organization on organization.id=invitation.organization_id where invitation.invited_user_id=auth.uid() and invitation.status='pending' and invitation.expires_at>now() and organization.status='active' order by invitation.created_at desc,invitation.id desc;
end;$function$;

create or replace function public.accept_own_learning_provider_organization_invitation(p_invitation_id bigint)
returns table(organization_id bigint,membership_id bigint,role text,status text)
language plpgsql security definer set search_path to '' as $function$
declare invitation public.learning_provider_organization_invitations%rowtype; membership_key bigint;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  perform public.assert_learning_approved_instructor(auth.uid());
  select * into invitation from public.learning_provider_organization_invitations where id=p_invitation_id and invited_user_id=auth.uid() for update;
  if not found then raise exception 'Organization invitation not found' using errcode='P0002'; end if;
  if invitation.status='accepted' then select membership.id into membership_key from public.learning_provider_organization_memberships membership where membership.organization_id=invitation.organization_id and membership.user_id=auth.uid() and membership.status='active'; return query select invitation.organization_id,membership_key,invitation.role,'active'::text; return; end if;
  if invitation.status<>'pending' or invitation.expires_at<=now() or not exists(select 1 from public.learning_provider_organizations organization where organization.id=invitation.organization_id and organization.status='active') then raise exception 'Organization invitation is not active' using errcode='22023'; end if;
  if exists(select 1 from public.learning_provider_organization_memberships membership where membership.organization_id=invitation.organization_id and membership.user_id=auth.uid() and membership.status='active') then raise exception 'Active organization membership already exists' using errcode='23505'; end if;
  insert into public.learning_provider_organization_memberships(organization_id,user_id,role,granted_by) values(invitation.organization_id,auth.uid(),invitation.role,invitation.invited_by) returning id into membership_key;
  update public.learning_provider_organization_invitations set status='accepted',responded_at=now() where id=invitation.id;
  insert into public.learning_provider_organization_membership_events(membership_id,organization_id,user_id,event_type,actor_user_id,metadata) values(membership_key,invitation.organization_id,auth.uid(),'membership.created',auth.uid(),jsonb_build_object('role',invitation.role,'source','invitation.accepted','invitation_id',invitation.id));
  insert into public.learning_provider_organization_invitation_events(invitation_id,organization_id,event_type,actor_user_id,metadata) values(invitation.id,invitation.organization_id,'invitation.accepted',auth.uid(),jsonb_build_object('role',invitation.role,'membership_id',membership_key));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(auth.uid(),'instructor','provider_organization.invitation_accepted','learning_provider_organization_invitation',invitation.id::text,jsonb_build_object('organization_id',invitation.organization_id,'membership_id',membership_key));
  return query select invitation.organization_id,membership_key,invitation.role,'active'::text;
end;$function$;

revoke all on function public.prevent_learning_provider_organization_invitation_mutation(),public.prevent_learning_provider_organization_invitation_event_mutation(),public.create_learning_provider_organization_invitation(bigint,text,text),public.list_own_learning_provider_organization_invitations(),public.accept_own_learning_provider_organization_invitation(bigint) from public,anon,authenticated;
grant execute on function public.create_learning_provider_organization_invitation(bigint,text,text),public.list_own_learning_provider_organization_invitations(),public.accept_own_learning_provider_organization_invitation(bigint) to authenticated,postgres,service_role;
grant execute on function public.prevent_learning_provider_organization_invitation_mutation(),public.prevent_learning_provider_organization_invitation_event_mutation() to postgres,service_role;

commit;
