-- Phase 3C: preserve signed company refund/dispute notices for manual review.
-- This is an inbox, NOT a refund finalizer. It never changes seats, access,
-- balances, earnings or payouts. Provider verification and reversal handling
-- require a later reviewed migration and application workflow.
-- Forward-fix rollback: revoke execute on the receive function and stop
-- sending new events; retain the immutable event/audit history.
begin;

create table public.learning_company_reversal_event_inbox (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.learning_company_paid_course_purchases(id) on delete restrict,
  attempt_id bigint not null references public.learning_company_paid_course_purchase_attempts(id) on delete restrict,
  paystack_domain text not null check (paystack_domain in ('test','live')),
  provider_event_key text not null check (char_length(provider_event_key) between 3 and 200),
  payload_digest text not null check (payload_digest ~ '^[a-f0-9]{64}$'),
  event_type text not null check (event_type in (
    'refund.pending','refund.processing','refund.needs-attention','refund.failed','refund.processed',
    'charge.dispute.create','charge.dispute.remind','charge.dispute.resolve')),
  provider_reference text not null check (provider_reference ~ '^CP-[A-F0-9]{32}$'),
  provider_case_id text not null check (char_length(provider_case_id) between 1 and 120),
  provider_status text not null check (char_length(provider_status) between 1 and 80),
  reported_amount_minor bigint not null check (reported_amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  received_at timestamptz not null default now(),
  unique(paystack_domain,provider_event_key)
);

create index learning_company_reversal_inbox_purchase_idx
  on public.learning_company_reversal_event_inbox(purchase_id,received_at desc,id desc);

alter table public.learning_company_reversal_event_inbox enable row level security;
revoke all on public.learning_company_reversal_event_inbox from public,anon,authenticated,service_role;
grant select on public.learning_company_reversal_event_inbox to service_role;

create trigger prevent_learning_company_reversal_inbox_mutation
before update or delete on public.learning_company_reversal_event_inbox
for each row execute function public.prevent_learning_company_sale_mutation();

create or replace function public.receive_learning_company_reversal_notice(
  p_provider_event_key text,p_payload_digest text,p_event_type text,
  p_provider_reference text,p_provider_case_id text,p_provider_status text,
  p_reported_amount_minor bigint,p_currency text,p_domain text)
returns table(event_id bigint,outcome text)
language plpgsql security definer set search_path to '' as $function$
declare attempt_row public.learning_company_paid_course_purchase_attempts%rowtype;
  purchase_row public.learning_company_paid_course_purchases%rowtype;
  existing public.learning_company_reversal_event_inbox%rowtype;
begin
  if nullif(btrim(coalesce(p_provider_event_key,'')),'') is null
     or char_length(p_provider_event_key) > 200
     or p_payload_digest is null or p_payload_digest !~ '^[a-f0-9]{64}$'
     or p_event_type not in (
       'refund.pending','refund.processing','refund.needs-attention','refund.failed','refund.processed',
       'charge.dispute.create','charge.dispute.remind','charge.dispute.resolve')
     or p_provider_reference is null or p_provider_reference !~ '^CP-[A-F0-9]{32}$'
     or nullif(btrim(coalesce(p_provider_case_id,'')),'') is null or char_length(p_provider_case_id) > 120
     or nullif(btrim(coalesce(p_provider_status,'')),'') is null or char_length(p_provider_status) > 80
     or p_reported_amount_minor is null or p_reported_amount_minor <= 0
     or p_currency <> 'NGN' or p_domain not in ('test','live') then
    raise exception 'Invalid company reversal notice' using errcode = '22023';
  end if;
  select * into attempt_row from public.learning_company_paid_course_purchase_attempts attempt
  where attempt.provider = 'paystack' and attempt.provider_reference = p_provider_reference
    and attempt.paystack_domain = p_domain and attempt.status = 'succeeded' for share;
  if not found then raise exception 'Verified company charge attempt was not found' using errcode = '22023'; end if;
  select * into purchase_row from public.learning_company_paid_course_purchases purchase
  where purchase.id = attempt_row.purchase_id and purchase.status = 'paid' for share;
  if not found or purchase_row.currency <> p_currency then
    raise exception 'Paid company purchase does not match the notice' using errcode = '22023';
  end if;

  insert into public.learning_company_reversal_event_inbox(
    purchase_id,attempt_id,paystack_domain,provider_event_key,payload_digest,event_type,
    provider_reference,provider_case_id,provider_status,reported_amount_minor,currency)
  values(purchase_row.id,attempt_row.id,p_domain,p_provider_event_key,p_payload_digest,p_event_type,
    p_provider_reference,p_provider_case_id,p_provider_status,p_reported_amount_minor,p_currency)
  on conflict(paystack_domain,provider_event_key) do nothing
  returning * into existing;
  if found then
    insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
    values(null,'payment_system','company_paid_course.reversal_notice_received',
      'learning_company_paid_course_purchase',purchase_row.id::text,
      jsonb_build_object('inbox_event_id',existing.id,'event_type',p_event_type,'paystack_domain',p_domain));
    return query select existing.id,'pending_manual_review'::text;
    return;
  end if;
  select * into existing from public.learning_company_reversal_event_inbox inbox
  where inbox.paystack_domain = p_domain and inbox.provider_event_key = p_provider_event_key;
  if not found or existing.purchase_id <> purchase_row.id or existing.attempt_id <> attempt_row.id
     or existing.payload_digest <> p_payload_digest or existing.event_type <> p_event_type
     or existing.provider_reference <> p_provider_reference
     or existing.provider_case_id <> p_provider_case_id
     or existing.provider_status <> p_provider_status
     or existing.reported_amount_minor <> p_reported_amount_minor or existing.currency <> p_currency then
    raise exception 'Company reversal event key conflicts with an earlier notice' using errcode = '23505';
  end if;
  return query select existing.id,'already_received'::text;
end;$function$;

revoke all on function public.receive_learning_company_reversal_notice(
  text,text,text,text,text,text,bigint,text,text) from public,anon,authenticated;
grant execute on function public.receive_learning_company_reversal_notice(
  text,text,text,text,text,text,bigint,text,text) to postgres,service_role;

commit;
