-- Phase 3C: accounting foundation for held -> available -> reserved company
-- seller proceeds. No service writer, payout, transfer, or live activation.
begin;

create table public.learning_company_seller_liability_movements (
  id bigint generated by default as identity primary key,
  boundary_id bigint not null unique references public.learning_company_seller_outflow_boundaries(id) on delete restrict,
  purchase_id bigint not null references public.learning_company_commercial_sales(purchase_id) on delete restrict,
  seller_payee_id uuid not null references public.profiles(id) on delete restrict,
  movement_kind text not null check (movement_kind in ('released','reserved')),
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  recorded_at timestamptz not null default now()
);

create table public.learning_company_seller_liability_movement_entries (
  movement_id bigint not null references public.learning_company_seller_liability_movements(id) on delete restrict,
  line_number smallint not null check (line_number in (1,2)),
  account_code text not null check (account_code in (
    'liability.company_seller_earnings_held',
    'liability.company_seller_earnings_available',
    'liability.company_seller_earnings_reserved')),
  amount_minor bigint not null check (amount_minor <> 0),
  currency text not null check (currency = 'NGN'),
  primary key(movement_id,line_number)
);

create index learning_company_seller_liability_movements_purchase_idx
  on public.learning_company_seller_liability_movements(purchase_id,id);

alter table public.learning_company_seller_liability_movements enable row level security;
alter table public.learning_company_seller_liability_movement_entries enable row level security;
revoke all on public.learning_company_seller_liability_movements,
  public.learning_company_seller_liability_movement_entries
  from public,anon,authenticated,service_role;
grant select on public.learning_company_seller_liability_movements,
  public.learning_company_seller_liability_movement_entries to service_role;

create trigger prevent_learning_company_seller_liability_movement_mutation
before update or delete on public.learning_company_seller_liability_movements
for each row execute function public.prevent_learning_company_sale_mutation();
create trigger prevent_learning_company_seller_liability_entry_mutation
before update or delete on public.learning_company_seller_liability_movement_entries
for each row execute function public.prevent_learning_company_sale_mutation();

create or replace function public.validate_learning_company_seller_liability_movement()
returns trigger language plpgsql security definer set search_path to '' as $function$
declare boundary_row public.learning_company_seller_outflow_boundaries%rowtype;
  sale_row public.learning_company_commercial_sales%rowtype;
  released_total bigint; reserved_total bigint; reversed_total bigint;
begin
  -- Serialize with refund posting and the outflow boundary trigger.
  perform 1 from public.learning_company_paid_course_purchases purchase
  where purchase.id = new.purchase_id for update;
  select * into boundary_row from public.learning_company_seller_outflow_boundaries boundary
  where boundary.id = new.boundary_id;
  select * into sale_row from public.learning_company_commercial_sales sale
  where sale.purchase_id = new.purchase_id;
  if not found or boundary_row.id is null
      or boundary_row.purchase_id <> new.purchase_id
      or boundary_row.seller_payee_id <> new.seller_payee_id
      or boundary_row.boundary_kind <> new.movement_kind
      or boundary_row.amount_minor <> new.amount_minor
      or boundary_row.currency <> new.currency
      or sale_row.seller_payee_id <> new.seller_payee_id
      or sale_row.currency <> new.currency then
    raise exception 'Company seller liability movement identity mismatch' using errcode = '22023';
  end if;
  select coalesce(sum(movement.amount_minor),0) into released_total
  from public.learning_company_seller_liability_movements movement
  where movement.purchase_id = new.purchase_id and movement.movement_kind = 'released';
  select coalesce(sum(movement.amount_minor),0) into reserved_total
  from public.learning_company_seller_liability_movements movement
  where movement.purchase_id = new.purchase_id and movement.movement_kind = 'reserved';
  select coalesce(sum(reversal.seller_gross_minor),0) into reversed_total
  from public.learning_company_commercial_reversals reversal
  where reversal.purchase_id = new.purchase_id;
  if new.movement_kind = 'released' then
    released_total := released_total + new.amount_minor;
  else
    reserved_total := reserved_total + new.amount_minor;
  end if;
  if released_total > sale_row.seller_gross_minor - reversed_total
      or reserved_total > released_total then
    raise exception 'Company seller liability movement exceeds its source balance'
      using errcode = '23514';
  end if;
  return new;
end;$function$;

create trigger validate_learning_company_seller_liability_movement
before insert on public.learning_company_seller_liability_movements
for each row execute function public.validate_learning_company_seller_liability_movement();

create or replace function public.post_learning_company_seller_liability_movement_entries()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if new.movement_kind = 'released' then
    insert into public.learning_company_seller_liability_movement_entries
      (movement_id,line_number,account_code,amount_minor,currency)
    values(new.id,1,'liability.company_seller_earnings_held',new.amount_minor,new.currency),
      (new.id,2,'liability.company_seller_earnings_available',-new.amount_minor,new.currency);
  else
    insert into public.learning_company_seller_liability_movement_entries
      (movement_id,line_number,account_code,amount_minor,currency)
    values(new.id,1,'liability.company_seller_earnings_available',new.amount_minor,new.currency),
      (new.id,2,'liability.company_seller_earnings_reserved',-new.amount_minor,new.currency);
  end if;
  return new;
end;$function$;

create trigger post_learning_company_seller_liability_movement_entries
after insert on public.learning_company_seller_liability_movements
for each row execute function public.post_learning_company_seller_liability_movement_entries();

create or replace function public.list_learning_company_seller_held_liabilities()
returns table(
  purchase_id bigint,seller_payee_id uuid,seller_organization_id bigint,
  original_held_minor bigint,reversed_minor bigint,remaining_held_minor bigint,currency text)
language sql stable security definer set search_path to '' as $function$
  select sale.purchase_id,sale.seller_payee_id,sale.seller_organization_id,
    sale.seller_gross_minor,
    coalesce((select sum(reversal.seller_gross_minor)
      from public.learning_company_commercial_reversals reversal
      where reversal.purchase_id = sale.purchase_id),0)::bigint,
    (sale.seller_gross_minor
      - coalesce((select sum(reversal.seller_gross_minor)
        from public.learning_company_commercial_reversals reversal
        where reversal.purchase_id = sale.purchase_id),0)
      - coalesce((select sum(movement.amount_minor)
        from public.learning_company_seller_liability_movements movement
        where movement.purchase_id = sale.purchase_id
          and movement.movement_kind = 'released'),0))::bigint,
    sale.currency
  from public.learning_company_commercial_sales sale;
$function$;

create or replace function public.reconcile_learning_company_seller_liability_movements()
returns table(purchase_id bigint,issue_type text)
language sql stable security definer set search_path to '' as $function$
  select movement.purchase_id,'company_seller_liability_movement_ledger_mismatch'::text
  from public.learning_company_seller_liability_movements movement
  left join public.learning_company_seller_liability_movement_entries debit
    on debit.movement_id = movement.id and debit.line_number = 1
  left join public.learning_company_seller_liability_movement_entries credit
    on credit.movement_id = movement.id and credit.line_number = 2
  where debit.amount_minor is distinct from movement.amount_minor
    or credit.amount_minor is distinct from -movement.amount_minor
    or debit.currency is distinct from movement.currency
    or credit.currency is distinct from movement.currency
    or debit.account_code is distinct from case movement.movement_kind
      when 'released' then 'liability.company_seller_earnings_held'
      else 'liability.company_seller_earnings_available' end
    or credit.account_code is distinct from case movement.movement_kind
      when 'released' then 'liability.company_seller_earnings_available'
      else 'liability.company_seller_earnings_reserved' end
  union all
  select boundary.purchase_id,'company_seller_outflow_boundary_without_ledger'::text
  from public.learning_company_seller_outflow_boundaries boundary
  where boundary.boundary_kind in ('released','reserved')
    and not exists(select 1 from public.learning_company_seller_liability_movements movement
      where movement.boundary_id = boundary.id)
  union all
  select hold.purchase_id,'company_seller_liability_negative_held'::text
  from public.list_learning_company_seller_held_liabilities() hold
  where hold.remaining_held_minor < 0
  union all
  select sale.purchase_id,'company_seller_liability_over_reserved'::text
  from public.learning_company_commercial_sales sale
  where coalesce((select sum(movement.amount_minor)
      from public.learning_company_seller_liability_movements movement
      where movement.purchase_id = sale.purchase_id and movement.movement_kind = 'reserved'),0)
    > coalesce((select sum(movement.amount_minor)
      from public.learning_company_seller_liability_movements movement
      where movement.purchase_id = sale.purchase_id and movement.movement_kind = 'released'),0);
$function$;

create or replace function public.list_learning_company_seller_payout_review_queue()
returns table(
  purchase_id bigint,seller_payee_id uuid,seller_organization_id bigint,
  remaining_held_minor bigint,currency text,hold_until timestamptz,
  reversal_notice_count bigint,accounting_issue_count bigint,review_state text)
language sql stable security definer set search_path to '' as $function$
  with accounting_issues as (
    select issue.purchase_id from public.reconcile_learning_company_commercial_sales() issue
    union all
    select reversal.purchase_id
    from public.reconcile_learning_company_commercial_reversals() issue
    join public.learning_company_commercial_reversals reversal on reversal.id = issue.reversal_id
    union all
    select issue.purchase_id from public.reconcile_learning_company_seller_held_liabilities() issue
    union all
    select issue.purchase_id from public.reconcile_learning_company_seller_liability_movements() issue
    union all
    select issue.purchase_id from public.reconcile_learning_company_paid_seat_access() issue
    union all
    select reversal.purchase_id
    from public.reconcile_learning_company_reversal_access() issue
    join public.learning_company_commercial_reversals reversal on reversal.id = issue.reversal_id
  )
  select hold.purchase_id,hold.seller_payee_id,hold.seller_organization_id,
    hold.remaining_held_minor,hold.currency,
    purchase.paid_at + make_interval(days => terms.earnings_hold_days) as hold_until,
    (select count(*) from public.learning_company_reversal_event_inbox notice
      where notice.purchase_id = hold.purchase_id) as reversal_notice_count,
    (select count(*) from accounting_issues issue
      where issue.purchase_id = hold.purchase_id) as accounting_issue_count,
    case
      when hold.remaining_held_minor <= 0 then 'no_remaining_balance'
      when purchase.paid_at is null then 'payment_timestamp_missing'
      when exists (select 1 from accounting_issues issue
        where issue.purchase_id = hold.purchase_id) then 'accounting_review_required'
      when now() < purchase.paid_at + make_interval(days => terms.earnings_hold_days)
        then 'hold_active'
      when exists (select 1 from public.learning_company_reversal_event_inbox notice
        where notice.purchase_id = hold.purchase_id)
        then 'reversal_notice_review_required'
      else 'manual_admin_review_required'
    end as review_state
  from public.list_learning_company_seller_held_liabilities() hold
  join public.learning_company_commercial_sales sale on sale.purchase_id = hold.purchase_id
  join public.learning_company_paid_course_purchases purchase on purchase.id = hold.purchase_id
  join public.learning_commercial_terms terms on terms.version = sale.commercial_terms_version
  order by purchase.paid_at,hold.purchase_id;
$function$;

revoke all on function public.validate_learning_company_seller_liability_movement(),
  public.post_learning_company_seller_liability_movement_entries(),
  public.reconcile_learning_company_seller_liability_movements()
  from public,anon,authenticated,service_role;
grant execute on function public.reconcile_learning_company_seller_liability_movements()
  to postgres,service_role;

commit;
