-- Phase 1E3: durable, Test-only instructor payout approval and transfer intake.
-- It intentionally does not settle an earning as paid or create a payout ledger entry.
begin;

create table public.learning_instructor_payout_items (
  id bigint generated by default as identity primary key,
  payout_item_reference text not null unique check (payout_item_reference ~ '^lpi-[a-z0-9_-]{12,50}$'),
  idempotency_key text not null unique check (idempotency_key ~ '^[a-z][a-z0-9:_-]{2,120}$'),
  reservation_id bigint not null unique references public.learning_instructor_earning_reservations(id) on delete restrict,
  earning_id bigint not null unique references public.learning_instructor_earnings(id) on delete restrict,
  allocation_id bigint not null references public.learning_commercial_allocations(id) on delete restrict,
  instructor_id uuid not null references public.profiles(id) on delete restrict,
  payout_profile_id bigint not null references public.learning_instructor_payout_profiles(id) on delete restrict,
  provider text not null default 'paystack' check (provider='paystack'),
  provider_domain text not null default 'test' check (provider_domain='test'),
  recipient_code text not null check (recipient_code ~ '^RCP_[A-Za-z0-9]+$'),
  provider_recipient_id text not null check (provider_recipient_id ~ '^[0-9]+$'),
  amount_minor bigint not null check (amount_minor>0),
  currency text not null check (currency='NGN'),
  status text not null default 'approved' check (status in ('approved','submitting','pending','recovery_required','succeeded','failed','reversed','cancelled','financially_blocked')),
  provider_transfer_id text unique check (provider_transfer_id is null or provider_transfer_id ~ '^[0-9]+$'),
  provider_transfer_code text unique check (provider_transfer_code is null or provider_transfer_code ~ '^TRF_[A-Za-z0-9]+$'),
  provider_status text,
  approved_by uuid not null references public.profiles(id) on delete restrict,
  approved_at timestamptz not null default now(),
  initiated_by uuid references public.profiles(id) on delete restrict,
  initiated_at timestamptz,
  provider_received_at timestamptz,
  failure_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint learning_instructor_payout_items_initiation_check check ((initiated_by is null and initiated_at is null) or (initiated_by is not null and initiated_at is not null))
);
create index learning_instructor_payout_items_instructor_idx on public.learning_instructor_payout_items(instructor_id,created_at desc,id desc);
create index learning_instructor_payout_items_status_idx on public.learning_instructor_payout_items(status,created_at,id);

create table public.learning_instructor_payout_item_events (
  id bigint generated by default as identity primary key,
  payout_item_id bigint not null references public.learning_instructor_payout_items(id) on delete restrict,
  event_type text not null check (event_type ~ '^[a-z][a-z0-9_.]{2,80}$'),
  from_status text,
  to_status text,
  provenance text not null check (provenance in ('admin','webhook','provider_api','system')),
  provider_event_id text unique,
  payload_digest text check (payload_digest is null or payload_digest ~ '^[a-f0-9]{64}$'),
  actor_user_id uuid references public.profiles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  occurred_at timestamptz not null default now()
);
create index learning_instructor_payout_item_events_item_idx on public.learning_instructor_payout_item_events(payout_item_id,occurred_at,id);

alter table public.learning_instructor_payout_items enable row level security;
alter table public.learning_instructor_payout_item_events enable row level security;
revoke all on public.learning_instructor_payout_items,public.learning_instructor_payout_item_events from public,anon,authenticated;
grant select,insert,update,delete on public.learning_instructor_payout_items,public.learning_instructor_payout_item_events to postgres,service_role;

create or replace function public.prevent_learning_instructor_payout_item_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if tg_op='DELETE' then raise exception 'Payout item history is retained' using errcode='42501'; end if;
  if old.payout_item_reference is distinct from new.payout_item_reference or old.idempotency_key is distinct from new.idempotency_key
    or old.reservation_id is distinct from new.reservation_id or old.earning_id is distinct from new.earning_id
    or old.allocation_id is distinct from new.allocation_id or old.instructor_id is distinct from new.instructor_id
    or old.payout_profile_id is distinct from new.payout_profile_id or old.provider is distinct from new.provider
    or old.provider_domain is distinct from new.provider_domain or old.recipient_code is distinct from new.recipient_code
    or old.provider_recipient_id is distinct from new.provider_recipient_id or old.amount_minor is distinct from new.amount_minor
    or old.currency is distinct from new.currency or old.approved_by is distinct from new.approved_by or old.approved_at is distinct from new.approved_at
    or old.created_at is distinct from new.created_at then raise exception 'Payout item financial identity is immutable' using errcode='42501'; end if;
  if old.status='approved' and new.status in ('submitting','cancelled')
    or old.status='submitting' and new.status in ('pending','recovery_required','succeeded','failed','reversed','cancelled','financially_blocked')
    or old.status='pending' and new.status in ('succeeded','failed','reversed','financially_blocked')
    or old.status='recovery_required' and new.status in ('pending','succeeded','failed','reversed','financially_blocked')
    or old.status='financially_blocked' and new.status='financially_blocked'
    or old.status='succeeded' and new.status='reversed' then new.updated_at:=now(); return new; end if;
  raise exception 'Unsupported payout item transition' using errcode='22023';
end;$function$;
create trigger prevent_learning_instructor_payout_item_mutation before update or delete on public.learning_instructor_payout_items for each row execute function public.prevent_learning_instructor_payout_item_mutation();

create or replace function public.prevent_learning_instructor_payout_item_event_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin raise exception 'Payout item events are append-only' using errcode='42501'; end;$function$;
create trigger prevent_learning_instructor_payout_item_event_mutation before update or delete on public.learning_instructor_payout_item_events for each row execute function public.prevent_learning_instructor_payout_item_event_mutation();

create or replace function public.approve_learning_instructor_payout_item(p_reservation_id bigint,p_idempotency_key text,p_actor_user_id uuid)
returns table(payout_item_id bigint,payout_item_reference text,status text,amount_minor bigint,currency text)
language plpgsql security definer set search_path to '' as $function$
declare r public.learning_instructor_earning_reservations%rowtype; e public.learning_instructor_earnings%rowtype; a public.learning_commercial_allocations%rowtype; o public.learning_orders%rowtype; p public.learning_instructor_payout_profiles%rowtype; existing public.learning_instructor_payout_items%rowtype; item_id bigint;
begin
  if p_reservation_id is null or p_actor_user_id is null or p_idempotency_key !~ '^[a-z][a-z0-9:_-]{2,120}$' then raise exception 'Valid payout approval identity is required' using errcode='22023'; end if;
  if not exists(select 1 from public.account_capabilities c where c.user_id=p_actor_user_id and c.capability='admin' and c.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
  select * into existing from public.learning_instructor_payout_items where idempotency_key=p_idempotency_key for update;
  if found then if existing.reservation_id<>p_reservation_id then raise exception 'Payout approval idempotency conflict' using errcode='23505'; end if; return query select existing.id,existing.payout_item_reference,existing.status,existing.amount_minor,existing.currency; return; end if;
  select * into r from public.learning_instructor_earning_reservations where id=p_reservation_id for update;
  if not found or r.status<>'reserved' then raise exception 'Reserved earning is required' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended('learning-payout-item:'||r.id::text,0));
  select * into existing from public.learning_instructor_payout_items where reservation_id=r.id for update;
  if found then return query select existing.id,existing.payout_item_reference,existing.status,existing.amount_minor,existing.currency; return; end if;
  select * into e from public.learning_instructor_earnings where id=r.earning_id for update;
  select * into a from public.learning_commercial_allocations where id=r.allocation_id for update;
  select * into o from public.learning_orders where id=a.order_id for update;
  if not found or e.status<>'reserved' or e.instructor_id<>r.instructor_id or e.gross_amount_minor<>r.amount_minor or a.status<>'allocated' or a.instructor_id<>r.instructor_id or a.instructor_gross_minor<>r.amount_minor or o.status<>'paid' then raise exception 'Reservation financial identity is no longer eligible' using errcode='22023'; end if;
  perform public.assert_learning_approved_instructor(r.instructor_id);
  select * into p from public.learning_instructor_payout_profiles where instructor_id=r.instructor_id and provider='paystack' and provider_domain='test' and status='active' for update;
  if not found or p.currency<>r.currency then raise exception 'Active Test payout recipient is required' using errcode='22023'; end if;
  lock table public.learning_payment_cases in share row exclusive mode;
  if exists(select 1 from public.learning_payment_cases c where c.order_id=o.id and c.status in ('requested','submitting','pending','processing','needs_attention','opened','action_required','submitted','under_review')) then raise exception 'Active financial protection prevents payout approval' using errcode='22023'; end if;
  insert into public.learning_instructor_payout_items(payout_item_reference,idempotency_key,reservation_id,earning_id,allocation_id,instructor_id,payout_profile_id,recipient_code,provider_recipient_id,amount_minor,currency,approved_by)
  values('lpi-reservation-'||r.id::text,p_idempotency_key,r.id,r.earning_id,r.allocation_id,r.instructor_id,p.id,p.recipient_code,p.provider_recipient_id,r.amount_minor,r.currency,p_actor_user_id) returning id into item_id;
  update public.learning_instructor_earning_reservations set future_payout_item_reference='lpi-reservation-'||r.id::text where id=r.id and future_payout_item_reference is null;
  if not found then raise exception 'Reservation is already linked to a payout item' using errcode='23505'; end if;
  insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,to_status,provenance,actor_user_id,metadata) values(item_id,'payout_item.approved','approved','admin',p_actor_user_id,jsonb_build_object('reservation_reference',r.reservation_reference));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(p_actor_user_id,'admin_operator','instructor_payout_item.approved','learning_instructor_payout_item',item_id::text,jsonb_build_object('reservation_id',r.id,'provider_domain','test'));
  return query select item_id,'lpi-reservation-'||r.id::text,'approved',r.amount_minor,r.currency;
end;$function$;

create or replace function public.begin_learning_instructor_test_transfer(p_payout_item_id bigint,p_actor_user_id uuid)
returns table(payout_item_id bigint,payout_item_reference text,recipient_code text,amount_minor bigint,currency text)
language plpgsql security definer set search_path to '' as $function$
declare item public.learning_instructor_payout_items%rowtype; e public.learning_instructor_earnings%rowtype; a public.learning_commercial_allocations%rowtype; o public.learning_orders%rowtype;
begin
  if p_payout_item_id is null or p_actor_user_id is null or not exists(select 1 from public.account_capabilities c where c.user_id=p_actor_user_id and c.capability='admin' and c.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
  select * into item from public.learning_instructor_payout_items where id=p_payout_item_id for update;
  if not found then raise exception 'Payout item not found' using errcode='P0002'; end if;
  if item.provider_transfer_id is not null then raise exception 'Provider transfer already exists' using errcode='22023'; end if;
  if item.status<>'approved' then raise exception 'Approved payout item is required' using errcode='22023'; end if;
  select * into e from public.learning_instructor_earnings where id=item.earning_id for update; select * into a from public.learning_commercial_allocations where id=item.allocation_id for update; select * into o from public.learning_orders where id=a.order_id for update;
  if e.status<>'reserved' or a.status<>'allocated' or o.status<>'paid' then raise exception 'Payout item is no longer financially eligible' using errcode='22023'; end if;
  lock table public.learning_payment_cases in share row exclusive mode;
  if exists(select 1 from public.learning_payment_cases c where c.order_id=o.id and c.status in ('requested','submitting','pending','processing','needs_attention','opened','action_required','submitted','under_review')) then update public.learning_instructor_payout_items set status='cancelled',failure_code='financial_protection' where id=item.id; insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,actor_user_id) values(item.id,'payout_item.cancelled','approved','cancelled','system',p_actor_user_id); raise exception 'Active financial protection prevents transfer submission' using errcode='22023'; end if;
  update public.learning_instructor_payout_items set status='submitting',initiated_by=p_actor_user_id,initiated_at=now() where id=item.id;
  insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,actor_user_id) values(item.id,'payout_item.submitting','approved','submitting','admin',p_actor_user_id);
  return query select item.id,item.payout_item_reference,item.recipient_code,item.amount_minor,item.currency;
end;$function$;

create or replace function public.record_learning_instructor_test_transfer_submission(p_payout_item_id bigint,p_transfer_id text,p_transfer_code text,p_provider_status text,p_actor_user_id uuid)
returns void language plpgsql security definer set search_path to '' as $function$
declare item public.learning_instructor_payout_items%rowtype;
begin
  if p_transfer_id !~ '^[0-9]+$' or (p_transfer_code is not null and p_transfer_code !~ '^TRF_[A-Za-z0-9]+$') or p_provider_status is null then raise exception 'Invalid Paystack Test transfer identity' using errcode='22023'; end if;
  select * into item from public.learning_instructor_payout_items where id=p_payout_item_id for update;
  if not found or item.status<>'submitting' or item.provider_domain<>'test' then raise exception 'Submitting Test payout item required' using errcode='22023'; end if;
  update public.learning_instructor_payout_items set status='pending',provider_transfer_id=p_transfer_id,provider_transfer_code=p_transfer_code,provider_status=p_provider_status,provider_received_at=now() where id=item.id;
  insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,actor_user_id,metadata) values(item.id,'payout_item.pending','submitting','pending','provider_api',p_actor_user_id,jsonb_build_object('provider_transfer_id',p_transfer_id,'provider_status',p_provider_status));
end;$function$;

create or replace function public.fail_learning_instructor_test_transfer_submission(p_payout_item_id bigint,p_failure_code text,p_actor_user_id uuid)
returns void language plpgsql security definer set search_path to '' as $function$
declare item public.learning_instructor_payout_items%rowtype;
begin
  select * into item from public.learning_instructor_payout_items where id=p_payout_item_id for update;
  if not found or item.status<>'submitting' or item.provider_transfer_id is not null then raise exception 'Submitting payout item required' using errcode='22023'; end if;
  update public.learning_instructor_payout_items set status='failed',failure_code=left(coalesce(p_failure_code,'provider_submission_failed'),120) where id=item.id;
  insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,actor_user_id) values(item.id,'payout_item.failed','submitting','failed','system',p_actor_user_id);
end;$function$;

create or replace function public.mark_learning_instructor_test_transfer_recovery_required(p_payout_item_id bigint,p_actor_user_id uuid)
returns void language plpgsql security definer set search_path to '' as $function$
declare item public.learning_instructor_payout_items%rowtype;
begin
  select * into item from public.learning_instructor_payout_items where id=p_payout_item_id for update;
  if not found or item.status<>'submitting' or item.provider_transfer_id is not null then raise exception 'Unconfirmed submitting payout item required' using errcode='22023'; end if;
  update public.learning_instructor_payout_items set status='recovery_required',failure_code='provider_submission_unknown' where id=item.id;
  insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,actor_user_id) values(item.id,'payout_item.recovery_required','submitting','recovery_required','system',p_actor_user_id);
end;$function$;

create or replace function public.receive_paystack_test_transfer_event(p_provider_event_id text,p_payload_digest text,p_reference text,p_transfer_id text,p_transfer_code text,p_status text,p_amount_minor bigint,p_currency text,p_payload jsonb)
returns table(outcome text,payout_item_id bigint) language plpgsql security definer set search_path to '' as $function$
declare item public.learning_instructor_payout_items%rowtype; next_status text;
begin
  if p_provider_event_id is null or p_payload_digest !~ '^[a-f0-9]{64}$' or p_reference !~ '^lpi-[a-z0-9_-]{12,50}$' or p_transfer_id !~ '^[0-9]+$' or p_status not in ('succeeded','failed','reversed') or p_amount_minor<=0 or p_currency<>'NGN' then raise exception 'Invalid Paystack Test transfer event' using errcode='22023'; end if;
  select * into item from public.learning_instructor_payout_items where payout_item_reference=p_reference for update;
  if not found or item.provider_domain<>'test' or item.amount_minor<>p_amount_minor or item.currency<>p_currency then raise exception 'Transfer event does not match a Test payout item' using errcode='22023'; end if;
  if exists(select 1 from public.learning_instructor_payout_item_events e where e.provider_event_id=p_provider_event_id) then return query select 'already_received',item.id; return; end if;
  if item.provider_transfer_id is not null and item.provider_transfer_id<>p_transfer_id then raise exception 'Transfer identity mismatch' using errcode='22023'; end if;
  next_status:=p_status;
  if item.status in ('submitting','pending','recovery_required') and next_status in ('succeeded','failed','reversed') then update public.learning_instructor_payout_items set status=next_status,provider_transfer_id=coalesce(provider_transfer_id,p_transfer_id),provider_transfer_code=coalesce(provider_transfer_code,p_transfer_code),provider_status=p_status,provider_received_at=now(),failure_code=null where id=item.id;
  elsif item.status='financially_blocked' then update public.learning_instructor_payout_items set provider_transfer_id=coalesce(provider_transfer_id,p_transfer_id),provider_transfer_code=coalesce(provider_transfer_code,p_transfer_code),provider_status=p_status,provider_received_at=now() where id=item.id; next_status:=item.status;
  elsif item.status=next_status then null;
  else raise exception 'Transfer event has invalid payout item state' using errcode='22023'; end if;
  insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,provider_event_id,payload_digest,metadata) values(item.id,'paystack.'||p_status,item.status,next_status,'webhook',p_provider_event_id,p_payload_digest,jsonb_build_object('transfer_id',p_transfer_id,'transfer_code',p_transfer_code,'provider_status',p_status));
  return query select 'received',item.id;
end;$function$;

create or replace function public.get_learning_instructor_test_transfer_for_recovery(p_payout_item_id bigint,p_actor_user_id uuid)
returns table(payout_item_id bigint,payout_item_reference text,amount_minor bigint,currency text,status text)
language plpgsql security definer set search_path to '' as $function$
declare item public.learning_instructor_payout_items%rowtype;
begin
  if p_actor_user_id is null or not exists(select 1 from public.account_capabilities c where c.user_id=p_actor_user_id and c.capability='admin' and c.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
  select * into item from public.learning_instructor_payout_items where id=p_payout_item_id for update;
  if not found or item.provider_domain<>'test' or item.status not in ('submitting','pending','recovery_required') then raise exception 'Test payout recovery is not available' using errcode='22023'; end if;
  return query select item.id,item.payout_item_reference,item.amount_minor,item.currency,item.status;
end;$function$;

create or replace function public.record_learning_instructor_test_transfer_verification(p_payout_item_id bigint,p_transfer_id text,p_transfer_code text,p_provider_status text,p_actor_user_id uuid)
returns void language plpgsql security definer set search_path to '' as $function$
declare item public.learning_instructor_payout_items%rowtype; next_status text;
begin
  if p_transfer_id !~ '^[0-9]+$' or (p_transfer_code is not null and p_transfer_code !~ '^TRF_[A-Za-z0-9]+$') or p_provider_status not in ('succeeded','failed','reversed','pending') then raise exception 'Invalid verified Test transfer identity' using errcode='22023'; end if;
  select * into item from public.learning_instructor_payout_items where id=p_payout_item_id for update;
  if not found or item.provider_domain<>'test' then raise exception 'Test payout item required' using errcode='22023'; end if;
  if item.provider_transfer_id is not null and item.provider_transfer_id<>p_transfer_id then raise exception 'Transfer identity mismatch' using errcode='22023'; end if;
  next_status:=p_provider_status;
  if item.status in ('submitting','pending','recovery_required') then update public.learning_instructor_payout_items set status=next_status,provider_transfer_id=coalesce(provider_transfer_id,p_transfer_id),provider_transfer_code=coalesce(provider_transfer_code,p_transfer_code),provider_status=p_provider_status,provider_received_at=now(),failure_code=null where id=item.id;
  elsif item.status='financially_blocked' then update public.learning_instructor_payout_items set provider_transfer_id=coalesce(provider_transfer_id,p_transfer_id),provider_transfer_code=coalesce(provider_transfer_code,p_transfer_code),provider_status=p_provider_status,provider_received_at=now() where id=item.id; next_status:=item.status;
  elsif item.status=next_status then null; else raise exception 'Verified transfer conflicts with local terminal state' using errcode='22023'; end if;
  insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,actor_user_id,metadata) values(item.id,'payout_item.verified',item.status,next_status,'provider_api',p_actor_user_id,jsonb_build_object('provider_transfer_id',p_transfer_id,'provider_status',p_provider_status));
end;$function$;

create or replace function public.block_learning_payout_item_after_earning_reversal()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if new.status in ('reversed','recoverable') and old.status='reserved' then
    update public.learning_instructor_payout_items set status=case when status='approved' then 'cancelled' else 'financially_blocked' end,failure_code='financial_reversal'
    where earning_id=new.id and status in ('approved','submitting','pending','recovery_required');
    insert into public.learning_instructor_payout_item_events(payout_item_id,event_type,from_status,to_status,provenance,metadata)
    select id,'payout_item.financially_blocked',status,case when status='cancelled' then 'cancelled' else 'financially_blocked' end,'system',jsonb_build_object('earning_status',new.status)
    from public.learning_instructor_payout_items where earning_id=new.id and status in ('cancelled','financially_blocked') and failure_code='financial_reversal';
  end if;
  return new;
end;$function$;
create trigger block_learning_payout_item_after_earning_reversal after update on public.learning_instructor_earnings for each row execute function public.block_learning_payout_item_after_earning_reversal();

create or replace function public.list_learning_instructor_payout_items(p_operator_id uuid,p_limit integer default 100)
returns table(payout_item_id bigint,reservation_id bigint,reservation_reference text,payout_item_reference text,instructor_name text,instructor_email text,amount_minor bigint,currency text,status text,provider_status text,provider_transfer_code text,provider_domain text,approved_at timestamptz,initiated_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if p_operator_id is null or not exists(select 1 from public.account_capabilities c where c.user_id=p_operator_id and c.capability='admin' and c.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
  return query select item.id,item.reservation_id,reservation.reservation_reference,item.payout_item_reference,profile.full_name,profile.email,item.amount_minor,item.currency,item.status,item.provider_status,item.provider_transfer_code,item.provider_domain,item.approved_at,item.initiated_at
  from public.learning_instructor_payout_items item join public.learning_instructor_earning_reservations reservation on reservation.id=item.reservation_id join public.profiles profile on profile.id=item.instructor_id order by item.created_at desc,item.id desc limit least(greatest(coalesce(p_limit,100),1),200);
end;$function$;

create or replace function public.list_learning_instructor_payout_candidates(p_operator_id uuid,p_limit integer default 100)
returns table(reservation_id bigint,reservation_reference text,instructor_name text,instructor_email text,amount_minor bigint,currency text,eligible boolean)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if p_operator_id is null or not exists(select 1 from public.account_capabilities c where c.user_id=p_operator_id and c.capability='admin' and c.status='active') then raise exception 'Active administrator required' using errcode='42501'; end if;
  return query select r.id,r.reservation_reference,p.full_name,p.email,r.amount_minor,r.currency,
    e.status='reserved' and a.status='allocated' and o.status='paid' and exists(select 1 from public.learning_instructor_payout_profiles pp where pp.instructor_id=r.instructor_id and pp.provider='paystack' and pp.provider_domain='test' and pp.status='active') and not exists(select 1 from public.learning_payment_cases c where c.order_id=o.id and c.status in ('requested','submitting','pending','processing','needs_attention','opened','action_required','submitted','under_review'))
  from public.learning_instructor_earning_reservations r join public.learning_instructor_earnings e on e.id=r.earning_id join public.learning_commercial_allocations a on a.id=r.allocation_id join public.learning_orders o on o.id=a.order_id join public.profiles p on p.id=r.instructor_id left join public.learning_instructor_payout_items item on item.reservation_id=r.id
  where item.id is null order by r.reserved_at desc,r.id desc limit least(greatest(coalesce(p_limit,100),1),200);
end;$function$;

revoke all on function public.prevent_learning_instructor_payout_item_mutation(),public.prevent_learning_instructor_payout_item_event_mutation(),public.approve_learning_instructor_payout_item(bigint,text,uuid),public.begin_learning_instructor_test_transfer(bigint,uuid),public.record_learning_instructor_test_transfer_submission(bigint,text,text,text,uuid),public.fail_learning_instructor_test_transfer_submission(bigint,text,uuid),public.mark_learning_instructor_test_transfer_recovery_required(bigint,uuid),public.receive_paystack_test_transfer_event(text,text,text,text,text,text,bigint,text,jsonb),public.get_learning_instructor_test_transfer_for_recovery(bigint,uuid),public.record_learning_instructor_test_transfer_verification(bigint,text,text,text,uuid),public.block_learning_payout_item_after_earning_reversal(),public.list_learning_instructor_payout_items(uuid,integer),public.list_learning_instructor_payout_candidates(uuid,integer) from public,anon,authenticated;
grant execute on function public.prevent_learning_instructor_payout_item_mutation(),public.prevent_learning_instructor_payout_item_event_mutation(),public.approve_learning_instructor_payout_item(bigint,text,uuid),public.begin_learning_instructor_test_transfer(bigint,uuid),public.record_learning_instructor_test_transfer_submission(bigint,text,text,text,uuid),public.fail_learning_instructor_test_transfer_submission(bigint,text,uuid),public.mark_learning_instructor_test_transfer_recovery_required(bigint,uuid),public.receive_paystack_test_transfer_event(text,text,text,text,text,text,bigint,text,jsonb),public.get_learning_instructor_test_transfer_for_recovery(bigint,uuid),public.record_learning_instructor_test_transfer_verification(bigint,text,text,text,uuid),public.block_learning_payout_item_after_earning_reversal(),public.list_learning_instructor_payout_items(uuid,integer),public.list_learning_instructor_payout_candidates(uuid,integer) to postgres,service_role;
commit;
