-- Phase 3C: append-only, held-liability reversal accounting for verified
-- company refunds and lost disputes. A trusted service must fetch the final
-- Paystack case before invoking this function. No access or payout mutation.
-- Historical paid Test purchases without sale/access provenance fail closed.
-- Forward-fix rollback: revoke function execute; retain posted history.
begin;

create table public.learning_company_commercial_reversals (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.learning_company_commercial_sales(purchase_id) on delete restrict,
  inbox_event_id bigint not null unique references public.learning_company_reversal_event_inbox(id) on delete restrict,
  reversal_type text not null check (reversal_type in ('processed_refund','lost_dispute')),
  paystack_domain text not null check (paystack_domain in ('test','live')),
  provider_case_id text not null check (provider_case_id ~ '^[1-9][0-9]*$'),
  provider_reference text not null,
  provider_transaction_id text not null,
  gross_amount_minor bigint not null check (gross_amount_minor > 0),
  platform_commission_minor bigint not null check (platform_commission_minor >= 0),
  seller_gross_minor bigint not null check (seller_gross_minor >= 0),
  currency text not null check (currency = 'NGN'),
  verified_at timestamptz not null default now(),
  unique(paystack_domain,reversal_type,provider_case_id),
  check(gross_amount_minor = platform_commission_minor + seller_gross_minor)
);

create table public.learning_company_commercial_reversal_lines (
  reversal_id bigint not null references public.learning_company_commercial_reversals(id) on delete restrict,
  purchase_id bigint not null,
  assigned_user_id uuid not null,
  unit_amount_minor bigint not null check (unit_amount_minor > 0),
  platform_commission_minor bigint not null check (platform_commission_minor >= 0),
  seller_gross_minor bigint not null check (seller_gross_minor >= 0),
  currency text not null check (currency = 'NGN'),
  primary key(reversal_id,assigned_user_id),
  unique(purchase_id,assigned_user_id),
  foreign key(purchase_id,assigned_user_id)
    references public.learning_company_commercial_sale_lines(purchase_id,assigned_user_id) on delete restrict,
  check(unit_amount_minor = platform_commission_minor + seller_gross_minor)
);

create table public.learning_company_commercial_reversal_ledger_entries (
  reversal_id bigint not null references public.learning_company_commercial_reversals(id) on delete restrict,
  line_number smallint not null check (line_number > 0),
  account_code text not null check (account_code in (
    'asset.paystack_receivable','revenue.platform_commission','liability.company_seller_earnings_held')),
  amount_minor bigint not null check (amount_minor <> 0),
  currency text not null check (currency = 'NGN'),
  primary key(reversal_id,line_number)
);

create index learning_company_commercial_reversals_purchase_idx
  on public.learning_company_commercial_reversals(purchase_id,verified_at desc,id desc);

alter table public.learning_company_commercial_reversals enable row level security;
alter table public.learning_company_commercial_reversal_lines enable row level security;
alter table public.learning_company_commercial_reversal_ledger_entries enable row level security;
revoke all on public.learning_company_commercial_reversals,
  public.learning_company_commercial_reversal_lines,
  public.learning_company_commercial_reversal_ledger_entries from public,anon,authenticated,service_role;
grant select on public.learning_company_commercial_reversals,
  public.learning_company_commercial_reversal_lines,
  public.learning_company_commercial_reversal_ledger_entries to service_role;

create trigger prevent_learning_company_commercial_reversal_mutation
before update or delete on public.learning_company_commercial_reversals
for each row execute function public.prevent_learning_company_sale_mutation();
create trigger prevent_learning_company_commercial_reversal_line_mutation
before update or delete on public.learning_company_commercial_reversal_lines
for each row execute function public.prevent_learning_company_sale_mutation();
create trigger prevent_learning_company_commercial_reversal_entry_mutation
before update or delete on public.learning_company_commercial_reversal_ledger_entries
for each row execute function public.prevent_learning_company_sale_mutation();

create or replace function public.post_learning_company_commercial_reversal(
  p_inbox_event_id bigint,p_provider_transaction_id text,p_verified_status text,
  p_verified_resolution text,p_verified_amount_minor bigint,p_selected_user_ids uuid[])
returns bigint language plpgsql security definer set search_path to '' as $function$
declare notice_row public.learning_company_reversal_event_inbox%rowtype;
  sale_row public.learning_company_commercial_sales%rowtype;
  existing_row public.learning_company_commercial_reversals%rowtype;
  reversal_kind text; reversal_key bigint; selected_count integer; selected_distinct_count integer;
  selected_gross bigint; selected_platform bigint; selected_seller bigint;
begin
  if p_inbox_event_id is null or p_verified_amount_minor is null or p_verified_amount_minor <= 0
     or p_provider_transaction_id is null or p_provider_transaction_id !~ '^[1-9][0-9]*$'
     or p_selected_user_ids is null or cardinality(p_selected_user_ids) = 0 then
    raise exception 'Invalid company reversal evidence or seat selection' using errcode = '22023';
  end if;
  select * into notice_row from public.learning_company_reversal_event_inbox notice
  where notice.id = p_inbox_event_id for share;
  if not found or notice_row.provider_case_id !~ '^[1-9][0-9]*$' then
    raise exception 'Company reversal notice was not found or has no numeric provider case ID' using errcode = '22023';
  end if;
  if notice_row.event_type = 'refund.processed' and p_verified_status = 'processed' then
    reversal_kind := 'processed_refund';
  elsif notice_row.event_type = 'charge.dispute.resolve'
        and p_verified_status = 'resolved' and p_verified_resolution = 'merchant-accepted' then
    reversal_kind := 'lost_dispute';
  else
    raise exception 'Final provider reversal outcome is required' using errcode = '22023';
  end if;
  -- Serializes all reversals for this purchase, including separate provider cases.
  perform 1 from public.learning_company_paid_course_purchases purchase
  where purchase.id = notice_row.purchase_id and purchase.status = 'paid' for update;
  if not found then raise exception 'Paid company purchase is required' using errcode = '22023'; end if;
  select * into sale_row from public.learning_company_commercial_sales sale
  where sale.purchase_id = notice_row.purchase_id;
  if not found or sale_row.attempt_id <> notice_row.attempt_id
     or sale_row.paystack_domain <> notice_row.paystack_domain
     or sale_row.provider_reference <> notice_row.provider_reference
     or sale_row.provider_transaction_id <> p_provider_transaction_id
     or sale_row.currency <> notice_row.currency then
    raise exception 'Company sale does not match verified reversal identity' using errcode = '22023';
  end if;
  select count(*),count(distinct selected.user_id) into selected_count,selected_distinct_count
  from unnest(p_selected_user_ids) as selected(user_id);
  if selected_count <> selected_distinct_count or exists(
    select 1 from unnest(p_selected_user_ids) as selected(user_id) where selected.user_id is null) then
    raise exception 'Company reversal seats must be unique and non-null' using errcode = '22023';
  end if;
  select coalesce(sum(line.unit_amount_minor),0),coalesce(sum(line.platform_commission_minor),0),
    coalesce(sum(line.seller_gross_minor),0)
  into selected_gross,selected_platform,selected_seller
  from public.learning_company_commercial_sale_lines line
  where line.purchase_id = sale_row.purchase_id
    and line.assigned_user_id = any(p_selected_user_ids);
  if (select count(*) from public.learning_company_commercial_sale_lines line
      where line.purchase_id = sale_row.purchase_id
        and line.assigned_user_id = any(p_selected_user_ids)) <> selected_count
     or selected_gross <> p_verified_amount_minor
     or selected_gross <> selected_platform + selected_seller
     or (reversal_kind = 'lost_dispute'
       and (selected_count <> sale_row.seat_count or selected_gross <> sale_row.gross_amount_minor)) then
    raise exception 'Company reversal amount or paid seats do not match sale lines' using errcode = '22023';
  end if;
  select * into existing_row from public.learning_company_commercial_reversals reversal
  where reversal.paystack_domain = sale_row.paystack_domain
    and reversal.reversal_type = reversal_kind
    and reversal.provider_case_id = notice_row.provider_case_id;
  if found then
    if existing_row.purchase_id <> sale_row.purchase_id
       or existing_row.gross_amount_minor <> selected_gross
       or existing_row.platform_commission_minor <> selected_platform
       or existing_row.seller_gross_minor <> selected_seller
       or (select count(*) from public.learning_company_commercial_reversal_lines line
           where line.reversal_id = existing_row.id and line.assigned_user_id = any(p_selected_user_ids)) <> selected_count then
      raise exception 'Provider reversal case conflicts with an earlier posting' using errcode = '23505';
    end if;
    return existing_row.id;
  end if;
  if (select count(*) from public.learning_company_paid_seat_access access_row
      where access_row.purchase_id = sale_row.purchase_id
        and access_row.assigned_user_id = any(p_selected_user_ids)
        and access_row.status = 'active') <> selected_count then
    raise exception 'Active company paid-seat provenance is required' using errcode = '22023';
  end if;
  if exists(select 1 from public.learning_company_commercial_reversal_lines line
    where line.purchase_id = sale_row.purchase_id and line.assigned_user_id = any(p_selected_user_ids)) then
    raise exception 'A company paid seat has already been reversed' using errcode = '23505';
  end if;
  insert into public.learning_company_commercial_reversals(
    purchase_id,inbox_event_id,reversal_type,paystack_domain,provider_case_id,
    provider_reference,provider_transaction_id,gross_amount_minor,
    platform_commission_minor,seller_gross_minor,currency)
  values(sale_row.purchase_id,p_inbox_event_id,reversal_kind,sale_row.paystack_domain,
    notice_row.provider_case_id,sale_row.provider_reference,sale_row.provider_transaction_id,
    selected_gross,selected_platform,selected_seller,sale_row.currency)
  returning id into reversal_key;
  insert into public.learning_company_commercial_reversal_lines(
    reversal_id,purchase_id,assigned_user_id,unit_amount_minor,
    platform_commission_minor,seller_gross_minor,currency)
  select reversal_key,line.purchase_id,line.assigned_user_id,line.unit_amount_minor,
    line.platform_commission_minor,line.seller_gross_minor,line.currency
  from public.learning_company_commercial_sale_lines line
  where line.purchase_id = sale_row.purchase_id and line.assigned_user_id = any(p_selected_user_ids);
  -- Reverse only held sale accounts. A future payout release must prove that
  -- this held liability was never transferred before touching this path.
  if selected_platform > 0 then
    insert into public.learning_company_commercial_reversal_ledger_entries(
      reversal_id,line_number,account_code,amount_minor,currency)
    values(reversal_key,1,'revenue.platform_commission',selected_platform,sale_row.currency);
  end if;
  if selected_seller > 0 then
    insert into public.learning_company_commercial_reversal_ledger_entries(
      reversal_id,line_number,account_code,amount_minor,currency)
    values(reversal_key,2,'liability.company_seller_earnings_held',selected_seller,sale_row.currency);
  end if;
  insert into public.learning_company_commercial_reversal_ledger_entries(
    reversal_id,line_number,account_code,amount_minor,currency)
  values(reversal_key,3,'asset.paystack_receivable',-selected_gross,sale_row.currency);
  if (select coalesce(sum(entry.amount_minor),0) from public.learning_company_commercial_reversal_ledger_entries entry
      where entry.reversal_id = reversal_key) <> 0 then
    raise exception 'Company reversal ledger is not balanced' using errcode = '23514';
  end if;
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(null,'payment_system','company_paid_course.commercial_reversal_posted',
    'learning_company_paid_course_purchase',sale_row.purchase_id::text,
    jsonb_build_object('reversal_id',reversal_key,'inbox_event_id',p_inbox_event_id,
      'kind',reversal_kind,'gross_amount_minor',selected_gross,'seat_count',selected_count));
  return reversal_key;
end;$function$;

create or replace function public.reconcile_learning_company_commercial_reversals()
returns table(reversal_id bigint,issue_type text)
language sql stable security definer set search_path to '' as $function$
  select reversal.id,'company_reversal_seat_sum_mismatch'::text
  from public.learning_company_commercial_reversals reversal
  where reversal.gross_amount_minor <> coalesce((select sum(line.unit_amount_minor)
      from public.learning_company_commercial_reversal_lines line where line.reversal_id = reversal.id),0)
    or reversal.platform_commission_minor <> coalesce((select sum(line.platform_commission_minor)
      from public.learning_company_commercial_reversal_lines line where line.reversal_id = reversal.id),0)
    or reversal.seller_gross_minor <> coalesce((select sum(line.seller_gross_minor)
      from public.learning_company_commercial_reversal_lines line where line.reversal_id = reversal.id),0)
  union all
  select reversal.id,'company_reversal_ledger_mismatch'::text
  from public.learning_company_commercial_reversals reversal
  where (select coalesce(sum(entry.amount_minor),0)
      from public.learning_company_commercial_reversal_ledger_entries entry
      where entry.reversal_id = reversal.id and entry.account_code = 'revenue.platform_commission')
        <> reversal.platform_commission_minor
    or (select coalesce(sum(entry.amount_minor),0)
      from public.learning_company_commercial_reversal_ledger_entries entry
      where entry.reversal_id = reversal.id and entry.account_code = 'liability.company_seller_earnings_held')
        <> reversal.seller_gross_minor
    or (select coalesce(sum(entry.amount_minor),0)
      from public.learning_company_commercial_reversal_ledger_entries entry
      where entry.reversal_id = reversal.id and entry.account_code = 'asset.paystack_receivable')
        <> -reversal.gross_amount_minor;
$function$;

revoke all on function public.post_learning_company_commercial_reversal(
  bigint,text,text,text,bigint,uuid[]),
  public.reconcile_learning_company_commercial_reversals() from public,anon,authenticated;
grant execute on function public.post_learning_company_commercial_reversal(
  bigint,text,text,text,bigint,uuid[]),
  public.reconcile_learning_company_commercial_reversals() to postgres,service_role;

commit;
