-- Phase 2B2: verified provider profiles. Profiles are public only when the
-- organization is active and its provider verification is approved.

create table public.learning_provider_organization_profiles (
  organization_id bigint primary key references public.learning_provider_organizations(id) on delete restrict,
  headline text not null check (char_length(btrim(headline)) between 8 and 160),
  description text not null check (char_length(btrim(description)) between 80 and 2400),
  contact_email text not null check (char_length(btrim(contact_email)) between 5 and 320),
  website_url text check (website_url is null or char_length(website_url) <= 400),
  linkedin_url text check (linkedin_url is null or char_length(linkedin_url) <= 400),
  instagram_url text check (instagram_url is null or char_length(instagram_url) <= 400),
  updated_by uuid not null references public.profiles(id) on delete restrict,
  updated_at timestamptz not null default now()
);

create table public.learning_provider_organization_profile_events (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.learning_provider_organizations(id) on delete restrict,
  actor_user_id uuid references public.profiles(id) on delete restrict,
  event_type text not null check (event_type in ('profile.created','profile.updated')),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  occurred_at timestamptz not null default now()
);

-- Profile history is part of the provider record. Keep it append-only so a
-- public profile change remains auditable even after a member is removed.
create or replace function public.prevent_learning_provider_organization_profile_event_mutation()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  raise exception 'Provider profile events are immutable' using errcode = '42501';
end;
$function$;

create trigger prevent_learning_provider_organization_profile_event_mutation_trigger
before update or delete on public.learning_provider_organization_profile_events
for each row execute function public.prevent_learning_provider_organization_profile_event_mutation();

alter table public.learning_provider_organization_profiles enable row level security;
alter table public.learning_provider_organization_profile_events enable row level security;
revoke all on public.learning_provider_organization_profiles, public.learning_provider_organization_profile_events from public, anon, authenticated;
grant select, insert, update, delete on public.learning_provider_organization_profiles, public.learning_provider_organization_profile_events to postgres, service_role;

create or replace function public.update_own_learning_provider_organization_profile(
  p_organization_id bigint,
  p_headline text,
  p_description text,
  p_contact_email text,
  p_website_url text,
  p_linkedin_url text,
  p_instagram_url text
)
returns table(organization_id bigint, updated_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare
  headline_value text:=btrim(p_headline); description_value text:=btrim(p_description); contact_email_value text:=lower(btrim(p_contact_email));
  website_url_value text:=nullif(btrim(p_website_url),''); linkedin_url_value text:=nullif(btrim(p_linkedin_url),''); instagram_url_value text:=nullif(btrim(p_instagram_url),'');
  profile_exists boolean:=false;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if p_organization_id is null or not exists (
    select 1 from public.learning_provider_organization_memberships membership
    join public.learning_provider_organizations organization on organization.id=membership.organization_id
    join public.learning_provider_organization_verifications verification on verification.organization_id=organization.id
    where membership.organization_id=p_organization_id and membership.user_id=auth.uid() and membership.role='owner' and membership.status='active'
      and organization.status='active' and verification.status='verified'
  ) then raise exception 'An active owner of a verified provider is required' using errcode='42501'; end if;
  if headline_value is null or char_length(headline_value) not between 8 and 160 or description_value is null or char_length(description_value) not between 80 and 2400
    or contact_email_value is null or contact_email_value !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
    or (website_url_value is not null and (char_length(website_url_value)>400 or website_url_value !~* '^https?://'))
    or (linkedin_url_value is not null and (char_length(linkedin_url_value)>400 or linkedin_url_value !~* '^https://([^/]+\.)?linkedin\.com/'))
    or (instagram_url_value is not null and (char_length(instagram_url_value)>400 or instagram_url_value !~* '^https://([^/]+\.)?instagram\.com/'))
  then raise exception 'Invalid provider profile details' using errcode='22023'; end if;
  select exists(select 1 from public.learning_provider_organization_profiles profile where profile.organization_id=p_organization_id) into profile_exists;
  insert into public.learning_provider_organization_profiles(organization_id,headline,description,contact_email,website_url,linkedin_url,instagram_url,updated_by,updated_at)
  values(p_organization_id,headline_value,description_value,contact_email_value,website_url_value,linkedin_url_value,instagram_url_value,auth.uid(),now())
  on conflict on constraint learning_provider_organization_profiles_pkey do update set headline=excluded.headline,description=excluded.description,contact_email=excluded.contact_email,website_url=excluded.website_url,linkedin_url=excluded.linkedin_url,instagram_url=excluded.instagram_url,updated_by=excluded.updated_by,updated_at=excluded.updated_at;
  insert into public.learning_provider_organization_profile_events(organization_id,actor_user_id,event_type,metadata) values(p_organization_id,auth.uid(),case when profile_exists then 'profile.updated' else 'profile.created' end,jsonb_build_object('website_supplied',website_url_value is not null,'linkedin_supplied',linkedin_url_value is not null,'instagram_supplied',instagram_url_value is not null));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata) values(auth.uid(),'organization_owner','provider_organization.profile_saved','learning_provider_organization',p_organization_id::text,jsonb_build_object('updated',profile_exists));
  return query select profile.organization_id,profile.updated_at from public.learning_provider_organization_profiles profile where profile.organization_id=p_organization_id;
end;$function$;

create or replace function public.list_own_learning_provider_organization_profiles()
returns table(organization_id bigint,headline text,description text,contact_email text,website_url text,linkedin_url text,instagram_url text,updated_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  return query select profile.organization_id,profile.headline,profile.description,profile.contact_email,profile.website_url,profile.linkedin_url,profile.instagram_url,profile.updated_at from public.learning_provider_organization_profiles profile join public.learning_provider_organization_memberships membership on membership.organization_id=profile.organization_id where membership.user_id=auth.uid() and membership.status='active';
end;$function$;

create or replace function public.get_public_learning_provider_organization_profile(p_slug text)
returns table(name text,slug text,headline text,description text,contact_email text,website_url text,linkedin_url text,instagram_url text,updated_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
declare normalized_slug text:=lower(btrim(p_slug));
begin
  if normalized_slug is null or normalized_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then return; end if;
  return query select organization.name,organization.slug,profile.headline,profile.description,profile.contact_email,profile.website_url,profile.linkedin_url,profile.instagram_url,profile.updated_at from public.learning_provider_organizations organization join public.learning_provider_organization_verifications verification on verification.organization_id=organization.id and verification.status='verified' join public.learning_provider_organization_profiles profile on profile.organization_id=organization.id where organization.slug=normalized_slug and organization.status='active';
end;$function$;

revoke all on function public.update_own_learning_provider_organization_profile(bigint,text,text,text,text,text,text),public.list_own_learning_provider_organization_profiles(),public.get_public_learning_provider_organization_profile(text) from public,anon,authenticated;
grant execute on function public.update_own_learning_provider_organization_profile(bigint,text,text,text,text,text,text),public.list_own_learning_provider_organization_profiles() to authenticated,postgres,service_role;
grant execute on function public.get_public_learning_provider_organization_profile(text) to anon,authenticated,postgres,service_role;
