-- Phase 1E1: Test-mode payout profile and Paystack recipient foundation.
-- This is deliberately non-financial: it cannot reserve earnings, initiate a
-- transfer, or alter commercial allocations, earnings, or historical orders.

begin;

create table public.learning_instructor_payout_profiles (
  id bigint generated by default as identity primary key,
  instructor_id uuid not null references public.profiles(id) on delete restrict,
  provider text not null default 'paystack' check (provider='paystack'),
  provider_domain text not null check (provider_domain in ('test','live')),
  status text not null default 'active' check (status in ('active','disabled')),
  recipient_code text not null check (recipient_code ~ '^RCP_[A-Za-z0-9]+$'),
  provider_recipient_id text not null check (provider_recipient_id ~ '^[0-9]+$'),
  currency text not null default 'NGN' check (currency='NGN'),
  bank_code text not null check (bank_code ~ '^[A-Za-z0-9_-]{2,32}$'),
  bank_name text not null check (char_length(bank_name) between 1 and 160),
  account_name text not null check (char_length(account_name) between 1 and 200),
  account_last4 text not null check (account_last4 ~ '^[0-9]{4}$'),
  created_at timestamptz not null default now(),
  disabled_at timestamptz,
  created_by uuid not null references public.profiles(id) on delete restrict,
  constraint learning_instructor_payout_profiles_lifecycle_check check (
    (status='active' and disabled_at is null) or (status='disabled' and disabled_at is not null)
  ),
  constraint learning_instructor_payout_profiles_domain_recipient_unique unique(provider_domain,recipient_code),
  constraint learning_instructor_payout_profiles_domain_recipient_id_unique unique(provider_domain,provider_recipient_id)
);
create unique index learning_instructor_payout_profiles_one_active_profile
  on public.learning_instructor_payout_profiles(instructor_id,provider,provider_domain)
  where status='active';
create index learning_instructor_payout_profiles_instructor_idx
  on public.learning_instructor_payout_profiles(instructor_id,created_at desc,id desc);

create table public.learning_instructor_payout_profile_events (
  id bigint generated by default as identity primary key,
  payout_profile_id bigint not null references public.learning_instructor_payout_profiles(id) on delete restrict,
  instructor_id uuid not null references public.profiles(id) on delete restrict,
  event_type text not null check (event_type in ('payout_profile.created','payout_profile.disabled','payout_profile.replaced')),
  actor_user_id uuid references public.profiles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  occurred_at timestamptz not null default now()
);
create index learning_instructor_payout_profile_events_profile_idx
  on public.learning_instructor_payout_profile_events(payout_profile_id,occurred_at desc,id desc);

alter table public.learning_instructor_payout_profiles enable row level security;
alter table public.learning_instructor_payout_profile_events enable row level security;
revoke all on public.learning_instructor_payout_profiles,public.learning_instructor_payout_profile_events from public,anon,authenticated;
grant select,insert,update,delete on public.learning_instructor_payout_profiles,public.learning_instructor_payout_profile_events to postgres,service_role;

create or replace function public.prevent_learning_instructor_payout_profile_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  if tg_op='DELETE' then
    raise exception 'Payout profile history is retained and cannot be deleted' using errcode='42501';
  end if;
  if old.instructor_id is distinct from new.instructor_id
    or old.provider is distinct from new.provider
    or old.provider_domain is distinct from new.provider_domain
    or old.recipient_code is distinct from new.recipient_code
    or old.provider_recipient_id is distinct from new.provider_recipient_id
    or old.currency is distinct from new.currency
    or old.bank_code is distinct from new.bank_code
    or old.bank_name is distinct from new.bank_name
    or old.account_name is distinct from new.account_name
    or old.account_last4 is distinct from new.account_last4
    or old.created_at is distinct from new.created_at
    or old.created_by is distinct from new.created_by then
    raise exception 'Payout profile identity is immutable' using errcode='42501';
  end if;
  if (old.status='active' and new.status='disabled' and new.disabled_at is not null)
    or (old.status='disabled' and new.status='active' and new.disabled_at is null) then
    return new;
  end if;
  raise exception 'Unsupported payout profile transition' using errcode='22023';
end;$function$;
create trigger prevent_learning_instructor_payout_profile_mutation
before update or delete on public.learning_instructor_payout_profiles
for each row execute function public.prevent_learning_instructor_payout_profile_mutation();

create or replace function public.prevent_learning_instructor_payout_profile_event_mutation()
returns trigger language plpgsql security definer set search_path to '' as $function$
begin
  raise exception 'Payout profile event history is append-only' using errcode='42501';
end;$function$;
create trigger prevent_learning_instructor_payout_profile_event_mutation
before update or delete on public.learning_instructor_payout_profile_events
for each row execute function public.prevent_learning_instructor_payout_profile_event_mutation();

create or replace function public.assert_learning_approved_instructor(p_instructor_id uuid)
returns void language plpgsql stable security definer set search_path to '' as $function$
begin
  if p_instructor_id is null or not exists(
    select 1
    from public.account_capabilities capability
    join public.instructor_profiles instructor_profile on instructor_profile.user_id=capability.user_id
    where capability.user_id=p_instructor_id
      and capability.capability='instructor'
      and capability.status='active'
      and instructor_profile.approval_status='approved'
  ) then
    raise exception 'Active approved instructor required' using errcode='42501';
  end if;
end;$function$;

-- The route only calls this Test-specific function. The schema retains a
-- provider_domain column so a separately approved future Live implementation
-- cannot mix recipient identities across Paystack environments.
create or replace function public.create_learning_instructor_paystack_test_payout_profile(
  p_instructor_id uuid,
  p_recipient_code text,
  p_provider_recipient_id text,
  p_bank_code text,
  p_bank_name text,
  p_account_name text,
  p_account_last4 text,
  p_actor_user_id uuid
)
returns table(
  payout_profile_id bigint,
  status text,
  provider_domain text,
  recipient_code text,
  bank_name text,
  account_name text,
  account_last4 text,
  created_at timestamptz
)
language plpgsql security definer set search_path to '' as $function$
declare existing_row public.learning_instructor_payout_profiles%rowtype; profile_id bigint;
begin
  if p_actor_user_id is distinct from p_instructor_id then
    raise exception 'Instructor ownership is required' using errcode='42501';
  end if;
  perform public.assert_learning_approved_instructor(p_instructor_id);
  if p_recipient_code is null or p_recipient_code !~ '^RCP_[A-Za-z0-9]+$'
    or p_provider_recipient_id is null or p_provider_recipient_id !~ '^[0-9]+$'
    or p_bank_code is null or p_bank_code !~ '^[A-Za-z0-9_-]{2,32}$'
    or p_bank_name is null or char_length(p_bank_name) not between 1 and 160
    or p_account_name is null or char_length(p_account_name) not between 1 and 200
    or p_account_last4 is null or p_account_last4 !~ '^[0-9]{4}$' then
    raise exception 'Invalid payout profile recipient metadata' using errcode='22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('learning-payout-profile:test:'||p_instructor_id::text,0));
  select * into existing_row
  from public.learning_instructor_payout_profiles
  where instructor_id=p_instructor_id and provider='paystack' and provider_domain='test' and status='active'
  for update;

  if found and existing_row.recipient_code=p_recipient_code
    and existing_row.provider_recipient_id=p_provider_recipient_id
    and existing_row.bank_code=p_bank_code
    and existing_row.bank_name=p_bank_name
    and existing_row.account_name=p_account_name
    and existing_row.account_last4=p_account_last4 then
    return query select existing_row.id,existing_row.status,existing_row.provider_domain,existing_row.recipient_code,
      existing_row.bank_name,existing_row.account_name,existing_row.account_last4,existing_row.created_at;
    return;
  end if;

  if found then
    update public.learning_instructor_payout_profiles
    set status='disabled',disabled_at=now()
    where id=existing_row.id;
    insert into public.learning_instructor_payout_profile_events(payout_profile_id,instructor_id,event_type,actor_user_id,metadata)
    values(existing_row.id,p_instructor_id,'payout_profile.replaced',p_actor_user_id,jsonb_build_object('provider','paystack','provider_domain','test'));
    insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
    values(p_actor_user_id,'instructor','payout_profile.replaced','learning_instructor_payout_profile',existing_row.id::text,jsonb_build_object('provider','paystack','provider_domain','test'));
  end if;

  -- Paystack may return the same recipient for a repeated account submission.
  -- Reusing that immutable provider identity is safe; creating a second local
  -- identity is not. Re-activation is only possible through this service path.
  select * into existing_row
  from public.learning_instructor_payout_profiles
  where instructor_id=p_instructor_id and provider='paystack' and provider_domain='test'
    and recipient_code=p_recipient_code and provider_recipient_id=p_provider_recipient_id
  for update;
  if found then
    if existing_row.bank_code is distinct from p_bank_code or existing_row.bank_name is distinct from p_bank_name
      or existing_row.account_name is distinct from p_account_name or existing_row.account_last4 is distinct from p_account_last4 then
      raise exception 'Paystack recipient metadata does not match the stored identity' using errcode='22023';
    end if;
    update public.learning_instructor_payout_profiles set status='active',disabled_at=null where id=existing_row.id;
    insert into public.learning_instructor_payout_profile_events(payout_profile_id,instructor_id,event_type,actor_user_id,metadata)
    values(existing_row.id,p_instructor_id,'payout_profile.replaced',p_actor_user_id,jsonb_build_object('provider','paystack','provider_domain','test'));
    insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
    values(p_actor_user_id,'instructor','payout_profile.replaced','learning_instructor_payout_profile',existing_row.id::text,jsonb_build_object('provider','paystack','provider_domain','test'));
    return query select existing_row.id,'active','test',existing_row.recipient_code,existing_row.bank_name,existing_row.account_name,existing_row.account_last4,existing_row.created_at;
    return;
  end if;

  insert into public.learning_instructor_payout_profiles(
    instructor_id,provider,provider_domain,status,recipient_code,provider_recipient_id,currency,bank_code,bank_name,account_name,account_last4,created_by
  ) values (
    p_instructor_id,'paystack','test','active',p_recipient_code,p_provider_recipient_id,'NGN',p_bank_code,p_bank_name,p_account_name,p_account_last4,p_actor_user_id
  ) returning id into profile_id;
  insert into public.learning_instructor_payout_profile_events(payout_profile_id,instructor_id,event_type,actor_user_id,metadata)
  values(profile_id,p_instructor_id,'payout_profile.created',p_actor_user_id,jsonb_build_object('provider','paystack','provider_domain','test','account_last4',p_account_last4));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(p_actor_user_id,'instructor','payout_profile.created','learning_instructor_payout_profile',profile_id::text,jsonb_build_object('provider','paystack','provider_domain','test','account_last4',p_account_last4));
  return query
  select profile.id,profile.status,profile.provider_domain,profile.recipient_code,profile.bank_name,profile.account_name,profile.account_last4,profile.created_at
  from public.learning_instructor_payout_profiles profile where profile.id=profile_id;
end;$function$;

create or replace function public.disable_own_learning_instructor_paystack_test_payout_profile(p_instructor_id uuid,p_actor_user_id uuid)
returns boolean language plpgsql security definer set search_path to '' as $function$
declare profile_row public.learning_instructor_payout_profiles%rowtype;
begin
  if p_actor_user_id is distinct from p_instructor_id then raise exception 'Instructor ownership is required' using errcode='42501'; end if;
  perform public.assert_learning_approved_instructor(p_instructor_id);
  perform pg_advisory_xact_lock(hashtextextended('learning-payout-profile:test:'||p_instructor_id::text,0));
  select * into profile_row from public.learning_instructor_payout_profiles
  where instructor_id=p_instructor_id and provider='paystack' and provider_domain='test' and status='active' for update;
  if not found then return false; end if;
  update public.learning_instructor_payout_profiles set status='disabled',disabled_at=now() where id=profile_row.id;
  insert into public.learning_instructor_payout_profile_events(payout_profile_id,instructor_id,event_type,actor_user_id,metadata)
  values(profile_row.id,p_instructor_id,'payout_profile.disabled',p_actor_user_id,jsonb_build_object('provider','paystack','provider_domain','test'));
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(p_actor_user_id,'instructor','payout_profile.disabled','learning_instructor_payout_profile',profile_row.id::text,jsonb_build_object('provider','paystack','provider_domain','test'));
  return true;
end;$function$;

create or replace function public.get_own_learning_instructor_payout_profiles()
returns table(
  payout_profile_id bigint,status text,provider text,provider_domain text,recipient_code text,currency text,
  bank_code text,bank_name text,account_name text,account_last4 text,created_at timestamptz,disabled_at timestamptz
)
language plpgsql stable security definer set search_path to '' as $function$
declare actor_id uuid:=auth.uid();
begin
  if actor_id is null then raise exception 'Authentication required' using errcode='42501'; end if;
  perform public.assert_learning_approved_instructor(actor_id);
  return query select profile.id,profile.status,profile.provider,profile.provider_domain,profile.recipient_code,profile.currency,
    profile.bank_code,profile.bank_name,profile.account_name,profile.account_last4,profile.created_at,profile.disabled_at
  from public.learning_instructor_payout_profiles profile
  where profile.instructor_id=actor_id
  order by profile.created_at desc,profile.id desc;
end;$function$;

create or replace function public.list_learning_instructor_payout_profiles(p_operator_id uuid,p_limit integer default 100)
returns table(
  payout_profile_id bigint,instructor_id uuid,instructor_name text,instructor_email text,status text,provider text,provider_domain text,
  recipient_code text,currency text,bank_code text,bank_name text,account_name text,account_last4 text,created_at timestamptz,disabled_at timestamptz
)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if p_operator_id is null or not exists(
    select 1 from public.account_capabilities capability
    where capability.user_id=p_operator_id and capability.capability='admin' and capability.status='active'
  ) then raise exception 'Active administrator required' using errcode='42501'; end if;
  return query select profile.id,profile.instructor_id,instructor.full_name,instructor.email,profile.status,profile.provider,profile.provider_domain,
    profile.recipient_code,profile.currency,profile.bank_code,profile.bank_name,profile.account_name,profile.account_last4,profile.created_at,profile.disabled_at
  from public.learning_instructor_payout_profiles profile
  join public.profiles instructor on instructor.id=profile.instructor_id
  order by profile.created_at desc,profile.id desc
  limit least(greatest(coalesce(p_limit,100),1),200);
end;$function$;

revoke all on function
  public.prevent_learning_instructor_payout_profile_mutation(),
  public.prevent_learning_instructor_payout_profile_event_mutation(),
  public.assert_learning_approved_instructor(uuid),
  public.create_learning_instructor_paystack_test_payout_profile(uuid,text,text,text,text,text,text,uuid),
  public.disable_own_learning_instructor_paystack_test_payout_profile(uuid,uuid),
  public.get_own_learning_instructor_payout_profiles(),
  public.list_learning_instructor_payout_profiles(uuid,integer)
from public,anon,authenticated;
grant execute on function public.get_own_learning_instructor_payout_profiles() to authenticated,postgres,service_role;
grant execute on function
  public.prevent_learning_instructor_payout_profile_mutation(),
  public.prevent_learning_instructor_payout_profile_event_mutation(),
  public.assert_learning_approved_instructor(uuid),
  public.create_learning_instructor_paystack_test_payout_profile(uuid,text,text,text,text,text,text,uuid),
  public.disable_own_learning_instructor_paystack_test_payout_profile(uuid,uuid),
  public.list_learning_instructor_payout_profiles(uuid,integer)
to postgres,service_role;

commit;
