-- Phase 3C: retain private evidence of an independently verified company
-- seller transfer. This migration provides no transfer or evidence writer.
-- Release/reservation and company transfer execution remain disabled.
begin;

create table public.learning_company_seller_transfer_evidence (
  id bigint generated by default as identity primary key,
  boundary_id bigint not null unique references public.learning_company_seller_outflow_boundaries(id) on delete restrict,
  purchase_id bigint not null references public.learning_company_commercial_sales(purchase_id) on delete restrict,
  seller_payee_id uuid not null references public.profiles(id) on delete restrict,
  payout_profile_id bigint not null references public.learning_instructor_payout_profiles(id) on delete restrict,
  provider_reference text not null unique check (provider_reference ~ '^lcs-[a-z0-9_-]{12,46}$'),
  provider_transfer_id text not null unique check (provider_transfer_id ~ '^[1-9][0-9]{0,18}$'),
  provider_transfer_code text check (provider_transfer_code is null or provider_transfer_code ~ '^TRF_[A-Za-z0-9]+$'),
  recipient_code text not null check (recipient_code ~ '^RCP_[A-Za-z0-9]+$'),
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null default 'NGN' check (currency = 'NGN'),
  paystack_domain text not null default 'live' check (paystack_domain = 'live'),
  provider_source text not null default 'balance' check (provider_source = 'balance'),
  provider_status text not null default 'success' check (provider_status = 'success'),
  verified_by uuid not null references public.profiles(id) on delete restrict,
  verified_at timestamptz not null default now(),
  recorded_at timestamptz not null default now()
);

create index learning_company_seller_transfer_evidence_purchase_idx
  on public.learning_company_seller_transfer_evidence(purchase_id,recorded_at,id);

alter table public.learning_company_seller_transfer_evidence enable row level security;
revoke all on public.learning_company_seller_transfer_evidence
  from public,anon,authenticated,service_role;
grant select on public.learning_company_seller_transfer_evidence to service_role;

create trigger prevent_learning_company_seller_transfer_evidence_mutation
before update or delete on public.learning_company_seller_transfer_evidence
for each row execute function public.prevent_learning_company_sale_mutation();

create function public.validate_learning_company_seller_transfer_evidence()
returns trigger language plpgsql security definer set search_path to '' as $function$
declare purchase_row public.learning_company_paid_course_purchases%rowtype;
  sale_row public.learning_company_commercial_sales%rowtype;
  boundary_row public.learning_company_seller_outflow_boundaries%rowtype;
  payout_profile_row public.learning_instructor_payout_profiles%rowtype;
  reserved_total bigint; transferred_total bigint;
begin
  -- Serialize a transfer record with reservations and any reversal posting.
  select * into purchase_row from public.learning_company_paid_course_purchases purchase
  where purchase.id = new.purchase_id for update;
  if not found or purchase_row.status <> 'paid' then
    raise exception 'Paid company purchase is required for transfer evidence' using errcode = '22023';
  end if;
  select * into sale_row from public.learning_company_commercial_sales sale
  where sale.purchase_id = new.purchase_id;
  select * into boundary_row from public.learning_company_seller_outflow_boundaries boundary
  where boundary.id = new.boundary_id;
  select * into payout_profile_row from public.learning_instructor_payout_profiles payout_profile
  where payout_profile.id = new.payout_profile_id;

  if sale_row.purchase_id is null or sale_row.paystack_domain <> 'live'
      or sale_row.currency <> 'NGN' or sale_row.seller_payee_id <> new.seller_payee_id
      or boundary_row.id is null or boundary_row.purchase_id <> new.purchase_id
      or boundary_row.seller_payee_id <> new.seller_payee_id
      or boundary_row.boundary_kind <> 'transferred'
      or boundary_row.amount_minor <> new.amount_minor
      or boundary_row.currency <> new.currency
      or boundary_row.movement_reference <> new.provider_reference
      or payout_profile_row.id is null
      or payout_profile_row.instructor_id <> new.seller_payee_id
      or payout_profile_row.provider <> 'paystack'
      or payout_profile_row.provider_domain <> 'live'
      or payout_profile_row.status <> 'active'
      or payout_profile_row.currency <> 'NGN'
      or payout_profile_row.recipient_code <> new.recipient_code then
    raise exception 'Company seller transfer evidence identity mismatch' using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.account_capabilities capability
    where capability.user_id = new.verified_by
      and capability.capability = 'admin' and capability.status = 'active'
  ) then
    raise exception 'Active Learning Admin required for transfer evidence' using errcode = '42501';
  end if;

  -- A provider-success record cannot exceed the funds already reserved for
  -- this exact company sale. The purchase lock serializes concurrent inserts.
  select coalesce(sum(movement.amount_minor),0) into reserved_total
  from public.learning_company_seller_liability_movements movement
  where movement.purchase_id = new.purchase_id and movement.movement_kind = 'reserved';
  select coalesce(sum(evidence.amount_minor),0) into transferred_total
  from public.learning_company_seller_transfer_evidence evidence
  where evidence.purchase_id = new.purchase_id;
  if new.amount_minor > reserved_total - transferred_total then
    raise exception 'Company seller transfer exceeds reserved balance' using errcode = '23514';
  end if;

  -- Any reversal notice requires a fresh human review before an outflow is
  -- recorded. This remains conservative until manual resolution is modeled.
  if exists(select 1 from public.learning_company_reversal_event_inbox notice
    where notice.purchase_id = new.purchase_id) then
    raise exception 'Company reversal notice requires manual review before transfer' using errcode = '22023';
  end if;
  return new;
end;$function$;

create trigger validate_learning_company_seller_transfer_evidence
before insert on public.learning_company_seller_transfer_evidence
for each row execute function public.validate_learning_company_seller_transfer_evidence();

create function public.reconcile_learning_company_seller_transfers()
returns table(purchase_id bigint,issue_type text)
language sql stable security definer set search_path to '' as $function$
  select boundary.purchase_id,'company_seller_transfer_boundary_without_evidence'::text
  from public.learning_company_seller_outflow_boundaries boundary
  where boundary.boundary_kind = 'transferred'
    and not exists(select 1 from public.learning_company_seller_transfer_evidence evidence
      where evidence.boundary_id = boundary.id)
  union all
  select sale.purchase_id,'company_seller_transfer_exceeds_reserved_balance'::text
  from public.learning_company_commercial_sales sale
  where coalesce((select sum(evidence.amount_minor)
      from public.learning_company_seller_transfer_evidence evidence
      where evidence.purchase_id = sale.purchase_id),0)
    > coalesce((select sum(movement.amount_minor)
      from public.learning_company_seller_liability_movements movement
      where movement.purchase_id = sale.purchase_id and movement.movement_kind = 'reserved'),0)
  union all
  select evidence.purchase_id,'company_seller_transfer_identity_mismatch'::text
  from public.learning_company_seller_transfer_evidence evidence
  join public.learning_company_seller_outflow_boundaries boundary on boundary.id = evidence.boundary_id
  join public.learning_company_commercial_sales sale on sale.purchase_id = evidence.purchase_id
  join public.learning_instructor_payout_profiles payout_profile on payout_profile.id = evidence.payout_profile_id
  where boundary.purchase_id <> evidence.purchase_id
    or boundary.seller_payee_id <> evidence.seller_payee_id
    or boundary.boundary_kind <> 'transferred'
    or boundary.amount_minor <> evidence.amount_minor
    or boundary.movement_reference <> evidence.provider_reference
    or sale.seller_payee_id <> evidence.seller_payee_id
    or sale.paystack_domain <> 'live'
    or payout_profile.instructor_id <> evidence.seller_payee_id
    or payout_profile.provider_domain <> 'live'
    or payout_profile.recipient_code <> evidence.recipient_code
  union all
  select evidence.purchase_id,'company_seller_transfer_reversal_review_required'::text
  from public.learning_company_seller_transfer_evidence evidence
  where exists(select 1 from public.learning_company_reversal_event_inbox notice
    where notice.purchase_id = evidence.purchase_id);
$function$;

revoke all on function public.validate_learning_company_seller_transfer_evidence()
  from public,anon,authenticated,service_role;
revoke all on function public.reconcile_learning_company_seller_transfers()
  from public,anon,authenticated,service_role;
grant execute on function public.reconcile_learning_company_seller_transfers()
  to postgres,service_role;

commit;
