-- Phase 2A: durable delivery state for instructor and organization notifications.
begin;

create table public.learning_instructor_notifications (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique check (char_length(idempotency_key) between 8 and 240),
  notification_type text not null check (notification_type in ('organization_invitation','organization_invitation_accepted','instructor_application_approved')),
  organization_invitation_id bigint references public.learning_provider_organization_invitations(id) on delete restrict,
  instructor_user_id uuid references public.profiles(id) on delete restrict,
  recipient_email text not null check (char_length(recipient_email) between 3 and 320),
  delivery_status text not null default 'pending' check (delivery_status in ('pending','sent','failed','not_configured')),
  provider_message_id text,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error text check (last_error is null or char_length(last_error) <= 1000),
  created_at timestamptz not null default now(),
  last_attempted_at timestamptz,
  sent_at timestamptz
);
create index learning_instructor_notifications_status_idx on public.learning_instructor_notifications(delivery_status, created_at);

alter table public.learning_instructor_notifications enable row level security;
revoke all on public.learning_instructor_notifications from public, anon, authenticated;
grant select, insert, update on public.learning_instructor_notifications to postgres, service_role;
grant usage, select on sequence public.learning_instructor_notifications_id_seq to postgres, service_role;

commit;
