-- Phase 3C2: provider-neutral company checkout lifecycle and paid access boundary.
-- A browser can prepare a purchase, but only a trusted payment finalizer can
-- mark it paid and grant employee access. Paystack is deliberately not called
-- here; live checkout remains disabled until its approval is available.
begin;

create table public.learning_company_paid_course_purchase_attempts (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.learning_company_paid_course_purchases(id) on delete restrict,
  provider text not null check (provider in ('paystack')),
  provider_reference text not null unique check (provider_reference ~ '^CP-[A-F0-9]{32}$'),
  provider_transaction_id text,
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null check (currency = 'NGN'),
  status text not null default 'initialized' check (status in ('initialized','pending','succeeded','failed','abandoned')),
  failure_code text,
  failure_message text,
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  completed_at timestamptz,
  failed_at timestamptz,
  constraint learning_company_paid_attempt_lifecycle_check check (
    (status = 'initialized' and submitted_at is null and completed_at is null and failed_at is null)
    or (status = 'pending' and submitted_at is not null and completed_at is null and failed_at is null)
    or (status = 'succeeded' and completed_at is not null and failed_at is null)
    or (status in ('failed','abandoned') and failed_at is not null and completed_at is null)
  )
);

create unique index learning_company_paid_attempt_one_open_per_purchase
  on public.learning_company_paid_course_purchase_attempts(purchase_id)
  where status in ('initialized','pending');
create index learning_company_paid_attempt_purchase_idx
  on public.learning_company_paid_course_purchase_attempts(purchase_id, created_at desc, id desc);

alter table public.learning_company_paid_course_purchase_attempts enable row level security;
revoke all on public.learning_company_paid_course_purchase_attempts from public, anon, authenticated;
grant select, insert, update, delete on public.learning_company_paid_course_purchase_attempts to postgres, service_role;
grant usage, select on sequence public.learning_company_paid_course_purchase_attempts_id_seq to postgres, service_role;

create or replace function public.start_learning_company_paid_course_checkout(p_purchase_id bigint)
returns table(purchase_id bigint,attempt_id bigint,provider_reference text,amount_minor bigint,currency text,status text)
language plpgsql security definer set search_path to '' as $function$
declare purchase_row public.learning_company_paid_course_purchases%rowtype; attempt_row public.learning_company_paid_course_purchase_attempts%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if p_purchase_id is null then raise exception 'Invalid company purchase' using errcode = '22023'; end if;
  select * into purchase_row from public.learning_company_paid_course_purchases purchase where purchase.id = p_purchase_id for update;
  if not found then raise exception 'Company purchase was not found' using errcode = '22023'; end if;
  if not exists(
    select 1 from public.learning_company_workspaces workspace
    join public.learning_company_memberships manager on manager.workspace_id = workspace.id
    where workspace.id = purchase_row.workspace_id and workspace.status = 'active'
      and manager.user_id = auth.uid() and manager.status = 'active' and manager.role in ('owner','admin')
  ) then raise exception 'Active company manager required' using errcode = '42501'; end if;
  if purchase_row.status = 'checkout_pending' then
    select * into attempt_row from public.learning_company_paid_course_purchase_attempts attempt
    where attempt.purchase_id = purchase_row.id and attempt.status in ('initialized','pending')
    order by attempt.id desc limit 1;
    if found then
      return query select purchase_row.id,attempt_row.id,attempt_row.provider_reference,attempt_row.amount_minor,attempt_row.currency,attempt_row.status;
      return;
    end if;
  end if;
  if purchase_row.status <> 'checkout_ready' then raise exception 'This company purchase cannot start checkout' using errcode = '22023'; end if;
  insert into public.learning_company_paid_course_purchase_attempts(purchase_id,provider,provider_reference,amount_minor,currency)
  values(purchase_row.id,'paystack','CP-' || upper(replace(gen_random_uuid()::text,'-','')),purchase_row.total_amount_minor,purchase_row.currency)
  returning * into attempt_row;
  update public.learning_company_paid_course_purchases
  set status = 'checkout_pending', checkout_started_at = now()
  where id = purchase_row.id;
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(auth.uid(),'company_manager','company_paid_course.checkout_started','learning_company_paid_course_purchase',purchase_row.id::text,
    jsonb_build_object('attempt_id',attempt_row.id,'provider',attempt_row.provider,'provider_reference',attempt_row.provider_reference,'amount_minor',attempt_row.amount_minor,'currency',attempt_row.currency));
  return query select purchase_row.id,attempt_row.id,attempt_row.provider_reference,attempt_row.amount_minor,attempt_row.currency,attempt_row.status;
end;$function$;

create or replace function public.grant_paid_learning_company_purchase_access(p_purchase_id bigint)
returns table(granted_seat_count integer)
language plpgsql security definer set search_path to '' as $function$
declare purchase_row public.learning_company_paid_course_purchases%rowtype; seat_row record; granted_count integer := 0;
begin
  if p_purchase_id is null then raise exception 'Invalid company purchase' using errcode = '22023'; end if;
  select * into purchase_row from public.learning_company_paid_course_purchases purchase where purchase.id = p_purchase_id and purchase.status = 'paid' for update;
  if not found then raise exception 'Paid company purchase required before granting access' using errcode = '22023'; end if;
  for seat_row in select seat.assigned_user_id from public.learning_company_paid_course_purchase_seats seat where seat.purchase_id = purchase_row.id loop
    perform pg_advisory_xact_lock(hashtextextended('learning-company-paid-access:' || purchase_row.workspace_id::text || ':' || purchase_row.course_id::text || ':' || seat_row.assigned_user_id::text, 0));
    insert into public.enrollments(learner_id,course_id,status)
    values(seat_row.assigned_user_id,purchase_row.course_id,'active')
    on conflict(learner_id,course_id) do update set status = 'active', completed_at = null
      where public.enrollments.status = 'cancelled';
    insert into public.learning_company_course_assignments(workspace_id,course_id,assigned_user_id,assigned_by)
    values(purchase_row.workspace_id,purchase_row.course_id,seat_row.assigned_user_id,purchase_row.requested_by)
    on conflict do nothing;
    granted_count := granted_count + 1;
  end loop;
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(purchase_row.requested_by,'payment_webhook','company_paid_course.access_granted','learning_company_paid_course_purchase',purchase_row.id::text,
    jsonb_build_object('workspace_id',purchase_row.workspace_id,'course_id',purchase_row.course_id,'seat_count',granted_count));
  return query select granted_count;
end;$function$;

create or replace function public.finalize_learning_company_paid_course_purchase(p_purchase_id bigint,p_provider_reference text,p_provider_transaction_id text default null)
returns table(purchase_id bigint,status text,granted_seat_count integer)
language plpgsql security definer set search_path to '' as $function$
declare purchase_row public.learning_company_paid_course_purchases%rowtype; attempt_row public.learning_company_paid_course_purchase_attempts%rowtype; granted_count integer;
begin
  if p_purchase_id is null or nullif(btrim(coalesce(p_provider_reference,'')),'') is null then raise exception 'Invalid payment finalization' using errcode = '22023'; end if;
  select purchase.* into purchase_row
  from public.learning_company_paid_course_purchases purchase where purchase.id = p_purchase_id for update;
  if not found then raise exception 'Company purchase was not found' using errcode = '22023'; end if;
  select * into attempt_row from public.learning_company_paid_course_purchase_attempts attempt
  where attempt.purchase_id = purchase_row.id and attempt.provider = 'paystack' and attempt.provider_reference = btrim(p_provider_reference) for update;
  if not found then raise exception 'Payment attempt was not found' using errcode = '22023'; end if;
  if purchase_row.status = 'paid' and attempt_row.status = 'succeeded' then
    return query select purchase_row.id,purchase_row.status,purchase_row.seat_count;
    return;
  end if;
  if purchase_row.status <> 'checkout_pending' or attempt_row.status not in ('initialized','pending') then raise exception 'This company payment cannot be finalized' using errcode = '22023'; end if;
  update public.learning_company_paid_course_purchases set status = 'paid', paid_at = now() where id = purchase_row.id;
  update public.learning_company_paid_course_purchase_attempts
  set status = 'succeeded', provider_transaction_id = nullif(btrim(coalesce(p_provider_transaction_id,'')),''), completed_at = now()
  where id = attempt_row.id;
  select grant_row.granted_seat_count into granted_count from public.grant_paid_learning_company_purchase_access(purchase_row.id) grant_row;
  return query select purchase_row.id,'paid'::text,coalesce(granted_count,0);
end;$function$;

revoke all on function public.start_learning_company_paid_course_checkout(bigint), public.grant_paid_learning_company_purchase_access(bigint), public.finalize_learning_company_paid_course_purchase(bigint,text,text) from public, anon, authenticated;
grant execute on function public.start_learning_company_paid_course_checkout(bigint) to authenticated, postgres, service_role;
grant execute on function public.grant_paid_learning_company_purchase_access(bigint), public.finalize_learning_company_paid_course_purchase(bigint,text,text) to postgres, service_role;

commit;
