-- Phase 1A test-fixture control: one paid course, one disposable learner, one expiry.
-- Forward-only and data-preserving. No fixture is created or activated by this migration.

create table public.learning_paystack_test_fixtures (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.learning_courses(id) on delete restrict,
  tester_id uuid not null references public.profiles(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'closed')),
  expires_at timestamptz not null,
  activated_at timestamptz not null default now(),
  activated_by uuid not null references public.profiles(id) on delete restrict,
  closed_at timestamptz,
  closed_by uuid references public.profiles(id) on delete restrict,
  close_reason text,
  constraint learning_paystack_test_fixtures_expiry_check check (expires_at > activated_at),
  constraint learning_paystack_test_fixtures_lifecycle_check check (
    (status = 'active' and closed_at is null and closed_by is null and close_reason is null)
    or (status = 'closed' and closed_at is not null and closed_by is not null and char_length(btrim(close_reason)) between 3 and 500)
  )
);

alter table public.learning_paystack_test_fixtures enable row level security;

create unique index learning_paystack_test_fixtures_one_active_key
  on public.learning_paystack_test_fixtures (status) where status = 'active';
create unique index learning_paystack_test_fixtures_course_key
  on public.learning_paystack_test_fixtures (course_id);
create index learning_paystack_test_fixtures_tester_idx
  on public.learning_paystack_test_fixtures (tester_id, expires_at desc);

revoke all on table public.learning_paystack_test_fixtures from public, anon, authenticated;
grant select, insert, update on table public.learning_paystack_test_fixtures to postgres, service_role;
revoke all on sequence public.learning_paystack_test_fixtures_id_seq from public, anon, authenticated;
grant usage, select on sequence public.learning_paystack_test_fixtures_id_seq to postgres, service_role;

create or replace function public.is_paystack_test_fixture_course(p_course_id bigint)
returns boolean language sql stable security definer set search_path to '' as $function$
  select exists(select 1 from public.learning_paystack_test_fixtures where course_id=p_course_id);
$function$;
revoke all on function public.is_paystack_test_fixture_course(bigint) from public;
grant execute on function public.is_paystack_test_fixture_course(bigint) to anon,authenticated,postgres,service_role;

create or replace function public.get_own_paystack_test_fixture_eligibility(p_course_id bigint)
returns table (eligible boolean, fixture_id bigint, expires_at timestamptz)
language sql stable security definer set search_path to '' as $function$
  select
    coalesce(bool_or(
      fixture.status = 'active'
      and fixture.expires_at > now()
      and fixture.tester_id = auth.uid()
      and course.status = 'published'
      and course.is_free = false
      and course.is_limited_time_free = false
      and course.price_amount > 0
      and course.price_currency = 'NGN'
    ), false),
    min(fixture.id) filter (where fixture.status = 'active' and fixture.expires_at > now() and fixture.tester_id = auth.uid()),
    min(fixture.expires_at) filter (where fixture.status = 'active' and fixture.expires_at > now() and fixture.tester_id = auth.uid())
  from public.learning_paystack_test_fixtures fixture
  join public.learning_courses course on course.id = fixture.course_id
  where fixture.course_id = p_course_id and auth.uid() is not null;
$function$;

revoke all on function public.get_own_paystack_test_fixture_eligibility(bigint) from public, anon;
grant execute on function public.get_own_paystack_test_fixture_eligibility(bigint) to authenticated, postgres, service_role;

create or replace function public.activate_paystack_test_fixture(
  p_course_id bigint,
  p_tester_id uuid,
  p_operator_id uuid,
  p_expires_at timestamptz,
  p_declaration_version text,
  p_rights_basis text
)
returns table (fixture_id bigint, course_id bigint, tester_id uuid, expires_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare
  course_row record;
  fixture_key bigint;
  normalized_basis text := lower(btrim(p_rights_basis));
begin
  if p_course_id is null or p_tester_id is null or p_operator_id is null or p_expires_at is null then
    raise exception 'Course, tester, operator, and expiry are required' using errcode = '22023';
  end if;
  if p_expires_at <= now() + interval '15 minutes' or p_expires_at > now() + interval '24 hours' then
    raise exception 'Fixture expiry must be between 15 minutes and 24 hours from now' using errcode = '22023';
  end if;
  if btrim(coalesce(p_declaration_version, '')) <> '2026-08-v1'
    or normalized_basis not in ('original', 'licensed', 'authorized') then
    raise exception 'A current course-rights declaration is required' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.account_capabilities capability
    where capability.user_id = p_operator_id and capability.capability = 'admin' and capability.status = 'active'
  ) then raise exception 'An active Growvelt Learning administrator is required' using errcode = '42501'; end if;
  if not exists (select 1 from public.profiles where id = p_tester_id) then
    raise exception 'Disposable learner profile was not found' using errcode = 'P0002';
  end if;
  if exists (
    select 1 from public.account_capabilities capability
    where capability.user_id = p_tester_id and capability.status = 'active' and capability.capability in ('admin', 'instructor')
  ) then raise exception 'Fixture tester must be a learner-only disposable account' using errcode = '22023'; end if;

  perform pg_advisory_xact_lock(hashtextextended('phase1a-test-fixture', 0));
  if exists (select 1 from public.learning_paystack_test_fixtures where status = 'active') then
    raise exception 'An active Paystack test fixture already exists' using errcode = '23505';
  end if;

  select course.* into course_row from public.learning_courses course
  where course.id = p_course_id and course.status = 'draft' for update;
  if not found then raise exception 'Paid test course must be an editable draft' using errcode = 'P0002'; end if;
  if course_row.slug !~ '^phase1a-paystack-test-[a-z0-9-]+$' or course_row.title !~ '^\[TEST\] ' then
    raise exception 'Fixture course must use the reserved test title and slug markers' using errcode = '22023';
  end if;
  if course_row.instructor_id is null or not exists (
    select 1 from public.account_capabilities capability
    where capability.user_id = course_row.instructor_id and capability.capability = 'instructor' and capability.status = 'active'
  ) then raise exception 'Fixture course must belong to an approved instructor' using errcode = '42501'; end if;
  if course_row.is_free or course_row.is_limited_time_free or course_row.price_amount is null
    or course_row.price_amount <= 0 or course_row.price_currency <> 'NGN' or scale(course_row.price_amount) > 2 then
    raise exception 'Fixture course must have an eligible paid NGN price' using errcode = '22023';
  end if;
  if char_length(btrim(course_row.title)) not between 3 and 160
    or char_length(btrim(course_row.summary)) not between 10 and 320
    or char_length(btrim(course_row.description)) not between 40 and 10000
    or course_row.category not in ('Data Analytics','Business','Data Science','Business Intelligence','Programming','Web Development','Cybersecurity','Digital Marketing','Creative Skills','Digital Skills','Productivity')
    or course_row.level not in ('Beginner','Intermediate','Beginner to intermediate','Beginner to job-ready') then
    raise exception 'Complete the required test-course metadata before activation' using errcode = '22023';
  end if;
  if not exists (select 1 from public.course_modules module where module.course_id = p_course_id)
    or not exists (select 1 from public.lessons lesson where lesson.course_id = p_course_id) then
    raise exception 'Add at least one module and one lesson before activation' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.course_modules module where module.course_id = p_course_id
      and char_length(btrim(module.title)) not between 2 and 160
  ) then raise exception 'Complete every module title before activation' using errcode = '22023'; end if;
  if exists (
    select 1 from public.lessons lesson
    left join public.course_modules module on module.id = lesson.module_id and module.course_id = lesson.course_id
    where lesson.course_id = p_course_id and (
      module.id is null or char_length(btrim(lesson.title)) not between 2 and 160
      or lesson.lesson_type not in ('video','text','quiz')
      or (lesson.lesson_type = 'video' and (lesson.content is not null or lesson.video_provider is distinct from 'youtube'
        or lesson.video_reference is null or lesson.video_reference !~ '^[A-Za-z0-9_-]{11}$'
        or lesson.video_visibility not in ('public','unlisted') or lesson.duration_seconds not between 1 and 86400
        or lesson.video_url is not null or lesson.duration_minutes is not null))
      or (lesson.lesson_type = 'text' and (lesson.content is null or char_length(btrim(lesson.content)) not between 1 and 20000
        or lesson.video_provider is not null or lesson.video_reference is not null or lesson.video_visibility is not null
        or lesson.duration_seconds is not null or lesson.video_url is not null or lesson.duration_minutes is not null))
    )
  ) then raise exception 'Complete every lesson before activation' using errcode = '22023'; end if;

  insert into public.course_rights_declarations(course_id, instructor_id, declaration_version, rights_basis)
  values (p_course_id, course_row.instructor_id, '2026-08-v1', normalized_basis);
  update public.learning_courses set status = 'published', submitted_at = now(), reviewed_at = now(), reviewed_by = p_operator_id,
    review_note = 'Phase 1A controlled Paystack test fixture', published_at = now(), updated_at = now()
  where id = p_course_id and status = 'draft';
  if not found then raise exception 'Test course changed during activation' using errcode = '40001'; end if;

  insert into public.learning_paystack_test_fixtures(course_id, tester_id, expires_at, activated_by)
  values (p_course_id, p_tester_id, p_expires_at, p_operator_id) returning id into fixture_key;
  insert into public.learning_audit_events(actor_user_id, actor_role, action, entity_type, entity_id, metadata)
  values (p_operator_id, 'admin_operator', 'paystack_test_fixture.activated', 'paystack_test_fixture', fixture_key::text,
    jsonb_build_object('course_id', p_course_id, 'tester_id', p_tester_id, 'expires_at', p_expires_at));
  return query select fixture_key, p_course_id, p_tester_id, p_expires_at;
end;$function$;

create or replace function public.close_paystack_test_fixture(p_fixture_id bigint, p_operator_id uuid, p_reason text)
returns table (fixture_id bigint, course_id bigint, status text, closed_at timestamptz)
language plpgsql security definer set search_path to '' as $function$
declare fixture_row record; closed_time timestamptz := now(); normalized_reason text := btrim(p_reason);
begin
  if p_fixture_id is null or p_operator_id is null or char_length(normalized_reason) not between 3 and 500 then
    raise exception 'Fixture, operator, and closure reason are required' using errcode = '22023';
  end if;
  if not exists (select 1 from public.account_capabilities capability where capability.user_id=p_operator_id and capability.capability='admin' and capability.status='active') then
    raise exception 'An active Growvelt Learning administrator is required' using errcode = '42501';
  end if;
  select fixture.* into fixture_row from public.learning_paystack_test_fixtures fixture where fixture.id=p_fixture_id and fixture.status='active' for update;
  if not found then raise exception 'Active test fixture was not found' using errcode = 'P0002'; end if;
  update public.learning_paystack_test_fixtures fixture set status='closed',closed_at=closed_time,closed_by=p_operator_id,close_reason=normalized_reason where fixture.id=p_fixture_id;
  update public.learning_courses course set status='archived',updated_at=closed_time where course.id=fixture_row.course_id and course.status='published';
  insert into public.learning_audit_events(actor_user_id,actor_role,action,entity_type,entity_id,metadata)
  values(p_operator_id,'admin_operator','paystack_test_fixture.closed','paystack_test_fixture',p_fixture_id::text,
    jsonb_build_object('course_id',fixture_row.course_id,'tester_id',fixture_row.tester_id,'reason',normalized_reason));
  return query select p_fixture_id,fixture_row.course_id,'closed'::text,closed_time;
end;$function$;

revoke all on function public.activate_paystack_test_fixture(bigint,uuid,uuid,timestamptz,text,text) from public,anon,authenticated;
revoke all on function public.close_paystack_test_fixture(bigint,uuid,text) from public,anon,authenticated;
grant execute on function public.activate_paystack_test_fixture(bigint,uuid,uuid,timestamptz,text,text) to postgres,service_role;
grant execute on function public.close_paystack_test_fixture(bigint,uuid,text) to postgres,service_role;

create or replace function public.initialize_paystack_test_learning_order(p_learner_id uuid, p_course_id bigint)
returns table (order_id bigint, order_reference text, payment_attempt_id bigint, amount_minor bigint, currency text)
language plpgsql security definer set search_path to '' as $function$
declare course_row record; order_key bigint; order_ref text; attempt_key bigint; amount_key bigint;
begin
  if p_learner_id is null or p_course_id is null then raise exception 'Learner and course are required' using errcode='22023'; end if;
  if not exists(select 1 from public.learning_paystack_test_fixtures fixture where fixture.course_id=p_course_id and fixture.tester_id=p_learner_id and fixture.status='active' and fixture.expires_at>now())
  then raise exception 'Learner is not eligible for this controlled test checkout' using errcode='42501'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_learner_id::text||':'||p_course_id::text,0));
  if not exists(select 1 from public.profiles where id=p_learner_id) then raise exception 'Learner profile was not found' using errcode='P0002'; end if;
  select c.id,c.instructor_id,c.title,c.price_amount,c.price_currency,c.is_free,c.is_limited_time_free,c.status,p.full_name instructor_name into course_row
  from public.learning_courses c left join public.profiles p on p.id=c.instructor_id where c.id=p_course_id;
  if not found or course_row.status<>'published' then raise exception 'Course is not available for purchase' using errcode='22023'; end if;
  if course_row.is_free or course_row.is_limited_time_free or course_row.price_amount is null or course_row.price_amount<=0 or course_row.price_currency<>'NGN' or scale(course_row.price_amount)>2
  then raise exception 'Course does not have an eligible paid NGN price' using errcode='22023'; end if;
  if exists(select 1 from public.enrollments where learner_id=p_learner_id and course_id=p_course_id and status in ('active','completed'))
    or exists(select 1 from public.learning_course_entitlements where learner_id=p_learner_id and course_id=p_course_id and status='active')
  then raise exception 'Learner already has course access' using errcode='23505'; end if;
  if exists(select 1 from public.learning_orders where learner_id=p_learner_id and course_id=p_course_id and status in ('created','payment_pending','paid','partially_refunded'))
  then raise exception 'A purchase already exists for this course' using errcode='23505'; end if;
  amount_key:=round(course_row.price_amount*100)::bigint;
  insert into public.learning_orders(learner_id,course_id,instructor_id,course_title_snapshot,instructor_name_snapshot,gross_amount_minor,currency,status,commercial_terms_version)
  values(p_learner_id,p_course_id,course_row.instructor_id,course_row.title,course_row.instructor_name,amount_key,'NGN','created','phase1a-test-v1')
  returning id,learning_orders.order_reference into order_key,order_ref;
  insert into public.learning_payment_attempts(order_id,provider,provider_reference,amount_minor,currency,status)
  values(order_key,'paystack',order_ref,amount_key,'NGN','initialized') returning id into attempt_key;
  return query select order_key,order_ref,attempt_key,amount_key,'NGN'::text;
end;$function$;

drop policy "Published courses are public" on public.learning_courses;
create policy "Published courses are public" on public.learning_courses for select to anon,authenticated
using (status='published' and not public.is_paystack_test_fixture_course(learning_courses.id));
drop policy "Published course modules are public" on public.course_modules;
create policy "Published course modules are public" on public.course_modules for select to anon,authenticated using (exists(
  select 1 from public.learning_courses course where course.id=course_modules.course_id and course.status='published'
    and not public.is_paystack_test_fixture_course(course.id)));
drop policy "Published course preview lessons are public" on public.lessons;
create policy "Published course preview lessons are public" on public.lessons for select to anon,authenticated using (is_preview=true and exists(
  select 1 from public.learning_courses course where course.id=lessons.course_id and course.status='published'
    and not public.is_paystack_test_fixture_course(course.id)));

create or replace function public.get_published_learning_course_by_slug(p_slug text)
returns table(course_id bigint,slug text,course_title text,summary text,description text,category text,level text,is_free boolean,price_amount numeric,price_currency text,instructor_name text,published_at timestamptz,module_id bigint,module_title text,module_position integer,lesson_id bigint,lesson_title text,lesson_type text,is_preview boolean,preview_text_content text,preview_video_provider text,preview_video_reference text,preview_video_visibility text,preview_duration_seconds integer,lesson_position integer)
language plpgsql stable security definer set search_path to '' as $function$
declare normalized_slug text:=lower(btrim(p_slug));
begin
  if normalized_slug is null or normalized_slug='' or char_length(normalized_slug)>220 then raise exception 'Invalid published course reference' using errcode='22023'; end if;
  return query select c.id,c.slug,c.title,c.summary,c.description,c.category,c.level,c.is_free,c.price_amount,c.price_currency,p.full_name,c.published_at,
    m.id,m.title,m.position,l.id,l.title,l.lesson_type,l.is_preview,case when l.is_preview then l.content end,case when l.is_preview then l.video_provider end,
    case when l.is_preview then l.video_reference end,case when l.is_preview then l.video_visibility end,case when l.is_preview then l.duration_seconds end,l.position
  from public.learning_courses c left join public.profiles p on p.id=c.instructor_id left join public.course_modules m on m.course_id=c.id
  left join public.lessons l on l.course_id=c.id and l.module_id=m.id
  where c.slug=normalized_slug and c.status='published' and (
    not exists(select 1 from public.learning_paystack_test_fixtures f where f.course_id=c.id)
    or exists(select 1 from public.learning_paystack_test_fixtures f where f.course_id=c.id and f.status='active' and f.expires_at>now() and f.tester_id=auth.uid()))
  order by m.position nulls last,m.id,l.position nulls last,l.id;
end;$function$;

create or replace function public.list_published_learning_courses(p_limit integer default 24,p_offset integer default 0)
returns table(course_id bigint,slug text,title text,summary text,category text,level text,is_free boolean,price_amount numeric,price_currency text,instructor_name text,published_at timestamptz)
language plpgsql stable security definer set search_path to '' as $function$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if p_limit not between 1 and 36 or p_offset<0 then raise exception 'Invalid published-course pagination' using errcode='22023'; end if;
  return query select c.id,c.slug,c.title,c.summary,c.category,c.level,c.is_free,c.price_amount,c.price_currency,p.full_name,c.published_at
  from public.learning_courses c left join public.profiles p on p.id=c.instructor_id
  where c.status='published' and not exists(select 1 from public.learning_paystack_test_fixtures f where f.course_id=c.id)
  order by c.published_at desc nulls last,c.id desc limit p_limit offset p_offset;
end;$function$;

create or replace function public.search_public_published_learning_courses(p_query text default null,p_category text default null,p_level text default null,p_is_free boolean default null,p_sort text default 'newest',p_limit integer default 12,p_offset integer default 0)
returns table(course_id bigint,slug text,title text,summary text,category text,level text,is_free boolean,price_amount numeric,price_currency text,instructor_name text,published_at timestamptz,total_courses integer)
language plpgsql stable security definer set search_path to '' as $function$
declare q text:=nullif(lower(btrim(p_query)),''); cat text:=nullif(lower(btrim(p_category)),''); lvl text:=nullif(lower(btrim(p_level)),''); sort_key text:=lower(btrim(coalesce(p_sort,'newest')));
begin
  if q is not null and char_length(q)>120 or cat is not null and char_length(cat)>100 or lvl is not null and char_length(lvl)>100 then raise exception 'Invalid catalog filter' using errcode='22023'; end if;
  if sort_key not in ('newest','title_asc','title_desc') or p_limit not between 1 and 24 or p_offset<0 then raise exception 'Invalid catalog pagination or sort' using errcode='22023'; end if;
  return query select c.id,c.slug,c.title,c.summary,c.category,c.level,c.is_free,c.price_amount,c.price_currency,p.full_name,c.published_at,count(*) over()::integer
  from public.learning_courses c left join public.profiles p on p.id=c.instructor_id
  where c.status='published' and not exists(select 1 from public.learning_paystack_test_fixtures f where f.course_id=c.id)
    and (q is null or position(q in lower(concat_ws(' ',c.title,c.summary,c.category,c.level)))>0)
    and (cat is null or lower(c.category)=cat) and (lvl is null or lower(c.level)=lvl) and (p_is_free is null or c.is_free=p_is_free)
  order by case when sort_key='title_asc' then lower(c.title) end asc nulls last,case when sort_key='title_desc' then lower(c.title) end desc nulls last,
    case when sort_key='newest' then c.published_at end desc nulls last,c.id desc limit p_limit offset p_offset;
end;$function$;
