import { CommercialReleaseControl } from "@/app/components/admin/commercial-release-control";
import { CommercialPayoutTransferControl } from "@/app/components/admin/commercial-payout-transfer-control";
import { listCommercialEarningsReleaseRuns, listCommercialOperations, listInstructorPayoutCandidates, listInstructorPayoutItems, listInstructorPayoutProfiles, listInstructorPayoutReconciliationFindings } from "@/app/lib/admin/commercial-operations";
import { createClient } from "@/app/lib/supabase/server";

export const metadata = { title: "Commercial earnings review" };
const money = (amountMinor: number, currency = "NGN") => new Intl.NumberFormat("en-NG", { style: "currency", currency, minimumFractionDigits: 2 }).format(amountMinor / 100);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-NG", { dateStyle: "medium" }).format(new Date(value)) : "—";

export default async function AdminCommercialPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;
  const [operations, releaseRuns, payoutProfiles, payoutCandidates, payoutItems, payoutFindings] = await Promise.all([listCommercialOperations(user.id), listCommercialEarningsReleaseRuns(user.id), listInstructorPayoutProfiles(user.id), listInstructorPayoutCandidates(user.id), listInstructorPayoutItems(user.id), listInstructorPayoutReconciliationFindings(user.id)]);
  const issues = operations.reduce((total, item) => total + item.reconciliation_issue_count, 0);
  return <section className="admin-page commercial-operations-page section-shell">
    <header className="admin-page-header admin-review-hero"><p className="eyebrow">Commercial operations</p><h1>Instructor earnings review</h1><p>Read-only visibility into authoritative commercial allocations and earnings. Payouts, transfers, and withholding deductions are not enabled.</p></header>
    <section className="commercial-operations-summary"><article><span>Commercial earnings</span><strong>{operations.length}</strong><small>Verified allocation records</small></article><article><span>Reconciliation findings</span><strong>{issues}</strong><small>From the authoritative commercial reconciliation</small></article></section>
    <CommercialReleaseControl />
    <section className="commercial-payout-profiles"><header><p className="eyebrow">Controlled Test payouts</p><h2>Approval and transfer intake</h2><p>Approval and Test transfer submission keep earnings reserved. A queued transfer is not a completed payout.</p></header>{payoutCandidates.length ? <div className="commercial-payout-profile-list">{payoutCandidates.map((item) => <article key={item.reservation_id}><div><strong>{item.instructor_name ?? "Instructor"}</strong><span>{item.reservation_reference}</span></div><div><span>{money(item.amount_minor, item.currency)} · Test recipient verified</span><span>{item.eligible ? "Eligible for approval" : "Financially protected"}</span></div>{item.eligible && <CommercialPayoutTransferControl reservationId={item.reservation_id} />}</article>)}</div> : <p className="admin-empty-copy">No reserved earnings are eligible for Test payout approval.</p>}</section>
    <section className="commercial-payout-profiles"><header><p className="eyebrow">Payout item history</p><h2>Provider transfer status</h2></header>{payoutItems.length ? <div className="commercial-payout-profile-list">{payoutItems.map((item) => <article key={item.payout_item_id}><div><strong>{item.instructor_name ?? "Instructor"}</strong><span>{item.payout_item_reference}</span></div><div><span>{money(item.amount_minor, item.currency)} · TEST · {item.status}</span><span>{item.provider_transfer_code ?? item.provider_status ?? "Not submitted"}</span></div><CommercialPayoutTransferControl payoutItemId={item.payout_item_id} canSubmit={item.status === "approved"} canRecover={item.status === "recovery_required" || item.status === "submitting" || item.status === "pending"} /></article>)}</div> : <p className="admin-empty-copy">No payout items have been approved.</p>}</section>
    <section className="commercial-payout-profiles"><header><p className="eyebrow">Payout reconciliation</p><h2>Provider outcomes requiring attention</h2><p>These are operational findings, not a new payout request or settlement control.</p></header>{payoutFindings.length ? <div className="commercial-payout-profile-list">{payoutFindings.map((finding) => <article key={finding.finding_id}><div><strong>{finding.finding_type.replaceAll("_", " ")}</strong><span>{finding.payout_item_reference ?? "Unmatched provider event"}</span></div><div><span className={`admin-status is-${finding.status}`}>{finding.status}</span><span>{date(finding.created_at)}</span></div><p>{finding.detail}</p>{finding.status === "open" && finding.provider_event_id ? <CommercialPayoutTransferControl providerEventId={finding.provider_event_id} /> : null}</article>)}</div> : <p className="admin-empty-copy">No payout reconciliation findings.</p>}</section>
    <section className="commercial-payout-profiles"><header><p className="eyebrow">Payout profile review</p><h2>Recipient readiness</h2><p>Read-only Test-mode recipient metadata. No payout, reservation, or transfer is available.</p></header>{payoutProfiles.length ? <div className="commercial-payout-profile-list">{payoutProfiles.map((profile) => <article key={profile.payout_profile_id}><div><strong>{profile.instructor_name ?? "Instructor"}</strong><span>{profile.instructor_email ?? "Email unavailable"}</span></div><div><span>{profile.bank_name} · account ending in {profile.account_last4}</span><span>{profile.provider_domain.toUpperCase()} · {profile.status}</span></div><code>{profile.recipient_code}</code></article>)}</div> : <p className="admin-empty-copy">No instructor payout profiles exist.</p>}</section>
    <section className="commercial-release-runs"><header><p className="eyebrow">Operational audit</p><h2>Recent matured-earnings release runs</h2></header>{releaseRuns.length ? <ul>{releaseRuns.map((run) => <li key={run.run_id}><span className={`admin-status is-${run.status}`}>{run.status}</span><span>{run.invocation_source === "scheduler" ? "Daily scheduler" : "Administrator recovery"}</span><span>{run.released_count} released</span><time dateTime={run.started_at}>{date(run.completed_at ?? run.started_at)}</time></li>)}</ul> : <p>No release operation has run yet.</p>}</section>
    {operations.length ? <div className="commercial-operations-list">{operations.map((item) => <article key={item.earning_id}>
      <div className="commercial-operation-heading"><div><p className={`admin-status is-${item.earning_status}`}>{item.earning_status} · {item.allocation_status}</p><h2>{item.course_title}</h2><p>{item.instructor_name ?? "Instructor"} · {item.instructor_email ?? "Email unavailable"}</p><code>{item.order_reference}</code></div><strong>{money(item.instructor_gross_minor, item.currency)}</strong></div>
      <dl><div><dt>Gross sale</dt><dd>{money(item.gross_amount_minor, item.currency)}</dd></div><div><dt>Growvelt share</dt><dd>{money(item.platform_commission_minor, item.currency)}</dd></div><div><dt>Instructor share</dt><dd>{money(item.instructor_gross_minor, item.currency)}</dd></div><div><dt>Available from</dt><dd>{date(item.available_at)}</dd></div><div><dt>Released</dt><dd>{date(item.released_at)}</dd></div><div><dt>Terms</dt><dd>{item.commercial_terms_version}</dd></div></dl>
      <div className="commercial-operation-foot"><span>Recoverable: {money(item.recoverable_amount_minor, item.currency)}</span><span>Reversal case: {item.reversal_case_id ?? "—"}</span><span>{item.reconciliation_issue_count} reconciliation issue{item.reconciliation_issue_count === 1 ? "" : "s"}</span></div>
      {item.reconciliation_details.length ? <ul className="commercial-operation-issues">{item.reconciliation_details.map((detail) => <li key={detail}>{detail}</li>)}</ul> : null}
    </article>)}</div> : <section className="admin-empty-state"><p className="eyebrow">No commercial earnings</p><h2>No allocations exist yet.</h2><p>Phase 1C1 intentionally did not backfill historical orders. Future verified paid sales will appear here after commercial allocation.</p></section>}
  </section>;
}
