import Link from "next/link";
import { OperationsSearchControls } from "@/app/components/operations-search-controls";
import { SearchHighlight } from "@/app/components/search-highlight";
import { searchPendingInstructorApplications } from "@/app/lib/admin/instructor-applications";
import { normalizeOperationsQuery, operationsHref } from "@/app/lib/operations-query";

export const metadata = { title: "Instructor reviews" };

export default async function DashboardAdminInstructorQueuePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = normalizeOperationsQuery(await searchParams);
  const { applications, total, page, pageSize } = await searchPendingInstructorApplications(query.query, query.page);
  const lastPage = Math.max(1, Math.ceil(total / pageSize));
  return <section className="admin-page admin-instructor-review-queue section-shell"><header className="admin-page-header admin-review-hero"><p className="eyebrow">Admin Reviews</p><h1>Instructor reviews</h1><p>Review teaching applications and grant Instructor capability only through the protected database decision.</p><div className="admin-review-summary"><span><strong>{total}</strong> awaiting review</span><span>Page {page} of {lastPage}</span></div></header>
    <OperationsSearchControls basePath="/dashboard/admin/instructors" query={query} fields={[{ name: "query", label: "Search applications", placeholder: "Name, email, headline, country, or expertise" }]} />
    {applications.length ? <><div className="admin-application-list admin-course-review-list">{applications.map((application) => <article className="admin-application-row admin-course-review-row" key={application.user_id}><div><p className="admin-status">Pending review</p><h2><SearchHighlight text={application.full_name || application.headline || "Instructor application"} query={query.query} /></h2><p className="admin-course-instructor"><SearchHighlight text={application.headline || "Professional headline not supplied"} query={query.query} /></p><div className="admin-course-meta"><span><SearchHighlight text={application.country || "Country not supplied"} query={query.query} /></span>{application.expertise?.filter(Boolean).slice(0, 4).map((expertise) => <span key={expertise}><SearchHighlight text={expertise} query={query.query} /></span>)}</div></div><div className="admin-row-meta"><time dateTime={application.created_at}>Submitted {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(application.created_at))}</time><Link className="button button-secondary" href={`/dashboard/admin/instructors/${application.user_id}`}>Review application <span aria-hidden="true">→</span><span className="sr-only"> from {application.full_name || application.headline || "this applicant"}</span></Link></div></article>)}</div><nav className="operations-pagination" aria-label="Instructor review pages">{page > 1 && <Link className="button button-secondary" href={operationsHref("/dashboard/admin/instructors", query, { page: page - 1 })}>Previous</Link>}{page < lastPage && <Link className="button button-secondary" href={operationsHref("/dashboard/admin/instructors", query, { page: page + 1 })}>Next</Link>}</nav><div className="results-end-marker admin-review-end-marker">{page === lastPage ? "End of Instructor Reviews" : `Showing ${applications.length} of ${total} applications`}</div></> : <section className="admin-empty-state admin-course-review-empty"><p className="eyebrow">{query.query ? "No matching applications" : "All caught up"}</p><h2>{query.query ? "Try a different search." : "No pending Instructor applications."}</h2><p>{query.query ? "Clear your search to return to the full pending application queue." : "New applications will appear here when submitted."}</p>{query.query ? <Link className="button button-secondary" href="/dashboard/admin/instructors">Clear search</Link> : null}</section>}</section>;
}
