import type { Metadata } from "next";
import { LegalPage } from "@/app/components/legal-page";

export const metadata: Metadata = { title: "Terms of Service", description: "Growvelt Terms of Service for learning, careers, courses, certificates, and related services." };

const sections = [
  { heading: "1. Acceptance of these terms", paragraphs: ["By visiting Growvelt, creating an account, enrolling in a course, posting or applying for a job, purchasing an upgrade, or using a Growvelt service, you agree to these Terms of Service and our Privacy Policy.", "If you do not agree, please do not use our websites, courses, job platform, payment features, or communication tools."] },
  { heading: "2. About Growvelt", paragraphs: ["Growvelt Technologies Limited provides technology training, career resources, job discovery tools, employer services, course delivery, certificates, email updates, and related digital services through Growvelt websites and subdomains.", "The Growvelt jobs platform is available at www.growvelt.com. Growvelt Learning provides course and training experiences through this website."] },
  { heading: "3. Eligibility and accounts", paragraphs: ["You must provide accurate information when creating an account, applying for jobs, posting jobs, registering for courses, or contacting support. You are responsible for safeguarding your login details and for activity under your account.", "Growvelt may suspend, restrict, or remove accounts that appear fraudulent, abusive, misleading, automated, unsafe, or otherwise in breach of these terms."] },
  { heading: "4. Jobs and employer services", paragraphs: ["Job seekers may discover jobs, save jobs, create alerts, apply for roles, track applications, receive updates, and use available career tools. Applying does not guarantee an interview, response, offer, visa sponsorship, salary, or employment outcome.", "Employers must provide accurate, lawful, non-discriminatory information. Growvelt may review, approve, reject, edit, remove, or suspend employer accounts and job posts to protect users and maintain platform quality."] },
  { heading: "5. Courses, learning, and certificates", paragraphs: ["Course information, schedules, prices, instructors, materials, and availability may change as Growvelt improves training quality and reflects current industry practice.", "Certificates are issued only from an eligible completed course record. A course, certificate, mentoring session, or training participation does not guarantee a job, promotion, income, immigration outcome, or external professional certification unless expressly stated."] },
  { heading: "6. Career Assistant and automated tools", paragraphs: ["Career Assistant and automated tools provide decision-support guidance. Outputs may contain errors, omissions, or unsuitable recommendations and are not legal advice, professional certification, a guarantee of employment, or a substitute for qualified human judgment.", "Users must review outputs before relying on, publishing, or sharing them. Employers must have an appropriate right or lawful basis to submit candidate information and must not use automated output as the sole basis for a hiring decision."] },
  { heading: "7. Payments, third parties, and external links", paragraphs: ["Growvelt may offer paid services or upgrades. Prices, currencies, benefits, and availability may change. Payments may be processed by third-party providers under their own terms.", "Growvelt may link to partner jobs and other third-party websites. We do not control their hiring decisions, forms, cookies, privacy policies, payment requests, or communications. Review external services carefully before submitting information."] },
  { heading: "8. User content and prohibited conduct", paragraphs: ["You are responsible for information and materials you submit, including profiles, applications, job posts, messages, files, media, reviews, and course content. You must have the right to share them."], bullets: ["Do not post fake jobs, misleading company information, or scam opportunities.", "Do not collect personal data for unlawful or unrelated purposes.", "Do not bypass verification, payment, security, or access controls.", "Do not upload malware, spam, phishing links, harmful code, or privacy-invasive content.", "Do not harass users, applicants, employers, instructors, or support staff."] },
  { heading: "9. Intellectual property and disclaimers", paragraphs: ["Growvelt names, logos, designs, course materials, platform content, templates, text, graphics, and software belong to Growvelt or its licensors. You may not copy, reproduce, distribute, or modify them without written permission except where law permits.", "Services are provided on an as-available basis. To the fullest extent permitted by law, Growvelt Technologies Limited is not liable for indirect, incidental, special, consequential, or punitive damages, including lost opportunities, lost profits, lost data, employment outcomes, or issues caused by third parties."] },
  { heading: "10. Changes, governing law, and contact", paragraphs: ["We may update services, features, pricing, policies, and these terms. Where appropriate, we may give notice through the website, email, or account notifications. Continued use means you accept the updated terms.", "These terms are governed by applicable laws of the Federal Republic of Nigeria. For questions or a practical resolution, Contact us."] },
];

export default function TermsOfServicePage() { return <LegalPage title="Terms of Service" summary="The rules for using Growvelt Learning, careers, courses, certificates, and related services." updated="July 24, 2026" sections={sections} />; }
