create table "public"."certificates" (
  "id"               bigint                   generated by default as identity not null,
  "learner_id"       uuid                     not null,
  "course_id"        bigint                   not null,
  "certificate_code" text                     not null,
  "issued_at"        timestamp with time zone not null default now(),
  "certificate_url"  text,
  "learner_name"     text                     not null,
  "course_title"     text                     not null,
  "instructor_name"  text,
  "completed_at"     timestamp with time zone not null,
  "status"           text                     not null default 'issued'::text,
  "revoked_at"       timestamp with time zone,
  constraint "certificates_certificate_code_key" unique (certificate_code),
  constraint "certificates_learner_id_course_id_key" unique (learner_id, course_id),
  constraint "certificates_pkey" primary key (id),
  constraint "certificates_revocation_check" check ((((status = 'issued'::text) AND (revoked_at IS NULL)) OR ((status = 'revoked'::text) AND (revoked_at IS NOT NULL)))),
  constraint "certificates_status_check" check ((status = ANY (ARRAY['issued'::text, 'revoked'::text]))),
  constraint "certificates_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete cascade,
  constraint "certificates_learner_id_fkey" foreign key (learner_id) references public.profiles(id) on delete cascade
);

alter table "public"."certificates"
  enable row level security;

create policy "Learners can read own certificates" on "public"."certificates"
  for select
  to "authenticated"
  using ((auth.uid() = learner_id));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."certificates" to "postgres", "service_role";

revoke all on table "public"."certificates" from "anon";

grant maintain on table "public"."certificates" to "anon";

revoke all on table "public"."certificates" from "authenticated";

grant maintain on table "public"."certificates" to "authenticated";
