create table "public"."certificates" (
  "id"                 bigint                   generated by default as identity not null,
  "learner_id"         uuid,
  "course_id"          bigint                   not null,
  "certificate_code"   text                     not null,
  "issued_at"          timestamp with time zone not null default now(),
  "certificate_url"    text,
  "learner_name"       text,
  "course_title"       text                     not null,
  "instructor_name"    text,
  "completed_at"       timestamp with time zone not null,
  "status"             text                     not null default 'issued'::text,
  "revoked_at"         timestamp with time zone,
  "retention_state"    text                     not null default 'account_active'::text,
  "account_deleted_at" timestamp with time zone,
  constraint "certificates_certificate_code_key" unique (certificate_code),
  constraint "certificates_learner_id_course_id_key" unique (learner_id, course_id),
  constraint "certificates_pkey" primary key (id),
  constraint "certificates_retention_lifecycle_check" check ((((retention_state = 'account_active'::text) AND (learner_id IS
    NOT NULL) AND (account_deleted_at IS NULL)) OR ((retention_state = 'preserved_after_account_deletion'::text) AND (learner_id IS NULL) AND (learner_name IS
    NOT NULL) AND (account_deleted_at IS
    NOT NULL)) OR ((retention_state = 'anonymized_after_account_deletion'::text) AND (learner_id IS NULL) AND (learner_name IS NULL) AND (account_deleted_at IS
    NOT NULL) AND (status = 'revoked'::text)))),
  constraint "certificates_retention_state_check"
    check ((retention_state = ANY (ARRAY['account_active'::text, 'preserved_after_account_deletion'::text, 'anonymized_after_account_deletion'::text]))),
  constraint "certificates_revocation_check" check ((((status = 'issued'::text) AND (revoked_at IS NULL)) OR ((status = 'revoked'::text) AND (revoked_at IS NOT NULL)))),
  constraint "certificates_status_check" check ((status = ANY (ARRAY['issued'::text, 'revoked'::text]))),
  constraint "certificates_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete cascade,
  constraint "certificates_learner_id_fkey" foreign key (learner_id) references public.profiles(id) on delete set null
);

alter table "public"."certificates"
  enable row level security;

create trigger audit_learning_certificate_issue
  after insert on public.certificates
  for each row
  execute function public.capture_learning_security_audit_event('certificate.issued', 'certificate');

create trigger audit_learning_certificate_status
  after update of status on public.certificates
  for each row
  when ((old.status IS DISTINCT FROM new.status))
  execute function public.capture_learning_security_audit_event('certificate.status_changed', 'certificate');

create policy "Learners can read own certificates" on "public"."certificates"
  for select
  to "authenticated"
  using ((auth.uid() = learner_id));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."certificates" to "postgres", "service_role";
