create table "public"."course_modules" (
  "id"         bigint                   generated by default as identity not null,
  "course_id"  bigint                   not null,
  "title"      text                     not null,
  "position"   integer                  not null default 0,
  "created_at" timestamp with time zone not null default now(),
  constraint "course_modules_pkey" primary key (id),
  constraint "course_modules_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete cascade
);

alter table "public"."course_modules"
  enable row level security;

create unique index course_modules_course_position_key on public.course_modules using btree (course_id, "position");

create unique index course_modules_id_course_id_key on public.course_modules using btree (id, course_id);

create policy "Published course modules are public" on "public"."course_modules"
  for select
  to "anon", "authenticated"
  using ((exists ( select 1
   from public.learning_courses
  where ((learning_courses.id = course_modules.course_id) AND (learning_courses.status = 'published'::text)))));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."course_modules" to "postgres", "service_role";

revoke all on table "public"."course_modules" from "anon";

grant maintain, references, select, trigger, truncate on table "public"."course_modules" to "anon";

revoke all on table "public"."course_modules" from "authenticated";

grant maintain, references, select, trigger, truncate on table "public"."course_modules" to "authenticated";
