create table "public"."course_rights_declarations" (
  "id"                  bigint                   generated by default as identity not null,
  "course_id"           bigint                   not null,
  "instructor_id"       uuid                     not null,
  "declaration_version" text                     not null,
  "rights_basis"        text                     not null,
  "accepted_at"         timestamp with time zone not null default now(),
  constraint "course_rights_declarations_declaration_version_check" check ((declaration_version = '2026-08-v1'::text)),
  constraint "course_rights_declarations_pkey" primary key (id),
  constraint "course_rights_declarations_rights_basis_check" check ((rights_basis = ANY (ARRAY['original'::text, 'licensed'::text, 'authorized'::text]))),
  constraint "course_rights_declarations_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete restrict,
  constraint "course_rights_declarations_instructor_id_fkey" foreign key (instructor_id) references public.profiles(id) on delete restrict
);

alter table "public"."course_rights_declarations"
  enable row level security;

create index course_rights_declarations_course_accepted_idx on public.course_rights_declarations using btree (course_id, accepted_at desc);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."course_rights_declarations" to "postgres", "service_role";
