create table "public"."course_leads" (
  "id"          bigint                   generated by default as identity not null,
  "payload"     jsonb                    not null default '{}'::jsonb,
  "source_page" text,
  "created_at"  timestamp with time zone not null default now(),
  constraint "course_leads_pkey" primary key (id)
);

alter table "public"."course_leads"
  enable row level security;

create policy "Allow public course lead submissions" on "public"."course_leads"
  for insert
  to "anon"
  with check (true);

grant insert on table "public"."course_leads" to "anon", "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."course_leads" to "postgres", "service_role";
