create table "public"."course_registrations" (
  "id"                      bigint                   generated by default as identity not null,
  "full_name"               text                     not null,
  "email"                   text                     not null,
  "phone"                   text,
  "course"                  text                     not null,
  "learning_mode"           text,
  "experience_level"        text,
  "message"                 text,
  "payment_status"          text                     not null default 'pending'::text,
  "source_page"             text,
  "created_at"              timestamp with time zone not null default now(),
  "payment_amount"          numeric(10,2),
  "payment_currency"        text,
  "paypal_order_id"         text,
  "paypal_capture_id"       text,
  "payer_email"             text,
  "paid_at"                 timestamp with time zone,
  "email_sent_at"           timestamp with time zone,
  "admin_notified_at"       timestamp with time zone,
  "registration_ref"        text,
  "paystack_reference"      text,
  "paystack_access_code"    text,
  "paystack_transaction_id" text,
  constraint "course_registrations_pkey" primary key (id),
  constraint "course_registrations_registration_ref_key" unique (registration_ref)
);

alter table "public"."course_registrations"
  enable row level security;

create unique index course_registrations_paystack_reference_key on public.course_registrations using btree (paystack_reference);

create policy "Admins can read course registrations" on "public"."course_registrations"
  for select
  to "authenticated"
  using (public.is_growvelt_learning_admin());

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."course_registrations" to "postgres", "service_role";
