create table "public"."course_contacts" (
  "id"          bigint                   generated by default as identity not null,
  "name"        text,
  "email"       text                     not null,
  "phone"       text,
  "type"        text,
  "message"     text,
  "source_page" text,
  "created_at"  timestamp with time zone not null default now(),
  constraint "course_contacts_pkey" primary key (id)
);

alter table "public"."course_contacts"
  enable row level security;

create policy "Allow public course contact submissions" on "public"."course_contacts"
  for insert
  to "anon"
  with check (true);

grant insert on table "public"."course_contacts" to "anon", "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."course_contacts" to "postgres", "service_role";
