create table "public"."enrollments" (
  "id"           bigint                   generated by default as identity not null,
  "learner_id"   uuid                     not null,
  "course_id"    bigint                   not null,
  "status"       text                     not null default 'active'::text,
  "enrolled_at"  timestamp with time zone not null default now(),
  "completed_at" timestamp with time zone,
  constraint "enrollments_learner_id_course_id_key" unique (learner_id, course_id),
  constraint "enrollments_pkey" primary key (id),
  constraint "enrollments_status_check" check ((status = ANY (ARRAY['active'::text, 'completed'::text, 'cancelled'::text]))),
  constraint "enrollments_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete cascade,
  constraint "enrollments_learner_id_fkey" foreign key (learner_id) references public.profiles(id) on delete cascade
);

alter table "public"."enrollments"
  enable row level security;

create unique index enrollments_id_learner_course_id_key on public.enrollments using btree (id, learner_id, course_id);

create trigger delete_learning_quiz_attempts_with_enrollment
  before delete on public.enrollments
  for each row
  execute function public.delete_learning_quiz_attempts_with_enrollment();

create policy "Learners can read own enrollments" on "public"."enrollments"
  for select
  to "authenticated"
  using ((auth.uid() = learner_id));

grant select on table "public"."enrollments" to "anon", "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."enrollments" to "postgres", "service_role";
