create table "public"."instructor_profiles" (
  "id"                  bigint                   generated by default as identity not null,
  "user_id"             uuid                     not null,
  "headline"            text,
  "bio"                 text,
  "expertise"           text[],
  "approval_status"     text                     not null default 'pending'::text,
  "reviewed_at"         timestamp with time zone,
  "created_at"          timestamp with time zone not null default now(),
  "updated_at"          timestamp with time zone not null default now(),
  "reviewed_by"         uuid,
  "review_note"         text,
  "country"             text,
  "phone"               text,
  "years_experience"    smallint,
  "teaching_experience" text,
  "motivation"          text,
  "portfolio_url"       text,
  constraint "instructor_profiles_approval_status_check" check ((approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))),
  constraint "instructor_profiles_country_length_check" check (((country IS NULL) OR ((char_length(btrim(country)) >= 2) AND (char_length(btrim(country)) <= 100)))),
  constraint "instructor_profiles_motivation_length_check" check (((motivation IS NULL) OR (char_length(motivation) <= 1500))),
  constraint "instructor_profiles_phone_length_check" check (((phone IS NULL) OR ((char_length(btrim(phone)) >= 3) AND (char_length(btrim(phone)) <= 32)))),
  constraint "instructor_profiles_pkey" primary key (id),
  constraint "instructor_profiles_portfolio_url_check"
    check (((portfolio_url IS NULL) OR ((char_length(portfolio_url) <= 500) AND (portfolio_url ~ '^https?://[^[:space:]]+$'::text)))),
  constraint "instructor_profiles_review_note_length_check" check (((review_note IS NULL) OR (char_length(review_note) <= 2000))),
  constraint "instructor_profiles_teaching_experience_length_check" check (((teaching_experience IS NULL) OR (char_length(teaching_experience) <= 1500))),
  constraint "instructor_profiles_user_id_key" unique (user_id),
  constraint "instructor_profiles_years_experience_check" check (((years_experience IS NULL) OR ((years_experience >= 0) AND (years_experience <= 60)))),
  constraint "instructor_profiles_reviewed_by_fkey" foreign key (reviewed_by) references public.profiles(id) on delete set null,
  constraint "instructor_profiles_user_id_fkey" foreign key (user_id) references public.profiles(id) on delete cascade
);

alter table "public"."instructor_profiles"
  enable row level security;

create policy "Admins can read instructor applications" on "public"."instructor_profiles"
  for select
  to "authenticated"
  using (public.is_growvelt_learning_admin());

create policy "Instructor profiles are created by owner" on "public"."instructor_profiles"
  for insert
  to "authenticated"
  with check (((auth.uid() = user_id) AND (approval_status = 'pending'::text) AND (reviewed_at IS NULL) AND (country IS
    NOT NULL) AND ((char_length(btrim(country)) >= 2) AND (char_length(btrim(country)) <= 100)) AND (headline IS
    NOT NULL) AND ((char_length(btrim(headline)) >= 2) AND (char_length(btrim(headline)) <= 160)) AND
    ((COALESCE(array_length(expertise, 1), 0) >= 1) AND (COALESCE(array_length(expertise, 1), 0) <= 12)) AND ((years_experience >= 0) AND (years_experience <= 60)) AND
    (teaching_experience IS NOT NULL) AND ((char_length(btrim(teaching_experience)) >= 2) AND (char_length(btrim(teaching_experience)) <= 1500)) AND (bio IS
    NOT NULL) AND ((char_length(btrim(bio)) >= 2) AND (char_length(btrim(bio)) <= 2000)) AND (motivation IS
    NOT NULL) AND ((char_length(btrim(motivation)) >= 2) AND (char_length(btrim(motivation)) <= 1500))));

create policy "Instructor profiles are readable by owner" on "public"."instructor_profiles"
  for select
  to "authenticated"
  using ((auth.uid() = user_id));

create policy "Instructor profiles are updated by owner while pending" on "public"."instructor_profiles"
  for update
  to "authenticated"
  using (((auth.uid() = user_id) AND (approval_status = 'pending'::text)))
  with check (((auth.uid() = user_id) AND (approval_status = 'pending'::text) AND (reviewed_at IS NULL) AND (country IS
    NOT NULL) AND ((char_length(btrim(country)) >= 2) AND (char_length(btrim(country)) <= 100)) AND (headline IS
    NOT NULL) AND ((char_length(btrim(headline)) >= 2) AND (char_length(btrim(headline)) <= 160)) AND
    ((COALESCE(array_length(expertise, 1), 0) >= 1) AND (COALESCE(array_length(expertise, 1), 0) <= 12)) AND ((years_experience >= 0) AND (years_experience <= 60)) AND
    (teaching_experience IS NOT NULL) AND ((char_length(btrim(teaching_experience)) >= 2) AND (char_length(btrim(teaching_experience)) <= 1500)) AND (bio IS
    NOT NULL) AND ((char_length(btrim(bio)) >= 2) AND (char_length(btrim(bio)) <= 2000)) AND (motivation IS
    NOT NULL) AND ((char_length(btrim(motivation)) >= 2) AND (char_length(btrim(motivation)) <= 1500))));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."instructor_profiles" to "postgres", "service_role";

revoke all on table "public"."instructor_profiles" from "anon";

grant maintain, references, trigger on table "public"."instructor_profiles" to "anon";

revoke all ("approval_status") on table "public"."instructor_profiles" from "authenticated";

grant select ("approval_status") on table "public"."instructor_profiles" to "authenticated";

revoke all ("bio") on table "public"."instructor_profiles" from "authenticated";

grant insert ("bio"), select ("bio"), update ("bio") on table "public"."instructor_profiles" to "authenticated";

revoke all ("country") on table "public"."instructor_profiles" from "authenticated";

grant insert ("country"), select ("country"), update ("country") on table "public"."instructor_profiles" to "authenticated";

revoke all ("created_at") on table "public"."instructor_profiles" from "authenticated";

grant select ("created_at") on table "public"."instructor_profiles" to "authenticated";

revoke all ("expertise") on table "public"."instructor_profiles" from "authenticated";

grant insert ("expertise"), select ("expertise"), update ("expertise") on table "public"."instructor_profiles" to "authenticated";

revoke all ("headline") on table "public"."instructor_profiles" from "authenticated";

grant insert ("headline"), select ("headline"), update ("headline") on table "public"."instructor_profiles" to "authenticated";

revoke all ("id") on table "public"."instructor_profiles" from "authenticated";

grant select ("id") on table "public"."instructor_profiles" to "authenticated";

revoke all ("motivation") on table "public"."instructor_profiles" from "authenticated";

grant insert ("motivation"), select ("motivation"), update ("motivation") on table "public"."instructor_profiles" to "authenticated";

revoke all ("phone") on table "public"."instructor_profiles" from "authenticated";

grant insert ("phone"), select ("phone"), update ("phone") on table "public"."instructor_profiles" to "authenticated";

revoke all ("portfolio_url") on table "public"."instructor_profiles" from "authenticated";

grant insert ("portfolio_url"), select ("portfolio_url"), update ("portfolio_url") on table "public"."instructor_profiles" to "authenticated";

revoke all ("reviewed_at") on table "public"."instructor_profiles" from "authenticated";

grant select ("reviewed_at") on table "public"."instructor_profiles" to "authenticated";

revoke all ("teaching_experience") on table "public"."instructor_profiles" from "authenticated";

grant insert ("teaching_experience"), select ("teaching_experience"), update ("teaching_experience") on table "public"."instructor_profiles" to "authenticated";

revoke all ("updated_at") on table "public"."instructor_profiles" from "authenticated";

grant select ("updated_at") on table "public"."instructor_profiles" to "authenticated";

revoke all ("user_id") on table "public"."instructor_profiles" from "authenticated";

grant insert ("user_id"), select ("user_id") on table "public"."instructor_profiles" to "authenticated";

revoke all ("years_experience") on table "public"."instructor_profiles" from "authenticated";

grant insert ("years_experience"), select ("years_experience"), update ("years_experience") on table "public"."instructor_profiles" to "authenticated";

revoke all on table "public"."instructor_profiles" from "authenticated";

grant maintain, references, trigger on table "public"."instructor_profiles" to "authenticated";
