create table "public"."learning_payment_cases" (
  "id" bigint generated by default as identity not null,
  "case_reference" uuid not null default gen_random_uuid(),
  "order_id" bigint not null,
  "payment_attempt_id" bigint,
  "case_type" text not null,
  "status" text not null default 'opened'::text,
  "amount_minor" bigint not null,
  "currency" text not null,
  "reason" text,
  "provider_case_reference" text,
  "initiated_by" uuid,
  "opened_at" timestamptz not null default now(),
  "resolved_at" timestamptz,
  constraint "learning_payment_cases_pkey" primary key (id),
  constraint "learning_payment_cases_case_reference_key" unique (case_reference),
  constraint "learning_payment_cases_provider_reference_key" unique (case_type, provider_case_reference),
  constraint "learning_payment_cases_order_id_fkey" foreign key (order_id) references public.learning_orders(id) on delete restrict,
  constraint "learning_payment_cases_payment_attempt_id_fkey" foreign key (payment_attempt_id) references public.learning_payment_attempts(id) on delete restrict,
  constraint "learning_payment_cases_initiated_by_fkey" foreign key (initiated_by) references public.profiles(id) on delete set null,
  constraint "learning_payment_cases_type_check" check (case_type = any (array['refund'::text, 'chargeback'::text])),
  constraint "learning_payment_cases_status_check" check (status = any (array['opened'::text, 'pending'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text, 'won'::text, 'lost'::text])),
  constraint "learning_payment_cases_amount_check" check (amount_minor > 0),
  constraint "learning_payment_cases_currency_check" check (currency = 'NGN'::text),
  constraint "learning_payment_cases_reason_length_check" check (reason is null or char_length(reason) <= 2000),
  constraint "learning_payment_cases_resolution_check" check (((status = any (array['opened'::text, 'pending'::text])) and resolved_at is null) or ((status = any (array['succeeded'::text, 'failed'::text, 'cancelled'::text, 'won'::text, 'lost'::text])) and resolved_at is not null))
);
alter table "public"."learning_payment_cases" enable row level security;
create index learning_payment_cases_order_idx on public.learning_payment_cases using btree (order_id, opened_at desc, id desc);
create index learning_payment_cases_status_idx on public.learning_payment_cases using btree (status, opened_at, id);
create trigger prevent_learning_payment_case_delete before delete on public.learning_payment_cases for each row execute function public.prevent_learning_financial_record_delete();
create trigger validate_learning_payment_case before insert or update of order_id, payment_attempt_id, amount_minor, currency on public.learning_payment_cases for each row execute function public.validate_learning_payment_case();
create trigger audit_learning_payment_case_insert after insert on public.learning_payment_cases for each row execute function public.capture_learning_financial_audit_event('payment_case.created', 'payment_case');
create trigger audit_learning_payment_case_status after update of status on public.learning_payment_cases for each row when (old.status is distinct from new.status) execute function public.capture_learning_financial_audit_event('payment_case.status_changed', 'payment_case');
grant delete, insert, select, update on table "public"."learning_payment_cases" to "postgres", "service_role";
