create table "public"."learning_payment_cases" (
  "id"                      bigint                   generated by default as identity not null,
  "case_reference"          uuid                     not null default gen_random_uuid(),
  "order_id"                bigint                   not null,
  "payment_attempt_id"      bigint,
  "case_type"               text                     not null,
  "status"                  text                     not null default 'opened'::text,
  "amount_minor"            bigint                   not null,
  "currency"                text                     not null,
  "reason"                  text,
  "provider_case_reference" text,
  "initiated_by"            uuid,
  "opened_at"               timestamp with time zone not null default now(),
  "resolved_at"             timestamp with time zone,
  "provider"                text                     not null default 'paystack'::text,
  "idempotency_key"         uuid,
  "provider_status"         text,
  "provider_case_id"        text,
  "provider_transaction_id" text,
  "requested_amount_minor"  bigint,
  "processed_amount_minor"  bigint,
  "reason_code"             text,
  "operator_note"           text,
  "requested_at"            timestamp with time zone,
  "provider_submitted_at"   timestamp with time zone,
  "last_verified_at"        timestamp with time zone,
  "action_required_at"      timestamp with time zone,
  "processed_at"            timestamp with time zone,
  "failed_at"               timestamp with time zone,
  "failure_code"            text,
  "failure_message"         text,
  "updated_at"              timestamp with time zone not null default now(),
  "dispute_category"        text,
  "dispute_reason"          text,
  "response_deadline_at"    timestamp with time zone,
  "provider_resolution"     text,
  "reminded_at"             timestamp with time zone,
  "provider_resolved_at"    timestamp with time zone,
  constraint "learning_payment_cases_amount_minor_check" check ((amount_minor > 0)),
  constraint "learning_payment_cases_case_reference_key" unique (case_reference),
  constraint "learning_payment_cases_case_type_check" check ((case_type = ANY (ARRAY['refund'::text, 'chargeback'::text]))),
  constraint "learning_payment_cases_currency_check" check ((currency = 'NGN'::text)),
  constraint "learning_payment_cases_dispute_fields_check" check (((case_type <> 'chargeback'::text) OR ((provider_case_id IS NOT NULL) AND (requested_amount_minor IS NULL)))),
  constraint "learning_payment_cases_dispute_text_check"
    check
    ((((dispute_category IS NULL) OR (char_length(dispute_category) <= 120)) AND ((dispute_reason IS NULL) OR (char_length(dispute_reason) <= 1000)) AND ((provider_resolution IS
    NULL) OR (char_length(provider_resolution) <= 120)))),
  constraint "learning_payment_cases_failure_check" check (((failure_message IS NULL) OR (char_length(failure_message) <= 2000))),
  constraint "learning_payment_cases_operator_note_check" check (((operator_note IS NULL) OR ((char_length(operator_note) >= 3) AND (char_length(operator_note) <= 2000)))),
  constraint "learning_payment_cases_order_id_fkey" foreign key (order_id) references public.learning_orders(id) on delete restrict,
  constraint "learning_payment_cases_payment_attempt_id_fkey" foreign key (payment_attempt_id) references public.learning_payment_attempts(id) on delete restrict,
  constraint "learning_payment_cases_pkey" primary key (id),
  constraint "learning_payment_cases_provider_check" check ((provider = 'paystack'::text)),
  constraint "learning_payment_cases_provider_reference_key" unique (case_type, provider_case_reference),
  constraint "learning_payment_cases_provider_status_check"
    check
    (((provider_status IS NULL) OR (provider_status = ANY (ARRAY['requested'::text, 'pending'::text, 'processing'::text, 'needs-attention'::text, 'failed'::text, 'processed'::text,
    'cancelled'::text, 'awaiting-merchant-feedback'::text, 'awaiting-bank-feedback'::text, 'resolved'::text, 'archived'::text])))),
  constraint "learning_payment_cases_reason_code_check" check (((reason_code IS NULL) OR (reason_code ~ '^[a-z][a-z0-9_]{1,60}$'::text))),
  constraint "learning_payment_cases_reason_length_check" check (((reason IS NULL) OR (char_length(reason) <= 2000))),
  constraint "learning_payment_cases_refund_amount_check"
    check (((case_type <> 'refund'::text) OR ((requested_amount_minor = amount_minor) AND ((processed_amount_minor IS NULL) OR (processed_amount_minor = amount_minor))))),
  constraint "learning_payment_cases_status_check"
    check
    ((status = ANY (ARRAY['opened'::text, 'requested'::text, 'submitting'::text, 'pending'::text, 'processing'::text, 'needs_attention'::text, 'processed'::text, 'succeeded'::text,
    'failed'::text, 'cancelled'::text, 'action_required'::text, 'submitted'::text, 'under_review'::text, 'won'::text, 'lost'::text]))),
  constraint "learning_payment_cases_initiated_by_fkey" foreign key (initiated_by) references public.profiles(id) on delete set null
);

alter table "public"."learning_payment_cases"
  enable row level security;

create unique index learning_payment_cases_idempotency_key on public.learning_payment_cases using btree (idempotency_key)
  where (idempotency_key is not null);

create unique index learning_payment_cases_one_open_dispute on public.learning_payment_cases using btree (order_id)
  where ((case_type = 'chargeback'::text) AND (status = ANY (ARRAY['opened'::text, 'action_required'::text, 'submitted'::text, 'under_review'::text])));

create unique index learning_payment_cases_one_open_full_refund on public.learning_payment_cases using btree (order_id)
  where ((case_type = 'refund'::text) AND (status = ANY (ARRAY['requested'::text, 'submitting'::text, 'pending'::text, 'processing'::text, 'needs_attention'::text])));

create index learning_payment_cases_order_idx on public.learning_payment_cases using btree (order_id, opened_at desc, id desc);

create unique index learning_payment_cases_provider_case_id_key on public.learning_payment_cases using btree (provider, provider_case_id)
  where (provider_case_id is not null);

create index learning_payment_cases_status_idx on public.learning_payment_cases using btree (status, opened_at, id);

create trigger audit_learning_payment_case_insert
  after insert on public.learning_payment_cases
  for each row
  execute function public.capture_learning_financial_audit_event('payment_case.created', 'payment_case');

create trigger audit_learning_payment_case_status
  after update of status on public.learning_payment_cases
  for each row
  when ((old.status IS DISTINCT FROM new.status))
  execute function public.capture_learning_financial_audit_event('payment_case.status_changed', 'payment_case');

create trigger prevent_learning_payment_case_delete
  before delete on public.learning_payment_cases
  for each row
  execute function public.prevent_learning_financial_record_delete();

create trigger protect_learning_payment_case_identity
  before update on public.learning_payment_cases
  for each row
  execute function public.prevent_learning_payment_case_identity_change();

create trigger validate_learning_payment_case
  before insert or update of order_id, payment_attempt_id, amount_minor, currency on public.learning_payment_cases
  for each row
  execute function public.validate_learning_payment_case();

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_payment_cases" to "postgres", "service_role";
