create table "public"."learning_public_inquiries" (
  "id"           bigint                   generated by default as identity not null,
  "inquiry_type" text                     not null,
  "full_name"    text                     not null,
  "email"        text                     not null,
  "subject"      text                     not null,
  "message"      text                     not null,
  "organization" text,
  "phone"        text,
  "source_page"  text                     not null default 'learn.growvelt.com'::text,
  "created_at"   timestamp with time zone not null default now(),
  constraint "learning_public_inquiries_email_check" check (((char_length(email) >= 3) AND (char_length(email) <= 254))),
  constraint "learning_public_inquiries_full_name_check" check (((char_length(full_name) >= 2) AND (char_length(full_name) <= 160))),
  constraint "learning_public_inquiries_inquiry_type_check" check ((inquiry_type = ANY (ARRAY['contact'::text, 'partnership'::text]))),
  constraint "learning_public_inquiries_message_check" check (((char_length(message) >= 20) AND (char_length(message) <= 5000))),
  constraint "learning_public_inquiries_organization_check" check (((organization IS NULL) OR ((char_length(organization) >= 2) AND (char_length(organization) <= 160)))),
  constraint "learning_public_inquiries_phone_check" check (((phone IS NULL) OR ((char_length(phone) >= 3) AND (char_length(phone) <= 32)))),
  constraint "learning_public_inquiries_pkey" primary key (id),
  constraint "learning_public_inquiries_subject_check" check (((char_length(subject) >= 2) AND (char_length(subject) <= 160)))
);

alter table "public"."learning_public_inquiries"
  enable row level security;

create index learning_public_inquiries_type_created_at_idx on public.learning_public_inquiries using btree (inquiry_type, created_at desc, id desc);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_public_inquiries" to "postgres", "service_role";
