create table "public"."learning_payment_notifications" (
  "id"                  bigint                   generated by default as identity not null,
  "idempotency_key"     text                     not null,
  "notification_type"   text                     not null,
  "order_id"            bigint,
  "payment_case_id"     bigint,
  "recipient_email"     text                     not null,
  "delivery_status"     text                     not null default 'pending'::text,
  "provider_message_id" text,
  "attempt_count"       integer                  not null default 0,
  "last_error"          text,
  "created_at"          timestamp with time zone not null default now(),
  "last_attempted_at"   timestamp with time zone,
  "sent_at"             timestamp with time zone,
  constraint "learning_payment_notifications_attempt_count_check" check ((attempt_count >= 0)),
  constraint "learning_payment_notifications_delivery_status_check" check ((delivery_status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text]))),
  constraint "learning_payment_notifications_idempotency_key_check" check (((char_length(idempotency_key) >= 8) AND (char_length(idempotency_key) <= 240))),
  constraint "learning_payment_notifications_idempotency_key_key" unique (idempotency_key),
  constraint "learning_payment_notifications_last_error_check" check (((last_error IS NULL) OR (char_length(last_error) <= 1000))),
  constraint "learning_payment_notifications_notification_type_check"
    check
    ((notification_type = ANY (ARRAY['payment_access_ready'::text, 'payment_attention'::text, 'refund_requested'::text, 'refund_processed'::text, 'refund_attention'::text,
    'access_revoked'::text, 'operator_dispute'::text, 'operator_reconciliation'::text]))),
  constraint "learning_payment_notifications_order_id_fkey" foreign key (order_id) references public.learning_orders(id) on delete restrict,
  constraint "learning_payment_notifications_payment_case_id_fkey" foreign key (payment_case_id) references public.learning_payment_cases(id) on delete restrict,
  constraint "learning_payment_notifications_pkey" primary key (id),
  constraint "learning_payment_notifications_recipient_email_check" check (((char_length(recipient_email) >= 3) AND (char_length(recipient_email) <= 320)))
);

alter table "public"."learning_payment_notifications"
  enable row level security;

create index learning_payment_notifications_status_idx on public.learning_payment_notifications using btree (delivery_status, created_at);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_payment_notifications" to "postgres", "service_role";
