create table "public"."learning_payment_case_events" (
  "id"                bigint                   generated by default as identity not null,
  "payment_case_id"   bigint                   not null,
  "event_type"        text                     not null,
  "normalized_status" text                     not null,
  "provenance"        text                     not null,
  "provider_event_id" bigint,
  "operator_id"       uuid,
  "note"              text,
  "metadata"          jsonb                    not null default '{}'::jsonb,
  "created_at"        timestamp with time zone not null default now(),
  constraint "learning_payment_case_events_event_type_check" check ((event_type ~ '^[a-z][a-z0-9_.]{2,100}$'::text)),
  constraint "learning_payment_case_events_metadata_check" check ((jsonb_typeof(metadata) = 'object'::text)),
  constraint "learning_payment_case_events_note_check" check (((note IS NULL) OR (char_length(note) <= 2000))),
  constraint "learning_payment_case_events_pkey" primary key (id),
  constraint "learning_payment_case_events_provenance_check" check ((provenance = ANY (ARRAY['operator'::text, 'webhook'::text, 'provider_api'::text, 'system'::text]))),
  constraint "learning_payment_case_events_payment_case_id_fkey" foreign key (payment_case_id) references public.learning_payment_cases(id) on delete restrict,
  constraint "learning_payment_case_events_provider_event_id_fkey" foreign key (provider_event_id) references public.learning_payment_provider_events(id) on delete restrict,
  constraint "learning_payment_case_events_operator_id_fkey" foreign key (operator_id) references public.profiles(id) on delete set null
);

alter table "public"."learning_payment_case_events"
  enable row level security;

create index learning_payment_case_events_case_idx on public.learning_payment_case_events using btree (payment_case_id, created_at, id);

create trigger learning_payment_case_events_immutable
  before delete or update on public.learning_payment_case_events
  for each row
  execute function public.prevent_learning_ledger_mutation();

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_payment_case_events" to "postgres", "service_role";
