create table "public"."learning_payment_attempts" (
  "id" bigint generated by default as identity not null,
  "order_id" bigint not null,
  "idempotency_key" uuid not null default gen_random_uuid(),
  "provider" text not null,
  "provider_reference" text,
  "amount_minor" bigint not null,
  "currency" text not null,
  "status" text not null default 'initialized'::text,
  "initialized_at" timestamptz not null default now(),
  "verified_at" timestamptz,
  "failed_at" timestamptz,
  "failure_code" text,
  "failure_message" text,
  constraint "learning_payment_attempts_pkey" primary key (id),
  constraint "learning_payment_attempts_idempotency_key_key" unique (idempotency_key),
  constraint "learning_payment_attempts_provider_reference_key" unique (provider, provider_reference),
  constraint "learning_payment_attempts_order_id_fkey" foreign key (order_id) references public.learning_orders(id) on delete restrict,
  constraint "learning_payment_attempts_provider_check" check (provider ~ '^[a-z][a-z0-9_]{1,30}$'::text),
  constraint "learning_payment_attempts_amount_check" check (amount_minor > 0),
  constraint "learning_payment_attempts_currency_check" check (currency = 'NGN'::text),
  constraint "learning_payment_attempts_status_check" check (status = any (array['initialized'::text, 'pending'::text, 'succeeded'::text, 'failed'::text, 'abandoned'::text])),
  constraint "learning_payment_attempts_failure_message_length_check" check (failure_message is null or char_length(failure_message) <= 1000),
  constraint "learning_payment_attempts_status_timestamp_check" check ((status = 'succeeded'::text and verified_at is not null and failed_at is null) or (status = 'failed'::text and failed_at is not null and verified_at is null) or (status = any (array['initialized'::text, 'pending'::text, 'abandoned'::text])) and verified_at is null and failed_at is null)
);
alter table "public"."learning_payment_attempts" enable row level security;
create index learning_payment_attempts_order_idx on public.learning_payment_attempts using btree (order_id, initialized_at desc, id desc);
create index learning_payment_attempts_status_idx on public.learning_payment_attempts using btree (status, initialized_at desc, id desc);
create trigger validate_learning_payment_attempt before insert or update of order_id, amount_minor, currency on public.learning_payment_attempts for each row execute function public.validate_learning_payment_attempt();
create trigger prevent_learning_payment_attempt_delete before delete on public.learning_payment_attempts for each row execute function public.prevent_learning_financial_record_delete();
grant delete, insert, select, update on table "public"."learning_payment_attempts" to "postgres", "service_role";
