create table "public"."learning_orders" (
  "id" bigint generated by default as identity not null,
  "order_reference" text not null default ('GL-'::text || upper(replace(gen_random_uuid()::text, '-'::text, ''::text))),
  "learner_id" uuid,
  "course_id" bigint,
  "instructor_id" uuid,
  "learner_reference" uuid not null default gen_random_uuid(),
  "course_title_snapshot" text not null,
  "instructor_name_snapshot" text,
  "gross_amount_minor" bigint not null,
  "currency" text not null,
  "status" text not null default 'created'::text,
  "commercial_terms_version" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "paid_at" timestamptz,
  "cancelled_at" timestamptz,
  constraint "learning_orders_pkey" primary key (id),
  constraint "learning_orders_order_reference_key" unique (order_reference),
  constraint "learning_orders_reference_format_check" check (order_reference ~ '^GL-[A-F0-9]{32}$'::text),
  constraint "learning_orders_amount_check" check (gross_amount_minor > 0),
  constraint "learning_orders_currency_check" check (currency = 'NGN'::text),
  constraint "learning_orders_status_check" check (status = any (array['created'::text, 'payment_pending'::text, 'paid'::text, 'cancelled'::text, 'partially_refunded'::text, 'refunded'::text, 'chargeback'::text])),
  constraint "learning_orders_status_timestamp_check" check (((status = any (array['paid'::text, 'partially_refunded'::text, 'refunded'::text, 'chargeback'::text])) and paid_at is not null and cancelled_at is null) or (status = 'cancelled'::text and cancelled_at is not null and paid_at is null) or (status = any (array['created'::text, 'payment_pending'::text])) and paid_at is null and cancelled_at is null),
  constraint "learning_orders_learner_id_fkey" foreign key (learner_id) references public.profiles(id) on delete set null,
  constraint "learning_orders_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete set null,
  constraint "learning_orders_instructor_id_fkey" foreign key (instructor_id) references public.profiles(id) on delete set null
);
alter table "public"."learning_orders" enable row level security;
create index learning_orders_learner_created_idx on public.learning_orders using btree (learner_id, created_at desc, id desc);
create index learning_orders_course_created_idx on public.learning_orders using btree (course_id, created_at desc, id desc);
create index learning_orders_status_created_idx on public.learning_orders using btree (status, created_at desc, id desc);
create trigger protect_learning_order_financial_snapshot before update on public.learning_orders for each row execute function public.protect_learning_order_financial_snapshot();
create trigger prevent_learning_order_delete before delete on public.learning_orders for each row execute function public.prevent_learning_financial_record_delete();
create trigger audit_learning_order_insert after insert on public.learning_orders for each row execute function public.capture_learning_financial_audit_event('order.created', 'learning_order');
create trigger audit_learning_order_status after update of status on public.learning_orders for each row when (old.status is distinct from new.status) execute function public.capture_learning_financial_audit_event('order.status_changed', 'learning_order');
grant delete, insert, select, update on table "public"."learning_orders" to "postgres", "service_role";
