create table "public"."learning_courses" (
  "id"                              bigint                   generated by default as identity not null,
  "instructor_id"                   uuid,
  "title"                           text                     not null,
  "slug"                            text                     not null,
  "summary"                         text,
  "description"                     text,
  "level"                           text,
  "category"                        text,
  "thumbnail_url"                   text,
  "price_amount"                    numeric(10,2),
  "price_currency"                  text                     default 'NGN'::text,
  "is_free"                         boolean                  not null default false,
  "is_limited_time_free"            boolean                  not null default false,
  "status"                          text                     not null default 'draft'::text,
  "published_at"                    timestamp with time zone,
  "created_at"                      timestamp with time zone not null default now(),
  "updated_at"                      timestamp with time zone not null default now(),
  "submitted_at"                    timestamp with time zone,
  "reviewed_at"                     timestamp with time zone,
  "reviewed_by"                     uuid,
  "review_note"                     text,
  "course_video_cover_storage_path" text,
  constraint "learning_courses_course_video_cover_storage_path_check"
    check
    (((course_video_cover_storage_path IS NULL) OR (course_video_cover_storage_path ~
    '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[1-9][0-9]*/course-video-cover$'::text))),
  constraint "learning_courses_pkey" primary key (id),
  constraint "learning_courses_review_note_length_check" check (((review_note IS NULL) OR (char_length(review_note) <= 2000))),
  constraint "learning_courses_slug_key" unique (slug),
  constraint "learning_courses_status_check" check ((status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'published'::text, 'archived'::text]))),
  constraint "learning_courses_instructor_id_fkey" foreign key (instructor_id) references public.profiles(id) on delete set null,
  constraint "learning_courses_reviewed_by_fkey" foreign key (reviewed_by) references public.profiles(id) on delete set null
);

alter table "public"."learning_courses"
  enable row level security;

create index learning_courses_instructor_updated_at_idx on public.learning_courses using btree (instructor_id, updated_at desc);

create trigger audit_learning_course_status
  after update of status on public.learning_courses
  for each row
  when ((old.status IS DISTINCT FROM new.status))
  execute function public.capture_learning_security_audit_event('course.status_changed', 'learning_course');

create trigger learning_courses_quiz_readiness_before_submit
  before update of status on public.learning_courses
  for each row
  execute function public.validate_learning_course_quiz_readiness();

create policy "Published courses are public" on "public"."learning_courses"
  for select
  to "anon", "authenticated"
  using (((status = 'published'::text) AND (not public.is_paystack_test_fixture_course(id))));

grant select ("category") on table "public"."learning_courses" to "anon";

grant select ("created_at") on table "public"."learning_courses" to "anon";

grant select ("description") on table "public"."learning_courses" to "anon";

grant select ("id") on table "public"."learning_courses" to "anon";

grant select ("instructor_id") on table "public"."learning_courses" to "anon";

grant select ("is_free") on table "public"."learning_courses" to "anon";

grant select ("is_limited_time_free") on table "public"."learning_courses" to "anon";

grant select ("level") on table "public"."learning_courses" to "anon";

grant select ("price_amount") on table "public"."learning_courses" to "anon";

grant select ("price_currency") on table "public"."learning_courses" to "anon";

grant select ("published_at") on table "public"."learning_courses" to "anon";

grant select ("reviewed_at") on table "public"."learning_courses" to "anon";

grant select ("slug") on table "public"."learning_courses" to "anon";

grant select ("status") on table "public"."learning_courses" to "anon";

grant select ("submitted_at") on table "public"."learning_courses" to "anon";

grant select ("summary") on table "public"."learning_courses" to "anon";

grant select ("thumbnail_url") on table "public"."learning_courses" to "anon";

grant select ("title") on table "public"."learning_courses" to "anon";

grant select ("updated_at") on table "public"."learning_courses" to "anon";

grant select ("category") on table "public"."learning_courses" to "authenticated";

grant select ("created_at") on table "public"."learning_courses" to "authenticated";

grant select ("description") on table "public"."learning_courses" to "authenticated";

grant select ("id") on table "public"."learning_courses" to "authenticated";

grant select ("instructor_id") on table "public"."learning_courses" to "authenticated";

grant select ("is_free") on table "public"."learning_courses" to "authenticated";

grant select ("is_limited_time_free") on table "public"."learning_courses" to "authenticated";

grant select ("level") on table "public"."learning_courses" to "authenticated";

grant select ("price_amount") on table "public"."learning_courses" to "authenticated";

grant select ("price_currency") on table "public"."learning_courses" to "authenticated";

grant select ("published_at") on table "public"."learning_courses" to "authenticated";

grant select ("reviewed_at") on table "public"."learning_courses" to "authenticated";

grant select ("slug") on table "public"."learning_courses" to "authenticated";

grant select ("status") on table "public"."learning_courses" to "authenticated";

grant select ("submitted_at") on table "public"."learning_courses" to "authenticated";

grant select ("summary") on table "public"."learning_courses" to "authenticated";

grant select ("thumbnail_url") on table "public"."learning_courses" to "authenticated";

grant select ("title") on table "public"."learning_courses" to "authenticated";

grant select ("updated_at") on table "public"."learning_courses" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_courses" to "postgres", "service_role";
