create table "public"."learning_ledger_transactions" (
  "id"                    bigint                   generated by default as identity not null,
  "transaction_reference" uuid                     not null default gen_random_uuid(),
  "order_id"              bigint                   not null,
  "transaction_type"      text                     not null,
  "currency"              text                     not null,
  "occurred_at"           timestamp with time zone not null default now(),
  "description"           text,
  "created_by"            uuid,
  "payment_case_id"       bigint,
  constraint "learning_ledger_transactions_currency_check" check ((currency = 'NGN'::text)),
  constraint "learning_ledger_transactions_description_length_check" check (((description IS NULL) OR (char_length(description) <= 1000))),
  constraint "learning_ledger_transactions_pkey" primary key (id),
  constraint "learning_ledger_transactions_transaction_reference_key" unique (transaction_reference),
  constraint "learning_ledger_transactions_transaction_type_check"
    check ((transaction_type = ANY (ARRAY['payment_capture'::text, 'processor_fee'::text, 'refund'::text, 'chargeback'::text, 'adjustment'::text]))),
  constraint "learning_ledger_transactions_order_id_fkey" foreign key (order_id) references public.learning_orders(id) on delete restrict,
  constraint "learning_ledger_transactions_payment_case_id_fkey" foreign key (payment_case_id) references public.learning_payment_cases(id) on delete restrict,
  constraint "learning_ledger_transactions_created_by_fkey" foreign key (created_by) references public.profiles(id) on delete set null
);

alter table "public"."learning_ledger_transactions"
  enable row level security;

create unique index learning_ledger_one_capture_per_order_key on public.learning_ledger_transactions using btree (order_id)
  where (transaction_type = 'payment_capture'::text);

create unique index learning_ledger_one_chargeback_per_case_key on public.learning_ledger_transactions using btree (payment_case_id)
  where ((transaction_type = 'chargeback'::text) AND (payment_case_id is not null));

create unique index learning_ledger_one_refund_per_case_key on public.learning_ledger_transactions using btree (payment_case_id)
  where ((transaction_type = 'refund'::text) AND (payment_case_id is not null));

create index learning_ledger_transactions_order_idx on public.learning_ledger_transactions using btree (order_id, occurred_at, id);

create constraint TRIGGER assert_learning_ledger_transaction_balanced
  after insert on public.learning_ledger_transactions deferrable initially deferred
  for each row
  execute function public.assert_learning_ledger_transaction_balanced();

create trigger prevent_learning_ledger_transaction_update_delete
  before delete or update on public.learning_ledger_transactions
  for each row
  execute function public.prevent_learning_ledger_mutation();

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_ledger_transactions" to "postgres", "service_role";
