create table "public"."learning_course_entitlements" (
  "id"                bigint                   generated by default as identity not null,
  "learner_id"        uuid                     not null,
  "course_id"         bigint                   not null,
  "order_id"          bigint                   not null,
  "enrollment_id"     bigint,
  "status"            text                     not null default 'active'::text,
  "granted_at"        timestamp with time zone not null default now(),
  "revoked_at"        timestamp with time zone,
  "revocation_reason" text,
  constraint "learning_course_entitlements_enrollment_id_fkey" foreign key (enrollment_id) references public.enrollments(id) on delete set null,
  constraint "learning_course_entitlements_enrollment_id_key" unique (enrollment_id),
  constraint "learning_course_entitlements_learner_course_key" unique (learner_id, course_id),
  constraint "learning_course_entitlements_order_id_key" unique (order_id),
  constraint "learning_course_entitlements_pkey" primary key (id),
  constraint "learning_course_entitlements_revocation_reason_length_check" check (((revocation_reason IS NULL) OR (char_length(revocation_reason) <= 1000))),
  constraint "learning_course_entitlements_status_check" check ((status = ANY (ARRAY['active'::text, 'revoked'::text, 'refunded'::text, 'chargeback'::text]))),
  constraint "learning_course_entitlements_status_timestamp_check" check ((((status = 'active'::text) AND (revoked_at IS NULL)) OR ((status <> 'active'::text) AND (revoked_at IS
    NOT NULL)))),
  constraint "learning_course_entitlements_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete restrict,
  constraint "learning_course_entitlements_order_id_fkey" foreign key (order_id) references public.learning_orders(id) on delete restrict,
  constraint "learning_course_entitlements_learner_id_fkey" foreign key (learner_id) references public.profiles(id) on delete cascade
);

alter table "public"."learning_course_entitlements"
  enable row level security;

create index learning_course_entitlements_course_idx on public.learning_course_entitlements using btree (course_id, status, granted_at desc);

create trigger audit_learning_entitlement_insert
  after insert on public.learning_course_entitlements
  for each row
  execute function public.capture_learning_financial_audit_event('entitlement.created', 'course_entitlement');

create trigger audit_learning_entitlement_status
  after update of status on public.learning_course_entitlements
  for each row
  when ((old.status IS DISTINCT FROM new.status))
  execute function public.capture_learning_financial_audit_event('entitlement.status_changed', 'course_entitlement');

create trigger validate_learning_course_entitlement
  before insert or update of learner_id, course_id, order_id on public.learning_course_entitlements
  for each row
  execute function public.validate_learning_course_entitlement();

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_course_entitlements" to "postgres", "service_role";
