create table "public"."learning_audit_events" (
  "id"            bigint                   generated by default as identity not null,
  "occurred_at"   timestamp with time zone not null default now(),
  "actor_user_id" uuid,
  "actor_role"    text                     not null,
  "action"        text                     not null,
  "entity_type"   text                     not null,
  "entity_id"     text,
  "metadata"      jsonb                    not null default '{}'::jsonb,
  constraint "learning_audit_events_action_check" check ((action ~ '^[a-z][a-z0-9_.]{2,100}$'::text)),
  constraint "learning_audit_events_entity_type_check" check ((entity_type ~ '^[a-z][a-z0-9_]{1,60}$'::text)),
  constraint "learning_audit_events_metadata_object_check" check ((jsonb_typeof(metadata) = 'object'::text)),
  constraint "learning_audit_events_pkey" primary key (id)
);

alter table "public"."learning_audit_events"
  enable row level security;

create index learning_audit_events_actor_idx on public.learning_audit_events using btree (actor_user_id, occurred_at desc)
  where (actor_user_id is not null);

create index learning_audit_events_entity_idx on public.learning_audit_events using btree (entity_type, entity_id, occurred_at desc);

create index learning_audit_events_occurred_at_idx on public.learning_audit_events using btree (occurred_at desc, id desc);

create trigger learning_audit_events_immutable
  before delete or update on public.learning_audit_events
  for each row
  execute function public.prevent_learning_audit_event_mutation();

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."learning_audit_events" to "postgres", "service_role";
