create table "public"."lesson_progress" (
  "id"               bigint                   generated by default as identity not null,
  "enrollment_id"    bigint                   not null,
  "lesson_id"        bigint                   not null,
  "completed_at"     timestamp with time zone,
  "progress_percent" integer                  not null default 0,
  constraint "lesson_progress_enrollment_id_fkey" foreign key (enrollment_id) references public.enrollments(id) on delete cascade,
  constraint "lesson_progress_enrollment_id_lesson_id_key" unique (enrollment_id, lesson_id),
  constraint "lesson_progress_pkey" primary key (id),
  constraint "lesson_progress_progress_percent_check" check (((progress_percent >= 0) AND (progress_percent <= 100))),
  constraint "lesson_progress_lesson_id_fkey" foreign key (lesson_id) references public.lessons(id) on delete cascade
);

alter table "public"."lesson_progress"
  enable row level security;

create policy "Learners can read own lesson progress" on "public"."lesson_progress"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.enrollments enrollment_row
  where ((enrollment_row.id = lesson_progress.enrollment_id) AND (enrollment_row.learner_id = auth.uid())))));

grant select on table "public"."lesson_progress" to "anon", "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."lesson_progress" to "postgres", "service_role";
