create table "public"."lesson_resources" (
  "id"            bigint                   generated by default as identity not null,
  "lesson_id"     bigint                   not null,
  "title"         text                     not null,
  "resource_url"  text                     not null,
  "resource_type" text,
  "created_at"    timestamp with time zone not null default now(),
  constraint "lesson_resources_pkey" primary key (id),
  constraint "lesson_resources_lesson_id_fkey" foreign key (lesson_id) references public.lessons(id) on delete cascade
);

alter table "public"."lesson_resources"
  enable row level security;

create policy "Enrolled learners can read lesson resources" on "public"."lesson_resources"
  for select
  to "authenticated"
  using ((exists ( select 1
   from (public.lessons
     JOIN public.enrollments on ((enrollments.course_id = lessons.course_id)))
  where ((lessons.id = lesson_resources.lesson_id) AND (enrollments.learner_id = auth.uid()) AND (enrollments.status = ANY (ARRAY['active'::text, 'completed'::text]))))));

grant select on table "public"."lesson_resources" to "anon", "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."lesson_resources" to "postgres", "service_role";
