create table "public"."lessons" (
  "id"               bigint                   generated by default as identity not null,
  "course_id"        bigint                   not null,
  "module_id"        bigint                   not null,
  "title"            text                     not null,
  "lesson_type"      text                     not null default 'video'::text,
  "content"          text,
  "video_url"        text,
  "duration_minutes" integer,
  "is_preview"       boolean                  not null default false,
  "position"         integer                  not null default 0,
  "created_at"       timestamp with time zone not null default now(),
  "updated_at"       timestamp with time zone not null default now(),
  "video_provider"   text,
  "video_reference"  text,
  "video_visibility" text,
  "duration_seconds" integer,
  constraint "lessons_course_id_fkey" foreign key (course_id) references public.learning_courses(id) on delete cascade,
  constraint "lessons_duration_seconds_check" check (((duration_seconds IS NULL) OR ((duration_seconds >= 1) AND (duration_seconds <= 86400)))),
  constraint "lessons_lesson_type_check" check ((lesson_type = ANY (ARRAY['video'::text, 'text'::text, 'quiz'::text, 'project'::text]))),
  constraint "lessons_module_id_fkey" foreign key (module_id) references public.course_modules(id) on delete cascade,
  constraint "lessons_pkey" primary key (id),
  constraint "lessons_video_provider_check" check (((video_provider IS NULL) OR (video_provider = 'youtube'::text))),
  constraint "lessons_video_reference_check" check (((video_reference IS NULL) OR (video_reference ~ '^[A-Za-z0-9_-]{11}$'::text))),
  constraint "lessons_video_reference_pair_check" check ((((video_provider IS NULL) AND (video_reference IS NULL)) OR ((video_provider IS NOT NULL) AND (video_reference IS
    NOT NULL)))),
  constraint "lessons_video_visibility_check" check (((video_visibility IS NULL) OR (video_visibility = ANY (ARRAY['public'::text, 'unlisted'::text, 'private'::text])))),
  constraint "lessons_module_course_fkey" foreign key (module_id, course_id) references public.course_modules(id, course_id) on delete cascade
);

alter table "public"."lessons"
  enable row level security;

create unique index lessons_course_module_position_key on public.lessons using btree (course_id, module_id, "position");

create unique index lessons_id_course_id_key on public.lessons using btree (id, course_id);

create policy "Enrolled learners can read course lessons" on "public"."lessons"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.enrollments
  where ((enrollments.course_id = lessons.course_id) AND (enrollments.learner_id = auth.uid()) AND (enrollments.status = ANY (ARRAY['active'::text, 'completed'::text]))))));

create policy "Published course preview lessons are public" on "public"."lessons"
  for select
  to "anon", "authenticated"
  using (((is_preview = true) AND (exists ( select 1
   from public.learning_courses
  where ((learning_courses.id = lessons.course_id) AND (learning_courses.status = 'published'::text))))));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."lessons" to "postgres", "service_role";

revoke all on table "public"."lessons" from "anon";

grant maintain, references, select, trigger, truncate on table "public"."lessons" to "anon";

revoke all on table "public"."lessons" from "authenticated";

grant maintain, references, select, trigger, truncate on table "public"."lessons" to "authenticated";
