create table "public"."newsletter_subscribers" (
  "id"          bigint                   generated by default as identity not null,
  "email"       text                     not null,
  "source_page" text,
  "created_at"  timestamp with time zone not null default now(),
  constraint "newsletter_subscribers_email_key" unique (email),
  constraint "newsletter_subscribers_pkey" primary key (id)
);

alter table "public"."newsletter_subscribers"
  enable row level security;

create policy "Allow public newsletter subscriptions" on "public"."newsletter_subscribers"
  for insert
  to "anon"
  with check (true);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."newsletter_subscribers" to "anon", "authenticated", "postgres", "service_role";
