create table "public"."partner_requests" (
  "id"               bigint                   generated by default as identity not null,
  "full_name"        text,
  "email"            text                     not null,
  "phone"            text,
  "partnership_type" text,
  "idea"             text,
  "source_page"      text,
  "created_at"       timestamp with time zone not null default now(),
  constraint "partner_requests_pkey" primary key (id)
);

alter table "public"."partner_requests"
  enable row level security;

create policy "Allow public partner requests" on "public"."partner_requests"
  for insert
  to "anon"
  with check (true);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."partner_requests" to "anon", "authenticated", "postgres", "service_role";
