create table "public"."quiz_attempts" (
  "id"                   bigint                   generated by default as identity not null,
  "quiz_id"              bigint                   not null,
  "enrollment_id"        bigint                   not null,
  "learner_id"           uuid                     not null,
  "course_id"            bigint                   not null,
  "submitted_at"         timestamp with time zone not null default now(),
  "correct_answer_count" integer                  not null,
  "total_question_count" integer                  not null,
  "score_percentage"     integer                  not null,
  "passed"               boolean                  not null,
  constraint "quiz_attempts_correct_answer_count_check" check ((correct_answer_count >= 0)),
  constraint "quiz_attempts_counts_valid" check ((correct_answer_count <= total_question_count)),
  constraint "quiz_attempts_id_quiz_key" unique (id, quiz_id),
  constraint "quiz_attempts_pkey" primary key (id),
  constraint "quiz_attempts_score_percentage_check" check (((score_percentage >= 0) AND (score_percentage <= 100))),
  constraint "quiz_attempts_total_question_count_check" check ((total_question_count > 0)),
  constraint "quiz_attempts_quiz_course_fkey" foreign key (quiz_id, course_id) references public.quiz_lessons(id, course_id) on delete restrict,
  constraint "quiz_attempts_enrollment_identity_fkey" foreign key (enrollment_id, learner_id, course_id) references public.enrollments(id, learner_id, course_id) on delete restrict
);

alter table "public"."quiz_attempts"
  enable row level security;

create index quiz_attempts_learner_quiz_submitted_idx on public.quiz_attempts using btree (learner_id, enrollment_id, quiz_id, submitted_at desc, id desc);

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."quiz_attempts" to "postgres", "service_role";
