create table "public"."quiz_lessons" (
  "id"                 bigint                   generated by default as identity not null,
  "lesson_id"          bigint                   not null,
  "course_id"          bigint                   not null,
  "instructions"       text,
  "passing_percentage" integer                  not null default 70,
  "created_at"         timestamp with time zone not null default now(),
  "updated_at"         timestamp with time zone not null default now(),
  constraint "quiz_lessons_id_course_key" unique (id, course_id),
  constraint "quiz_lessons_lesson_id_key" unique (lesson_id),
  constraint "quiz_lessons_passing_percentage_check" check (((passing_percentage >= 1) AND (passing_percentage <= 100))),
  constraint "quiz_lessons_pkey" primary key (id),
  constraint "quiz_lessons_lesson_course_fkey" foreign key (lesson_id, course_id) references public.lessons(id, course_id) on delete cascade
);

alter table "public"."quiz_lessons"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."quiz_lessons" to "postgres", "service_role";
