create table "public"."quiz_attempt_answers" (
  "id"                 bigint                   generated by default as identity not null,
  "attempt_id"         bigint                   not null,
  "quiz_id"            bigint                   not null,
  "question_id"        bigint                   not null,
  "selected_option_id" bigint                   not null,
  "created_at"         timestamp with time zone not null default now(),
  constraint "quiz_attempt_answers_attempt_question_key" unique (attempt_id, question_id),
  constraint "quiz_attempt_answers_pkey" primary key (id),
  constraint "quiz_attempt_answers_attempt_quiz_fkey" foreign key (attempt_id, quiz_id) references public.quiz_attempts(id, quiz_id) on delete cascade,
  constraint "quiz_attempt_answers_option_question_fkey" foreign key (selected_option_id, question_id) references public.quiz_options(id, question_id) on delete restrict,
  constraint "quiz_attempt_answers_question_quiz_fkey" foreign key (question_id, quiz_id) references public.quiz_questions(id, quiz_id) on delete restrict
);

alter table "public"."quiz_attempt_answers"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."quiz_attempt_answers" to "postgres", "service_role";
