create table "public"."quiz_options" (
  "id"          bigint                   generated by default as identity not null,
  "question_id" bigint                   not null,
  "option_text" text                     not null,
  "position"    integer                  not null,
  "is_correct"  boolean                  not null default false,
  "created_at"  timestamp with time zone not null default now(),
  "updated_at"  timestamp with time zone not null default now(),
  constraint "quiz_options_id_question_key" unique (id, question_id),
  constraint "quiz_options_option_text_check" check (((char_length(btrim(option_text)) >= 1) AND (char_length(btrim(option_text)) <= 500))),
  constraint "quiz_options_pkey" primary key (id),
  constraint "quiz_options_position_check" check (("position" > 0)),
  constraint "quiz_options_question_position_key" unique (question_id, "position"),
  constraint "quiz_options_question_id_fkey" foreign key (question_id) references public.quiz_questions(id) on delete cascade
);

alter table "public"."quiz_options"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."quiz_options" to "postgres", "service_role";
