"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { ConfirmationDialog } from "@/app/components/ui/confirmation-dialog";

export function CompanyWorkspaceCreateForm() {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const form = new FormData(event.currentTarget); setPending(true); setMessage(null); try { const response = await fetch("/api/company/workspaces", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: String(form.get("name") ?? "").trim(), slug: String(form.get("slug") ?? "").trim().toLowerCase() }) }); const result = await response.json().catch(() => null) as { code?: string; workspace?: { workspace_id?: number } } | null; if (!response.ok) throw new Error(result?.code ?? "unavailable"); if (!result?.workspace?.workspace_id) throw new Error("unavailable"); router.refresh(); } catch (error) { const code = error instanceof Error ? error.message : "unavailable"; setMessage(code === "company_workspace_exists" ? "This account already owns a company learning workspace." : code === "company_slug_taken" ? "That company handle is already in use." : "We could not create the company workspace right now. Please try again."); } finally { setPending(false); } }
  return <form className="organization-create-form" onSubmit={submit}><p className="form-required-key"><span className="required-mark" aria-hidden="true">*</span> Required fields</p><label className="course-field"><span className="field-label">Company name <span className="required-mark" aria-hidden="true">*</span></span><input name="name" placeholder="e.g. Growvelt Technologies" minLength={2} maxLength={160} required /></label><label className="course-field"><span className="field-label">Company URL slug <span className="required-mark" aria-hidden="true">*</span></span><input name="slug" placeholder="e.g. growvelt-technologies" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" minLength={3} maxLength={100} required /><span>This permanent handle identifies your private company learning workspace.</span></label><button className="button button-primary" type="submit" disabled={pending}>{pending ? "Creating…" : "Create company workspace"}</button>{message && <p className="payout-profile-feedback is-error" role="status">{message}</p>}</form>;
}

export function CompanyInvitationForm({ workspaceId }: { workspaceId: number }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const form = new FormData(event.currentTarget); setPending(true); setFeedback(null); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/invitations`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: String(form.get("email") ?? "").trim(), role: String(form.get("role") ?? "member") }) }); const result = await response.json().catch(() => null) as { code?: string; notification?: string } | null; if (!response.ok) throw new Error(result?.code ?? "unavailable"); event.currentTarget.reset(); setFeedback({ kind: "success", text: result?.notification === "sent" ? "Invitation sent by email." : "Invitation saved. The employee can sign in and accept it from Company learning." }); router.refresh(); } catch (error) { const code = error instanceof Error ? error.message : "unavailable"; setFeedback({ kind: "error", text: code === "seat_limit_reached" ? "The workspace has no available seats. Remove a member or increase capacity later." : code === "already_member" ? "That person is already an active member." : "We could not send that invitation. Please try again." }); } finally { setPending(false); } }
  return <form className="organization-invitation-form" onSubmit={submit}><p className="form-required-key"><span className="required-mark" aria-hidden="true">*</span> Required fields</p><label className="course-field"><span className="field-label">Employee email <span className="required-mark" aria-hidden="true">*</span></span><input name="email" type="email" placeholder="employee@example.com" maxLength={320} required /><span>They will receive an invitation and can create or use a Growvelt account before accepting.</span></label><label className="course-field"><span className="field-label">Company role <span className="required-mark" aria-hidden="true">*</span></span><select name="role" defaultValue="member" required><option value="member">Member</option><option value="admin">Company admin</option></select></label><button className="button button-secondary" type="submit" disabled={pending}>{pending ? "Inviting…" : "Invite employee"}</button>{feedback && <p className={`payout-profile-feedback${feedback.kind === "error" ? " is-error" : ""}`} role="status">{feedback.text}</p>}</form>;
}

export function CompanyInvitationResponse({ invitationId }: { invitationId: number }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); const [confirmDecline, setConfirmDecline] = useState(false);
  async function respond(responseKind: "accepted" | "declined") { if (pending) return; setPending(true); setMessage(null); try { const response = await fetch(`/api/company/invitations/${invitationId}/${responseKind === "accepted" ? "accept" : "decline"}`, { method: "POST", credentials: "same-origin" }); if (!response.ok) throw new Error("unavailable"); setMessage(responseKind === "accepted" ? "You joined the company learning workspace." : "Invitation declined."); setConfirmDecline(false); router.refresh(); } catch { setMessage("We could not update this invitation. Refresh and try again."); setConfirmDecline(false); } finally { setPending(false); } }
  return <div className="organization-invitation-acceptance"><div className="organization-action-buttons"><button className="button button-primary" type="button" disabled={pending} onClick={() => respond("accepted")}>{pending ? "Responding…" : "Accept invitation"}</button><button className="button button-secondary" type="button" disabled={pending} onClick={() => setConfirmDecline(true)}>Decline invitation</button></div>{message && <p className="payout-profile-feedback" role="status">{message}</p>}{confirmDecline && <ConfirmationDialog title="Decline company invitation?" description={<p>You will not be added to this company learning workspace. The company can send a new invitation later.</p>} confirmLabel="Decline invitation" pendingLabel="Declining…" tone="danger" isPending={pending} onCancel={() => setConfirmDecline(false)} onConfirm={() => respond("declined")} />}</div>;
}

export function CompanyInvitationCancellation({ workspaceId, invitationId }: { workspaceId: number; invitationId: number }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [confirm, setConfirm] = useState(false);
  async function cancel() { if (pending) return; setPending(true); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/invitations/${invitationId}/cancel`, { method: "POST", credentials: "same-origin" }); if (!response.ok) throw new Error(); setConfirm(false); router.refresh(); } catch { setConfirm(false); } finally { setPending(false); } }
  return <div className="organization-management-action"><button className="text-button text-button-danger" type="button" disabled={pending} onClick={() => setConfirm(true)}>Cancel invitation</button>{confirm && <ConfirmationDialog title="Cancel this company invitation?" description={<p>The employee will no longer be able to accept this invitation.</p>} confirmLabel="Cancel invitation" pendingLabel="Cancelling…" tone="danger" isPending={pending} onCancel={() => setConfirm(false)} onConfirm={cancel} />}</div>;
}

export function CompanyMemberRemoval({ workspaceId, memberId, memberName }: { workspaceId: number; memberId: string; memberName: string }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [confirm, setConfirm] = useState(false);
  async function remove() { if (pending) return; setPending(true); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/members/${memberId}/remove`, { method: "POST", credentials: "same-origin" }); if (!response.ok) throw new Error(); setConfirm(false); router.refresh(); } catch { setConfirm(false); } finally { setPending(false); } }
  return <div className="organization-management-action"><button className="text-button text-button-danger" type="button" disabled={pending} onClick={() => setConfirm(true)}>Remove member</button>{confirm && <ConfirmationDialog title={`Remove ${memberName}?`} description={<p>This removes company-learning access only. It does not delete the person’s Growvelt account, courses, or personal earnings.</p>} confirmLabel="Remove member" pendingLabel="Removing…" tone="danger" isPending={pending} onCancel={() => setConfirm(false)} onConfirm={remove} />}</div>;
}
