"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { ConfirmationDialog } from "@/app/components/ui/confirmation-dialog";
import { LearningIcon } from "@/app/components/learning-icon";

export function CompanyWorkspaceCreateForm() {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const form = new FormData(event.currentTarget); setPending(true); setMessage(null); try { const response = await fetch("/api/company/workspaces", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: String(form.get("name") ?? "").trim(), slug: String(form.get("slug") ?? "").trim().toLowerCase() }) }); const result = await response.json().catch(() => null) as { code?: string; workspace?: { workspace_id?: number } } | null; if (!response.ok) throw new Error(result?.code ?? "unavailable"); if (!result?.workspace?.workspace_id) throw new Error("unavailable"); router.refresh(); } catch (error) { const code = error instanceof Error ? error.message : "unavailable"; setMessage(code === "company_workspace_exists" ? "This account already owns a company learning workspace." : code === "company_slug_taken" ? "That company handle is already in use." : "We could not create the company workspace right now. Please try again."); } finally { setPending(false); } }
  return <form className="organization-create-form" onSubmit={submit}><p className="form-required-key"><span className="required-mark" aria-hidden="true">*</span> Required fields</p><label className="course-field"><span className="field-label">Company name <span className="required-mark" aria-hidden="true">*</span></span><input name="name" placeholder="e.g. Growvelt Technologies" minLength={2} maxLength={160} required /></label><label className="course-field"><span className="field-label">Company URL slug <span className="required-mark" aria-hidden="true">*</span></span><input name="slug" placeholder="e.g. growvelt-technologies" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" minLength={3} maxLength={100} required /><span>This permanent handle identifies your private company learning workspace.</span></label><button className="button button-primary" type="submit" disabled={pending}>{pending ? "Creating…" : "Create company workspace"}</button>{message && <p className="payout-profile-feedback is-error" role="status">{message}</p>}</form>;
}

export function CompanyInvitationForm({ workspaceId }: { workspaceId: number }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const formElement = event.currentTarget; const form = new FormData(formElement); setPending(true); setFeedback(null); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/invitations`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: String(form.get("email") ?? "").trim(), role: String(form.get("role") ?? "member") }) }); const result = await response.json().catch(() => null) as { code?: string; notification?: string } | null; if (!response.ok) throw new Error(result?.code ?? "unavailable"); formElement.reset(); setFeedback({ kind: "success", text: result?.notification === "sent" ? "Invitation sent by email." : "Invitation saved. The employee can sign in and accept it from Company learning." }); router.refresh(); } catch (error) { const code = error instanceof Error ? error.message : "unavailable"; setFeedback({ kind: "error", text: code === "seat_limit_reached" ? "The workspace has no available seats. Remove a member or increase capacity later." : code === "already_member" ? "That person is already an active member." : "We could not save that invitation. Please try again." }); } finally { setPending(false); } }
  return <form className="organization-invitation-form" onSubmit={submit}><p className="form-required-key"><span className="required-mark" aria-hidden="true">*</span> Required fields</p><label className="course-field"><span className="field-label">Employee email <span className="required-mark" aria-hidden="true">*</span></span><input name="email" type="email" placeholder="employee@example.com" maxLength={320} required /><span>They will receive an invitation and can create or use a Growvelt account before accepting.</span></label><label className="course-field"><span className="field-label">Company role <span className="required-mark" aria-hidden="true">*</span></span><select name="role" defaultValue="member" required><option value="member">Member</option><option value="admin">Company admin</option></select></label><button className="button button-secondary" type="submit" disabled={pending}>{pending ? "Inviting…" : "Invite employee"}</button>{feedback && <p className={`payout-profile-feedback${feedback.kind === "error" ? " is-error" : ""}`} role="status">{feedback.text}</p>}</form>;
}

export function CompanyCourseAssignmentForm({ workspaceId, members, courses }: { workspaceId: number; members: { member_id: string; full_name: string | null; email: string; role: string; status: string }[]; courses: { course_id: number; title: string; category: string | null; level: string | null }[] }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const formElement = event.currentTarget; const form = new FormData(formElement); setPending(true); setFeedback(null); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/assignments`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assignedUserId: String(form.get("assignedUserId") ?? ""), courseId: Number(form.get("courseId")) }) }); const result = await response.json().catch(() => null) as { code?: string } | null; if (!response.ok) throw new Error(result?.code ?? "unavailable"); formElement.reset(); setFeedback({ kind: "success", text: "Course assigned. The employee can now find it in Company learning." }); router.refresh(); } catch (error) { const code = error instanceof Error ? error.message : "unavailable"; setFeedback({ kind: "error", text: code === "course_not_assignable" ? "Only published free courses can be assigned until company billing is available." : code === "company_access_denied" ? "Only an active company owner or admin can assign courses." : "We could not assign that course right now. Please try again." }); } finally { setPending(false); } }
  const activeMembers = members.filter((member) => member.status === "active" && member.role !== "owner");
  return <form className="company-assignment-form" onSubmit={submit}><p className="form-required-key"><span className="required-mark" aria-hidden="true">*</span> Required fields</p><label className="course-field"><span className="field-label">Employee <span className="required-mark" aria-hidden="true">*</span></span><select name="assignedUserId" required defaultValue=""><option value="" disabled>Select an active employee</option>{activeMembers.map((member) => <option value={member.member_id} key={member.member_id}>{member.full_name || member.email} · {member.email}</option>)}</select></label><label className="course-field"><span className="field-label">Published free course <span className="required-mark" aria-hidden="true">*</span></span><select name="courseId" required defaultValue=""><option value="" disabled>Select a course</option>{courses.map((course) => <option value={course.course_id} key={course.course_id}>{course.title}{course.level ? ` · ${course.level}` : ""}</option>)}</select><span>Paid company access and billing will be added in Phase 3C.</span></label><button className="button button-secondary" type="submit" disabled={pending || activeMembers.length === 0 || courses.length === 0}>{pending ? "Assigning…" : "Assign course"}</button>{feedback && <p className={`payout-profile-feedback${feedback.kind === "error" ? " is-error" : ""}`} role="status">{feedback.text}</p>}</form>;
}

export function CompanyPaidCoursePurchaseForm({ workspaceId, members, courses }: { workspaceId: number; members: { member_id: string; full_name: string | null; email: string; role: string; status: string }[]; courses: { course_id: number; title: string; price_amount: number; currency: string; provider_name: string }[] }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [courseId, setCourseId] = useState(""); const [selectedMembers, setSelectedMembers] = useState<string[]>([]); const [feedback, setFeedback] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  const employees = members.filter((member) => member.status === "active" && member.role !== "owner");
  const course = courses.find((item) => String(item.course_id) === courseId);
  const total = course ? Math.round(Number(course.price_amount) * 100) * selectedMembers.length : 0;
  const money = (minor: number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", minimumFractionDigits: 2 }).format(minor / 100);
  function toggleEmployee(memberId: string) { setSelectedMembers((current) => current.includes(memberId) ? current.filter((id) => id !== memberId) : [...current, memberId]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending || !course || selectedMembers.length === 0) return; setPending(true); setFeedback(null); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/purchases`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ courseId: course.course_id, assignedUserIds: selectedMembers }) }); const result = await response.json().catch(() => null) as { code?: string } | null; if (!response.ok) throw new Error(result?.code ?? "unavailable"); setFeedback({ kind: "success", text: "Purchase request prepared. Checkout will be enabled after Growvelt’s live Paystack approval is complete." }); setCourseId(""); setSelectedMembers([]); router.refresh(); } catch (error) { const code = error instanceof Error ? error.message : "unavailable"; const text = code === "purchase_exists" ? "One or more selected employees already have a company purchase for this course." : code === "company_access_denied" ? "Only an active company owner or admin can prepare a purchase." : code === "purchase_invalid" ? "Choose an eligible published paid course and active employees." : "We could not prepare this company purchase right now. Please try again."; setFeedback({ kind: "error", text }); } finally { setPending(false); } }
  return <form className="company-purchase-form" onSubmit={submit}><p className="form-required-key"><span className="required-mark" aria-hidden="true">*</span> Required fields</p><label className="course-field"><span className="field-label">Published paid course <span className="required-mark" aria-hidden="true">*</span></span><select value={courseId} onChange={(event) => setCourseId(event.target.value)} required><option value="" disabled>Select a paid course</option>{courses.map((item) => <option value={item.course_id} key={item.course_id}>{item.title} · {item.provider_name} · {money(Math.round(Number(item.price_amount) * 100))}</option>)}</select><span>Courses are supplied by Growvelt instructors and provider organizations, not by Growvelt itself.</span></label><fieldset className="company-purchase-employees"><legend>Employees <span className="required-mark" aria-hidden="true">*</span></legend><p>Select every active employee who needs this course seat.</p>{employees.length ? <div>{employees.map((member) => <label key={member.member_id}><input type="checkbox" checked={selectedMembers.includes(member.member_id)} onChange={() => toggleEmployee(member.member_id)} /> <span><strong>{member.full_name || member.email}</strong><small>{member.email}</small></span></label>)}</div> : <p className="payout-profile-feedback is-error">Invite and activate at least one employee before preparing a paid course purchase.</p>}</fieldset>{course && <aside className="company-purchase-summary"><p className="eyebrow">Purchase summary</p><strong>{course.title}</strong><span>{course.provider_name}</span><dl><div><dt>Price per employee</dt><dd>{money(Math.round(Number(course.price_amount) * 100))}</dd></div><div><dt>Employees selected</dt><dd>{selectedMembers.length}</dd></div><div><dt>Total due at checkout</dt><dd>{money(total)}</dd></div></dl><p>Checkout is paused until Growvelt’s live Paystack approval is active. Preparing this request does not charge the company or grant paid access.</p></aside>}<button className="button button-primary" type="submit" disabled={pending || !course || selectedMembers.length === 0 || employees.length === 0}>{pending ? "Preparing…" : "Prepare secure checkout"}</button>{feedback && <p className={`payout-profile-feedback${feedback.kind === "error" ? " is-error" : ""}`} role="status">{feedback.text}</p>}</form>;
}

export function CompanyAssignmentCard({ assignment }: { assignment: { assignment_id: number; employee_name: string | null; employee_email: string; course_title: string; progress_percent: number; enrollment_status: string | null } }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const initials = (assignment.employee_name || assignment.employee_email).trim().slice(0, 1).toUpperCase();
  return <li className="company-assignment-card"><div className="company-assignment-card-header"><span className="company-assignment-avatar" aria-hidden="true">{initials}</span><span className="company-assignment-person"><strong>{assignment.employee_name || assignment.employee_email}</strong><small>{assignment.employee_email} · {assignment.course_title}</small></span><span className="company-assignment-progress">{assignment.progress_percent}%</span><span className="company-assignment-menu-wrap"><button className="company-assignment-menu-button" type="button" aria-label={`Options for ${assignment.employee_name || assignment.employee_email}`} aria-expanded={menuOpen} onClick={() => setMenuOpen((current) => !current)}>⋮</button>{menuOpen && <span className="company-assignment-menu" role="menu"><Link href={`/dashboard/company/insights?assignment=${assignment.assignment_id}`} onClick={() => setMenuOpen(false)}><LearningIcon name="eye" size={16} />View progress</Link></span>}</span></div></li>;
}

export function CompanyInvitationResponse({ invitationId }: { invitationId: number }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); const [confirmDecline, setConfirmDecline] = useState(false);
  async function respond(responseKind: "accepted" | "declined") { if (pending) return; setPending(true); setMessage(null); try { const response = await fetch(`/api/company/invitations/${invitationId}/${responseKind === "accepted" ? "accept" : "decline"}`, { method: "POST", credentials: "same-origin" }); if (!response.ok) throw new Error("unavailable"); setMessage(responseKind === "accepted" ? "You joined the company learning workspace." : "Invitation declined."); setConfirmDecline(false); router.refresh(); } catch { setMessage("We could not update this invitation. Refresh and try again."); setConfirmDecline(false); } finally { setPending(false); } }
  return <div className="organization-invitation-acceptance"><div className="organization-action-buttons"><button className="button button-primary" type="button" disabled={pending} onClick={() => respond("accepted")}>{pending ? "Responding…" : "Accept invitation"}</button><button className="button button-secondary" type="button" disabled={pending} onClick={() => setConfirmDecline(true)}>Decline invitation</button></div>{message && <p className="payout-profile-feedback" role="status">{message}</p>}{confirmDecline && <ConfirmationDialog title="Decline company invitation?" description={<p>You will not be added to this company learning workspace. The company can send a new invitation later.</p>} confirmLabel="Decline invitation" pendingLabel="Declining…" tone="danger" isPending={pending} onCancel={() => setConfirmDecline(false)} onConfirm={() => respond("declined")} />}</div>;
}

export function CompanyInvitationCancellation({ workspaceId, invitationId }: { workspaceId: number; invitationId: number }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [confirm, setConfirm] = useState(false);
  async function cancel() { if (pending) return; setPending(true); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/invitations/${invitationId}/cancel`, { method: "POST", credentials: "same-origin" }); if (!response.ok) throw new Error(); setConfirm(false); router.refresh(); } catch { setConfirm(false); } finally { setPending(false); } }
  return <div className="organization-management-action"><button className="text-button text-button-danger" type="button" disabled={pending} onClick={() => setConfirm(true)}>Cancel invitation</button>{confirm && <ConfirmationDialog title="Cancel this company invitation?" description={<p>The employee will no longer be able to accept this invitation.</p>} confirmLabel="Cancel invitation" pendingLabel="Cancelling…" tone="danger" isPending={pending} onCancel={() => setConfirm(false)} onConfirm={cancel} />}</div>;
}

export function CompanyMemberRemoval({ workspaceId, memberId, memberName }: { workspaceId: number; memberId: string; memberName: string }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [confirm, setConfirm] = useState(false);
  async function remove() { if (pending) return; setPending(true); try { const response = await fetch(`/api/company/workspaces/${workspaceId}/members/${memberId}/remove`, { method: "POST", credentials: "same-origin" }); if (!response.ok) throw new Error(); setConfirm(false); router.refresh(); } catch { setConfirm(false); } finally { setPending(false); } }
  return <div className="organization-management-action"><button className="text-button text-button-danger" type="button" disabled={pending} onClick={() => setConfirm(true)}>Remove member</button>{confirm && <ConfirmationDialog title={`Remove ${memberName}?`} description={<p>This removes company-learning access only. It does not delete the person’s Growvelt account, courses, or personal earnings.</p>} confirmLabel="Remove member" pendingLabel="Removing…" tone="danger" isPending={pending} onCancel={() => setConfirm(false)} onConfirm={remove} />}</div>;
}
