import Link from "next/link";
import { notFound } from "next/navigation";
import { LessonCompleteButton } from "@/app/components/learning/lesson-complete-button";
import { QuizPlayer } from "@/app/components/learning/quiz-player";
import { getRequestLocale } from "@/app/lib/i18n-server";
import { getOwnEnrolledLearningCourse } from "@/app/lib/learning/enrollments";
import { getOwnEnrolledLessonSnapshot } from "@/app/lib/learning/lesson-player";
import { getOwnEnrolledQuizSnapshot } from "@/app/lib/learning/quiz";

export const metadata = { title: "Lesson" };
const copy = {
  en: { back: "Back to course", lessons: "Course lessons", later: "Coming later", current: "Current lesson", passed: "Quiz · Passed", completed: "Completed", video: "Video", text: "Text", quiz: "Quiz", videoLesson: "Video lesson", textLesson: "Text lesson", assessment: "Quiz assessment", unavailable: "Lesson unavailable", videoUnavailable: "This video reference is unavailable.", textUnavailable: "This lesson content is unavailable.", typeUnavailable: "This lesson type is not available in the player yet.", courseCompleted: "Course completed. Your certificate is available from the course page.", previous: "Previous lesson", next: "Next lesson", completedCourse: "View completed course" },
  fr: { back: "Retour au cours", lessons: "Leçons du cours", later: "Bientôt disponible", current: "Leçon actuelle", passed: "Quiz · Réussi", completed: "Terminé", video: "Vidéo", text: "Texte", quiz: "Quiz", videoLesson: "Leçon vidéo", textLesson: "Leçon texte", assessment: "Évaluation par quiz", unavailable: "Leçon indisponible", videoUnavailable: "Cette référence vidéo n’est pas disponible.", textUnavailable: "Le contenu de cette leçon n’est pas disponible.", typeUnavailable: "Ce type de leçon n’est pas encore disponible dans le lecteur.", courseCompleted: "Cours terminé. Votre certificat est disponible depuis la page du cours.", previous: "Leçon précédente", next: "Leçon suivante", completedCourse: "Voir le cours terminé" },
  es: { back: "Volver al curso", lessons: "Lecciones del curso", later: "Próximamente", current: "Lección actual", passed: "Cuestionario · Aprobado", completed: "Completado", video: "Vídeo", text: "Texto", quiz: "Cuestionario", videoLesson: "Lección de vídeo", textLesson: "Lección de texto", assessment: "Evaluación de cuestionario", unavailable: "Lección no disponible", videoUnavailable: "Esta referencia de vídeo no está disponible.", textUnavailable: "El contenido de esta lección no está disponible.", typeUnavailable: "Este tipo de lección aún no está disponible en el reproductor.", courseCompleted: "Curso completado. Tu certificado está disponible en la página del curso.", previous: "Lección anterior", next: "Siguiente lección", completedCourse: "Ver curso completado" },
} as const;
function youtubeEmbed(reference: string) { return `https://www.youtube-nocookie.com/embed/${encodeURIComponent(reference)}`; }

export default async function EnrolledLessonPage({ params }: { params: Promise<{ slug: string; lessonId: string }> }) {
  const [{ slug, lessonId }, locale] = await Promise.all([params, getRequestLocale()]);
  const text = copy[locale]; const parsedLessonId = Number(lessonId);
  if (!slug || slug.length > 220 || !Number.isSafeInteger(parsedLessonId) || parsedLessonId < 1) notFound();
  const [snapshot, course] = await Promise.all([getOwnEnrolledLessonSnapshot(slug, parsedLessonId), getOwnEnrolledLearningCourse(slug)]);
  if (!snapshot || !course || snapshot.course.id !== course.id) notFound();
  const { current } = snapshot; const quiz = current.type === "quiz" ? await getOwnEnrolledQuizSnapshot(slug, parsedLessonId) : null;
  if (current.type === "quiz" && !quiz) notFound();
  const courseHref = `/dashboard/my-learning/${encodeURIComponent(snapshot.course.slug)}`;
  const lessonIds = course.modules.flatMap((module) => module.lessons.filter((lesson) => lesson.type !== "project").map((lesson) => lesson.id));
  const index = lessonIds.indexOf(current.id); const previousId = index > 0 ? lessonIds[index - 1] : null; const nextId = index >= 0 ? lessonIds[index + 1] ?? null : null;
  const nextHref = nextId ? `${courseHref}/lessons/${nextId}` : null;
  const navLabel = (lesson: { type: "video" | "text" | "quiz" | "project"; completed: boolean; current: boolean }) => lesson.current ? text.current : lesson.completed ? lesson.type === "quiz" ? text.passed : text.completed : lesson.type === "video" ? text.video : lesson.type === "text" ? text.text : text.quiz;
  const lessonType = current.type === "video" ? text.videoLesson : current.type === "text" ? text.textLesson : current.type === "quiz" ? text.assessment : text.unavailable;
  return <section className="lesson-player-page section-shell"><header className="lesson-player-heading"><Link className="back-link" href={courseHref}>{text.back}</Link><p className="eyebrow">{snapshot.course.title}</p><h1>{current.title}</h1></header><div className="lesson-player-layout"><aside className="lesson-player-nav" aria-label={text.lessons}>{snapshot.modules.map((module) => <section key={module.id}><h2>{module.title}</h2><ol>{module.lessons.map((lesson) => <li key={lesson.id}>{lesson.type === "project" ? <div className="lesson-navigation-link is-unavailable"><span>{lesson.title}</span><small>{text.later}</small></div> : <Link className={`lesson-navigation-link${lesson.completed ? " is-completed" : ""}`} href={`${courseHref}/lessons/${lesson.id}`} aria-current={lesson.current ? "page" : undefined}><span>{lesson.title}</span><small>{navLabel(lesson)}</small></Link>}</li>)}</ol></section>)}</aside><article className="lesson-player-content"><p className="eyebrow">{lessonType}</p>{current.type === "video" ? current.videoProvider === "youtube" && current.videoReference ? <div className="lesson-video"><iframe src={youtubeEmbed(current.videoReference)} title={current.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div> : <p className="lesson-unavailable">{text.videoUnavailable}</p> : current.type === "text" ? <div className="lesson-text-content">{current.textContent || text.textUnavailable}</div> : current.type === "quiz" && quiz ? <QuizPlayer quiz={quiz} slug={slug} lessonId={current.id} nextHref={nextHref} courseHref={courseHref} /> : <p className="lesson-unavailable">{text.typeUnavailable}</p>}{course.enrollmentStatus === "completed" && <p className="lesson-complete-state" role="status">{text.courseCompleted}</p>}{(current.type === "video" || current.type === "text") && <LessonCompleteButton courseId={snapshot.course.id} lessonId={current.id} completed={current.completed} />}<nav className="lesson-pagination" aria-label={text.lessons}>{previousId ? <Link className="button button-secondary" href={`${courseHref}/lessons/${previousId}`}>{text.previous}</Link> : <span />}{current.type !== "quiz" && nextId ? <Link className="button button-primary" href={nextHref!}>{text.next}</Link> : current.type !== "quiz" ? <Link className="button button-primary" href={courseHref}>{course.enrollmentStatus === "completed" ? text.completedCourse : text.back}</Link> : null}</nav></article></div></section>;
}
