import Link from "next/link";
import { getRequestLocale } from "@/app/lib/i18n-server";
import { listOwnLearningEnrollments } from "@/app/lib/learning/enrollments";

export const metadata = { title: "My Learning" };

const copy = {
  en: { title: "My Learning", emptyTitle: "Your enrolled courses will appear here.", emptyCopy: "Enroll in a published free course to begin learning and track your progress here.", pace: "Learn at your pace", paceCopy: "Your next lesson, quiz progress, completion state, and certificate path will stay connected here.", explore: "Explore published courses", dashboard: "Back to dashboard", enrolledTitle: "Your enrolled courses", enrolledCopy: "Continue structured text, video, and quiz activities using progress saved securely to your account.", exploreMore: "Explore more courses", enrolled: "enrolled", completed: "completed", activities: "activities", complete: "Completed", progress: "In progress", ready: "Ready to begin", allLevels: "All levels", free: "Free", paid: "Paid", instructor: "Growvelt Instructor", by: "By", summary: "A practical Growvelt Learning course.", continue: "Continue learning", review: "Review course", view: "View course", details: "Course details", end: "End of My Learning", activitySummary: "text, video, and quiz activities", enrolledOn: "Enrolled" },
  fr: { title: "Mon apprentissage", emptyTitle: "Vos cours suivis apparaîtront ici.", emptyCopy: "Inscrivez-vous à un cours gratuit publié pour commencer à apprendre et suivre votre progression ici.", pace: "Apprenez à votre rythme", paceCopy: "Votre prochaine leçon, votre progression aux quiz, votre état d’achèvement et votre parcours de certificat resteront liés ici.", explore: "Explorer les cours publiés", dashboard: "Retour au tableau de bord", enrolledTitle: "Vos cours suivis", enrolledCopy: "Continuez les activités structurées de texte, vidéo et quiz avec une progression enregistrée de façon sécurisée sur votre compte.", exploreMore: "Explorer plus de cours", enrolled: "inscrit", completed: "terminé", activities: "activités", complete: "Terminé", progress: "En cours", ready: "Prêt à commencer", allLevels: "Tous niveaux", free: "Gratuit", paid: "Payant", instructor: "Instructeur Growvelt", by: "Par", summary: "Un cours pratique Growvelt Learning.", continue: "Continuer le cours", review: "Revoir le cours", view: "Voir le cours", details: "Détails du cours", end: "Fin de Mon apprentissage", activitySummary: "activités de texte, vidéo et quiz", enrolledOn: "Inscrit le" },
  es: { title: "Mi aprendizaje", emptyTitle: "Tus cursos inscritos aparecerán aquí.", emptyCopy: "Inscríbete en un curso gratuito publicado para comenzar a aprender y seguir tu progreso aquí.", pace: "Aprende a tu ritmo", paceCopy: "Tu próxima lección, el progreso de cuestionarios, el estado de finalización y la ruta de certificación permanecerán conectados aquí.", explore: "Explorar cursos publicados", dashboard: "Volver al panel", enrolledTitle: "Tus cursos inscritos", enrolledCopy: "Continúa las actividades estructuradas de texto, vídeo y cuestionarios con el progreso guardado de forma segura en tu cuenta.", exploreMore: "Explorar más cursos", enrolled: "inscrito", completed: "completado", activities: "actividades", complete: "Completado", progress: "En progreso", ready: "Listo para empezar", allLevels: "Todos los niveles", free: "Gratis", paid: "De pago", instructor: "Instructor de Growvelt", by: "Por", summary: "Un curso práctico de Growvelt Learning.", continue: "Continuar aprendiendo", review: "Revisar curso", view: "Ver curso", details: "Detalles del curso", end: "Fin de Mi aprendizaje", activitySummary: "actividades de texto, vídeo y cuestionarios", enrolledOn: "Inscrito" },
} as const;

export default async function MyLearningPage() {
  const [courses, locale] = await Promise.all([listOwnLearningEnrollments(), getRequestLocale()]);
  const text = copy[locale];
  const dateFormatter = new Intl.DateTimeFormat(locale === "fr" ? "fr-FR" : locale === "es" ? "es-ES" : "en-NG", { dateStyle: "medium" });
  if (!courses.length) return <section className="certificate-space learner-empty-space" aria-labelledby="my-learning-title"><div><p className="eyebrow">{text.title}</p><h1 id="my-learning-title">{text.emptyTitle}</h1><p>{text.emptyCopy}</p></div><div className="learner-empty-highlight"><span aria-hidden="true">↗</span><div><strong>{text.pace}</strong><p>{text.paceCopy}</p></div></div><div className="certificate-space-actions"><Link className="button button-primary" href="/dashboard/explore">{text.explore}</Link><Link className="text-link" href="/dashboard">{text.dashboard} <span aria-hidden="true">→</span></Link></div></section>;
  const completedCourses = courses.filter((course) => course.enrollmentStatus === "completed").length;
  const completedActivities = courses.reduce((total, course) => total + course.completedLessons, 0);
  const totalActivities = courses.reduce((total, course) => total + course.totalLessons, 0);
  return <section className="my-learning-page section-shell" aria-labelledby="my-learning-title"><header className="my-learning-hero"><div><p className="eyebrow">{text.title}</p><h1 id="my-learning-title">{text.enrolledTitle}</h1><p>{text.enrolledCopy}</p></div><Link className="button button-primary" href="/dashboard/explore">{text.exploreMore}</Link></header><div className="my-learning-summary" aria-label={text.title}><span><strong>{courses.length}</strong> {text.enrolled}</span><span><strong>{completedCourses}</strong> {text.completed}</span><span><strong>{completedActivities}/{totalActivities}</strong> {text.activities}</span></div><div className="my-learning-list">{courses.map((course) => { const href = course.resumeLessonId ? `/dashboard/my-learning/${encodeURIComponent(course.slug)}/lessons/${course.resumeLessonId}` : `/dashboard/my-learning/${encodeURIComponent(course.slug)}`; const action = course.resumeLessonId ? text.continue : course.enrollmentStatus === "completed" ? text.review : text.view; return <article className="my-learning-card" key={course.id}><div className="my-learning-card-content"><div className="my-learning-card-status"><span className={`learner-status-pill${course.enrollmentStatus === "completed" ? " is-complete" : ""}`}>{course.enrollmentStatus === "completed" ? text.complete : course.progressPercent > 0 ? text.progress : text.ready}</span><span>{course.progressPercent}%</span></div><p className="eyebrow">{course.category || "Growvelt Learning"}</p><h2>{course.title}</h2><p>{course.summary || text.summary}</p><div className="published-course-meta"><span>{course.level || text.allLevels}</span><span>{course.isFree ? text.free : text.paid}</span><span>{course.instructorName ? `${text.by} ${course.instructorName}` : text.instructor}</span></div><div className="learning-progress" aria-label={`${course.progressPercent}%`}><div className="progress-track" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={course.progressPercent}><span style={{ width: `${course.progressPercent}%` }} /></div><small>{course.completedLessons} / {course.totalLessons} {text.activitySummary} · {course.progressPercent}%</small></div><small>{text.enrolledOn} {dateFormatter.format(new Date(course.enrolledAt))}</small></div><div className="my-learning-card-action"><Link className="button button-primary learner-arrow-action" href={href}>{action}<span aria-hidden="true">→</span></Link><Link className="text-link" href={`/dashboard/my-learning/${encodeURIComponent(course.slug)}`}>{text.details}</Link></div></article>; })}</div><div className="results-end-marker my-learning-end-marker">{text.end}</div></section>;
}
