import Link from "next/link";
import { redirect } from "next/navigation";
import { OrganizationCreateForm } from "@/app/components/instructor/organization-create-form";
import { OrganizationInvitationAcceptance, OrganizationInvitationCancellation, OrganizationInvitationForm, OrganizationMemberRevocation } from "@/app/components/instructor/organization-invitation-controls";
import { VerifiedProviderBadge } from "@/app/components/verified-provider-badge";
import { isApprovedInstructor } from "@/app/lib/instructor/authorization";
import { getInstructorOrganizationManagement, getOwnInstructorOrganizationInvitations, getOwnInstructorOrganizationProfileBranding, getOwnInstructorOrganizationProfiles, getOwnInstructorOrganizations, getOwnInstructorOrganizationVerifications } from "@/app/lib/instructor/organizations";
import { createClient } from "@/app/lib/supabase/server";

export const metadata = { title: "Training organizations" };

export default async function InstructorOrganizationsPage() {
  if (!await isApprovedInstructor()) redirect("/teach/application");
  const [organizations, invitations, verifications, profiles] = await Promise.all([getOwnInstructorOrganizations(), getOwnInstructorOrganizationInvitations(), getOwnInstructorOrganizationVerifications(), getOwnInstructorOrganizationProfiles()]);
  const management = await Promise.all(organizations.map(async (organization) => ({ organization, ...(await getInstructorOrganizationManagement(organization)) })));
  const ownedOrganizationIds = organizations.filter((organization) => organization.membership_role === "owner" && organization.membership_status === "active" && organization.organization_status === "active").map((organization) => organization.organization_id);
  const providerBrandings = await Promise.all(ownedOrganizationIds.map(async (organizationId) => ({ organizationId, profile: await getOwnInstructorOrganizationProfileBranding(organizationId).catch(() => null) })));
  const supabase = await createClient();
  const providerLogos = await Promise.all(providerBrandings.map(async ({ organizationId, profile }) => ({ organizationId, url: profile?.logo_storage_path ? (await supabase.storage.from("learning-provider-media").createSignedUrl(profile.logo_storage_path, 60 * 60)).data?.signedUrl ?? null : null })));
  return <section className="instructor-earnings-page section-shell">
    <header className="instructor-earnings-hero"><p className="eyebrow">Training organizations</p><h1>Set up and collaborate through your provider workspace.</h1><p>Create an organization, collaborate with approved instructors, attribute new course drafts, and manage a complete provider profile. Your provider profile stays private until Learning Admin approves verification. Owners can also review aggregate learning, certificate, and commercial reporting without accessing individual instructor earnings.</p></header>
    {ownedOrganizationIds.length === 0 && <section className="organization-panel"><header><p className="eyebrow">Create organization</p><h2>Set up your provider identity</h2><p>Creating an organization makes you its active Owner. It becomes your one provider workspace for its team, profile, branding, verification, and organization-owned courses. Your existing individual courses and earnings stay unchanged.</p></header><OrganizationCreateForm /></section>}
    <section className="organization-panel"><header><p className="eyebrow">Your memberships</p><h2>Organization access</h2><p>Your role shows who you are within each provider workspace. Verified providers can create a public profile at their organization URL.</p></header>{management.length ? <div className="organization-list">{management.map(({ organization, members, courses, invitations: ownerInvitations }) => {
      const ownerCanManage = organization.membership_role === "owner" && organization.membership_status === "active" && organization.organization_status === "active";
      const verification = verifications.find((item) => item.organization_id === organization.organization_id);
      const profile = profiles.find((item) => item.organization_id === organization.organization_id);
      const logoUrl = providerLogos.find((item) => item.organizationId === organization.organization_id)?.url;
      return <article className="organization-management-card" key={organization.organization_id}>
        <div className="organization-identity"><strong>{organization.name}</strong><span>Organization handle: {organization.slug}</span><div className="organization-statuses"><span>Role: {organization.membership_role}</span><span>Membership: {organization.membership_status}</span><span>Organization: {organization.organization_status}</span>{verification && <span>Verification: {verification.status}</span>}</div></div>
        <section className="organization-management-section"><h3>Team members</h3>{members.length ? <ul>{members.map((member) => <li key={`${member.member_id}-${member.granted_at}`}><span><strong>{member.full_name || member.email}</strong><small>{member.email}</small></span><div className="organization-member-actions"><span>{member.role} · {member.status === "revoked" ? "removed" : member.status}</span>{ownerCanManage && member.role !== "owner" && member.status === "active" && <OrganizationMemberRevocation organizationId={organization.organization_id} memberId={member.member_id} memberName={member.full_name || member.email} />}</div></li>)}</ul> : <p>No organization members were found.</p>}</section>
        <section className="organization-management-section"><h3>Organization courses</h3>{courses.length ? <ul>{courses.map((course) => <li key={course.course_id}><span><strong>{course.title}</strong><small>Lead instructor: {course.instructor_name}</small></span><span>{course.status}</span></li>)}</ul> : <p>No course drafts have been attributed to this organization yet.</p>}<p className="organization-course-help">To create one, open <Link href="/dashboard/instructor/courses/new">Create course</Link>, choose <strong>{organization.name}</strong> under Provider organization, then create the draft.</p><div className="organization-action-buttons"><Link className="button button-secondary" href="/dashboard/instructor/courses/new">Create organization course</Link><Link className="button button-secondary" href={`/dashboard/instructor/organizations/${organization.organization_id}/insights`}>Organization insights</Link></div></section>
        {ownerCanManage && <><section className="organization-management-section organization-profile-entry"><div className="organization-profile-entry-mark" aria-hidden="true">{logoUrl ? <img src={logoUrl} alt="" /> : organization.name.charAt(0).toUpperCase() || "G"}</div><div><p className="eyebrow">Provider organization</p><h3>{organization.name} {verification?.status === "verified" && <VerifiedProviderBadge />}</h3><p>{profile ? verification?.status === "verified" ? "Your verified provider profile is live. Use the management page to update its public details, cover, and logo." : "Your provider profile is saved as a private draft. Complete verification when you are ready to publish it." : "Set up your organization’s profile, cover, logo, and provider details. It stays private until Learning Admin approves verification."}</p></div><Link className="button button-primary" href={`/dashboard/instructor/organizations/${organization.organization_id}/profile`}>Manage provider profile <span aria-hidden="true">↗</span></Link></section><section className="organization-management-section"><h3>Sent invitations</h3>{ownerInvitations.length ? <ul>{ownerInvitations.map((invitation) => <li key={invitation.invitation_id}><span><strong>{invitation.invited_email}</strong><small>Sent {new Date(invitation.created_at).toLocaleDateString("en-NG")}</small></span><div className="organization-member-actions"><span>{invitation.role} · {invitation.status}</span>{invitation.status === "pending" && <OrganizationInvitationCancellation organizationId={organization.organization_id} invitationId={invitation.invitation_id} />}</div></li>)}</ul> : <p>You have not invited an instructor yet.</p>}</section><section className="organization-management-section"><h3>Invite an instructor</h3><OrganizationInvitationForm organizationId={organization.organization_id} /></section></>}
      </article>;
    })}</div> : <p className="organization-empty">You have not created or joined a training organization yet. Create one above, or ask an organization owner to invite your approved instructor account.</p>}</section>
    {invitations.length > 0 && <section className="organization-panel"><header><p className="eyebrow">Pending invitations</p><h2>Join a training organization</h2><p>Accepting an invitation adds you as an approved instructor member. It does not transfer course ownership or change earnings.</p></header><div className="organization-list">{invitations.map((invitation) => <article key={invitation.invitation_id}><div><strong>{invitation.organization_name}</strong><span>{invitation.role} invitation · expires {new Date(invitation.expires_at).toLocaleDateString("en-NG")}</span></div><OrganizationInvitationAcceptance invitationId={invitation.invitation_id} /></article>)}</div></section>}
  </section>;
}
