import { redirect } from "next/navigation";
import { OrganizationCreateForm } from "@/app/components/instructor/organization-create-form";
import { OrganizationInvitationAcceptance, OrganizationInvitationForm } from "@/app/components/instructor/organization-invitation-controls";
import { isApprovedInstructor } from "@/app/lib/instructor/authorization";
import { getInstructorOrganizationManagement, getOwnInstructorOrganizationInvitations, getOwnInstructorOrganizations } from "@/app/lib/instructor/organizations";

export const metadata = { title: "Training organizations" };

export default async function InstructorOrganizationsPage() {
  if (!await isApprovedInstructor()) redirect("/teach/application");
  const [organizations, invitations] = await Promise.all([getOwnInstructorOrganizations(), getOwnInstructorOrganizationInvitations()]);
  const organizationManagement = await Promise.all(organizations.map(async (organization) => ({ organization, ...(await getInstructorOrganizationManagement(organization)) })));
  return <section className="instructor-earnings-page section-shell">
    <header className="instructor-earnings-hero"><p className="eyebrow">Training organizations</p><h1>Set up and collaborate through your provider workspace.</h1><p>In this phase you can create an organization, become its owner, invite approved instructors, accept invitations, and attribute new course drafts to an organization. Branding, public provider pages, provider analytics, and provider commercial reporting come later.</p></header>
    <section className="organization-panel"><header><p className="eyebrow">Create organization</p><h2>Set up your provider identity</h2><p>Creating an organization makes you its active Owner. Your existing individual courses and earnings stay unchanged. You can then invite approved instructors and choose this organization while creating a new course draft.</p></header><OrganizationCreateForm /></section>
    <section className="organization-panel"><header><p className="eyebrow">Your memberships</p><h2>Organization access</h2><p>Your role shows who you are within each provider workspace. The organization handle is stored now; it is not yet a public URL visitors can open.</p></header>{organizationManagement.length ? <div className="organization-list">{organizationManagement.map(({ organization, members, courses, invitations: ownerInvitations }) => <article className="organization-management-card" key={organization.organization_id}><div className="organization-identity"><strong>{organization.name}</strong><span>Organization handle: {organization.slug}</span><div className="organization-statuses"><span>Role: {organization.membership_role}</span><span>Membership: {organization.membership_status}</span><span>Organization: {organization.organization_status}</span></div></div><section className="organization-management-section"><h3>Team members</h3>{members.length ? <ul>{members.map((member) => <li key={`${member.member_id}-${member.granted_at}`}><span><strong>{member.full_name || member.email}</strong><small>{member.email}</small></span><span>{member.role} · {member.status}</span></li>)}</ul> : <p>No organization members were found.</p>}</section><section className="organization-management-section"><h3>Organization courses</h3>{courses.length ? <ul>{courses.map((course) => <li key={course.course_id}><span><strong>{course.title}</strong><small>Lead instructor: {course.instructor_name}</small></span><span>{course.status}</span></li>)}</ul> : <p>No course drafts have been attributed to this organization yet. Choose this organization when creating a new course.</p>}</section>{organization.membership_role === "owner" && organization.membership_status === "active" && organization.organization_status === "active" ? <><section className="organization-management-section"><h3>Sent invitations</h3>{ownerInvitations.length ? <ul>{ownerInvitations.map((invitation) => <li key={invitation.invitation_id}><span><strong>{invitation.invited_email}</strong><small>Sent {new Date(invitation.created_at).toLocaleDateString("en-NG")}</small></span><span>{invitation.role} · {invitation.status}</span></li>)}</ul> : <p>You have not invited an instructor yet.</p>}</section><section className="organization-management-section"><h3>Invite an instructor</h3><OrganizationInvitationForm organizationId={organization.organization_id} /></section></> : null}</article>)}</div> : <p className="organization-empty">You have not created or joined a training organization yet. Create one above, or ask an organization owner to invite your approved instructor account.</p>}</section>
    {invitations.length > 0 && <section className="organization-panel"><header><p className="eyebrow">Pending invitations</p><h2>Join a training organization</h2><p>Accepting an invitation adds you as an approved instructor member. It does not transfer course ownership or change earnings.</p></header><div className="organization-list">{invitations.map((invitation) => <article key={invitation.invitation_id}><div><strong>{invitation.organization_name}</strong><span>{invitation.role} invitation · expires {new Date(invitation.expires_at).toLocaleDateString("en-NG")}</span></div><OrganizationInvitationAcceptance invitationId={invitation.invitation_id} /></article>)}</div></section>}
  </section>;
}
