import "server-only";
import { renderGrowveltEmail } from "@/app/lib/email/growvelt-email-template";
import { createAdminClient } from "@/app/lib/supabase/admin";

type DeliveryStatus = "sent" | "not_configured" | "failed";

export async function sendCompanyInvitationEmail(input: { recipient: string; organizationName: string; inviterName: string | null; role: "admin" | "member"; invitationId: number; appBaseUrl: string }): Promise<DeliveryStatus> {
  const admin = createAdminClient(); const idempotencyKey = `growvelt-learning-company-invitation-${input.invitationId}`;
  const { data: claimed, error: claimError } = await admin.from("learning_company_notifications").upsert({ idempotency_key: idempotencyKey, invitation_id: input.invitationId, recipient_email: input.recipient.toLowerCase(), delivery_status: "pending" }, { onConflict: "idempotency_key", ignoreDuplicates: true }).select("id").maybeSingle();
  if (claimError) return "failed";
  if (!claimed) { const { data: existing } = await admin.from("learning_company_notifications").select("delivery_status").eq("idempotency_key", idempotencyKey).maybeSingle(); return existing?.delivery_status === "sent" ? "sent" : existing?.delivery_status === "not_configured" ? "not_configured" : "failed"; }
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) { await admin.from("learning_company_notifications").update({ delivery_status: "not_configured", last_error: "Email delivery is not configured", last_attempted_at: new Date().toISOString() }).eq("id", claimed.id); return "not_configured"; }
  const html = renderGrowveltEmail({ baseUrl: input.appBaseUrl, greeting: "there", title: "You’re invited to company learning", paragraphs: [`${input.inviterName || "Your company administrator"} invited you to join ${input.organizationName} as a ${input.role}.`, "Sign in or create your Growvelt account, then open Company learning to review the invitation."], primaryAction: { label: "View company invitation", href: new URL("/dashboard/company", input.appBaseUrl).href }, highlights: ["Review your company learning workspace", "Accept or decline from your dashboard", "Your personal learning activity remains your own"], reason: "You received this email because a company administrator invited you to a Growvelt Learning workspace." });
  try { const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, body: JSON.stringify({ from: "Growvelt <no-reply@growvelt.com>", to: [input.recipient], reply_to: "support@growvelt.com", subject: `You’re invited to ${input.organizationName} on Growvelt`, html, tags: [{ name: "category", value: "company_invitation" }, { name: "product", value: "learning" }] }), signal: AbortSignal.timeout(15000) }); const body = await response.json().catch(() => null) as { id?: string } | null; if (!response.ok) throw new Error(`provider_${response.status}`); await admin.from("learning_company_notifications").update({ delivery_status: "sent", provider_message_id: body?.id ?? null, attempt_count: 1, last_error: null, last_attempted_at: new Date().toISOString(), sent_at: new Date().toISOString() }).eq("id", claimed.id); return "sent"; } catch (error) { await admin.from("learning_company_notifications").update({ delivery_status: "failed", attempt_count: 1, last_error: error instanceof Error ? error.message.slice(0, 1000) : "Email delivery failed", last_attempted_at: new Date().toISOString() }).eq("id", claimed.id); return "failed"; }
}
