create or replace function public.reconcile_paystack_test_refunds()
returns table(issue_type text,order_reference text,detail text) language sql stable security definer set search_path to '' as $function$
 select 'processed_refund_without_ledger',o.order_reference,'Processed refund case has no reversal ledger' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and c.status='processed' and not exists(select 1 from public.learning_ledger_transactions t where t.payment_case_id=c.id and t.transaction_type='refund')
 union all select 'refund_ledger_without_processed_case',o.order_reference,'Refund ledger is not backed by a processed case' from public.learning_ledger_transactions t join public.learning_orders o on o.id=t.order_id left join public.learning_payment_cases c on c.id=t.payment_case_id where t.transaction_type='refund' and (c.id is null or c.status<>'processed')
 union all select 'refund_amount_mismatch',o.order_reference,'Processed refund amount differs from authoritative gross' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and c.status='processed' and (c.amount_minor<>o.gross_amount_minor or c.currency<>o.currency)
 union all select 'refund_ledger_imbalance',o.order_reference,'Refund ledger is unbalanced or does not contain exactly two entries' from public.learning_ledger_transactions t join public.learning_orders o on o.id=t.order_id left join public.learning_ledger_entries e on e.transaction_id=t.id where t.transaction_type='refund' group by o.id,o.order_reference,t.id having count(e.id)<>2 or coalesce(sum(e.amount_minor),0)<>0
 union all select 'duplicate_refund_reversal',o.order_reference,'Order has more than one refund reversal' from public.learning_ledger_transactions t join public.learning_orders o on o.id=t.order_id where t.transaction_type='refund' group by o.id,o.order_reference having count(*)>1
 union all select 'refund_exceeds_gross',o.order_reference,'Processed refund reversals exceed order gross' from public.learning_orders o join public.learning_payment_cases c on c.order_id=o.id and c.case_type='refund' and c.status='processed' group by o.id,o.order_reference,o.gross_amount_minor having sum(c.processed_amount_minor)>o.gross_amount_minor
 union all select 'refunded_order_active_entitlement',o.order_reference,'Refunded order retains active entitlement' from public.learning_orders o join public.learning_course_entitlements e on e.order_id=o.id and e.status='active' where o.status='refunded'
 union all select 'refunded_order_active_enrollment',o.order_reference,'Refunded order retains active/completed enrollment' from public.learning_orders o join public.learning_course_entitlements e on e.order_id=o.id join public.enrollments n on n.id=e.enrollment_id and n.status in('active','completed') where o.status='refunded'
 union all select 'failed_refund_with_reversal',o.order_reference,'Failed refund has an economic reversal' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id join public.learning_ledger_transactions t on t.payment_case_id=c.id and t.transaction_type='refund' where c.case_type='refund' and c.status='failed'
 union all select 'provider_processed_local_incomplete',o.order_reference,'Provider reports processed but local refund finalization is incomplete' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and c.provider_status='processed' and c.status<>'processed'
 union all select 'stale_refund_case',o.order_reference,'Refund case requires verification or operator attention' from public.learning_payment_cases c join public.learning_orders o on o.id=c.order_id where c.case_type='refund' and ((c.status in('pending','processing') and c.updated_at<now()-interval '2 hours') or (c.status='needs_attention' and c.updated_at<now()-interval '15 minutes'))
 union all select 'refund_provider_event_unresolved',o.order_reference,'Refund provider event is failed or stale' from public.learning_payment_provider_events e join public.learning_orders o on o.id=e.order_id where e.event_type like 'refund.%' and (e.processing_status='failed' or (e.processing_status='received' and e.received_at<now()-interval '5 minutes'));
$function$;
revoke all on function public.reconcile_paystack_test_refunds() from public, anon, authenticated;
grant execute on function public.reconcile_paystack_test_refunds() to postgres, service_role;
