create or replace function public.reconcile_paystack_test_learning_payments()
returns table(issue_type text,order_reference text,detail text) language sql stable security definer set search_path to '' as $function$
 select 'paid_without_successful_attempt',o.order_reference,'Paid order has no successful Paystack attempt' from public.learning_orders o where o.status in('paid','partially_refunded','refunded','chargeback') and not exists(select 1 from public.learning_payment_attempts a where a.order_id=o.id and a.provider='paystack' and a.status='succeeded')
 union all select 'paid_without_capture_ledger',o.order_reference,'Paid order has no payment-capture ledger transaction' from public.learning_orders o where o.status in('paid','partially_refunded','refunded','chargeback') and not exists(select 1 from public.learning_ledger_transactions t where t.order_id=o.id and t.transaction_type='payment_capture')
 union all select 'paid_without_entitlement',o.order_reference,'Paid order has no active entitlement' from public.learning_orders o where o.status='paid' and not exists(select 1 from public.learning_course_entitlements e where e.order_id=o.id and e.status='active')
 union all select 'entitlement_without_enrollment',o.order_reference,'Active entitlement has no active or completed enrollment' from public.learning_orders o join public.learning_course_entitlements e on e.order_id=o.id and e.status='active' where not exists(select 1 from public.enrollments n where n.id=e.enrollment_id and n.learner_id=e.learner_id and n.course_id=e.course_id and n.status in('active','completed'))
 union all select 'successful_attempt_unpaid_order',o.order_reference,'Successful attempt belongs to an unpaid order' from public.learning_orders o join public.learning_payment_attempts a on a.order_id=o.id where a.provider='paystack' and a.status='succeeded' and o.status not in('paid','partially_refunded','refunded','chargeback')
 union all select 'failed_provider_event',coalesce(o.order_reference,'unknown'),left(coalesce(ev.processing_error,'Provider event processing failed'),1000) from public.learning_payment_provider_events ev left join public.learning_orders o on o.id=ev.order_id where ev.provider='paystack' and ev.processing_status='failed';
$function$;
revoke all on function public.reconcile_paystack_test_learning_payments() from public,anon,authenticated;
grant execute on function public.reconcile_paystack_test_learning_payments() to postgres,service_role;
