"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

type Verification = { status: "pending" | "verified" | "rejected"; legal_name: string; contact_email: string; website_url: string | null; verification_statement: string; reviewed_at: string | null; review_note: string | null } | undefined;

export function OrganizationVerificationForm({ organizationId, verification }: { organizationId: number; verification: Verification }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  if (verification?.status === "verified") return <p className="organization-verification-status is-verified" role="status">Provider verification approved{verification.reviewed_at ? ` on ${new Date(verification.reviewed_at).toLocaleDateString("en-NG")}` : ""}. This is an internal provider status; no public provider profile is published yet.</p>;
  if (verification?.status === "pending") return <p className="organization-verification-status" role="status">Provider verification is pending Learning Admin review. We will keep your provider details private while it is reviewed.</p>;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending) return; const form = new FormData(event.currentTarget); setPending(true); setMessage(null); try { const response = await fetch(`/api/instructor/organizations/${organizationId}/verification`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ legalName: String(form.get("legalName") ?? ""), contactEmail: String(form.get("contactEmail") ?? ""), websiteUrl: String(form.get("websiteUrl") ?? ""), statement: String(form.get("statement") ?? "") }) }); if (!response.ok) throw new Error((await response.json().catch(() => null) as { code?: string } | null)?.code ?? "verification_unavailable"); setMessage("Verification request sent to Learning Admin for review."); router.refresh(); } catch (error) { const code = error instanceof Error ? error.message : "verification_unavailable"; setMessage(code === "owner_required" ? "Only the active organization owner can submit provider verification." : code === "invalid_verification" ? "Check the required details and try again." : "We could not submit provider verification right now. Please try again."); } finally { setPending(false); } }
  return <form className="organization-verification-form" onSubmit={submit}><label className="course-field">Registered or legal provider name<input name="legalName" defaultValue={verification?.legal_name} minLength={2} maxLength={160} required /></label><label className="course-field">Provider contact email<input name="contactEmail" type="email" defaultValue={verification?.contact_email} maxLength={320} required /></label><label className="course-field">Website (optional)<input name="websiteUrl" type="url" defaultValue={verification?.website_url ?? ""} placeholder="https://example.com" maxLength={400} /></label><label className="course-field">Verification statement<textarea name="statement" defaultValue={verification?.verification_statement} minLength={30} maxLength={2000} rows={5} required placeholder="Confirm your authority to represent this provider and explain what it offers learners." /><span>At least 30 characters. Do not include identity documents, bank details, or sensitive personal information here.</span></label>{verification?.status === "rejected" && <p className="organization-verification-status is-rejected">Previous review: {verification.review_note || "Not approved"}. Update the details and resubmit when ready.</p>}<button className="button button-primary" type="submit" disabled={pending}>{pending ? "Sending…" : verification ? "Resubmit verification" : "Submit for verification"}</button>{message && <p className={message.startsWith("Verification request") ? "payout-profile-feedback" : "payout-profile-feedback is-error"} role="status">{message}</p>}</form>;
}
