"use client";
import { useState } from "react";

type Dispute={caseId:number;status:string;amountMinor:number;currency:string;providerCaseId:string;providerStatus:string|null;resolution:string|null;category:string|null;reason:string|null;deadline:string|null;events:Array<{event_id:number;normalized_status:string;provenance:string;note:string|null;created_at:string}>};
export function PaymentDisputeSummary({dispute}:{dispute:Dispute}){
 const[pending,setPending]=useState(false);const[message,setMessage]=useState("");const terminal=["won","lost"].includes(dispute.status);
 async function recover(){setPending(true);setMessage("");try{const response=await fetch("/api/admin/payments/dispute/recover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({caseId:dispute.caseId})});const result=await response.json().catch(()=>null)as{outcome?:string;message?:string}|null;setMessage(response.ok?`Dispute verification: ${result?.outcome??"verified"}`:result?.message??"Dispute verification failed.");if(response.ok)setTimeout(()=>window.location.reload(),700);}catch{setMessage("Dispute verification failed.");}finally{setPending(false);}}
 return <div className="payment-refund-control"><p><strong>Dispute:</strong> {dispute.status}{dispute.providerStatus?` · ${dispute.providerStatus}`:""}</p><p><small>{dispute.currency} {(dispute.amountMinor/100).toLocaleString("en-NG",{minimumFractionDigits:2})} · Paystack dispute {dispute.providerCaseId}</small></p>{dispute.category||dispute.reason?<p><small>{[dispute.category,dispute.reason].filter(Boolean).join(" — ")}</small></p>:null}{dispute.deadline?<p><strong>Response deadline:</strong> <time dateTime={dispute.deadline}>{new Intl.DateTimeFormat("en-NG",{dateStyle:"medium",timeStyle:"short"}).format(new Date(dispute.deadline))}</time></p>:null}{dispute.resolution?<p><strong>Outcome:</strong> {dispute.resolution}</p>:null}<details><summary>Dispute timeline</summary><ol className="payment-refund-timeline">{dispute.events.map(event=><li key={event.event_id}><strong>{event.normalized_status}</strong><span>{event.provenance} · {new Intl.DateTimeFormat("en-NG",{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.created_at))}</span>{event.note?<span>{event.note}</span>:null}</li>)}</ol></details>{!terminal?<button className="button button-secondary" type="button" onClick={recover} disabled={pending}>{pending?"Verifying dispute…":"Verify dispute"}</button>:null}{message?<p role="status">{message}</p>:null}</div>;
}
