"use client";
import { useMemo, useState } from "react";

type ExistingCase = { caseId: number; status: string; providerStatus: string | null; providerCaseId: string | null; providerReference: string | null; events: Array<{ event_id: number; event_type: string; normalized_status: string; provenance: string; note: string | null; created_at: string }> };

export function PaymentRefundControl({ reference, orderStatus, enabled, existingCase }: { reference: string; orderStatus: string; enabled: boolean; existingCase?: ExistingCase }) {
  const [open, setOpen] = useState(false); const [confirmation, setConfirmation] = useState(""); const [reasonCode, setReasonCode] = useState("customer_request"); const [note, setNote] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState("");
  const idempotencyKey = useMemo(() => crypto.randomUUID(), []);
  async function submit() {
    setPending(true); setMessage("");
    try { const response = await fetch("/api/admin/payments/refund", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference, confirmation, reasonCode, note, idempotencyKey }) }); const result = await response.json().catch(() => null) as { outcome?: string; message?: string } | null; setMessage(response.ok ? `Refund status: ${result?.outcome ?? "submitted"}` : result?.message ?? "Refund could not be initiated."); if (response.ok) setTimeout(() => window.location.reload(), 700); } catch { setMessage("Refund could not be initiated."); } finally { setPending(false); }
  }
  async function recover() {
    if (!existingCase?.providerCaseId) return; setPending(true); setMessage("");
    try { const response = await fetch("/api/admin/payments/refund/recover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ caseId: existingCase.caseId }) }); const result = await response.json().catch(() => null) as { outcome?: string; message?: string } | null; setMessage(response.ok ? `Refund verification: ${result?.outcome ?? "verified"}` : result?.message ?? "Refund verification failed."); if (response.ok) setTimeout(() => window.location.reload(), 700); } catch { setMessage("Refund verification failed."); } finally { setPending(false); }
  }
  if (existingCase) return <div className="payment-refund-control"><p><strong>Refund:</strong> {existingCase.status}{existingCase.providerStatus ? ` · ${existingCase.providerStatus}` : ""}</p>{existingCase.providerReference ? <p><small>Provider reference: {existingCase.providerReference}</small></p> : null}<details><summary>Refund timeline</summary><ol className="payment-refund-timeline">{existingCase.events.map((event) => <li key={event.event_id}><strong>{event.normalized_status}</strong><span>{event.provenance} · {new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.created_at))}</span>{event.note ? <span>{event.note}</span> : null}</li>)}</ol></details>{existingCase.providerCaseId && !["processed", "failed", "cancelled"].includes(existingCase.status) ? <button className="button button-secondary" type="button" onClick={recover} disabled={pending || !enabled}>{pending ? "Verifying refund…" : "Verify refund"}</button> : null}{message ? <p role="status">{message}</p> : null}</div>;
  if (orderStatus !== "paid") return null;
  if (!enabled) return <p className="payment-refund-disabled">Full refunds are operationally disabled.</p>;
  return <div className="payment-refund-control">{!open ? <button className="button button-secondary" type="button" onClick={() => setOpen(true)}>Full refund</button> : <div className="payment-refund-form"><p><strong>Confirm an irreversible full refund request</strong></p><label>Reason<select value={reasonCode} onChange={(event) => setReasonCode(event.target.value)}><option value="customer_request">Customer request</option><option value="course_unavailable">Course unavailable</option><option value="duplicate_payment">Duplicate payment</option><option value="exceptional_admin_refund">Exceptional admin refund</option></select></label><label>Operator note<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} /></label><label>Type the exact order reference<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder={reference} /></label><div><button className="button button-danger" type="button" onClick={submit} disabled={pending || confirmation !== reference || note.trim().length < 3}>{pending ? "Submitting refund…" : "Submit full refund"}</button><button className="button button-secondary" type="button" onClick={() => setOpen(false)} disabled={pending}>Cancel</button></div>{message ? <p role="status">{message}</p> : null}</div>}</div>;
}
