export const localeCookieName = "growvelt-learning-locale";
export const supportedLocales = ["en", "fr", "es"] as const;
export type Locale = (typeof supportedLocales)[number];

export type LanguageOption = { code: Locale; label: string; shortLabel: string };
export const languageOptions: LanguageOption[] = [
  { code: "en", label: "English (Global)", shortLabel: "English" },
  { code: "fr", label: "Français", shortLabel: "Français" },
  { code: "es", label: "Español", shortLabel: "Español" },
];

export function normalizeLocale(value?: string | null): Locale {
  return supportedLocales.includes(value as Locale) ? value as Locale : "en";
}

const messages = {
  en: {
    "language.label": "Language & region", "language.browserRegion": "Language is saved for this device. Dates and formats follow your browser region.",
    "nav.home": "Home", "nav.learning": "My Learning", "nav.explore": "Explore catalog", "nav.jobs": "Jobs", "nav.saved": "Saved Courses", "nav.certificates": "Certificates", "nav.instructor": "Instructor workspace", "nav.courses": "My Courses", "nav.createCourse": "Create Course", "nav.instructorReviews": "Instructor Reviews", "nav.courseReviews": "Course Reviews", "nav.teach": "Teach on Growvelt", "nav.profile": "Profile", "nav.settings": "Settings", "nav.signOut": "Sign out",
    "settings.eyebrow": "Preferences and controls", "settings.title": "Your Learning settings.", "settings.summary": "Manage your profile, access, appearance, and account security from one place.", "settings.account": "Learning account", "settings.signedIn": "Signed in", "settings.access": "Account access", "settings.manageProfile": "Manage profile", "settings.language": "Language & region", "settings.languageTitle": "Choose your display language", "settings.languageCopy": "This changes Growvelt Learning interface text. Course and instructor-created content remains in its original language.", "settings.appearance": "Appearance", "settings.appearanceTitle": "Choose your preferred view", "settings.appearanceCopy": "Your theme choice is saved locally on this device.", "settings.profile": "Profile", "settings.profileTitle": "How you appear in Learning", "settings.editProfile": "Edit profile", "settings.security": "Account security", "settings.securityTitle": "Change your password", "settings.securityCopy": "Use the secure recovery flow to set a new password. Google sign-in accounts can manage their password with Google.", "settings.resetPassword": "Reset password", "settings.danger": "Danger zone", "settings.deleteTitle": "Delete your account", "settings.deleteCopy": "Permanently remove your Learning profile and related account data. This action cannot be undone.", "settings.delete": "Delete account", "settings.roleAdmin": "Learning Administrator", "settings.roleInstructor": "Approved Instructor", "settings.roleApplicant": "Instructor applicant", "settings.roleLearner": "Learner", "settings.adminCopy": "You can review approved Growvelt Learning operations.", "settings.instructorCopy": "You can create and manage courses while continuing to learn.", "settings.applicantCopy": "Your Instructor application is under review. You can continue learning while you wait.", "settings.learnerCopy": "Learn practical skills, track progress, and apply to teach when you are ready.", "settings.openWorkspace": "Open Instructor workspace", "settings.viewApplication": "View application",
    "theme.label": "Appearance preference", "theme.light": "Light", "theme.dark": "Dark", "theme.system": "System",
    "delete.eyebrow": "Account deletion", "delete.before": "Before you delete your account", "delete.confirmTitle": "Delete your Learning account?", "delete.intro": "Your feedback helps us improve Growvelt Learning.", "delete.reason": "Why are you leaving?", "delete.more": "Tell us more", "delete.placeholder": "Share anything that would have made your experience better.", "delete.optional": "Optional unless you select Other.", "delete.cancel": "Cancel", "delete.continue": "Continue", "delete.back": "Back", "delete.confirmInstruction": "Type DELETE to confirm", "delete.confirmCopy": "Deleting your account permanently removes your Learning profile and any related account data configured to cascade with it. This cannot be undone.", "delete.permanent": "Permanently delete account", "delete.pending": "Deleting account…", "delete.choose": "Choose at least one reason before continuing.", "delete.otherRequired": "Briefly tell us why you are leaving.", "delete.typeDelete": "Type DELETE exactly to confirm account deletion.", "delete.notConfigured": "Account deletion is not configured on this deployment yet.", "delete.notSignedIn": "Your session has expired. Please sign in again before deleting your account.", "delete.failed": "We couldn’t complete the deletion. Please try again or contact support.", "delete.reasonUnused": "I no longer use Growvelt Learning", "delete.reasonAlternative": "I prefer another learning platform", "delete.reasonTechnical": "I had a technical issue", "delete.reasonPrivacy": "I have privacy concerns", "delete.reasonAnother": "I created another account", "delete.reasonOther": "Other",
  },
  fr: {
    "language.label": "Langue et région", "language.browserRegion": "La langue est enregistrée sur cet appareil. Les dates et formats suivent les réglages de votre navigateur.",
    "nav.home": "Accueil", "nav.learning": "Mon apprentissage", "nav.explore": "Explorer le catalogue", "nav.jobs": "Emplois", "nav.saved": "Cours enregistrés", "nav.certificates": "Certificats", "nav.instructor": "Espace formateur", "nav.courses": "Mes cours", "nav.createCourse": "Créer un cours", "nav.instructorReviews": "Examens des formateurs", "nav.courseReviews": "Examens des cours", "nav.teach": "Enseigner sur Growvelt", "nav.profile": "Profil", "nav.settings": "Paramètres", "nav.signOut": "Se déconnecter",
    "settings.eyebrow": "Préférences et contrôles", "settings.title": "Vos paramètres Learning.", "settings.summary": "Gérez votre profil, vos accès, votre apparence et la sécurité de votre compte au même endroit.", "settings.account": "Compte Learning", "settings.signedIn": "Connecté", "settings.access": "Accès au compte", "settings.manageProfile": "Gérer le profil", "settings.language": "Langue et région", "settings.languageTitle": "Choisissez votre langue d’affichage", "settings.languageCopy": "Cela modifie le texte de l’interface Growvelt Learning. Le contenu des cours et celui créé par les formateurs reste dans sa langue d’origine.", "settings.appearance": "Apparence", "settings.appearanceTitle": "Choisissez votre affichage", "settings.appearanceCopy": "Votre thème est enregistré localement sur cet appareil.", "settings.profile": "Profil", "settings.profileTitle": "Votre apparence dans Learning", "settings.editProfile": "Modifier le profil", "settings.security": "Sécurité du compte", "settings.securityTitle": "Modifier votre mot de passe", "settings.securityCopy": "Utilisez le flux de récupération sécurisé pour définir un nouveau mot de passe. Les comptes Google gèrent leur mot de passe avec Google.", "settings.resetPassword": "Réinitialiser le mot de passe", "settings.danger": "Zone dangereuse", "settings.deleteTitle": "Supprimer votre compte", "settings.deleteCopy": "Supprimez définitivement votre profil Learning et les données associées. Cette action est irréversible.", "settings.delete": "Supprimer le compte", "settings.roleAdmin": "Administrateur Learning", "settings.roleInstructor": "Formateur approuvé", "settings.roleApplicant": "Candidat formateur", "settings.roleLearner": "Apprenant", "settings.adminCopy": "Vous pouvez examiner les opérations approuvées de Growvelt Learning.", "settings.instructorCopy": "Vous pouvez créer et gérer des cours tout en continuant à apprendre.", "settings.applicantCopy": "Votre candidature de formateur est en cours d’examen. Vous pouvez continuer à apprendre en attendant.", "settings.learnerCopy": "Développez des compétences pratiques, suivez vos progrès et postulez pour enseigner quand vous êtes prêt.", "settings.openWorkspace": "Ouvrir l’espace formateur", "settings.viewApplication": "Voir la candidature",
    "theme.label": "Préférence d’apparence", "theme.light": "Clair", "theme.dark": "Sombre", "theme.system": "Système",
    "delete.eyebrow": "Suppression du compte", "delete.before": "Avant de supprimer votre compte", "delete.confirmTitle": "Supprimer votre compte Learning ?", "delete.intro": "Vos commentaires nous aident à améliorer Growvelt Learning.", "delete.reason": "Pourquoi partez-vous ?", "delete.more": "Dites-nous en plus", "delete.placeholder": "Partagez ce qui aurait pu améliorer votre expérience.", "delete.optional": "Facultatif sauf si vous sélectionnez Autre.", "delete.cancel": "Annuler", "delete.continue": "Continuer", "delete.back": "Retour", "delete.confirmInstruction": "Saisissez DELETE pour confirmer", "delete.confirmCopy": "La suppression de votre compte retire définitivement votre profil Learning et les données associées configurées pour être supprimées. Cette action est irréversible.", "delete.permanent": "Supprimer définitivement le compte", "delete.pending": "Suppression du compte…", "delete.choose": "Choisissez au moins un motif avant de continuer.", "delete.otherRequired": "Indiquez brièvement pourquoi vous partez.", "delete.typeDelete": "Saisissez DELETE exactement pour confirmer la suppression.", "delete.notConfigured": "La suppression du compte n’est pas encore configurée pour ce déploiement.", "delete.notSignedIn": "Votre session a expiré. Connectez-vous à nouveau avant de supprimer votre compte.", "delete.failed": "Nous n’avons pas pu terminer la suppression. Réessayez ou contactez l’assistance.", "delete.reasonUnused": "Je n’utilise plus Growvelt Learning", "delete.reasonAlternative": "Je préfère une autre plateforme d’apprentissage", "delete.reasonTechnical": "J’ai rencontré un problème technique", "delete.reasonPrivacy": "J’ai des préoccupations concernant la confidentialité", "delete.reasonAnother": "J’ai créé un autre compte", "delete.reasonOther": "Autre",
  },
  es: {
    "language.label": "Idioma y región", "language.browserRegion": "El idioma se guarda en este dispositivo. Las fechas y formatos siguen la configuración regional de tu navegador.",
    "nav.home": "Inicio", "nav.learning": "Mi aprendizaje", "nav.explore": "Explorar catálogo", "nav.jobs": "Empleos", "nav.saved": "Cursos guardados", "nav.certificates": "Certificados", "nav.instructor": "Espacio de instructor", "nav.courses": "Mis cursos", "nav.createCourse": "Crear curso", "nav.instructorReviews": "Revisiones de instructores", "nav.courseReviews": "Revisiones de cursos", "nav.teach": "Enseñar en Growvelt", "nav.profile": "Perfil", "nav.settings": "Configuración", "nav.signOut": "Cerrar sesión",
    "settings.eyebrow": "Preferencias y controles", "settings.title": "Tu configuración de Learning.", "settings.summary": "Administra tu perfil, acceso, apariencia y seguridad de la cuenta desde un solo lugar.", "settings.account": "Cuenta Learning", "settings.signedIn": "Sesión iniciada", "settings.access": "Acceso a la cuenta", "settings.manageProfile": "Administrar perfil", "settings.language": "Idioma y región", "settings.languageTitle": "Elige tu idioma de visualización", "settings.languageCopy": "Esto cambia el texto de la interfaz de Growvelt Learning. El contenido de cursos y creado por instructores permanece en su idioma original.", "settings.appearance": "Apariencia", "settings.appearanceTitle": "Elige tu vista preferida", "settings.appearanceCopy": "Tu tema se guarda localmente en este dispositivo.", "settings.profile": "Perfil", "settings.profileTitle": "Cómo apareces en Learning", "settings.editProfile": "Editar perfil", "settings.security": "Seguridad de la cuenta", "settings.securityTitle": "Cambia tu contraseña", "settings.securityCopy": "Usa el flujo seguro de recuperación para establecer una nueva contraseña. Las cuentas de Google pueden gestionar su contraseña con Google.", "settings.resetPassword": "Restablecer contraseña", "settings.danger": "Zona de peligro", "settings.deleteTitle": "Elimina tu cuenta", "settings.deleteCopy": "Elimina permanentemente tu perfil Learning y los datos relacionados. Esta acción no se puede deshacer.", "settings.delete": "Eliminar cuenta", "settings.roleAdmin": "Administrador de Learning", "settings.roleInstructor": "Instructor aprobado", "settings.roleApplicant": "Solicitante de instructor", "settings.roleLearner": "Estudiante", "settings.adminCopy": "Puedes revisar operaciones aprobadas de Growvelt Learning.", "settings.instructorCopy": "Puedes crear y administrar cursos mientras sigues aprendiendo.", "settings.applicantCopy": "Tu solicitud de instructor está en revisión. Puedes seguir aprendiendo mientras esperas.", "settings.learnerCopy": "Desarrolla habilidades prácticas, sigue tu progreso y solicita enseñar cuando estés listo.", "settings.openWorkspace": "Abrir espacio de instructor", "settings.viewApplication": "Ver solicitud",
    "theme.label": "Preferencia de apariencia", "theme.light": "Claro", "theme.dark": "Oscuro", "theme.system": "Sistema",
    "delete.eyebrow": "Eliminación de cuenta", "delete.before": "Antes de eliminar tu cuenta", "delete.confirmTitle": "¿Eliminar tu cuenta Learning?", "delete.intro": "Tus comentarios nos ayudan a mejorar Growvelt Learning.", "delete.reason": "¿Por qué te vas?", "delete.more": "Cuéntanos más", "delete.placeholder": "Comparte lo que habría mejorado tu experiencia.", "delete.optional": "Opcional, salvo que selecciones Otro.", "delete.cancel": "Cancelar", "delete.continue": "Continuar", "delete.back": "Volver", "delete.confirmInstruction": "Escribe DELETE para confirmar", "delete.confirmCopy": "Eliminar tu cuenta borra permanentemente tu perfil Learning y los datos relacionados configurados para eliminarse en cascada. Esta acción no se puede deshacer.", "delete.permanent": "Eliminar cuenta permanentemente", "delete.pending": "Eliminando cuenta…", "delete.choose": "Elige al menos un motivo antes de continuar.", "delete.otherRequired": "Cuéntanos brevemente por qué te vas.", "delete.typeDelete": "Escribe DELETE exactamente para confirmar la eliminación.", "delete.notConfigured": "La eliminación de cuentas aún no está configurada para esta implementación.", "delete.notSignedIn": "Tu sesión ha caducado. Inicia sesión otra vez antes de eliminar tu cuenta.", "delete.failed": "No pudimos completar la eliminación. Inténtalo de nuevo o contacta a soporte.", "delete.reasonUnused": "Ya no uso Growvelt Learning", "delete.reasonAlternative": "Prefiero otra plataforma de aprendizaje", "delete.reasonTechnical": "Tuve un problema técnico", "delete.reasonPrivacy": "Tengo inquietudes sobre privacidad", "delete.reasonAnother": "Creé otra cuenta", "delete.reasonOther": "Otro",
  },
} as const;

export type TranslationKey = keyof typeof messages.en;
export function translate(locale: Locale, key: TranslationKey) { return messages[locale][key] ?? messages.en[key]; }
