-- Public Growvelt Learning contact and partnership inquiries.
-- Forward-only. This migration is intentionally not executed by the app.

begin;

do $$
begin
  if to_regnamespace('public') is null then
    raise exception 'Public Learning inquiries aborted: public schema is missing';
  end if;

  if to_regclass('public.learning_public_inquiries') is not null
    or to_regprocedure('public.submit_public_learning_inquiry(text,text,text,text,text,text,text,text)') is not null then
    raise exception 'Public Learning inquiries aborted: partial inquiry state already exists';
  end if;
end;
$$;

create table public.learning_public_inquiries (
  id bigint generated by default as identity primary key,
  inquiry_type text not null check (inquiry_type in ('contact', 'partnership')),
  full_name text not null check (char_length(full_name) between 2 and 160),
  email text not null check (char_length(email) between 3 and 254),
  subject text not null check (char_length(subject) between 2 and 160),
  message text not null check (char_length(message) between 20 and 5000),
  organization text check (organization is null or char_length(organization) between 2 and 160),
  phone text check (phone is null or char_length(phone) between 3 and 32),
  source_page text not null default 'learn.growvelt.com',
  created_at timestamptz not null default now()
);

alter table public.learning_public_inquiries enable row level security;

create index learning_public_inquiries_type_created_at_idx
  on public.learning_public_inquiries (inquiry_type, created_at desc, id desc);

revoke all on table public.learning_public_inquiries from public, anon, authenticated;

create function public.submit_public_learning_inquiry(
  p_inquiry_type text,
  p_name text,
  p_email text,
  p_subject text,
  p_message text,
  p_organization text default null,
  p_phone text default null,
  p_website text default null
)
returns table (
  inquiry_id bigint,
  submitted_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_type text := lower(btrim(coalesce(p_inquiry_type, '')));
  normalized_name text := btrim(coalesce(p_name, ''));
  normalized_email text := lower(btrim(coalesce(p_email, '')));
  normalized_subject text := btrim(coalesce(p_subject, ''));
  normalized_message text := btrim(coalesce(p_message, ''));
  normalized_organization text := nullif(btrim(coalesce(p_organization, '')), '');
  normalized_phone text := nullif(btrim(coalesce(p_phone, '')), '');
  inserted_id bigint;
  inserted_at timestamptz;
begin
  if nullif(btrim(coalesce(p_website, '')), '') is not null then
    raise exception 'Unable to submit this message' using errcode = '22023';
  end if;

  if normalized_type not in ('contact', 'partnership')
    or char_length(normalized_name) not between 2 and 160
    or char_length(normalized_email) not between 3 and 254
    or normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    or char_length(normalized_subject) not between 2 and 160
    or char_length(normalized_message) not between 20 and 5000
    or (normalized_organization is not null and char_length(normalized_organization) not between 2 and 160)
    or (normalized_phone is not null and char_length(normalized_phone) not between 3 and 32)
    or (normalized_type = 'partnership' and normalized_organization is null) then
    raise exception 'Invalid public inquiry' using errcode = '22023';
  end if;

  insert into public.learning_public_inquiries (
    inquiry_type,
    full_name,
    email,
    subject,
    message,
    organization,
    phone,
    source_page
  )
  values (
    normalized_type,
    normalized_name,
    normalized_email,
    normalized_subject,
    normalized_message,
    normalized_organization,
    normalized_phone,
    'learn.growvelt.com'
  )
  returning learning_public_inquiries.id, learning_public_inquiries.created_at
    into inserted_id, inserted_at;

  return query select inserted_id, inserted_at;
end;
$$;

revoke execute on function public.submit_public_learning_inquiry(text, text, text, text, text, text, text, text) from public;
grant execute on function public.submit_public_learning_inquiry(text, text, text, text, text, text, text, text) to anon, authenticated;

do $$
declare
  inquiry_relation regclass := 'public.learning_public_inquiries'::regclass;
  inquiry_function regprocedure := 'public.submit_public_learning_inquiry(text,text,text,text,text,text,text,text)'::regprocedure;
  mismatch_row record;
begin
  if not (select relation_row.relrowsecurity from pg_class as relation_row where relation_row.oid = inquiry_relation) then
    raise exception 'Public Learning inquiries aborted: RLS is not enabled';
  end if;

  if has_table_privilege('anon', inquiry_relation, 'SELECT, INSERT, UPDATE, DELETE')
    or has_table_privilege('authenticated', inquiry_relation, 'SELECT, INSERT, UPDATE, DELETE') then
    raise exception 'Public Learning inquiries aborted: browser table access is unexpectedly granted';
  end if;

  if not exists (
    select 1
    from pg_proc as procedure_row
    where procedure_row.oid = inquiry_function
      and procedure_row.prosecdef
      and exists (
        select 1
        from unnest(coalesce(procedure_row.proconfig, array[]::text[])) as setting_row(setting_value)
        where split_part(setting_row.setting_value, '=', 1) = 'search_path'
          and replace(split_part(setting_row.setting_value, '=', 2), '"', '') = ''
      )
  ) then
    raise exception 'Public Learning inquiries aborted: inquiry function security configuration is unexpected';
  end if;

  if has_function_privilege('public', inquiry_function, 'EXECUTE')
    or not has_function_privilege('anon', inquiry_function, 'EXECUTE')
    or not has_function_privilege('authenticated', inquiry_function, 'EXECUTE') then
    raise exception 'Public Learning inquiries aborted: inquiry function grants are unexpected';
  end if;

  for mismatch_row in
    with expected_outputs(output_position, output_name, output_type) as (
      values
        (1, 'inquiry_id'::text, 'bigint'::regtype::oid),
        (2, 'submitted_at'::text, 'timestamptz'::regtype::oid)
    ), actual_outputs as (
      select
        row_number() over (order by argument_row.ordinality)::integer as output_position,
        argument_row.output_name::text,
        argument_row.output_type
      from pg_proc as procedure_row
      cross join lateral unnest(procedure_row.proallargtypes, procedure_row.proargmodes, procedure_row.proargnames)
        with ordinality as argument_row(output_type, output_mode, output_name, ordinality)
      where procedure_row.oid = inquiry_function
        and argument_row.output_mode in ('t'::"char", 'o'::"char")
    )
    select
      coalesce(expected_outputs.output_position, actual_outputs.output_position) as output_position,
      expected_outputs.output_name as expected_name,
      expected_outputs.output_type as expected_type,
      actual_outputs.output_name as actual_name,
      actual_outputs.output_type as actual_type
    from expected_outputs
    full join actual_outputs
      on actual_outputs.output_position = expected_outputs.output_position
    where expected_outputs.output_position is null
      or actual_outputs.output_position is null
      or expected_outputs.output_name is distinct from actual_outputs.output_name
      or expected_outputs.output_type is distinct from actual_outputs.output_type
    order by coalesce(expected_outputs.output_position, actual_outputs.output_position)
    limit 1
  loop
    raise exception 'Public Learning inquiries aborted: return contract mismatch at output position %, expected % (%), actual % (%)',
      mismatch_row.output_position,
      coalesce(mismatch_row.expected_name, '<none>'),
      coalesce(mismatch_row.expected_type::regtype::text, '<none>'),
      coalesce(mismatch_row.actual_name, '<none>'),
      coalesce(mismatch_row.actual_type::regtype::text, '<none>');
  end loop;
end;
$$;

commit;
