-- Growvelt Learning Phase 2B-E: secure certificate issuance and verification.
-- Forward-only. This MVP requires the legacy certificates table to be empty.
begin;

do $$
begin
  if to_regclass('public.certificates') is null then raise exception 'Certificate issuance aborted: certificates table is missing'; end if;
  if exists (select 1 from public.certificates) then raise exception 'Certificate issuance aborted: legacy certificate rows require a separately reviewed backfill'; end if;
  if exists (select 1 from pg_class as relation_row join pg_namespace as namespace_row on namespace_row.oid=relation_row.relnamespace where namespace_row.nspname='public' and relation_row.relname='certificates' and not relation_row.relrowsecurity) then raise exception 'Certificate issuance aborted: certificates RLS must remain enabled'; end if;
  if (select count(*) from information_schema.columns where table_schema='public' and table_name='certificates' and ((column_name='id' and data_type='bigint') or (column_name='learner_id' and data_type='uuid' and is_nullable='NO') or (column_name='course_id' and data_type='bigint' and is_nullable='NO') or (column_name='certificate_code' and data_type='text' and is_nullable='NO') or (column_name='issued_at' and data_type='timestamp with time zone' and is_nullable='NO'))) <> 5 then raise exception 'Certificate issuance aborted: baseline certificate columns are unexpected'; end if;
  if not exists (select 1 from pg_constraint as constraint_row join pg_index as index_row on index_row.indexrelid=constraint_row.conindid where constraint_row.conrelid='public.certificates'::regclass and constraint_row.contype='u' and (select array_agg(attribute_row.attname::text order by key_column.ordinality) from unnest(index_row.indkey) with ordinality as key_column(attnum,ordinality) join pg_attribute as attribute_row on attribute_row.attrelid=index_row.indrelid and attribute_row.attnum=key_column.attnum where key_column.ordinality<=index_row.indnkeyatts)=array['learner_id','course_id']::text[])
    or not exists (select 1 from pg_index as index_row where index_row.indrelid='public.certificates'::regclass and index_row.indisunique and (select array_agg(attribute_row.attname::text order by key_column.ordinality) from unnest(index_row.indkey) with ordinality as key_column(attnum,ordinality) join pg_attribute as attribute_row on attribute_row.attrelid=index_row.indrelid and attribute_row.attnum=key_column.attnum where key_column.ordinality<=index_row.indnkeyatts)=array['certificate_code']::text[]) then raise exception 'Certificate issuance aborted: certificate uniqueness baseline is missing'; end if;
  if not exists (select 1 from pg_constraint as constraint_row where constraint_row.conrelid='public.certificates'::regclass and constraint_row.contype='f' and constraint_row.confrelid='public.profiles'::regclass and constraint_row.confdeltype='c') or not exists (select 1 from pg_constraint as constraint_row where constraint_row.conrelid='public.certificates'::regclass and constraint_row.contype='f' and constraint_row.confrelid='public.learning_courses'::regclass and constraint_row.confdeltype='c') then raise exception 'Certificate issuance aborted: expected cascade foreign keys are missing'; end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='certificates' and column_name in ('learner_name','course_title','instructor_name','completed_at','status','revoked_at')) then raise exception 'Certificate issuance aborted: partial Phase 2B-E column state exists'; end if;
  if to_regprocedure('public.get_own_learning_certificate_state(bigint)') is not null or to_regprocedure('public.issue_own_learning_certificate(bigint)') is not null or to_regprocedure('public.list_own_learning_certificates()') is not null or to_regprocedure('public.get_own_learning_certificate(text)') is not null or to_regprocedure('public.verify_learning_certificate(text)') is not null then raise exception 'Certificate issuance aborted: partial Phase 2B-E RPC state exists'; end if;
end; $$;

alter table public.certificates add column learner_name text not null, add column course_title text not null, add column instructor_name text, add column completed_at timestamptz not null, add column status text not null default 'issued', add column revoked_at timestamptz;
alter table public.certificates add constraint certificates_status_check check (status in ('issued','revoked')), add constraint certificates_revocation_check check ((status='issued' and revoked_at is null) or (status='revoked' and revoked_at is not null));

revoke select, insert, update, delete on table public.certificates from public, anon, authenticated;
do $$ declare certificate_columns text; begin select string_agg(format('%I',attribute_row.attname),', ' order by attribute_row.attnum) into certificate_columns from pg_attribute as attribute_row where attribute_row.attrelid='public.certificates'::regclass and attribute_row.attnum>0 and not attribute_row.attisdropped; execute format('revoke insert (%1$s), update (%1$s) on table public.certificates from public, anon, authenticated',certificate_columns); end; $$;

create function public.get_own_learning_certificate_state(p_course_id bigint) returns table (is_eligible boolean, certificate_code text, certificate_status text) language plpgsql security definer stable set search_path='' as $$ declare eligible_count integer; done_count integer; begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; select count(lesson_row.id)::integer,count(lesson_row.id) filter(where progress_row.completed_at is not null and progress_row.progress_percent=100)::integer into eligible_count,done_count from public.enrollments as enrollment_row join public.learning_courses as course_row on course_row.id=enrollment_row.course_id and course_row.status='published' join public.course_modules as module_row on module_row.course_id=course_row.id join public.lessons as lesson_row on lesson_row.course_id=course_row.id and lesson_row.module_id=module_row.id and lesson_row.lesson_type in ('text','video') left join public.lesson_progress as progress_row on progress_row.enrollment_id=enrollment_row.id and progress_row.lesson_id=lesson_row.id where enrollment_row.learner_id=auth.uid() and enrollment_row.course_id=p_course_id and enrollment_row.status='completed' and enrollment_row.completed_at is not null; return query select coalesce(eligible_count,0)>0 and eligible_count=done_count, certificate_row.certificate_code,certificate_row.status from (select 1) as state_row left join public.certificates as certificate_row on certificate_row.learner_id=auth.uid() and certificate_row.course_id=p_course_id; end; $$;

create function public.issue_own_learning_certificate(p_course_id bigint) returns table (certificate_code text, certificate_status text, issued_at timestamptz) language plpgsql security definer set search_path='' as $$ declare own_enrollment_id bigint; eligible_count integer; done_count integer; generated_code text; begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; select enrollment_row.id into own_enrollment_id from public.enrollments as enrollment_row join public.learning_courses as course_row on course_row.id=enrollment_row.course_id and course_row.status='published' where enrollment_row.learner_id=auth.uid() and enrollment_row.course_id=p_course_id and enrollment_row.status='completed' and enrollment_row.completed_at is not null for update of enrollment_row,course_row; if own_enrollment_id is null then raise exception 'This course is not eligible for a certificate' using errcode='42501'; end if; select count(lesson_row.id)::integer,count(lesson_row.id) filter(where progress_row.completed_at is not null and progress_row.progress_percent=100)::integer into eligible_count,done_count from public.lessons as lesson_row join public.course_modules as module_row on module_row.id=lesson_row.module_id and module_row.course_id=p_course_id left join public.lesson_progress as progress_row on progress_row.enrollment_id=own_enrollment_id and progress_row.lesson_id=lesson_row.id where lesson_row.course_id=p_course_id and lesson_row.lesson_type in ('text','video'); if eligible_count=0 or done_count<>eligible_count then raise exception 'This course is not eligible for a certificate' using errcode='22023'; end if; generated_code:=upper(replace(gen_random_uuid()::text,'-','')); insert into public.certificates (learner_id,course_id,certificate_code,learner_name,course_title,instructor_name,completed_at,status) select auth.uid(),course_row.id,generated_code,profile_row.full_name,course_row.title,instructor_profile.full_name,enrollment_row.completed_at,'issued' from public.learning_courses as course_row join public.enrollments as enrollment_row on enrollment_row.id=own_enrollment_id left join public.profiles as profile_row on profile_row.id=auth.uid() left join public.profiles as instructor_profile on instructor_profile.id=course_row.instructor_id where course_row.id=p_course_id and profile_row.full_name is not null on conflict (learner_id,course_id) do nothing; if not found then if not exists(select 1 from public.certificates as certificate_row where certificate_row.learner_id=auth.uid() and certificate_row.course_id=p_course_id) then raise exception 'Certificate issuance failed' using errcode='22023'; end if; end if; return query select certificate_row.certificate_code,certificate_row.status,certificate_row.issued_at from public.certificates as certificate_row where certificate_row.learner_id=auth.uid() and certificate_row.course_id=p_course_id; end; $$;

create function public.list_own_learning_certificates() returns table (certificate_code text, course_title text, learner_name text, completed_at timestamptz, issued_at timestamptz, certificate_status text) language plpgsql security definer stable set search_path='' as $$ begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; return query select certificate_row.certificate_code,certificate_row.course_title,certificate_row.learner_name,certificate_row.completed_at,certificate_row.issued_at,certificate_row.status from public.certificates as certificate_row where certificate_row.learner_id=auth.uid() order by certificate_row.issued_at desc; end; $$;
create function public.get_own_learning_certificate(p_certificate_code text) returns table (certificate_code text, course_title text, learner_name text, instructor_name text, completed_at timestamptz, issued_at timestamptz, certificate_status text) language plpgsql security definer stable set search_path='' as $$ begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; return query select certificate_row.certificate_code,certificate_row.course_title,certificate_row.learner_name,certificate_row.instructor_name,certificate_row.completed_at,certificate_row.issued_at,certificate_row.status from public.certificates as certificate_row where certificate_row.learner_id=auth.uid() and certificate_row.certificate_code=upper(btrim(p_certificate_code)); end; $$;
create function public.verify_learning_certificate(p_certificate_code text) returns table (is_valid boolean, certificate_code text, learner_name text, course_title text, completed_at timestamptz, issued_at timestamptz, certificate_status text) language plpgsql security definer stable set search_path='' as $$ declare normalized_code text:=upper(btrim(p_certificate_code)); begin if normalized_code is null or normalized_code !~ '^[A-F0-9]{32}$' then return; end if; return query select certificate_row.status='issued',certificate_row.certificate_code,certificate_row.learner_name,certificate_row.course_title,certificate_row.completed_at,certificate_row.issued_at,certificate_row.status from public.certificates as certificate_row where certificate_row.certificate_code=normalized_code; end; $$;

revoke execute on function public.get_own_learning_certificate_state(bigint),public.issue_own_learning_certificate(bigint),public.list_own_learning_certificates(),public.get_own_learning_certificate(text),public.verify_learning_certificate(text) from public,anon,authenticated;
grant execute on function public.get_own_learning_certificate_state(bigint),public.issue_own_learning_certificate(bigint),public.list_own_learning_certificates(),public.get_own_learning_certificate(text) to authenticated;
grant execute on function public.verify_learning_certificate(text) to anon,authenticated;

do $$ begin if has_table_privilege('public','public.certificates','SELECT') or has_table_privilege('anon','public.certificates','SELECT') or has_table_privilege('authenticated','public.certificates','INSERT') or has_table_privilege('authenticated','public.certificates','UPDATE') or has_table_privilege('authenticated','public.certificates','DELETE') or not has_table_privilege('service_role','public.certificates','SELECT') or not has_table_privilege('service_role','public.certificates','INSERT') or has_function_privilege('public','public.verify_learning_certificate(text)','EXECUTE') or has_function_privilege('anon','public.issue_own_learning_certificate(bigint)','EXECUTE') or not has_function_privilege('anon','public.verify_learning_certificate(text)','EXECUTE') then raise exception 'Certificate issuance aborted: grants are not hardened'; end if; end; $$;
commit;
